Feat/civ 4343 | How much do you want to continue claiming?
hmcts/civil-citizen-ui pull request #1000
Opened 2022-10-19 15:03 UTC by lfazelyniaHMCTS

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4343

### Change description ###
This change will add a page for "How much do you want to continue claiming?"

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-10-19 15:16 UTC, TatsyMaslova commented on src/main/common/form/models/interest/howMuchContinueClaiming.ts
> +  //TODO: Validation for this field not fully working
Do we need this todo? and if we do then wouldn't it be best to fix validation for this field?

2022-10-19 15:27 UTC, TatsyMaslova commented on src/main/views/features/claim/interest/how-much-continue-claiming.njk
> +  value: form.model.dailyInterestAmount,
what happens when you enter 0 in the daily amount interest? I think there is a know bug with govuk input where it displays an empty value sadly and we have a hack to convert our value to string so in your case this would be `{% set amountValue =  '' + form.model.dailyInterestAmount %}` and then set the input to that value.

2022-10-19 15:46 UTC, lfazelyniaHMCTS commented on src/main/views/features/claim/interest/how-much-continue-claiming.njk
> +  value: form.model.dailyInterestAmount,
Resolved in next commit

2022-10-19 15:52 UTC, TatsyMaslova approved these changes

2022-10-20 08:33 UTC, commitBlob commented on src/main/routes/features/claim/interest/howMuchContinueClaimingController.ts
> +    //const dailyInterestAmount = req.body.option === SameRateInterestType.SAME_RATE_INTEREST_DIFFERENT_RATE ? toNumber(req.body.dailyInterestAmount) : null;
can you remove this commented out line please it is raised as a code smell in sonar

2022-10-20 08:33 UTC, commitBlob commented on src/main/views/features/claim/interest/how-much-continue-claiming.njk
> +              errorMessage: { text: t(optionError) } if t(optionError) else ''
don't think you need else here

2022-10-20 12:04 UTC, lfazelyniaHMCTS commented on src/main/routes/features/claim/interest/howMuchContinueClaimingController.ts
> +    //const dailyInterestAmount = req.body.option === SameRateInterestType.SAME_RATE_INTEREST_DIFFERENT_RATE ? toNumber(req.body.dailyInterestAmount) : null;
Resolved

2022-10-20 12:33 UTC, laarmada requested changes

2022-10-20 12:33 UTC, laarmada commented on src/main/routes/features/claim/interest/howMuchContinueClaimingController.ts
> +      await saveInterest(caseId, form.model, 'howMuchContinueClaiming');
please use a constant instead of string 'howMuchContinueClaiming'

2022-10-20 12:33 UTC, laarmada commented on src/main/routes/urls.ts
> +export const CLAIM_INTEREST_HOW_MUCH = `${BASE_CLAIM_URL}/interest-how-much`;
please add _URL at the end of the name

2022-10-20 12:33 UTC, laarmada commented on src/main/views/features/claim/interest/how-much-continue-claiming.njk
> +{% set amountValue = '' + form.model.dailyInterestAmount %}
why you need to do that? '' + only a curiosity

2022-10-20 12:37 UTC, lfazelyniaHMCTS commented on src/main/views/features/claim/interest/how-much-continue-claiming.njk
> +{% set amountValue = '' + form.model.dailyInterestAmount %}
This is because of a bug that occurs when you enter 0 in dailyInterestAmount
Here's the explanation from @TatsyMaslova from a previous comment on this PR:
_I think there is a know bug with govuk input where it displays an empty value sadly and we have a hack to convert our value to string so in your case this would be {% set amountValue = '' + form.model.dailyInterestAmount %} and then set the input to that value._

2022-10-20 12:41 UTC, lfazelyniaHMCTS commented on src/main/routes/urls.ts
> +export const CLAIM_INTEREST_HOW_MUCH = `${BASE_CLAIM_URL}/interest-how-much`;
I've just realised that it already existed (3 lines above) so am removing **CLAIM_INTEREST_HOW_MUCH** and replacing it's uses with **CLAIM_INTEREST_HOW_MUCH_URL** in next commit

2022-10-20 12:49 UTC, lfazelyniaHMCTS commented on src/main/routes/features/claim/interest/howMuchContinueClaimingController.ts
> +      await saveInterest(caseId, form.model, 'howMuchContinueClaiming');
Resolved

2022-10-20 14:02 UTC, lfazelyniaHMCTS commented on src/main/views/features/claim/interest/how-much-continue-claiming.njk
> +              errorMessage: { text: t(optionError) } if t(optionError)
You're right it's not being set
I've added a bit of code that sets it near the top of the file

2022-10-20 14:05 UTC, commitBlob approved these changes

2022-10-24 08:30 UTC, merged