Civ 5037
hmcts/civil-citizen-ui pull request #1022
Opened 2022-10-26 20:02 UTC by kamilewandowski

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-5037

### Change description ###
adding welsh translation for send-your-response-by-email

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-27 08:01 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/cy.json
> +      "PAGE_TITLE": "Send your response by email",
alphabetical order

2022-10-27 08:10 UTC, commitBlob requested changes

2022-10-27 08:10 UTC, commitBlob commented on src/main/modules/i18n/locales/cy.json
> +      "WE_MUST_RECEIVE_COMPLETED_FORM": "Rhaid i ni gael eich ffurflen wedi'i llenwi cyn 4pm ar 20 Awst 2023. Bydd yr hawliad yn eich erbyn yn mynd yn ei flaen os na fyddwn yn cael eich ffurflen.",
`4pm ar 20 Awst 2023` this is dynamic date, see how it is done in en.json `{{ deadline }}`

2022-10-27 08:10 UTC, commitBlob commented on src/main/modules/i18n/locales/cy.json
> +      "PDF_ADMISSION": "Download admission form (PDF, 102 KB)",
If we don't have these translations ticket should still be blocked we don't want to address tech debt ticket with another tech debt

2022-10-27 08:10 UTC, commitBlob commented on src/main/modules/i18n/locales/cy.json
> +      "PAGE_TITLE": "Under 18",
aren't these part of the different tech debt? CIV-5036

2022-10-27 08:10 UTC, commitBlob commented
removed deployment labels until ticket is ready for QA

2022-10-31 08:16 UTC, kamilewandowski commented on src/main/modules/i18n/locales/cy.json
> +      "PAGE_TITLE": "Send your response by email",
fixed

2022-10-31 08:16 UTC, kamilewandowski commented on src/main/modules/i18n/locales/cy.json
> +      "WE_MUST_RECEIVE_COMPLETED_FORM": "Rhaid i ni gael eich ffurflen wedi'i llenwi cyn 4pm ar 20 Awst 2023. Bydd yr hawliad yn eich erbyn yn mynd yn ei flaen os na fyddwn yn cael eich ffurflen.",
updated that

2022-10-31 08:18 UTC, kamilewandowski commented on src/main/modules/i18n/locales/cy.json
> +      "PAGE_TITLE": "Under 18",
yes, it is civ-5036 I just created this branch from the previous

2022-10-31 08:18 UTC, kamilewandowski commented on src/main/modules/i18n/locales/cy.json
> +      "PDF_ADMISSION": "Download admission form (PDF, 102 KB)",
translations in place

2022-10-31 13:20 UTC, commitBlob reviewed
When you are working on the ticket please branch from master.
We want to have one branch and one PR per ticket

2022-10-31 13:20 UTC, commitBlob commented on src/main/modules/i18n/locales/cy.json
> +  "Claim number": "Mialc rebmun",
These are not translations it is just text written in reverse.
You should remove all translations until common object (line 11)

2022-10-31 15:34 UTC, kamilewandowski commented on src/main/modules/i18n/locales/cy.json
> +  "Claim number": "Mialc rebmun",
fixed in next commits

2022-11-01 11:04 UTC, kamilewandowski commented on src/main/modules/i18n/locales/cy.json
> +      "COUNTER_CLAIM_CHOSEN": "Rydych wedi dewis gwneud gwrth-hawliad. Mae hyn yn golygu ni all eich amddiffyniad barhau ar-lein. Dilynwch y camau hyn i lwytho, llenwi a dychwelyd ffurflen N9B. Rhaid
fixed

2022-11-01 11:07 UTC, commitBlob approved these changes

2022-11-07 13:17 UTC, merged