resetting redis data with changing response type.
hmcts/civil-citizen-ui pull request #1029
Opened 2022-10-28 11:00 UTC by neeta-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-3144

### Change description ###
Added a code to reset the redis data when user changes the response type.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-28 11:15 UTC, commitBlob reviewed
I think this should be demoed to the whole team as it would be easier to visualise the change

2022-10-28 11:15 UTC, commitBlob commented on src/main/routes/features/response/responseType/citizenResponseTypeController.ts
> +        await resetPreviousResponseTypeSettings(req.params.id);
I think this call should happen before `saveDraftClaim` otherwise we are overwriting selections we just made (line 57) ?

2022-10-28 11:32 UTC, commitBlob commented
removing labels until it passes dev review

2022-10-28 12:29 UTC, laarmada requested changes

2022-10-28 12:29 UTC, laarmada commented on src/main/services/features/response/resetPreviousResponseTypeSettingService.ts
> +    claim.paymentOption = undefined;
we need to move to the correspondent hierarchy no make sense have in claim....

2022-10-28 12:29 UTC, laarmada commented on src/main/routes/features/response/responseType/citizenResponseTypeController.ts
> +        await resetPreviousResponseTypeSettings(req.params.id);
I don't have clear if that is correct, you will remove everything under:
 claim.partialAdmission
 claim.rejectAllOfClaim
claim.statementOfMeans

after that page.... so we will loose information

2022-10-28 12:40 UTC, laarmada requested changes

2022-10-28 12:40 UTC, laarmada commented on src/main/routes/features/response/responseType/citizenResponseTypeController.ts
> +        await resetPreviousResponseTypeSettings(req.params.id);
take care with that if we remove statementOfMeans before to save maybe we loose data from the previous steps....

2022-10-28 12:52 UTC, TatsyMaslova commented on src/main/services/features/response/resetPreviousResponseTypeSettingService.ts
> +    //clear common fields
after we selected a payment option we should not clear the whole thing. we should clear the previously associated fields if they do not apply. also don't like comments in code sorry . prefer clear method names and small methods instead of big methods with comments

2022-11-01 12:27 UTC, neeta-hmcts commented
closing this pull request as it got messed up with other commits.  I have addressed the given comments for this PR and will raise a new PR for same.

2022-11-01 12:27 UTC, closed without merging