CUI Welsh UI Translations 21
hmcts/civil-citizen-ui pull request #1032
Opened 2022-10-28 12:42 UTC by pascalkankonde

**Before creating a pull request make sure that:**

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-5255

### Change description ###

The scope of this ticket is to develop Welsh content translation of the following screens: 

DQ-Do you want an extra 4 weeks to settle the claim
DQ-Enter the expert's details

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-10-28 13:34 UTC, laarmada requested changes

2022-10-28 13:34 UTC, laarmada commented on src/main/views/features/directionsQuestionnaire/request-extra-4weeks.njk
> +            {{ yesNoRadioButton(t,id,name,title,form,'',{yes: 'COMMON.VARIATION_2.YES', no: 'COMMON.VARIATION_2.NO'}) }}
are you sure the tests are passing? if you remove option from there, it doesn`t work

2022-10-28 14:55 UTC, pascalkankonde commented on src/main/modules/i18n/locales/cy.json
>        "REMOVE_EXPERT": "Remove expert",
Remove expert, was not provided

2022-10-28 14:56 UTC, pascalkankonde commented on src/main/views/features/directionsQuestionnaire/request-extra-4weeks.njk
> +            {{ yesNoRadioButton(t,id,name,title,form,'',{yes: 'COMMON.VARIATION_2.YES', no: 'COMMON.VARIATION_2.NO'}) }}
I have tested, it is fine

2022-10-31 12:17 UTC, commitBlob requested changes

2022-10-31 12:17 UTC, commitBlob commented on src/main/views/features/directionsQuestionnaire/request-extra-4weeks.njk
> +            {{ yesNoRadioButton(t,id,name,title,form,'',{yes: 'COMMON.VARIATION_2.YES', no: 'COMMON.VARIATION_2.NO'}) }}
This won't work. select an option and press save and continue, you can't get out of the page

2022-10-31 12:29 UTC, commitBlob commented
Removing myself as a reviewer as otherwise will be blocking this issue.
Pascal to refactor yesNoRadioButton to  `yesNoRadioButton(t, 'option', 'option', title ,form, '', {yes: 'COMMON.VARIATION_2.YES', no: 'COMMON.VARIATION_2.NO'})` as Sergio pointed out page won't function properly.
Remove expert translation to be requested from Josh as well.

2022-10-31 12:30 UTC, commitBlob reviewed
Removing myself as a reviewer as otherwise will be blocking this issue.
Pascal to refactor yesNoRadioButton to  `yesNoRadioButton(t, 'option', 'option', title ,form, '', {yes: 'COMMON.VARIATION_2.YES', no: 'COMMON.VARIATION_2.NO'})` as Sergio pointed out page won't function properly.
Remove expert translation to be requested from Josh as well.

Need re-review when translation is provided.

2022-11-02 12:54 UTC, merged