Features/civ 5479 check answers hearing requirements
hmcts/civil-citizen-ui pull request #1035
Opened 2022-10-31 09:45 UTC by commitBlob

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-10-31 12:52 UTC, TatsyMaslova approved these changes

2022-10-31 13:08 UTC, laperla11 approved these changes

2022-11-02 08:52 UTC, laarmada requested changes

2022-11-02 08:52 UTC, laarmada commented on src/main/routes/features/directionsQuestionnaire/defendantYourselfEvidenceController.ts
> -const dqParentName = 'experts';
if you remove from expert, you should added to hearing as you already have in the build section:
if (claim?.directionQuestionnaire?.defendantYourselfEvidence?.option) {
    hearingRequirementsSection.summaryList.rows.push(giveEvidenceYourself(claim, claimId, lng));
  }

2022-11-02 09:08 UTC, commitBlob commented on src/main/routes/features/directionsQuestionnaire/defendantYourselfEvidenceController.ts
> -const dqParentName = 'experts';
no, look at the Claim model. You were saving defendantYourselfEvidence in the experts and in the claim model defendantYourselfEvidence and experts are on the same level (directionQuestionnaire).

This change is regression fix

`export class DirectionQuestionnaire {
  defendantYourselfEvidence?: GenericYesNo;   <-----------
  hearing?: Hearing;
  vulnerabilityQuestions?: VulnerabilityQuestions;
  experts?: Experts; <-----------
  welshLanguageRequirements?: WelshLanguageRequirements;
  witnesses?: Witnesses;`

2022-11-02 09:28 UTC, laarmada approved these changes

2022-11-09 17:49 UTC, merged