Feature/civ 807 view claim screen v2
hmcts/civil-citizen-ui pull request #108
Opened 2022-01-25 15:17 UTC by RosDiaf

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-01-26 12:19 UTC, taomoh requested changes
1. I am a bit worried about the number of files added in this PR. I understand there are dependencies, but we should reduce them to the bear minimum with the nunjucks view being the anchor for the copy and only pulling the strict minimum needed with a critical view. This is what we did for the dashboard 1st thin slice (See PR: https://github.com/hmcts/civil-citizen-ui/pull/94)
Some files are not required for the View claim scope (e.g. payment code, some model and enumerations classes, etc.)

2. The following files shouldn't be modified for this story:
- bin/generate-ssl-options.sh
- bin/init.sh 

3. `package-lock.json` shouldn't be added to git. This is already covered by `yarn.lock`

4. Please also refer to inline comments I've added

2022-01-28 10:00 UTC, RosDiaf commented on src/main/assets/scss/main.scss
> +}
Removed

2022-01-28 10:12 UTC, RosDiaf commented on src/main/views/claim-details-tpl.njk
> +    <!-- [if lt IE 9]> <script src="/html5-shiv/html5shiv.js"></script> <![endif] -->
Code removed, not needed. I have doubled checked with Mounika.

2022-01-28 19:01 UTC, RosDiaf commented on package.json
> +    "request": "^2.88.2",
Removed

2022-01-28 19:03 UTC, RosDiaf commented on src/main/features/response/routes/claim-details.ts
> +const civilServiceApiBaseUrl = 'http://localhost:8765';
Changed to master router structure now

2022-01-28 19:04 UTC, RosDiaf commented on src/main/app.ts
> +import { Feature as DefendantResponseFeature } from './features/response/index';
Changed to master router structure

2022-01-29 19:19 UTC, RosDiaf commented on .gitignore
> -.yarnrc
Changes reverted

2022-01-29 19:50 UTC, RosDiaf commented on package.json
> +    "@hmcts/requestretry": "^1.1.2",
Removed

2022-01-29 19:50 UTC, RosDiaf commented on src/main/app/utils/numberFormatter.ts
> +}
Removed. currencyFormat used

2022-01-29 19:50 UTC, RosDiaf commented on package.json
> +    "request-promise-native": "^1.0.9",
Removed

2022-01-31 10:52 UTC, taomoh approved these changes
Looking good. Thanks @RosDiaf for taking the time to incorporate the feedback!

2022-01-31 17:07 UTC, mounikahmcts approved these changes

2022-01-31 18:55 UTC, RosDiaf commented on src/main/app/client/civilServiceClient.ts
> +    const objects = response.data as Claim;
I have added a try catch block

2022-01-31 18:58 UTC, RosDiaf commented on src/main/app/client/civilServiceClient.ts
> +    //const token = 'eyJ0eXAiOiJKV1QiLCJ6aXAiOiJOT05FIiwia2lkIjoiYi9PNk92VnYxK3krV2dySDVVaTlXVGlvTHQwPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiYXV0aF9sZXZlbCI6MCwiYXVkaXRUcmFja2luZ0
Yes, once we deploy those lines will be removed. We left there to do the demo on local machine

2022-01-31 20:13 UTC, merged