CIV-5558 | Claimant Intent – Full admit pay by set date + How they want to pay
hmcts/civil-citizen-ui pull request #1081
Opened 2022-11-04 15:19 UTC by lfazelyniaHMCTS

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-5558

### Change description ###
This change will add screen in claimant response journey for when defendant selects full admit and pay by set date 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-11-04 15:24 UTC, portizdev commented on src/main/views/features/claimantResponse/full-admit-set-date-payment.njk
> +{% from "govuk/components/input/macro.njk" import govukInput %}
You don't need to import govUkInput

2022-11-04 15:25 UTC, lfazelyniaHMCTS commented on src/main/views/features/claimantResponse/full-admit-set-date-payment.njk
> +{% from "govuk/components/input/macro.njk" import govukInput %}
Thanks Pablo, I forgot to remove it when copying the imports from a different njk file
I'll sort it in the next commit

2022-11-04 15:36 UTC, TatsyMaslova commented on src/test/unit/services/features/claimantResponse/fullAdmitSetDatePaymentService.test.ts
> +        claim.claimantResponse.fullAdmitSetDateAcceptPayment = undefined;
If you are testing that claimant response does not exist (the condition in your service) then you need to make claimant response undefined. Then in your 'Then' section verify that claimant response is not undefined. this way you are checking your condition `(claim?.claimantResponse) ? claim.claimantResponse : new ClaimantResponse();`. Otherwise it is not clear what you are testing here in my opinion

2022-11-04 15:49 UTC, GorilaNaranja requested changes

2022-11-04 15:49 UTC, GorilaNaranja commented on src/main/routes/features/claimantResponse/fullAdmitSetDatePaymentController.ts
> +      res.redirect(CLAIMANT_RESPONSE_TASK_LIST_URL);
This is redirection to a wrong url, literaly with ":id" in the url:
`http://localhost:3001/claimant-response/:id/task-list`

You have to use this function:
`res.redirect(constructResponseUrlWithIdParams(yourId, YOUR_URL));`

2022-11-04 15:50 UTC, TatsyMaslova commented on src/main/services/features/claimantResponse/fullAdmitSetDatePaymentService.ts
> +    const defendantName = claim.getDefendantName();
Perhaps this is a good place to fix the bug here 😉 (was caused by our refactoring the model) but essentially the fix for this would be instead of returning party name return  based on party type - if individual  or sole trader return title if exists plus First name Last name otherwise partyName. I think there was already a method before that that did it but we changed it to return partyName because it was based on ccd that would always return party name in correct way (logic is in civil service)

2022-11-04 15:56 UTC, lfazelyniaHMCTS commented on src/test/unit/services/features/claimantResponse/fullAdmitSetDatePaymentService.test.ts
> +        claim.claimantResponse.fullAdmitSetDateAcceptPayment = undefined;
I'm testing whether the fullAdmitSetDateAcceptPayment doesn't exist not the whole claimant response
I'll change name to make it clearer

2022-11-04 15:57 UTC, GorilaNaranja commented on src/main/services/features/claimantResponse/fullAdmitSetDatePaymentService.ts
> +    const defendantName = claim.getDefendantName();
We have it already developed in buildTheirDetailsSection.ts file, you can reuse it:


const getDefendantFullName = (claim: Claim): string => {
  if (claim.respondent1?.type === PartyType.ORGANISATION || claim.respondent1?.type === PartyType.COMPANY) {
    return claim.respondent1?.partyName;
  }
  return `${claim.respondent1?.individualTitle} ${claim.respondent1?.individualFirstName} ${claim.respondent1?.individualLastName}`;
};

2022-11-04 16:05 UTC, neeta-hmcts commented on src/main/routes/urls.ts
> +const BASE_CLAIMANT_RESPONSE_URL = '/claimant-response/:id';
This URL should be $(BASE_CASE_URL)/claimant-response ?

2022-11-04 17:12 UTC, lfazelyniaHMCTS commented on src/test/unit/services/features/claimantResponse/fullAdmitSetDatePaymentService.test.ts
> +        claim.claimantResponse.fullAdmitSetDateAcceptPayment = undefined;
Resolved

2022-11-04 17:12 UTC, lfazelyniaHMCTS commented on src/main/services/features/claimantResponse/fullAdmitSetDatePaymentService.ts
> +const logger = Logger.getLogger('supportRequiredService');
Resolved

2022-11-04 17:12 UTC, lfazelyniaHMCTS commented on src/main/services/features/claimantResponse/fullAdmitSetDatePaymentService.ts
> +    const defendantName = claim.getDefendantName();
Resolved

2022-11-04 17:12 UTC, lfazelyniaHMCTS commented on src/main/routes/features/claimantResponse/fullAdmitSetDatePaymentController.ts
> +      res.redirect(CLAIMANT_RESPONSE_TASK_LIST_URL);
Resolved

2022-11-04 17:12 UTC, lfazelyniaHMCTS commented on src/main/routes/urls.ts
> +const BASE_CLAIMANT_RESPONSE_URL = '/claimant-response/:id';
Resolved

2022-11-07 08:19 UTC, GorilaNaranja commented on src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
> +export const getDefendantFullName = (claim: Claim): string => {
We meant to create a function as a method in Claim.ts instead export this one.
 
Also, the method should be something like this:
const getDefendantFullName = (claim: Claim): string => {
  if (claim.respondent1?.type === PartyType.ORGANISATION || claim.respondent1?.type === PartyType.COMPANY) {
    return claim.respondent1?.partyName;
  }
  return `${claim.respondent1?.individualTitle} ${claim.respondent1?.individualFirstName} ${claim.respondent1?.individualLastName}`;
};

2022-11-07 08:55 UTC, TatsyMaslova commented on src/test/unit/services/features/claimantResponse/fullAdmitSetDatePaymentService.test.ts
> +        claim.claimantResponse.fullAdmitSetDateAcceptPayment = undefined;
Ok then you are missing the test for the this condition `(claim?.claimantResponse) ? claim.claimantResponse : new ClaimantResponse();`

2022-11-07 08:58 UTC, TatsyMaslova commented on src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
> +export const getDefendantFullName = (claim: Claim): string => {
Lawrence, if you look at git history on claim - we had already a method that did all this for both defendant and claimant full name. but then it was removed because the same logic existed on the civil service side. But now that we have changes in our party model we can bring that method back

2022-11-07 09:06 UTC, TatsyMaslova commented on src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
> +export const getDefendantFullName = (claim: Claim): string => {
Only in our case we just have party.title instead. And we would need to check whether title exists before adding it to the full name/ Hope it makes sense

2022-11-07 09:20 UTC, laarmada requested changes

2022-11-07 09:20 UTC, laarmada commented on src/main/routes/features/claimantResponse/fullAdmitSetDatePaymentController.ts
> +    const parentPropertyName = 'fullAdmitSetDateAcceptPayment';
you dont need to use a parentProperty if you have only a 1 level.... parentProperty  is optional..... 
await saveClaimantResponse(claimId, form.model.option, claimantResponsePropertyName);
.....
claimantResponsePropertyName= 'fullAdmitSetDateAcceptPayment';

2022-11-07 09:24 UTC, GorilaNaranja commented on src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
> +export const getDefendantFullName = (claim: Claim): string => {
In addition, we are always saving title, firstName and lastName in fields individualTitle, individualFirstName and individualLastName even if type is SOLE_TRADER... I think someone is working on Party refactorization, but I think at this point we have to `return party.individualTitle + ' ' + party.individualFirstName + ' ' + party.individualLastName;` for both, INDIVIDUAL and SOLE_TRADER.

Also, you can use the modern string concat: 
`return ${party.individualTitle} ${party.individualFirstName} ${party.individualLastName};`

2022-11-10 12:48 UTC, TatsyMaslova commented on src/main/common/models/claim.ts
> +  getName(party: Party): string {
we should have getDefendantName(){
 return this.getName(this.respondent1);
}
and getClaimamantName(){
return this.getName(this.applicant1);
}

2022-11-10 12:49 UTC, TatsyMaslova commented on src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
> +      summaryRow(t('PAGES.CHECK_YOUR_ANSWER.FULL_NAME', {lng: getLng(lang)}), claim.getName(claim.respondent1), yourDetailsHref, changeLabel(lang)),
then here we would call claim.getDefendantName() and won't have to pass claim.respondent1

2022-11-10 15:32 UTC, TatsyMaslova approved these changes

2022-11-10 15:33 UTC, portizdev commented on src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
> +      summaryRow(t('PAGES.CHECK_YOUR_ANSWER.FULL_NAME', {lng: getLng(lang)}), claim.getName(claim.respondent1), yourDetailsHref, changeLabel(lang)),
Done

2022-11-10 15:34 UTC, portizdev commented on src/main/routes/features/claimantResponse/fullAdmitSetDatePaymentController.ts
> +    const parentPropertyName = 'fullAdmitSetDateAcceptPayment';
Done

2022-11-10 15:34 UTC, portizdev commented on src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
> +export const getDefendantFullName = (claim: Claim): string => {
Done

2022-11-10 15:37 UTC, neeta-hmcts approved these changes

2022-11-10 15:37 UTC, neeta-hmcts commented on src/main/routes/features/claimantResponse/fullAdmitSetDatePaymentController.ts
> +    console.log(details);
missed to remove console log

2022-11-11 08:00 UTC, laarmada approved these changes

2022-11-11 08:53 UTC, GorilaNaranja commented on src/main/common/models/claim.ts
> +    if (party?.type == PartyType.INDIVIDUAL || party?.type == PartyType.SOLE_TRADER) {
if we receive party as paramaters and is not optional why we need to add question mark in all party?

2022-11-11 09:02 UTC, GorilaNaranja approved these changes

2022-11-11 09:12 UTC, portizdev commented on src/main/common/models/claim.ts
> +    if (party?.type == PartyType.INDIVIDUAL || party?.type == PartyType.SOLE_TRADER) {
Good point Felipe. Analysed and you are right. It is already solved.

2022-11-14 15:41 UTC, merged