CIV-5662 : Part admit + already paid- Rejection reason.
hmcts/civil-citizen-ui pull request #1089
Opened 2022-11-07 17:37 UTC by neeta-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-5662

### Change description ###
This PR has changes to accept the claimant rejection reason.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-11-07 18:15 UTC, laarmada requested changes

2022-11-07 18:15 UTC, laarmada commented on src/main/services/features/claimantResponse/rejectionReasonService.ts
> +import {ClaimantResponse} from '../../../common/models/claimantResponse';
Why toy dont use the existing genericService for claimantResponse?

2022-11-08 09:15 UTC, laperla11 commented on src/main/services/features/claimantResponse/rejectionReasonService.ts
> +import {ClaimantResponse} from '../../../common/models/claimantResponse';
I agree with Sergio, you can use generic `getClaimantResponse` and `saveClaimantResponse` methods

2022-11-08 12:09 UTC, neeta-hmcts commented on src/main/services/features/claimantResponse/rejectionReasonService.ts
> +import {ClaimantResponse} from '../../../common/models/claimantResponse';
resolved.

2022-11-08 12:14 UTC, commitBlob commented on src/main/common/form/models/claimantResponse/rejectionReason.ts
> +  @IsNotEmpty({message: CLAIMANT_REJECTION_RESPONSE_REQUIRED})
This error message will not be translated, please dont use `errorMessageContstants.ts`

2022-11-08 12:15 UTC, laperla11 approved these changes

2022-11-08 12:45 UTC, neeta-hmcts commented on src/main/common/form/models/claimantResponse/rejectionReason.ts
> +  @IsNotEmpty({message: CLAIMANT_REJECTION_RESPONSE_REQUIRED})
resolved

2022-11-08 12:51 UTC, commitBlob approved these changes

2022-11-11 16:30 UTC, merged