Moving all dependabot version upgrades into one pr
hmcts/civil-citizen-ui pull request #110
Opened 2022-01-27 15:07 UTC by mounikahmcts

I have seen almost 10 PR's with version updates. So merged all of them into one.

2022-01-27 16:03 UTC, mounikahmcts commented on package.json
> +    "eslint": "^7.32.0",
eslint upgraded

2022-01-28 10:27 UTC, taomoh requested changes
Please remove package-lock.json. This is already covered by yarn.lock and shouldn't be committed.
Apart from this, all looking good. Well done for getting rid of that eslint warning 👍

2022-01-28 10:33 UTC, taomoh approved these changes

2022-01-28 10:33 UTC, LeonardoPalmeiro approved these changes
looks great :)

2022-01-28 10:48 UTC, merged