Feat/civ 5680 | CCJ repayment plan
hmcts/civil-citizen-ui pull request #1135
Opened 2022-11-18 16:57 UTC by lfazelyniaHMCTS

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-5680

### Change description ###
Adding a screen to show payment options for repayment, containing the payment amount, first payment date and frequency of payment

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-11-21 09:01 UTC, laarmada requested changes

2022-11-21 09:29 UTC, lfazelyniaHMCTS commented on src/main/modules/i18n/locales/cy.json
> +    },
I've just checked, they are

2022-11-21 09:30 UTC, lfazelyniaHMCTS commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanInstalmentsController.ts
> +      await saveClaimantResponse(claimId, form.model, 'repaymentPlanInstalments', 'ccjRequest');
Just for my understanding, why should we use a const here when these values are only used once?
Seems a bit redundant no and wasted lines of code?

2022-11-21 09:31 UTC, lfazelyniaHMCTS commented on src/main/common/models/claimantResponse/ccj/paymentFrequencyType.ts
> +  EACH_WEEK = 'EACH_WEEK',
transactionSchedule is slightly different and isn't called EACH_WEEK (for example), but WEEK
Will thist affect things?

2022-11-21 09:33 UTC, lfazelyniaHMCTS commented on src/main/common/models/claimantResponse/ccj/repaymentPlanInstalments.ts
> +    firstPaymentDate?: InstalmentFirstPaymentDate;
I can do actually, but the constructor on InstalmentFirstPaymentDate makes it cleaner on the controller when compared to PaymentDate
Better to reuse existing or create something (this model) that is cleaner?

2022-11-21 09:36 UTC, lfazelyniaHMCTS commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanInstalmentsController.ts
> +      await saveClaimantResponse(claimId, form.model, 'repaymentPlanInstalments', 'ccjRequest');
And in this PR, it has been approved with string values, not consts. So shouldn't this be consistent with other CCJ controllers?
https://github.com/hmcts/civil-citizen-ui/pull/1119/files#diff-3078f8a9770df91d8aa3fa5d9c5e2242d501913ec41bd1c29a5214edb249a9d8

2022-11-21 14:10 UTC, lfazelyniaHMCTS commented on src/main/common/models/claimantResponse/ccj/repaymentPlanInstalments.ts
> +    firstPaymentDate?: InstalmentFirstPaymentDate;
Resolved

2022-11-22 08:17 UTC, portizdev approved these changes

2022-11-22 09:11 UTC, neeta-hmcts approved these changes

2022-11-22 09:40 UTC, laarmada commented on src/main/common/models/claimantResponse/ccj/paymentFrequencyType.ts
> +  EACH_WEEK = 'EACH_WEEK',
but you dont use that enum for translation right? we can see on a call if you want...

2022-11-22 09:43 UTC, laarmada commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanInstalmentsController.ts
> +      await saveClaimantResponse(claimId, form.model, 'repaymentPlanInstalments', 'ccjRequest');
yes!! I didnt review that one, the correct way is use constant :) the reviewers didnt view that detail....

2022-11-22 11:59 UTC, lfazelyniaHMCTS commented on src/main/common/models/claimantResponse/ccj/paymentFrequencyType.ts
> +  EACH_WEEK = 'EACH_WEEK',
Resolved

2022-11-22 11:59 UTC, lfazelyniaHMCTS commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanInstalmentsController.ts
> +      await saveClaimantResponse(claimId, form.model, 'repaymentPlanInstalments', 'ccjRequest');
Resolved

2022-11-22 13:07 UTC, laarmada approved these changes

2022-11-23 13:30 UTC, lfazelyniaHMCTS commented
Closing as pipeline build errors
Opening a new one as advised by Sampan

2022-11-23 13:30 UTC, closed without merging