CIV-5978: Defendant response - Part admit - Not paid scenarios
hmcts/civil-citizen-ui pull request #1136
Opened 2022-11-21 12:08 UTC by portizdev

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-5978

### Change description ###

Defendant's response screen scenarios: 

- Part admit - Pay immediately
- Part admit - By date
- Part admit - Instalments

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-11-22 08:36 UTC, laarmada requested changes
only improve comments

2022-11-22 08:36 UTC, laarmada commented on src/main/services/features/claimantResponse/defendantResponse/partAdmitNotPaidDefendantsResponseContent.ts
> +  switch(claim.responseStatus) {
claim.responseStatus is a vble or a function instead of function should be claim.responseStatus() ???

2022-11-22 08:36 UTC, laarmada commented on src/test/unit/common/utils/dateUtils.test.ts
> +    const mockDate = new Date('2022-03-01') as unknown as string;
why  "as unknown????" is date or string else we should control de type.

2022-11-22 08:36 UTC, laarmada commented on src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
> +    // Given
maybe we can use a for each and have only one const for that.... 
```
const claim = mockClaim;
    claim.partialAdmission.alreadyPaid = {
      'option': 'no',
    };
    claim.partialAdmission.paymentIntention.paymentOption = PaymentOptionType.INSTALMENTS;
    claim.partialAdmission.howMuchDoYouOwe = new HowMuchDoYouOwe(700,1200);
    claim.partialAdmission.whyDoYouDisagree = {
      text: 'disagree text',
    };
```
and inside of each test set/update the specific vble

2022-11-22 08:47 UTC, portizdev commented on src/main/services/features/claimantResponse/defendantResponse/partAdmitNotPaidDefendantsResponseContent.ts
> +  switch(claim.responseStatus) {
It's a get accessor, () don't need.

2022-11-22 08:48 UTC, portizdev commented on src/test/unit/common/utils/dateUtils.test.ts
> +    const mockDate = new Date('2022-03-01') as unknown as string;
This test was already there, I have simply added the common correction (it is also in other PRs) to avoid errors for those of us in Spain. But I'll take a look at it to try to correct it.

2022-11-22 09:36 UTC, KyleMulvihillV1 approved these changes

2022-11-22 09:36 UTC, laperla11 approved these changes

2022-11-22 14:44 UTC, portizdev commented on src/test/unit/common/utils/dateUtils.test.ts
> +    const mockDate = new Date('2022-03-01') as unknown as string;
Tech debt created to correct

2022-11-22 14:45 UTC, portizdev commented on src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
> +    // Given
Done

2022-12-06 09:59 UTC, TatsyMaslova commented
reopen pr for testing

2023-01-24 15:26 UTC, merged