claim submitted page
hmcts/civil-citizen-ui pull request #1146
Opened 2022-11-24 20:31 UTC by kamilewandowski

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4406

### Change description ###
add claim submitted page

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-11-25 09:09 UTC, laperla11 requested changes

2022-11-25 09:09 UTC, laperla11 commented on src/main/views/features/claim/claim-submitted.njk
> +          Your claim will be issued once your Help With Fees application has been confirmed.
pls use translation keys

2022-11-25 09:09 UTC, laperla11 commented on src/main/views/features/claim/claim-submitted.njk
> +          {{ defendantFullName }} has until {{ defendantResponseLimit }}
same here

2022-11-25 09:09 UTC, laperla11 commented on src/main/routes/features/claim/claimSubmittedController.ts
> +claimSubmittedController.get(CLAIM_SUBMITTED_URL, async (req, res, next: NextFunction) => {
use  this url : `CLAIM_CONFIRMATION_URL` for your page which is already defined and used for redirecting your page from previous page

2022-11-25 09:38 UTC, laarmada requested changes

2022-11-25 09:38 UTC, laarmada commented on src/main/modules/i18n/locales/en.json
> +    "CLAIM_SUBMITTED": {
where is the tranlation in the cy.json

2022-11-25 09:38 UTC, laarmada commented on src/main/routes/features/claim/claimSubmittedController.ts
> +      const helpWithFee = claim.claimDetails?.helpWithFees?.option == YesNo.YES;
maybe we have a function for that is used in several pages. claim.claimDetails?.helpWithFees?.option == YesNo.YES;

2022-11-28 08:19 UTC, kamilewandowski commented on src/main/routes/features/claim/claimSubmittedController.ts
> +      const helpWithFee = claim.claimDetails?.helpWithFees?.option == YesNo.YES;
I did not find a function like this. I can create one.

2022-11-28 08:26 UTC, laarmada approved these changes

2022-11-28 08:30 UTC, laperla11 approved these changes

2022-12-13 14:33 UTC, closed without merging