Civ 6029 translate claim to ccd
hmcts/civil-citizen-ui pull request #1147
Opened 2022-11-25 13:58 UTC by GorilaNaranja

### JIRA link ###
https://[tools.hmcts.net](https://tools.hmcts.net/jira/browse/CIV-6029)/jira/browse/CIV-6029

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-16 12:55 UTC, laperla11 commented on src/main/routes/features/claim/checkAnswersController.ts
> +      console.log('controller---', submitClaim.bind, constructResponseUrlWithIdParams(submittedClaim.id, CLAIM_CONFIRMATION_URL));
this log is testing purposes only, it will be removed after testing

2023-01-16 12:55 UTC, laperla11 commented on src/main/app/client/civilServiceClient.ts
> +      logger.info('claimResponse after submit ', claimResponse);
this log is testing purposes only, it will be removed after testing

2023-01-16 12:55 UTC, laperla11 commented on src/main/app/client/civilServiceClient.ts
> +      logger.info('updated casedat with id ', caseData);
this log is testing purposes only, it will be removed after testing

2023-01-16 12:56 UTC, laperla11 commented on Jenkinsfile_CNP
> +def ccddefbranch = "feat/CIV-5341-partyPhone"
this needs to be removed after testing

2023-01-16 13:18 UTC, laarmada commented on src/main/common/models/ccdResponse/ccdInterestType.ts
> +  SAME_RATE_INTEREST = 'SAME_RATE_INTEREST',
why we dont reuse ?
![Uploading image.png…]()

2023-01-16 13:32 UTC, laarmada requested changes

2023-01-16 13:32 UTC, laarmada commented on src/main/common/models/ccdResponse/ccdEvidence.ts
> +  CONTRACTS_AND_AGREEMENTS = 'CONTRACTS_AND_AGREEMENTS',
why we dont reuse?:
![image](https://user-images.githubusercontent.com/23473639/212687473-e336ea34-e6cd-44ac-a4cc-1cfafd5a5f28.png)

2023-01-16 13:32 UTC, laarmada commented on src/main/common/models/ccdResponse/ccdSameRateInterestSelection.ts
> +  SAME_RATE_INTEREST_8_PC = 'SAME_RATE_INTEREST_8_PC',
the same here: 
![image](https://user-images.githubusercontent.com/23473639/212687572-65c8f2c1-3c73-44ec-81e6-b149af91699f.png)

2023-01-16 13:32 UTC, laarmada commented on src/main/services/translation/convertToCUI/convertToCUIParty.ts
> +import {CCDParty} from '../../../common/models/ccdResponse/ccdParty';
we have one developed under the /response take care to remove one of them

2023-01-16 13:32 UTC, laarmada commented on src/test/unit/routes/features/claim/checkAnswersController.test.ts
> +
should we remove?

2023-01-16 13:37 UTC, GorilaNaranja commented on src/main/common/models/ccdResponse/ccdInterestType.ts
> +  SAME_RATE_INTEREST = 'SAME_RATE_INTEREST',
This is the CCD enum and the one in the screenshot is the CUI enum.

2023-01-16 13:37 UTC, GorilaNaranja commented on src/main/common/models/ccdResponse/ccdEvidence.ts
> +  CONTRACTS_AND_AGREEMENTS = 'CONTRACTS_AND_AGREEMENTS',
This is the CCD enum and the one in the screenshot is the CUI enum.

2023-01-16 13:38 UTC, GorilaNaranja commented on src/main/common/models/ccdResponse/ccdSameRateInterestSelection.ts
> +  SAME_RATE_INTEREST_8_PC = 'SAME_RATE_INTEREST_8_PC',
This is the CCD enum and the one in the screenshot is the CUI enum.

2023-01-16 13:43 UTC, GorilaNaranja commented on src/main/common/models/ccdResponse/ccdSameRateInterestSelection.ts
> +  SAME_RATE_INTEREST_8_PC = 'SAME_RATE_INTEREST_8_PC',
I forgot to change the name. I'm updating from "CCDRepaymentPlanFrequency " to "CCDSameRateInterestType"

2023-01-16 22:28 UTC, laperla11 approved these changes

2023-01-17 08:44 UTC, laarmada approved these changes

2023-01-24 11:24 UTC, merged