Features/civ 5574 claim intent check answers
hmcts/civil-citizen-ui pull request #1148
Opened 2022-11-25 14:35 UTC by pascalkankonde

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-5574

### Change description ###

The scope of this ticket is to develop the 'Check your answers before submitting' screen in the scenario where the Defendant has fully admitted and offered to pay by a set date. This screen occurs after the citizen has clicked on the "Notify us about the debt respite scheme" option on the latest update section.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-11-25 14:49 UTC, laperla11 requested changes

2022-11-25 14:49 UTC, laperla11 commented on src/main/services/features/breathingSpace/debtRespiteScheme/buildDebtRespiteSection.ts
> +const changeLabel = (lang: string | unknown): string => t('COMMON.BUTTONS.CHANGE', {lng: getLng(lang)});
You can import this function from `src/main/common/utils/checkYourAnswer/changeButton.ts`

2022-11-25 14:49 UTC, laperla11 commented on src/main/common/models/breathingSpace/debtRespiteReferenceNumber.ts
> +export class DebtRespiteReferenceNumber {
Where do you use this model?

2022-11-25 14:49 UTC, laperla11 commented on src/main/routes/features/claim/breathingSpace/checkAnswersController.ts
> +//import {getBreathingSpace} from 'services/features/breathingSpace/breathingSpaceService';
remove the code if not needed

2022-11-25 14:49 UTC, laperla11 commented on src/main/routes/urls.ts
> +//const BASE_BREATHING_SPACE_URL = `${BASE_CASE_URL}/breathing-space`;
same here

2022-11-25 14:52 UTC, pascalkankonde commented on src/main/common/models/breathingSpace/debtRespiteReferenceNumber.ts
> +export class DebtRespiteReferenceNumber {
it was duplicated import, thank you for spotting that commented line. I have removed it.

2022-11-25 14:53 UTC, pascalkankonde commented on src/main/services/features/breathingSpace/debtRespiteScheme/buildDebtRespiteSection.ts
> +const changeLabel = (lang: string | unknown): string => t('COMMON.BUTTONS.CHANGE', {lng: getLng(lang)});
It was duplicated import, thank you for spotting that commented line. I have removed it.

2022-11-25 15:35 UTC, pascalkankonde commented on src/main/routes/features/claim/breathingSpace/checkAnswersController.ts
> +//import {getBreathingSpace} from 'services/features/breathingSpace/breathingSpaceService';
Yes, it was duplication 6 and 8, Removed now

2022-11-25 15:36 UTC, pascalkankonde commented on src/main/routes/urls.ts
> +//const BASE_BREATHING_SPACE_URL = `${BASE_CASE_URL}/breathing-space`;
duplication import commented, removed

2022-11-25 15:36 UTC, pascalkankonde commented on src/main/services/features/breathingSpace/debtRespiteScheme/buildDebtRespiteSection.ts
> +const changeLabel = (lang: string | unknown): string => t('COMMON.BUTTONS.CHANGE', {lng: getLng(lang)});
Done

2022-11-25 15:43 UTC, pascalkankonde commented on src/main/common/models/breathingSpace/debtRespiteReferenceNumber.ts
> +export class DebtRespiteReferenceNumber {
This has been used in  src/main/services/features/breathingSpace/debtRespiteScheme/buildDebtRespiteSection.ts  line 23 to get the referenceNumber

2022-11-25 16:25 UTC, laperla11 approved these changes

2022-11-25 16:43 UTC, laarmada requested changes

2022-11-25 16:43 UTC, laarmada commented on src/main/modules/i18n/locales/en.json
> +    "CLAIMANT_DEBT_RESPITE_CHECK_ANSWERS": {
we have miss some translations...

2022-11-25 16:43 UTC, laarmada commented on src/main/services/features/breathingSpace/checkAnswersService.ts
> +    sections: [
where is the test?

2022-11-28 09:16 UTC, pascalkankonde commented on src/main/modules/i18n/locales/en.json
> +    "CLAIMANT_DEBT_RESPITE_CHECK_ANSWERS": {
CLAIMANT_DEBT_RESPITE_CHECK_ANSWERS  is fine, I can see the Gap, maybe if related tasks are merge will solve the issue.

2022-11-28 09:23 UTC, pascalkankonde commented on src/main/services/features/breathingSpace/checkAnswersService.ts
> +    sections: [
I have test for that implantation in this files src/test/unit/services/features/breathingSpace/buildDebtRespiteSection.test.ts   there is  buildSummarySections implation which is called in checkAnswersService

2022-11-28 11:29 UTC, laarmada approved these changes

2022-11-28 11:29 UTC, laarmada commented
I think you will have a sonar issue..

2022-12-01 09:10 UTC, closed without merging