CIV:6054:Claimant Intent - Part admit + pay set by date - How they want to pay.
hmcts/civil-citizen-ui pull request #1179
Opened 2022-12-01 16:03 UTC by neeta-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-6054

### Change description ###
added a new screen for claimantIntent : Part admit + set by date scenario.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-12-01 17:27 UTC, laperla11 requested changes

2022-12-01 17:27 UTC, laperla11 commented on src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
> +        paid_by_date: formatDateToFullDate(claim.partialAdmission.paymentIntention.paymentDate),
pls use camel case here

2022-12-01 17:27 UTC, laperla11 commented on src/main/views/features/claimantResponse/how-they-want-to-pay-response.njk
> +              by_date: paid_by_date}) }}
pls use camel case here

2022-12-01 17:58 UTC, neeta-hmcts commented on src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
> +        paid_by_date: formatDateToFullDate(claim.partialAdmission.paymentIntention.paymentDate),
done

2022-12-01 17:58 UTC, neeta-hmcts commented on src/main/views/features/claimantResponse/how-they-want-to-pay-response.njk
> +              by_date: paid_by_date}) }}
done

2022-12-02 11:39 UTC, laperla11 approved these changes

2023-01-19 10:34 UTC, merged