CIV_5668 : Claimant Intent - Request a CCJ - Judgement amount calculation
hmcts/civil-citizen-ui pull request #1182
Opened 2022-12-05 15:48 UTC by neeta-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-5668

### Change description ###
Claimant Intent - Request a CCJ - Judgement amount calculation

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-12-05 16:35 UTC, TatsyMaslova approved these changes

2022-12-05 16:45 UTC, RosDiaf submitted a review, later dismissed

2023-01-30 09:27 UTC, laarmada requested changes

2023-01-30 09:27 UTC, laarmada commented on src/main/common/models/civilClaimResponse.ts
> +export interface ClaimFeeData {
duplicated function

2023-01-30 09:27 UTC, laarmada commented on src/main/common/models/claim.ts
> +    return !!this.directionQuestionnaire?.hearing?.supportRequiredList;
why !! is not the same as nothing?

2023-01-30 09:27 UTC, laarmada commented on src/main/common/models/claim.ts
> +    return this.claimInterest?.toLowerCase() === YesNo.YES;
why toLowerCase() function if YesNo is lowerCase:
export enum YesNo {
  YES = 'yes',
  NO = 'no'
}

2023-01-30 09:27 UTC, laarmada commented on src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
> +  const claimFee = await civilServiceClient.getClaimAmountFee(claim?.totalClaimAmount, req);
the await function should be under try/catch....

2023-01-30 09:27 UTC, laarmada commented on src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
> +  const claimFee = await civilServiceClient.getClaimAmountFee(claim?.totalClaimAmount, req);
the best aproach should be do into the get....

2023-01-30 09:32 UTC, laarmada approved these changes

2023-01-30 11:00 UTC, neeta-hmcts commented on src/main/common/models/claim.ts
> +    return !!this.directionQuestionnaire?.hearing?.supportRequiredList;
this was the old function.. just during conflict fix its position has changed. I am not sure the use of this.

2023-01-30 11:01 UTC, neeta-hmcts commented on src/main/common/models/civilClaimResponse.ts
> +export interface ClaimFeeData {
fixed

2023-01-30 11:03 UTC, neeta-hmcts commented on src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
> +  const claimFee = await civilServiceClient.getClaimAmountFee(claim?.totalClaimAmount, req);
Fixed it.

2023-01-30 11:04 UTC, neeta-hmcts commented on src/main/common/models/claim.ts
> +    return this.claimInterest?.toLowerCase() === YesNo.YES;
claimInterest - returns 'Yes' when interest is set.. hence I have to convert it to lower case.

2023-01-30 17:21 UTC, laperla11 approved these changes

2023-01-30 18:32 UTC, TatsyMaslova commented on src/main/common/models/claim.ts
> +    return this.claimInterest?.toLowerCase() === YesNo.YES;
I think we also have camel case yesno lol

2023-01-30 22:12 UTC, portizdev approved these changes

2023-01-31 08:01 UTC, LeonardoPalmeiro requested changes

2023-01-31 08:25 UTC, laarmada commented on src/main/common/models/claim.ts
> +    return this.claimInterest?.toLowerCase() === YesNo.YES;
![image](https://user-images.githubusercontent.com/23473639/215706824-59f76000-609d-4488-964c-14c972457137.png)

2023-01-31 08:28 UTC, laarmada requested changes

2023-01-31 08:28 UTC, laarmada commented on src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
> +  const claimFee = await civilServiceClient.getClaimAmountFee(claim?.totalClaimAmount, req);
that two:
  const claimFee = await civilServiceClient.getClaimAmountFee(claim?.totalClaimAmount, req);
  const judgmentSummaryDetails = getJudgmentAmountSummary(claim, claimFee, lang);

should be into .get and there into try{

2023-01-31 09:27 UTC, neeta-hmcts commented on src/main/common/models/claim.ts
> +    return this.claimInterest?.toLowerCase() === YesNo.YES;
Yes. We do have this but somehow I was not able to use it and hence used this approach. I was not sure where the claimInterest value sets hence I have not touched it.

2023-01-31 09:28 UTC, neeta-hmcts commented on src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
> +  const claimFee = await civilServiceClient.getClaimAmountFee(claim?.totalClaimAmount, req);
got it.. I will note down this comment and in my next CUI ticket I will fix it.

2023-01-31 09:31 UTC, neeta-hmcts commented on src/main/services/features/claimantResponse/ccj/judgmentAmountSummaryService.ts
> +    ...interestDetails,
yes.. interestDetails  has other variables which was required in template so instead passing individual field.. used spread operator.

2023-01-31 09:35 UTC, neeta-hmcts commented on src/main/views/features/claimantResponse/ccj/judgement-amount-summary.njk
> +                            <th scope="col" class="govuk-table__header govuk-!-text-align-right">{{ t('') }}</th>
this is intentionally added as I want to have a column like this  
![image](https://user-images.githubusercontent.com/115545612/215722830-82595c9e-f13e-49e0-a5c4-1678f36177ed.png)

2023-01-31 09:40 UTC, neeta-hmcts commented on src/test/unit/routes/features/claim/totalAmountController.test.ts
> +        .reply(200, {'calculatedAmountInPence': '50'});
ok.. I will note down and update it.

2023-01-31 09:40 UTC, neeta-hmcts commented on src/main/modules/i18n/locales/en.json
> +      "HOW_INTEREST_IS_CALCULATED": "Interest calculated as \"{{ reason }}\" for {{numberOfDays}} days."
I want to add a  this " special char hence added \

2023-01-31 11:53 UTC, laarmada commented on src/main/common/models/claim.ts
> +    return this.claimInterest?.toLowerCase() === YesNo.YES;
ok

2023-01-31 11:55 UTC, laarmada approved these changes

2023-01-31 13:26 UTC, LeonardoPalmeiro commented on src/main/views/features/claimantResponse/ccj/judgement-amount-summary.njk
> +                            <th scope="col" class="govuk-table__header govuk-!-text-align-right">{{ t('') }}</th>
in this case we could use &nbsp instead of call function t{''} because this could be add some unintentional bugs in the future.
but this is totally up to you.

2023-01-31 13:52 UTC, LeonardoPalmeiro commented on src/main/services/features/claimantResponse/ccj/judgmentAmountSummaryService.ts
> +    ...interestDetails,
as we talked this is really necessary to populate information in the view part

2023-01-31 13:53 UTC, LeonardoPalmeiro approved these changes
LGTM

2023-01-31 15:28 UTC, merged