CIV-5681 CCJ check answers
hmcts/civil-citizen-ui pull request #1250
Opened 2023-01-04 14:13 UTC by KyleMulvihillV1

2023-01-04 14:24 UTC, TatsyMaslova commented on src/main/common/form/models/claimantResponse/ccj/ccjPaymentOption.ts
> +      return 'By instalments';
what about translation of these to welsh?

2023-01-04 14:35 UTC, portizdev requested changes

2023-01-04 14:35 UTC, portizdev commented on src/main/modules/i18n/locales/en.json
> +      "PAYMENT_TITLE": "Payment",
Make sure you always use the same lines in the en and cy files.

2023-01-04 14:36 UTC, portizdev commented on src/main/services/features/claim/checkAnswers/financialSection/buildPaymentSection.ts
> +      return 'Each week';
Same as Tanya says. Use always key translations.

2023-01-05 17:01 UTC, laperla11 requested changes

2023-01-05 17:01 UTC, laperla11 commented on src/main/services/features/claim/checkAnswers/financialSection/buildPaymentSection.ts
> +        formatDateToFullDate(claim.claimantResponse.ccjRequest.defendantPaymentDate.date)));
you need to pass the `lng` as a second argument to translate month

2023-01-05 17:01 UTC, laperla11 commented on src/main/services/features/claim/checkAnswers/financialSection/buildPaymentSection.ts
> +        formatDateToFullDate(claim.claimantResponse.ccjRequest.repaymentPlanInstalments.firstPaymentDate.date)));
you need to pass the `lng` as a second argument to translate month

2023-01-06 13:06 UTC, laperla11 approved these changes

2023-01-06 13:11 UTC, TatsyMaslova commented on src/test/unit/services/features/claim/checkAnswers/financialSection/buildPaymentSection.test.ts
> +    expect(summarySections.sections[constVal.INDEX_CCJ_PAYMENT_SECTION].title).toBe('PAGES.CHECK_YOUR_ANSWER.PAYMENT_TITLE');
didn't Sampan say it slows down the tests when we are importing everything form constVal? i remember when he was fixing unit tests he was removing it

2023-01-06 13:13 UTC, TatsyMaslova commented on src/test/utils/checkAnswersConstants.ts
> +export const INDEX_CCJ_PAYMENT_SECTION = 1;
i think easier not to add this but just use the index 0 and 1 in the test to make it quicker

2023-01-06 13:56 UTC, TatsyMaslova approved these changes

2023-01-09 09:35 UTC, portizdev approved these changes

2023-01-24 14:44 UTC, merged