updated defendent claims on dashboard
hmcts/civil-citizen-ui pull request #1274
Opened 2023-01-16 09:01 UTC by kamilewandowski

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-6145

### Change description ###
update status for defendant claims

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-16 09:45 UTC, laarmada requested changes

2023-01-16 09:45 UTC, laarmada commented on src/main/services/features/claimantResponse/defendantResponse/defendantResponseStatusService.ts
> +      if(claim.fullAdmission.paymentIntention.paymentOption == PaymentOptionType.IMMEDIATELY ||
should we have a break for each case statement?

2023-01-16 09:45 UTC, laarmada commented on src/test/unit/routes/features/dashboard/dashboardController.test.ts
> +    // it('should return dashboard page', async () => {
remove or uncomment that part :)

2023-01-16 09:52 UTC, GorilaNaranja commented on src/main/common/form/models/admission/paymentOption/paymentOptionType.ts
> +  BY_SPECIFIED_DATE = 'BY_SPECIFIED_DATE'
Why are you adding one more payment option? I think it is not related to your ticket. "BY_SET_DATE" is by a specified date.

2023-01-16 09:52 UTC, GorilaNaranja commented on src/main/common/models/DefendantResponseStatus.ts
> +  ELIGIBLE_FOR_CCJ_AFTER_FULL_ADMIT_PAY_IMMEDIATELY_PAST_DEADLINE = 'ELIGIBLE_FOR_CCJ_AFTER_FULL_ADMIT_PAY_IMMEDIATELY_PAST_DEADLINE',
We should find a shorter variable name

2023-01-16 09:59 UTC, GorilaNaranja commented on src/main/common/models/claim.ts
> +  getDefendantResponseStatus(): string {
We don't need a method to return directly the variable. We can access that status directly claim.defendantResponseStatus.

We use a method when we want to return a variable that needs some calculation/transformation.

2023-01-16 09:59 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/cy.json
> +      "ELIGIBLE_FOR_CCJ_1": "You haven't responded to the claim. ",
In development we shouldn't use numbers, we should use a descriptive name because when other devs use your code they won't know what is CCJ_1, CCJ_2 and CCJ_3.

2023-01-16 10:10 UTC, GorilaNaranja commented on src/main/routes/features/dashboard/dashboardController.ts
> +    for(let i = 0; i < claimsAsDefendant.length; i++) {
Instead use "for" you should use a map in this case because you want to take an array and apply some changes to its items. In other circumstances, I recommend you to use "forEach" and not a "for".

https://www.freecodecamp.org/news/javascript-map-how-to-use-the-js-map-function-array-method/

2023-01-16 14:34 UTC, kamilewandowski commented on src/test/unit/routes/features/dashboard/dashboardController.test.ts
> +    // it('should return dashboard page', async () => {
test uncommented and updated.

2023-01-16 14:35 UTC, kamilewandowski commented on src/main/common/form/models/admission/paymentOption/paymentOptionType.ts
> +  BY_SPECIFIED_DATE = 'BY_SPECIFIED_DATE'
As we discussed I remove it and use BY_SET_DATE instead

2023-01-16 14:36 UTC, kamilewandowski commented on src/main/common/models/claim.ts
> +  getDefendantResponseStatus(): string {
done.

2023-01-16 14:37 UTC, kamilewandowski commented on src/main/modules/i18n/locales/cy.json
> +      "ELIGIBLE_FOR_CCJ_1": "You haven't responded to the claim. ",
updated with a name replacing number

2023-01-17 08:39 UTC, GorilaNaranja commented on src/main/routes/features/dashboard/dashboardController.ts
> +  if(claimsAsDefendant != undefined) {
Please use Strict Equality Comparison (!== or ===). In this case you can check if claimAsDefendant exists like that: `if(claimsAsDefendant) {`

https://262.ecma-international.org/11.0/#sec-strict-equality-comparison

2023-01-17 08:39 UTC, GorilaNaranja commented on src/main/services/features/claimantResponse/defendantResponse/defendantResponseStatusService.ts
> +      if(claim.fullAdmission.paymentIntention.paymentOption == PaymentOptionType.IMMEDIATELY ||
We have methods in Claim class to get that info easier, please use them in all the ifs. For example:
`claim.isFAPaymentOptionPayImmediately()`
`claim.isPAPaymentOptionPayImmediately()`

2023-01-17 08:39 UTC, GorilaNaranja commented on src/main/services/features/claimantResponse/defendantResponse/defendantResponseStatusService.ts
> +  } else if(days == 0) {
Triple operator (strict equality operator)

2023-01-17 08:42 UTC, laarmada approved these changes

2023-01-17 09:27 UTC, laperla11 submitted a review, later dismissed

2023-01-17 09:28 UTC, laperla11 reviewed
it's best practice to use `===` instad of `==` and `!==` instead of `!=` in JS

2023-01-17 12:41 UTC, kamilewandowski commented on src/main/routes/features/dashboard/dashboardController.ts
> +  if(claimsAsDefendant != undefined) {
done

2023-01-17 12:41 UTC, kamilewandowski commented on src/main/services/features/claimantResponse/defendantResponse/defendantResponseStatusService.ts
> +      if(claim.fullAdmission.paymentIntention.paymentOption == PaymentOptionType.IMMEDIATELY ||
replaced with methods

2023-01-17 12:41 UTC, kamilewandowski commented on src/main/services/features/claimantResponse/defendantResponse/defendantResponseStatusService.ts
> +  } else if(days == 0) {
done

2023-01-17 13:01 UTC, GorilaNaranja approved these changes

2023-01-18 13:17 UTC, GorilaNaranja commented on src/main/common/models/claim.ts
> +  defendantResponseStatus: string;
Can you use type type DefendantResponseStatus:
`defendantResponseStatus: DefendantResponseStatus;`

2023-01-18 13:17 UTC, GorilaNaranja commented on src/main/common/models/DefendantResponseStatus.ts
> +}
Please change the name of the file to "defendantResponseStatus.ts" in lowercase

2023-02-20 15:47 UTC, TatsyMaslova commented
reopen for testing

2023-02-20 19:13 UTC, TatsyMaslova commented
wrong pull request

2023-02-20 19:13 UTC, closed without merging