CIV-6131/Claimant response task list-P1
hmcts/civil-citizen-ui pull request #1287
Opened 2023-01-20 12:18 UTC by laperla11

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-01-27 14:50 UTC, laarmada approved these changes

2023-01-27 14:50 UTC, laarmada commented on src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
> +      await saveClaimantResponse(claimId, true, 'defendantResponseViewed');
use a constant instead of text: 'defendantResponseViewed'

2023-01-27 14:53 UTC, laarmada commented on src/main/services/features/response/taskListService.ts
> -
move the file one level above?

2023-01-27 15:09 UTC, GorilaNaranja approved these changes

2023-01-30 07:40 UTC, laperla11 commented on src/main/routes/features/claimantResponse/claimantResponseTasklistController.ts
> +import {getDescription, getTitle} from '../../../services/features/response/taskListService';
resolved

2023-01-30 07:40 UTC, laperla11 commented on src/main/services/features/response/taskListService.ts
> -
resolved

2023-01-30 07:40 UTC, laperla11 commented on src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
> +      await saveClaimantResponse(claimId, true, 'defendantResponseViewed');
resolved

2023-01-30 08:30 UTC, GorilaNaranja submitted a review, later dismissed

2023-01-30 08:35 UTC, laarmada approved these changes

2023-01-30 08:35 UTC, LeonardoPalmeiro requested changes

2023-01-30 08:35 UTC, LeonardoPalmeiro commented on src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
> +    if (!this.hearing?.whyUnavailableForHearing) {
Might be an option to change this with ternary operator.
What do you thing about it?

2023-01-30 08:35 UTC, LeonardoPalmeiro commented on src/main/routes/features/directionsQuestionnaire/experts/expertSmallClaimsController.ts
> +  try {
remove extra empty space.

2023-01-30 08:35 UTC, LeonardoPalmeiro commented on src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
> +      this.welshLanguageRequirements?.language
please, could you add some unit test in this? if it is possible.

2023-01-30 08:35 UTC, LeonardoPalmeiro commented on src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
> +    if (!this.hearing?.whyUnavailableForHearing) {
as well added unit test in here

2023-01-30 13:31 UTC, GorilaNaranja submitted a review, later dismissed

2023-01-31 15:46 UTC, LeonardoPalmeiro submitted a review, later dismissed
LGTM

2023-02-03 12:50 UTC, GorilaNaranja approved these changes

2023-02-03 12:51 UTC, laarmada approved these changes

2023-02-03 12:52 UTC, LeonardoPalmeiro approved these changes

2023-02-06 09:48 UTC, merged