CIV-5511 - Check your answers - Fast Track - Hearing Requirements Pt1
hmcts/civil-citizen-ui pull request #1337
Opened 2023-02-06 12:38 UTC by neeta-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-5511

### Change description ###
Check your answers - Fast Track - Hearing Requirements  changes for 3 screens 
1. tried to settle claim
2. request extra 4 week time
3. any claimant doc that they want court to consider.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-06 13:36 UTC, LeonardoPalmeiro requested changes

2023-02-06 13:36 UTC, LeonardoPalmeiro commented on src/main/common/models/claim.ts
> +  get claimType(): claimType {
what happened when totalClaimAmount is greater than 25000?

2023-02-06 13:36 UTC, LeonardoPalmeiro commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.test.ts
>  import {Witnesses} from '../../../../../../../main/common/models/directionsQuestionnaire/witnesses/witnesses';
maybe this Import can be shortened

2023-02-06 14:39 UTC, neeta-hmcts commented on src/main/common/models/claim.ts
> +  get claimType(): claimType {
That would be MultiTrack Claim (if claimAmount > 25K) I am not sure about it.

2023-02-06 14:40 UTC, neeta-hmcts commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.test.ts
>  import {Witnesses} from '../../../../../../../main/common/models/directionsQuestionnaire/witnesses/witnesses';
yes.. done.

2023-02-06 15:04 UTC, hmcts-version1-domini commented on src/main/modules/i18n/locales/cy.json
> +      "CONSIDER_CLAIMANT_DOCUMENT" : "Are there any documents the claimant has that you want the court to consider?",
We should put the keys in alphatecial order here.

2023-02-06 15:27 UTC, neeta-hmcts commented on src/main/modules/i18n/locales/cy.json
> +      "CONSIDER_CLAIMANT_DOCUMENT" : "Are there any documents the claimant has that you want the court to consider?",
oh.. sorry I missed this. Thanks for noticing. Fixed it.

2023-02-06 15:27 UTC, neeta-hmcts commented on src/main/modules/i18n/locales/en.json
> +      "CONSIDER_CLAIMANT_DOCUMENT" : "Are there any documents the claimant has that you want the court to consider?",
fixed

2023-02-06 15:54 UTC, GorilaNaranja commented on src/main/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.ts
> +    //TODO : add small claim related row's
Is that part of other ticket?

2023-02-06 16:31 UTC, neeta-hmcts commented on src/main/common/models/claim.ts
> +    if (this.totalClaimAmount <= 10000) {
done.

2023-02-06 16:31 UTC, neeta-hmcts commented on src/main/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.ts
> +    //TODO : add small claim related row's
Yes.. Its a different ticket.

2023-02-06 16:56 UTC, PaulH-HMCTS commented on src/main/common/models/claim.ts
> +    if (this.totalClaimAmount <= 10000) {
I think it would be nice to move this logic alongside the enum itself - i.e. add a namespace in the claimType.ts file which will provide functions that relate to the enum itself. So add something like this (but with constants as suggested by Felipe):

namespace claimType {
  export function parse(amount): claimType {
    if (amount <= 10000) {
     	      return claimType.SMALL_CLAIM;
    } else if (this.totalClaimAmount < 25000) {
      return claimType.FAST_TRACK_CLAIM;
    }
  }
}

Then you should be able to call `claimType.parse(this.totalClaimAmount)` here.

2023-02-06 16:56 UTC, PaulH-HMCTS commented on src/main/common/form/models/claimType.ts
> +  SMALL_CLAIM = 'SMALL_CLAIM',
Does this need to be a string enum or can we use a constant enum (i.e. without the string literals)

2023-02-06 16:56 UTC, PaulH-HMCTS commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.test.ts
> +  it('build hearing requirement for Fast Track Claim when there is no witnesses', () => {
```suggestion
  it('build hearing requirement for Fast Track Claim when there are no witnesses', () => {
```

2023-02-07 08:25 UTC, GorilaNaranja approved these changes

2023-02-07 09:32 UTC, laperla11 approved these changes

2023-02-07 09:32 UTC, laperla11 commented on src/main/common/models/claim.ts
> +  get claimType(): claimType {
CUI is responsible for only claims up to 25K, if it is more than 25K it shouldn't come to CUI it becomes a damages claim.

2023-02-07 11:36 UTC, neeta-hmcts commented on src/main/common/models/claim.ts
> +    if (this.totalClaimAmount <= 10000) {
modified this logic as per suggestion but instead namespace I used export function

2023-02-07 11:36 UTC, neeta-hmcts commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.test.ts
> +  it('build hearing requirement for Fast Track Claim when there is no witnesses', () => {
fixed

2023-02-07 11:37 UTC, neeta-hmcts commented on src/main/common/form/models/claimType.ts
> +  SMALL_CLAIM = 'SMALL_CLAIM',
can be constant enum.. I referred existing enum for this

2023-02-07 12:36 UTC, GorilaNaranja submitted a review, later dismissed

2023-02-07 12:40 UTC, LeonardoPalmeiro commented on src/main/common/models/claim.ts
> +  get claimType(): claimType {
Perfect. @Kadir thank you for the explanation.

2023-02-07 13:43 UTC, PaulH-HMCTS submitted a review, later dismissed

2023-02-08 13:14 UTC, GorilaNaranja submitted a review, later dismissed

2023-02-08 13:43 UTC, LeonardoPalmeiro approved these changes

2023-02-15 11:04 UTC, TatsyMaslova commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.test.ts
> +  it('build hearing requirement for Fast Track Claim when there are no witnesses', () => {
Given when then please?

2023-02-15 11:04 UTC, TatsyMaslova commented on src/test/unit/common/models/claim.test.ts
> +    it('Its a small claim', () => {
given when then please

2023-02-15 13:14 UTC, portizdev approved these changes

2023-02-15 13:18 UTC, LeonardoPalmeiro commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.test.ts
> +    claim.directionQuestionnaire.hearing = {
we can create a method or constant, what do you think?

2023-02-15 16:04 UTC, LeonardoPalmeiro commented on src/test/unit/common/models/claim.test.ts
> +    it('Its a small claim', () => {
Good spot.

2023-02-15 16:11 UTC, TatsyMaslova submitted a review, later dismissed

2023-02-15 16:16 UTC, PaulH-HMCTS approved these changes

2023-02-16 12:02 UTC, portizdev approved these changes

2023-02-16 12:28 UTC, TatsyMaslova approved these changes

2023-02-16 12:51 UTC, merged