CIV-6874 - Missing values in claim summary
hmcts/civil-citizen-ui pull request #1339
Opened 2023-02-06 16:24 UTC by portizdev

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-6874
https://tools.hmcts.net/jira/browse/CIV-6907

### Change description ###
- Translation of CCD model in CUI
- Refactoring of the endpoint

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-02-07 08:23 UTC, TatsyMaslova approved these changes

2023-02-07 10:01 UTC, LeonardoPalmeiro requested changes

2023-02-07 10:04 UTC, laperla11 approved these changes

2023-02-07 10:34 UTC, PaulH-HMCTS commented on src/main/services/translation/convertToCUI/convertToCUIEvidence.ts
> +const convertToCUIEvidenceType = (type: CCDEvidenceType) => {
I think it is better to remove these sort of enum conversion functions into a namespace class within the enum ts file. So you could add a parse function there that takes the CCDEvidenceType and returns the relevant EvidenceType.
I prefer this because the enum related logic is encapsulated then within the relevant file so it's easier to maintain but I appreciate that this is probably how other transformations are done for other types so you can leave as it is if you prefer.

2023-02-07 11:37 UTC, portizdev commented on src/main/services/translation/convertToCUI/convertToCUIEvidence.ts
> +    cuiEvidenceItems.push(evidenceItem);
From my point of view it is clearer as it is. Wecreate an intermediate object before with the type of CCDEvidence and push it once created.
Putting it directly in the push would lose the type declaration (const ccdEvidence: CCDEvidence) which I think facilitates the compression of the function.

The option of creating a separate method could be done, even if it only returns what is inside the {}.

2023-02-07 11:37 UTC, portizdev commented on src/main/services/translation/convertToCUI/convertToCUIClaimDetails.ts
> +import {CCDClaim} from '../../../common/models/civilClaimResponse';
Sure

2023-02-07 11:38 UTC, portizdev commented on src/main/services/translation/convertToCUI/convertToCUIClaimDetails.ts
> +  //TODO: Add all other translations for the claimDetails fields
I don't think we have it although it must be in the scope of release 2. I think for release one we only need detailsOfClaim from the elements inside ClaimDetails, but I'm not sure.

2023-02-07 12:38 UTC, LeonardoPalmeiro approved these changes
LGTM

2023-02-07 12:38 UTC, LeonardoPalmeiro commented on src/main/services/translation/convertToCUI/convertToCUIEvidence.ts
> +    cuiEvidenceItems.push(evidenceItem);
I agree. thanks.

2023-02-07 13:53 UTC, PaulH-HMCTS submitted a review, later dismissed

2023-02-09 14:33 UTC, hmcts-version1-domini approved these changes

2023-02-09 14:33 UTC, TatsyMaslova approved these changes

2023-02-09 14:34 UTC, PaulH-HMCTS approved these changes

2023-02-09 14:37 UTC, LeonardoPalmeiro approved these changes
LGMT

2023-02-09 17:25 UTC, merged