Civ 5469 dates added calculation
hmcts/civil-citizen-ui pull request #1344
Opened 2023-02-08 16:05 UTC by GorilaNaranja

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-5469

### Change description ###
Defendant Response - DQ - Dates Added Calculation

### URL ###
http://localhost:3001/case/6666/directions-questionnaire/availability-dates

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-09 09:29 UTC, laperla11 requested changes
We already have this hardcoded function `getCalculatedDays` used in `whyUnavailableForHearingController`, you could either update existing function or delete the hardcoded function and use your newly created function in `whyUnavailableForHearingController`.

2023-02-09 10:06 UTC, LeonardoPalmeiro approved these changes
LGTM

2023-02-09 11:00 UTC, laarmada requested changes

2023-02-09 11:00 UTC, laarmada commented on src/main/common/models/directionsQuestionnaire/hearing/unavailableDates.ts
> +export enum UnavailableDateType {
One question about that.... if we have the enum in that file instead of a individual one and we are importing the file in the nunjuck file ... Are we importing the hole file? that's is also for other files that use that enum...

2023-02-09 11:00 UTC, laarmada commented on src/main/routes/features/directionsQuestionnaire/hearing/unavailableDatesForHearingController.ts
> +    const form = new GenericForm(unavailableDatesForHearing);
that validation works fine without new of unavailableDatesForHearing???

2023-02-09 11:00 UTC, laarmada commented on src/main/routes/features/directionsQuestionnaire/hearing/unavailableDatesForHearingController.ts
> +    const form = new GenericForm(unavailableDatesForHearing);
How is taking the errors from the validation in the class?

2023-02-09 11:00 UTC, laarmada commented on src/main/services/features/directionsQuestionnaire/hearing/unavailableDatesForHearingService.ts
> +      return new UnavailableDatePeriod(UnavailableDateType.SINGLE_DATE, item.single.start, undefined);
why is necessary to send undefined? is not optional?

2023-02-09 11:00 UTC, laarmada commented on src/main/services/features/directionsQuestionnaire/hearing/unavailableDatesForHearingService.ts
> +    return new UnavailableDatePeriod(undefined);
why is necessary to send undefined? is not optional?

2023-02-09 11:05 UTC, GorilaNaranja commented on src/main/routes/features/directionsQuestionnaire/hearing/unavailableDatesForHearingController.ts
> +    const form = new GenericForm(unavailableDatesForHearing);
getUnavailableDatesForm() returns a new UnavailableDates

2023-02-09 11:17 UTC, GorilaNaranja commented on src/main/services/features/directionsQuestionnaire/hearing/unavailableDatesForHearingService.ts
> +    return new UnavailableDatePeriod(undefined);
done

2023-02-09 11:19 UTC, GorilaNaranja commented on src/main/common/models/directionsQuestionnaire/hearing/unavailableDates.ts
> +export enum UnavailableDateType {
In nunjuck we are not importing the whole file, we only import "UnavailableDateType"

2023-02-09 11:24 UTC, portizdev approved these changes

2023-02-09 11:39 UTC, laarmada approved these changes

2023-02-09 14:35 UTC, laarmada submitted a review, later dismissed

2023-02-09 17:01 UTC, laperla11 approved these changes

2023-02-10 12:21 UTC, laarmada approved these changes

2023-02-10 13:07 UTC, laperla11 approved these changes

2023-02-15 09:11 UTC, merged