CIV-5408 Longer period of time
hmcts/civil-citizen-ui pull request #1350
Opened 2023-02-09 22:03 UTC by laperla11

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-5408

### Change description ###
Develop the 'Add a longer period of time" on unavailable for hearing screen

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-10 09:49 UTC, laarmada requested changes

2023-02-10 09:49 UTC, laarmada commented on src/main/routes/features/directionsQuestionnaire/hearing/cantAttendHearingInNext12MonthsController.ts
>  import {GenericForm} from '../../../../common/form/models/genericForm';
we could try to cut the import url when we are modify this file....

2023-02-10 09:49 UTC, laarmada commented on src/main/routes/features/directionsQuestionnaire/witnesses/otherWitnessesController.ts
>  import {OtherWitnesses} from '../../../../common/models/directionsQuestionnaire/witnesses/otherWitnesses';
same here about cut urls

2023-02-10 09:49 UTC, laarmada commented on src/main/services/features/directionsQuestionnaire/hearing/unavailableDatesForHearingService.ts
> +    if (item.type === UnavailableDateType.SINGLE_DATE) {
should we replace all that code:
 if (item.type === UnavailableDateType.SINGLE_DATE) {
return new UnavailableDatePeriod(UnavailableDateType.SINGLE_DATE, item.single.start);
    }
    if (item.type === UnavailableDateType.LONGER_PERIOD) {
      return new UnavailableDatePeriod(UnavailableDateType.LONGER_PERIOD, item.period.start, item.period.end);
    }

for: 
 if (item?.type) {
    return new UnavailableDatePeriod(item.type, item.period.start, item.period.end);
 }

2023-02-10 09:49 UTC, laarmada commented
really nice that idea:
@MaxDate(addMonths(new Date(), 12), { message: generateErrorMessageForMaxDate })

2023-02-10 10:25 UTC, laarmada submitted a review, later dismissed

2023-02-10 10:26 UTC, laarmada commented on src/main/services/features/directionsQuestionnaire/hearing/unavailableDatesForHearingService.ts
> +    if (item.type === UnavailableDateType.SINGLE_DATE) {
we will discuss offline

2023-02-10 12:33 UTC, TatsyMaslova approved these changes

2023-02-10 13:05 UTC, portizdev submitted a review, later dismissed

2023-02-14 17:12 UTC, pascalkankonde approved these changes

2023-02-14 17:51 UTC, laarmada approved these changes

2023-02-14 18:07 UTC, TatsyMaslova approved these changes

2023-02-15 08:26 UTC, LeonardoPalmeiro approved these changes
LGTM

2023-02-15 09:11 UTC, merged