Features/civ 5984 check your answers fast track hearing requirements pt2
hmcts/civil-citizen-ui pull request #1361
Opened 2023-02-14 09:25 UTC by pascalkankonde

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-5984

### Change description ###

The scope of this ticket is to develop the 'Check your answers before submitting' screen in the scenario where the Defendant has fully admitted and offered to pay by a set date. This screen occurs after the citizen has clicked on the "Notify us about the debt respite scheme" option on the latest update section.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ n] No
```

2023-02-14 14:34 UTC, laarmada requested changes

2023-02-14 14:34 UTC, laarmada commented on src/main/common/models/claim.ts
> +
I think we are overload the functionality:
export function analyseClaimType(totalClaimAmount: number): claimType {
  
get isSmallClaimsTrackDQ(): boolean {

 get isFastTrackClaim(): boolean {

at the end 3 function for only one scope to know if is small or fast

2023-02-14 14:34 UTC, laarmada commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildSmallHearingRequirments.test.ts
> +jest.mock('../../../../../../../main/modules/draft-store/draftStoreService');
you dont need the draft-store twice...

2023-02-15 09:10 UTC, TatsyMaslova commented on src/main/common/models/claim.ts
> +
I don't know Sergio. i prefer it in the claim like that.

2023-02-15 09:13 UTC, TatsyMaslova commented on src/main/services/features/response/checkAnswers/hearingRequirementsSection/buildFastTrackHearingRequirements.ts
> +  console.log(JSON.stringify(hearingRequirementsSection));
perhaps this needs to be removed

2023-02-15 09:14 UTC, TatsyMaslova commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildFastTrackHearingRequirements.test.ts
> +      const claim = new Claim();
Given When Then please

2023-02-15 14:30 UTC, laarmada commented on src/main/common/models/claim.ts
> +
yes I agree it should be in the claim.ts but the three function have the same scope... I think we can do the same only with only one function...

2023-02-16 13:13 UTC, closed without merging