Welsh translation
hmcts/civil-citizen-ui pull request #1363
Opened 2023-02-14 17:19 UTC by pascalkankonde

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-7011

### Change description ###

The scope of this ticket is to develop Welsh content translation of the following screens: 

DQ- Welsh Language
DQ - Why are you, your experts or witnesses unavailable for a hearing for <xx> days

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-02-15 07:20 UTC, portizdev requested changes

2023-02-15 07:20 UTC, portizdev commented on src/main/modules/i18n/locales/cy.json
>        "PAGE_TITLE": "Why are they not available for hearing?",
We don't have a translation of the PAGE_TITLE? If not, you have to request it before the translation of the screen is finished.

2023-02-15 07:20 UTC, portizdev commented on src/main/modules/i18n/locales/cy.json
> +      "ENGLISH": "Cymraeg",
If you have created the ENGLISH and WELSH_AND_ENGLISH keys above, why don't you use them on all screens and reduce the number of lines in these files?

2023-02-15 07:20 UTC, portizdev commented on src/main/modules/i18n/locales/en.json
> +    "WELSH": "Welsh",
Where do you use these keys you have created? Since you have created it in COMMON, you can refactor the pages that have ENGLISH or WELSH_AND_ENGLISH created to use the COMMON ones and avoid redundancy (the same as I said before).

2023-02-15 09:06 UTC, TatsyMaslova commented on src/main/modules/i18n/locales/cy.json
> +      "ENGLISH": "Cymraeg",
this is a very strange key. perhaps it should say LANGUAGE?

2023-02-15 09:08 UTC, TatsyMaslova commented on src/main/modules/i18n/locales/cy.json
>        "PAGE_TITLE": "Why are they not available for hearing?",
I think the translation would be the same as title. so probably should add that?

2023-02-15 09:14 UTC, pascalkankonde commented on src/main/modules/i18n/locales/cy.json
> +      "ENGLISH": "Cymraeg",
this English key, under BILINGUAL_LANGUAGE_PREFERENCE

2023-02-15 09:49 UTC, portizdev commented on src/main/modules/i18n/locales/cy.json
>        "PAGE_TITLE": "Why are they not available for hearing?",
They are not exactly the same:
"PAGE_TITLE": "Why are they not available for hearing?",
"TITLE": "Why are you, your experts or witnesses unavailable for a hearing for {{days}} days?"

2023-02-15 10:07 UTC, pascalkankonde commented on src/main/modules/i18n/locales/cy.json
> +      "ENGLISH": "Cymraeg",
This Key was existing in en.json created by Felipe on 03/10/2022  to make it identique then I added there. I have created in COMMON ENGLIS AN WELSH for future use. This require refactoring if I removed the key from.

2023-02-15 10:07 UTC, pascalkankonde commented on src/main/modules/i18n/locales/en.json
> +    "WELSH": "Welsh",
This Key was existing in en.json created by Felipe on 03/10/2022  to make it identique then I added there. I have created in COMMON ENGLIS AN WELSH for future use. This require refactoring if I removed the key from.

2023-02-15 10:07 UTC, pascalkankonde commented on src/main/modules/i18n/locales/cy.json
> +      "ENGLISH": "Cymraeg",
This Key was existing in en.json created by Felipe on 03/10/2022  to make it identique then I added there. I have created in COMMON ENGLIS AN WELSH for future use. This require refactoring if I removed the key from.

2023-02-15 10:11 UTC, pascalkankonde commented on src/main/modules/i18n/locales/cy.json
>        "PAGE_TITLE": "Why are they not available for hearing?",
Okay I have to request

2023-02-15 13:33 UTC, portizdev commented on src/main/modules/i18n/locales/cy.json
> +      "ENGLISH": "Cymraeg",
I don't think they were so big changes as to need a techdebt. I mark as resolved, as it is strictly not the scope of this ticket.

2023-02-15 13:34 UTC, portizdev commented on src/main/modules/i18n/locales/cy.json
>        "PAGE_TITLE": "Why are they not available for hearing?",
You will need to move it to block until you have the translation. (Check it with Smily/Stu, I'm not sure at all)

2023-02-15 13:34 UTC, portizdev commented on src/main/modules/i18n/locales/en.json
> +    "WELSH": "Welsh",
I don't think they were so big changes as to need a techdebt. I mark as resolved, as it is strictly not the scope of this ticket.

2023-02-15 14:38 UTC, laarmada requested changes
the translation errors for :  /case/1645882162449409/directions-questionnaire/welsh-language?lang=cy
are missing 
![image](https://user-images.githubusercontent.com/23473639/219057668-a21eba1b-8538-4e0a-a1f6-2f2d61bb3269.png)

2023-02-16 07:20 UTC, portizdev commented on src/main/modules/i18n/locales/en.json
> +    "WELSH": "Welsh",
en.json and cy.json dont match. Please fix it.

2023-02-16 17:12 UTC, PaulH-HMCTS commented on src/main/modules/i18n/locales/cy.json
> +    "WELSH": "Saesneg",
Saesneg means English and Cymraeg is Welsh, so looks like we have been given incorrect translations. Smily is going to raise with the Welsh translation team.

2023-02-22 03:05 UTC, closed without merging