Feat/civ 5984 check your answers fast track hearing requirements pt2
hmcts/civil-citizen-ui pull request #1375
Opened 2023-02-20 08:52 UTC by pascalkankonde

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

[Check your answers - Fast Track - Hearing Requirements Pt2 Experts](https://tools.hmcts.net/jira/browse/CIV-5984)

### Change description ###
Check your answers - Fast Track - Hearing Requirements Pt2 Experts
Once mandatory items on the response task list are of 'Complete' status, the citizen is permitted to submit their response. On selection of 'Check and submit your response' the 'Check your answers' screen for a Part Admit or Reject type response is displayed to the citizen. This screen is required to display the defendant's details and their response to the claim. 

 

This ticket relates specifically to the Hearing Requirements section of Check your answers - Fast Track

 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-02-20 11:23 UTC, LeonardoPalmeiro commented on package.json
> +    "test": "jest -c jest.config.js",
please could you not push this?

2023-02-20 12:16 UTC, laperla11 requested changes

2023-02-20 12:16 UTC, laperla11 commented on src/main/common/utils/checkYourAnswer/getEmptyStringIfUndefined.ts
> +export const affirmation = (value:string, lng: string)=> {
I believe you don't need return a `get` method inside this function, switch statement should be enough.

2023-02-21 08:30 UTC, pascalkankonde commented on package.json
> +    "test": "jest -c jest.config.js",
fixed

2023-02-21 08:30 UTC, pascalkankonde commented on src/main/common/utils/checkYourAnswer/getEmptyStringIfUndefined.ts
> +export const affirmation = (value:string, lng: string)=> {
fixed

2023-02-21 09:40 UTC, laperla11 submitted a review, later dismissed

2023-02-21 10:57 UTC, laarmada requested changes
please review all my comments from the other close PR.... and merge the Neeta issue before.

2023-02-21 10:57 UTC, laarmada commented on package.json
> +    "test": "jest -c jest.config.js",
not fixed, I cant see it...

2023-02-21 11:15 UTC, GorilaNaranja commented on src/main/common/utils/checkYourAnswer/getEmptyStringIfUndefined.ts
> +      return t(`COMMON.${YesNoUpperCase.YES}`, {lng});
Why you are using YesNoUpperCase.YES instead
COMMON.YES?

2023-02-21 11:15 UTC, GorilaNaranja commented on src/main/common/utils/checkYourAnswer/getEmptyStringIfUndefined.ts
> +      return t(`COMMON.${YesNoUpperCase.NO}`, {lng});
Same here, use COMMON.NO

2023-02-21 11:15 UTC, GorilaNaranja commented on src/main/common/utils/checkYourAnswer/getEmptyStringIfUndefined.ts
> +}
add empty line at the end of each file

2023-02-21 11:15 UTC, GorilaNaranja commented on src/main/common/utils/checkYourAnswer/getEmptyStringIfUndefined.ts
> +export const affirmation = (value:string, lng: string)=> {
Format the code please.
Also, add return type to the function.

2023-02-21 11:15 UTC, GorilaNaranja commented on src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
> +    summaryRow(t('PAGES.CHECK_YOUR_ANSWER.CORRESPONDENCE_ADDRESS', {lng: getLng(lang)}), claim.respondent1.partyDetails.postToThisAddress === YesNo.YES ? addressToString(claim?.respondent1?.partyDeta
Do we need add a question mark to claim? I think we will always have a claim so it can not be undefined.

2023-02-21 11:17 UTC, GorilaNaranja commented on src/main/services/features/response/checkAnswers/hearingRequirementsSection/buildCommonHearingRequirements.ts
> +  const details = claim?.directionQuestionnaire?.vulnerabilityQuestions?.vulnerability?.vulnerabilityDetails;
does claim need ?
Please review it and fix it everywhere if needed

2023-02-21 11:24 UTC, hmcts-version1-domini requested changes
Reposting Serio's comments... Please review.

2023-02-21 11:24 UTC, hmcts-version1-domini commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildSmallHearingRequirments.test.ts
> +jest.mock('../../../../../../../main/modules/draft-store/draftStoreService');
Reposting Sergio's comment:
you don't need to import the draft-store twice

2023-02-21 11:24 UTC, hmcts-version1-domini commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildFastTrackHearingRequirements.test.ts
> +jest.mock('../../../../../../../main/modules/draft-store/draftStoreService');
Reposting Sergio's comment:
you don't need to import the draft-store twice

2023-02-21 11:24 UTC, hmcts-version1-domini commented on src/main/services/features/response/checkAnswers/hearingRequirementsSection/buildCommonHearingRequirements.ts
> +  switch (claim?.directionQuestionnaire?.welshLanguageRequirements?.language?.speakLanguage) {
Reposting Sergio's comment:
We have the switch twice in the same file.... please review

2023-02-21 11:24 UTC, hmcts-version1-domini commented on src/main/modules/i18n/locales/en.json
> +      "PHONE_NUMBER": "Phone number (optional)",
Reposting Sergio's comment:
Take care because you are modifying one key used on other screens and if you modify the translation we haven't the correct sentence/label on those pages.... so we are introducing a bug...

2023-02-21 11:24 UTC, hmcts-version1-domini commented on src/main/modules/i18n/locales/en.json
> +      "EMAIL_ADDRESS": "Email address (optional)",
Reposting Sergio's comment:
Take care because you are modifying one key used on other screens and if you modify the translation we haven't the correct sentence/label on those pages.... so we are introducing a bug...

2023-02-21 11:24 UTC, hmcts-version1-domini commented on src/main/modules/i18n/locales/cy.json
> +      "EMAIL_ADDRESS": "Email address (optional)",
Reposting Sergio's comment:
Take care because you are modifying one key used on other screens and if you modify the translation we haven't the correct sentence/label on those pages.... so we are introducing a bug...

2023-02-21 11:24 UTC, hmcts-version1-domini commented on src/main/modules/i18n/locales/cy.json
> +      "PHONE_NUMBER": "Phone number (optional)",
Reposting Sergio's comment:
Take care because you are modifying one key used on other screens and if you modify the translation we haven't the correct sentence/label on those pages.... so we are introducing a bug...

2023-02-21 12:19 UTC, GorilaNaranja commented on src/main/common/utils/checkYourAnswer/getEmptyStringIfUndefined.ts
> +      return value ?? "";
why we want to return value if it didn't match any of the 3 previous cases? I think if we want to handle posible errors we can always return "" in default case

2023-02-21 13:00 UTC, pascalkankonde commented on src/main/modules/i18n/locales/cy.json
> +      "EMAIL_ADDRESS": "Email address (optional)",
This code is coming from CIV-5986

2023-02-21 13:00 UTC, pascalkankonde commented on src/main/modules/i18n/locales/en.json
> +      "EMAIL_ADDRESS": "Email address (optional)",
This code is coming from CIV-5986

2023-02-21 13:00 UTC, pascalkankonde commented on src/main/modules/i18n/locales/en.json
> +      "PHONE_NUMBER": "Phone number (optional)",
This code is coming from CIV-5986

2023-02-21 13:01 UTC, pascalkankonde commented on src/main/services/features/response/checkAnswers/hearingRequirementsSection/buildCommonHearingRequirements.ts
> +  switch (claim?.directionQuestionnaire?.welshLanguageRequirements?.language?.speakLanguage) {
This code is coming from CIV-5986

2023-02-21 13:01 UTC, pascalkankonde commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildFastTrackHearingRequirements.test.ts
> +jest.mock('../../../../../../../main/modules/draft-store/draftStoreService');
This code is coming from CIV-5986

2023-02-21 13:01 UTC, pascalkankonde commented on src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildSmallHearingRequirments.test.ts
> +jest.mock('../../../../../../../main/modules/draft-store/draftStoreService');
This code is coming from CIV-5986

2023-02-21 13:01 UTC, pascalkankonde commented on src/main/services/features/response/checkAnswers/hearingRequirementsSection/buildCommonHearingRequirements.ts
> +  const details = claim?.directionQuestionnaire?.vulnerabilityQuestions?.vulnerability?.vulnerabilityDetails;
This code is coming from CIV-5986

2023-02-21 13:01 UTC, pascalkankonde commented on src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
> +    summaryRow(t('PAGES.CHECK_YOUR_ANSWER.CORRESPONDENCE_ADDRESS', {lng: getLng(lang)}), claim.respondent1.partyDetails.postToThisAddress === YesNo.YES ? addressToString(claim?.respondent1?.partyDeta
This code is coming from CIV-5986

2023-02-21 13:01 UTC, GorilaNaranja commented
Unit tests are not working

2023-02-21 13:03 UTC, pascalkankonde commented on src/main/common/utils/checkYourAnswer/getEmptyStringIfUndefined.ts
> +      return t(`COMMON.${YesNoUpperCase.NO}`, {lng});
This has be comment has hard code (COMMON.NO) that why I changed I have used this class

2023-02-21 13:03 UTC, pascalkankonde commented on src/main/common/utils/checkYourAnswer/getEmptyStringIfUndefined.ts
> +      return t(`COMMON.${YesNoUpperCase.YES}`, {lng});
This has be comment has hard code (COMMON.NO) that why I changed I have used this class

2023-02-22 08:48 UTC, GorilaNaranja commented on src/main/common/utils/checkYourAnswer/getEmptyStringIfUndefined.ts
> +      return t(`COMMON.${YesNoUpperCase.YES}`, {lng});
I commented that you should not use `case 'yes'` in line 8, you are mixing my previous comment with line 9 that is different. Doesn't make sense to use an COMMON.${YesNoUpperCase.YES} instead COMMON.YES as we discussed in the call.
Please apply same for NO case

2023-02-22 08:52 UTC, GorilaNaranja requested changes
Unit tests are not working. You have to have a working code (logic and tests) before move it to dev review.

2023-02-23 15:57 UTC, closed without merging