CIV-6581 Claimant suggested repayment plan
hmcts/civil-citizen-ui pull request #1387
Opened 2023-02-23 14:38 UTC by laperla11

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-6581

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-28 10:27 UTC, laarmada requested changes

2023-02-28 10:27 UTC, laarmada commented on src/main/routes/features/claimantResponse/claimantSuggestedPaymentDateController.ts
> +const title = 'PAGES.CCJ_DEFENDANT_PAYMENT_DATE.TITLE';
why do you need pass the title and insetText instead of use in the nunjuck directly?

2023-02-28 10:27 UTC, laarmada commented on src/main/routes/features/claimantResponse/claimantSuggestedPaymentOptionController.ts
> +      switch (form.model.paymentType) {
I think, it's better to extract to an util function

2023-02-28 10:27 UTC, laarmada commented on src/main/routes/features/response/admission/partialAdmission/partialAdmissionPaymentOptionController.ts
> +  res.render(citizenPaymentOptionViewPath, {form, amount});
could we use  claim.partialAdmissionPaymentAmount() in the nunjuck instead of pass amount?

2023-02-28 10:27 UTC, laarmada commented on src/main/routes/features/response/admission/partialAdmission/paymentDateController.ts
> +        res.render(paymentDatePath, {form, title});
could we control the title instead of the njk file instead to pass it from the controller?

2023-02-28 10:27 UTC, laarmada commented on src/main/views/features/claimantResponse/instalments-plan.njk
> +                text: "£"
we need to add in pounds to avoid accessibility problems, I will send you a related ticket for similar problems

2023-02-28 10:27 UTC, laarmada commented on src/test/unit/services/features/claimantResponse/src/main/services/features/claimantResponse/claimantSuggestedInstalmentsService.test.ts
> +jest.mock('../../../../../../../../../../main/modules/draft-store/draftStoreService');
we dont need twice the draftstore I think...

2023-02-28 10:27 UTC, laarmada commented on src/test/unit/services/features/claimantResponse/src/main/services/features/claimantResponse/claimantSuggestedInstalmentsService.test.ts
> +import {TestMessages} from '../../../../../../../../../utils/errorMessageTestConstants';
remove .../../../

2023-02-28 10:40 UTC, laperla11 commented on src/main/routes/features/claimantResponse/claimantSuggestedPaymentDateController.ts
> +const title = 'PAGES.CCJ_DEFENDANT_PAYMENT_DATE.TITLE';
because nunjucks file is used with other controllers with their title is different and they don't have ant inset.

2023-02-28 10:41 UTC, laperla11 commented on src/main/routes/features/claimantResponse/claimantSuggestedPaymentOptionController.ts
> +      switch (form.model.paymentType) {
but this redirection is specifiv to only this controller and I don't see the benefit to create an util function for this logic.

2023-02-28 10:43 UTC, laperla11 commented on src/main/routes/features/response/admission/partialAdmission/partialAdmissionPaymentOptionController.ts
> +  res.render(citizenPaymentOptionViewPath, {form, amount});
I'm not sure of that, I only refactore the existing page by moving `PaymentOptionType` to global variables and remove from here as `PaymentOptionType` is used multiple places.

2023-02-28 10:44 UTC, laperla11 commented on src/main/routes/features/response/admission/partialAdmission/paymentDateController.ts
> +        res.render(paymentDatePath, {form, title});
This logic was laready here, I just refactored it but I personally prefer to have logic in controller rather than view as we don't have debugging on nunjucks.

2023-02-28 10:45 UTC, laperla11 commented on src/main/views/features/claimantResponse/instalments-plan.njk
> +                text: "£"
as I remember we should and the `in pounds` inside the label but we need PO approval for that.

2023-02-28 10:46 UTC, laperla11 commented on src/test/unit/services/features/claimantResponse/src/main/services/features/claimantResponse/claimantSuggestedInstalmentsService.test.ts
> +import {TestMessages} from '../../../../../../../../../utils/errorMessageTestConstants';
it doesn't work if I remove it for  `TestMessages`

2023-02-28 10:50 UTC, laperla11 commented on src/test/unit/services/features/claimantResponse/src/main/services/features/claimantResponse/claimantSuggestedInstalmentsService.test.ts
> +jest.mock('../../../../../../../../../../main/modules/draft-store/draftStoreService');
good point, I removed the first one

2023-02-28 11:20 UTC, PaulH-HMCTS approved these changes

2023-02-28 11:20 UTC, PaulH-HMCTS commented on src/main/views/features/response/admission/payment-option.njk
> +                  html: hintPayImmediatly if not isClaimantResponse
Typo here on hintPayImmediatly - can we fix here and in the set block?

2023-02-28 11:25 UTC, laarmada commented on src/main/routes/features/claimantResponse/claimantSuggestedPaymentDateController.ts
> +const title = 'PAGES.CCJ_DEFENDANT_PAYMENT_DATE.TITLE';
ok I agree

2023-02-28 11:40 UTC, laarmada commented on src/main/routes/features/response/admission/partialAdmission/paymentDateController.ts
> +        res.render(paymentDatePath, {form, title});
ok no probms

2023-02-28 11:40 UTC, laarmada commented on src/test/unit/services/features/claimantResponse/src/main/services/features/claimantResponse/claimantSuggestedInstalmentsService.test.ts
> +jest.mock('../../../../../../../../../../main/modules/draft-store/draftStoreService');
cool

2023-02-28 11:46 UTC, laarmada approved these changes

2023-03-01 08:31 UTC, GorilaNaranja commented on src/main/routes/features/claimantResponse/ccj/ccjPaymentOptionController.ts
> +  CCJ_DEPENDANT_PAYMENT_DATE_URL,
I imagine is not "DEPENDANT", is "DEFENDANT"

2023-03-01 08:55 UTC, LeonardoPalmeiro commented on src/main/services/features/claimantResponse/claimantResponseService.ts
> +      if (claimantResponse.isClaimantSuggestedPayImmediately || claimantResponse.isClaimantSuggestedPayByDate) {
in sonar says that this that this part in not cover by test
![image](https://user-images.githubusercontent.com/93268657/222090165-3e5fd853-d2db-4948-bedd-85c59fa5556d.png)

2023-03-01 09:42 UTC, merged