Welsh translation
hmcts/civil-citizen-ui pull request #1392
Opened 2023-02-24 15:36 UTC by pascalkankonde

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-7123

### Change description ###
The scope of this ticket is to develop Welsh content translation of the following screens: 

DQ- Welsh Language
DQ - Why are you, your experts or witnesses unavailable for a hearing for <xx> days
 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-02-24 16:08 UTC, pascalkankonde commented on src/main/modules/i18n/locales/cy.json
>      "WELSH_LANGUAGE": {
THIS SHOULD BE REFACTORED (After a conversation the person who implemented this and tech lead)

2023-02-24 16:29 UTC, neeta-hmcts approved these changes

2023-02-24 16:35 UTC, laperla11 requested changes

2023-02-24 16:35 UTC, laperla11 commented on src/main/modules/i18n/locales/cy.json
> +      "ENGLISH": "Cymraeg",
`Cymraeg` means Welsh not `English`?

2023-02-24 16:35 UTC, laperla11 commented on src/main/modules/i18n/locales/cy.json
> +    "TECHNICAL_PROBLEMS": "Sorry, we had some technical problems during your last operation. Please try again later.",
There is no translation herfe only changing lines?

2023-02-24 16:35 UTC, laperla11 commented on src/main/modules/i18n/locales/cy.json
> +      "ENGLISH": "Cymraeg",
same here

2023-02-24 16:35 UTC, laperla11 commented on src/main/modules/i18n/locales/cy.json
> +      "WELSH": "Saesneg",
`Saeseng` means English in Welsh language

2023-02-24 18:02 UTC, PaulH-HMCTS commented
Can you ensure that comments left on previous PRs have been answered and addressed please? For example https://github.com/hmcts/civil-citizen-ui/pull/1363#pullrequestreview-1299625096

2023-02-27 15:55 UTC, PaulH-HMCTS commented on src/main/modules/i18n/locales/cy.json
> +      "ENGLISH": "Cymraeg",
As expected Smily has confirmed these changes should be made:
"ENGLISH":  "Saesneg"
"WELSH": "Cymraeg"

2023-03-02 17:39 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +      "WELSH": "Saesneg",
fix

2023-03-02 17:40 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +      "ENGLISH": "Cymraeg",
fix and review hole document

2023-03-02 17:40 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +      "ENGLISH": "Cymraeg",
modify and reviewed

2023-03-02 17:59 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +    "TECHNICAL_PROBLEMS": "Sorry, we had some technical problems during your last operation. Please try again later.",
this key is not related with the ticket pages

2023-03-02 18:01 UTC, laarmada approved these changes

2023-03-02 20:59 UTC, laperla11 approved these changes

2023-03-03 08:19 UTC, LeonardoPalmeiro approved these changes

2023-03-03 08:23 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/cy.json
> +      "CONSIDER_CLAIMANT_DOCUMENT": "Are there any documents the claimant has that you want the court to consider?",
Just to be sure, are not these translations in the scope? It is just because the format right?

2023-03-03 08:41 UTC, TatsyMaslova approved these changes

2023-03-03 08:43 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +      "CONSIDER_CLAIMANT_DOCUMENT": "Are there any documents the claimant has that you want the court to consider?",
you are right only format

2023-03-03 08:52 UTC, GorilaNaranja approved these changes

2023-03-06 12:47 UTC, LeonardoPalmeiro approved these changes

2023-03-09 17:33 UTC, PaulH-HMCTS approved these changes

2023-03-13 14:11 UTC, closed without merging

2023-03-13 14:12 UTC, laarmada commented
not valid user