Civ 637 citizen sign in to c UI money claims portal
hmcts/civil-citizen-ui pull request #140
Opened 2022-02-07 09:03 UTC by laarmada

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-637

### Change description ###
Allow sign-in to the created account using email address and password.

**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[ ] No
```

2022-02-07 09:16 UTC, laarmada commented on src/main/modules/oidc/index.ts
> +          if (req.session.user?.roles?.includes('civil-citizen')) {
we should include 'civil-citizen' into the config file as "default.yalm" file?

2022-02-07 09:17 UTC, taomoh requested changes

2022-02-07 09:17 UTC, taomoh commented on charts/civil-citizen-ui/values.aat.template.yaml
> +    divorce:
this isn't divorce

2022-02-07 09:17 UTC, taomoh commented on src/main/modules/oidc/index.ts
> +          return res.render(UNAUTHORISED);
render() takes a view name (unauthorised) and not a route (**/**unauthorised)

2022-02-07 09:17 UTC, taomoh commented on src/main/routes/urls.ts
> +export const GET_CASES: Urls = '/cases';
GET is HTTP method. Better to call this: CASES_URL

2022-02-07 09:17 UTC, taomoh commented on src/main/routes/urls.ts
> +export const DASHBOARD: Urls = '/dashboard';
rename to DASHBOARD_URL to keep consistent with the other constant names

2022-02-07 09:17 UTC, taomoh commented on src/main/routes/urls.ts
> +export const UNAUTHORISED: Urls = '/unauthorised';
Append _URL to keep consistent with the other constant names

2022-02-07 09:35 UTC, laarmada commented on src/main/routes/urls.ts
> +export const UNAUTHORISED: Urls = '/unauthorised';
done

2022-02-07 09:35 UTC, laarmada commented on src/main/routes/urls.ts
> +export const DASHBOARD: Urls = '/dashboard';
done

2022-02-07 09:35 UTC, laarmada commented on src/main/routes/urls.ts
> +export const GET_CASES: Urls = '/cases';
done

2022-02-07 09:35 UTC, laarmada commented on src/main/modules/oidc/index.ts
> +          return res.render(UNAUTHORISED);
done

2022-02-07 09:35 UTC, laarmada commented on charts/civil-citizen-ui/values.aat.template.yaml
> +    divorce:
done

2022-02-07 10:23 UTC, mounikahmcts commented on src/main/app.ts
> +export const cookieMaxAge = 21 * (60 * 1000); // 21 minutes
How did we come up with 21 min as maxCookieAge?

2022-02-07 10:23 UTC, mounikahmcts commented on src/main/modules/oidc/index.ts
> +          return res.render('unauthorised');
Is it not "return res.redirect(UNAUTHORISED);"

2022-02-07 10:23 UTC, mounikahmcts commented on src/test/unit/routes/home.test.ts
> +  const citizenRoleToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NUb2tlbiI6InRva2VuIiwic3ViIjoianNAdGVzdC5jb20iLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiU21pdGgiLCJ1aWQiOiIxMjMiLCJyb2
Is it possible to store the token in some test constants file so that we can reuse in all test files.

2022-02-07 10:44 UTC, taomoh commented on src/main/app.ts
> +export const cookieMaxAge = 21 * (60 * 1000); // 21 minutes
This was copied from nfdiv-frontend: https://github.com/hmcts/nfdiv-frontend/blob/18971ad9616085dd722ad66a0719e475b6dc819f/src/main/modules/session/index.ts#L12
Is there a specific requirement for Civil Citizen UI?

2022-02-07 10:45 UTC, taomoh commented on src/main/modules/oidc/index.ts
> +          return res.render('unauthorised');
I had res.redirect before but got a "too many redirect" exception. so switch to render

2022-02-07 10:50 UTC, taomoh commented on src/main/routes/urls.ts
> +export const UNAUTHORISED: Urls = '/unauthorised';
Not done for ROOT and UNAUTHORISED

2022-02-07 11:56 UTC, taomoh commented on src/main/modules/oidc/index.ts
> +          if (req.session.user?.roles?.includes('civil-citizen')) {
Good idea. Maybe somethings like:
services:
   idam:
      ....
      citizenRole: 'civil-citizen'

2022-02-07 13:08 UTC, laarmada commented on src/main/modules/oidc/index.ts
> +          if (req.session.user?.roles?.includes('civil-citizen')) {
exactly

2022-02-08 11:59 UTC, mounikahmcts commented on src/main/app.ts
> +export const cookieMaxAge = 21 * (60 * 1000); // 21 minutes
No I am not sure. Just checking if we are following same like other teams. I will mention it to steve when i demo things

2022-02-08 12:04 UTC, LeonardoPalmeiro approved these changes

2022-02-08 12:22 UTC, mounikahmcts commented on config/custom-environment-variables.yaml
>      clientSecret: IDAM_SECRET
Are we setting idam secret any where?

2022-02-08 12:22 UTC, mounikahmcts commented on config/default.yaml
> +    citizenRole: 'civil-citizen'
Where did we get this role?

2022-02-08 12:27 UTC, laarmada commented on config/default.yaml
> +    citizenRole: 'civil-citizen'
I have create this role, to allow civil-citizen-ui connect to idam. Else let me know which one is necessary

2022-02-08 12:31 UTC, laarmada commented on config/custom-environment-variables.yaml
>      clientSecret: IDAM_SECRET
we should add to:
 values.preview.template.yaml file?
 values.yaml?

also IDAM_CLIENT_ID we haven´t ... please let me know which is the purpose of each yalm configuration file...

2022-02-09 09:23 UTC, mounikahmcts commented on charts/civil-citizen-ui/values.yaml
> +    enabled: true
I think it should be disabled for preview and other environments. I see more pods are created in preview which will end up using all resources. We are already having resource issue on preview.
<img width="829" alt="Screenshot 2022-02-09 at 09 21 15" src="https://user-images.githubusercontent.com/43175082/153164842-e88a1b07-87f7-4bfd-b676-ec0e0d421c92.png">

2022-02-09 09:23 UTC, mounikahmcts commented on config/custom-environment-variables.yaml
>      clientSecret: IDAM_SECRET
Yeah i was expecting this secret update somewhere in config. It is updated now. can resolve this comment.

2022-02-09 09:31 UTC, mounikahmcts commented on config/default.yaml
> +    citizenRole: 'civil-citizen'
I think this is not needed. All citizens will get citizen role by default when they create account. IF we create a new role then we have to assing that role to the user somehow when they are registering

2022-02-09 13:47 UTC, mounikahmcts commented on config/default.yaml
> +    url: 'http://localhost:4000'
We are not overriding this value in custom env variables yaml so preview & other env fails.

2022-02-09 14:33 UTC, laarmada commented on config/default.yaml
> +    url: 'http://localhost:4000'
ok, fixed

2022-02-09 14:51 UTC, laarmada commented on charts/civil-citizen-ui/values.yaml
> +    enabled: true
I will set to false the autoscaling

2022-02-09 17:02 UTC, mounikahmcts approved these changes

2022-02-09 17:03 UTC, merged