CIV-5788 transform p2 for defendant response
hmcts/civil-citizen-ui pull request #1417
Opened 2023-03-02 15:42 UTC by kamilewandowski

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-5788

### Change description ###
add mapping for CCD objects

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-03-03 08:27 UTC, LeonardoPalmeiro commented on src/main/common/form/models/yesNo.ts
> +export const toUpperYesOrNo = (yesNo: GenericYesNo): YesNoUpperCamelCase => {
Please could you change the method name to toUpperCaseGenericYesNo os something like that.
What do you think ?

2023-03-03 08:34 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/evidence/evidenceController.ts
> +// import {Claim} from 'models/claim';
please remove this unnecessary comment

2023-03-03 08:34 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/evidence/evidenceController.ts
> +  // getEvidence,
please remove this unnecessary comment

2023-03-03 08:39 UTC, LeonardoPalmeiro commented on src/main/services/translation/response/convertToCCDResponseTimelineOfEvents.ts
> +    //TODO temporary solution
do we have debt tech ticket to do that?

2023-03-03 08:44 UTC, LeonardoPalmeiro commented on src/main/services/translation/response/convertToCCDAdmitPartRoute.ts
> +export const toCCDAdmitPartRoute = (partialAdmission: PartialAdmission): RespondToClaim => {
please could you change the method's name for more readable one?

2023-03-03 08:48 UTC, LeonardoPalmeiro commented on src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
> +  };
I don't know if is possible or not. what happened if those fields are undefined I asked because of question mark ?

2023-03-03 08:48 UTC, LeonardoPalmeiro reviewed
Please check sonar I saw some issues there :)

2023-03-03 11:17 UTC, kamilewandowski commented on src/main/common/form/models/yesNo.ts
> +export const toUpperYesOrNo = (yesNo: GenericYesNo): YesNoUpperCamelCase => {
sounds reasonable, I already rename this a few times, the cause I was not sure of the name

2023-03-03 11:18 UTC, kamilewandowski commented on src/main/routes/features/response/evidence/evidenceController.ts
> +// import {Claim} from 'models/claim';
done

2023-03-03 11:18 UTC, kamilewandowski commented on src/main/routes/features/response/evidence/evidenceController.ts
> +  // getEvidence,
done

2023-03-03 11:39 UTC, kamilewandowski commented on src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
> +  };
if the value is undefined for a field, it is not populated in the database. The question mark just makes sure that these fields can be undefined otherwise.

2023-03-03 11:43 UTC, kamilewandowski commented on src/main/services/translation/response/convertToCCDResponseTimelineOfEvents.ts
> +    //TODO temporary solution
I think there is already a ticket created for that https://tools.hmcts.net/jira/browse/CIV-7068

2023-03-03 11:54 UTC, kamilewandowski commented on src/main/services/translation/response/convertToCCDAdmitPartRoute.ts
> +export const toCCDAdmitPartRoute = (partialAdmission: PartialAdmission): RespondToClaim => {
done

2023-03-03 13:42 UTC, kenneth-hmcts commented on src/main/common/models/ccdResponse/ccdResponse.ts
> +  respondent1LiPResponse: CCDRespondentLiPResponse;
I think it should be respondent1LiPResponse? in stead of respondent1LiPResponse
That is because it can be undefined

2023-03-03 13:46 UTC, kenneth-hmcts commented on src/main/common/models/ccdResponse/ccdTimeLineOfEvents.ts
> +  value: CCDTimeLineOfEventsItem;
Is it better to add ? after in order to prevent the undefined problem?

2023-03-06 08:40 UTC, portizdev commented on src/main/common/models/ccdResponse/ccdAdmitPartRoute.ts
> +  // howWasThisAmountPaid?: PaymentMethod
Is this comment still necessary? I see that it has finally been translated.

2023-03-06 08:40 UTC, portizdev commented on src/main/services/translation/response/convertToCCDResponseTimelineOfEvents.ts
> +    //TODO temporary solution
Add even in the tech debt comment (better to do it in the description) this problem. Since the techDebt does not make reference to what you have introduced.

2023-03-06 10:05 UTC, laperla11 requested changes

2023-03-06 14:06 UTC, hmcts-version1-domini commented on src/main/common/models/ccdResponse/ccdAdmitPartRoute.ts
> +export interface RespondToClaim {
I think that this model shouldn't be here, but it should be created separately in an individual ts model file, so it can be reused, as other fields in other journeys will use this same model. It happens in my ticket, for example. And I'm creating the model separately. Besides, if the RespondToClaim model is defined already, it should have only the four properties it contains (howMuchWasPaid, whenWasThisAmountPaid, howWasThisAmountPaid, howWasThisAmountPaidOther). The other property you put here (respondToAdmittedClaimOwingAmount) is another different field of type string, and it's not a property of RespondToClaim.

2023-03-06 14:07 UTC, hmcts-version1-domini requested changes

2023-03-07 07:48 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdResponse.ts
> +  respondent1LiPResponse: CCDRespondentLiPResponse;
updated

2023-03-07 07:49 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdTimeLineOfEvents.ts
> +  value: CCDTimeLineOfEventsItem;
ok

2023-03-07 07:50 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdAdmitPartRoute.ts
> +  // howWasThisAmountPaid?: PaymentMethod
will remove it than

2023-03-07 11:35 UTC, kamilewandowski commented on src/main/routes/features/response/evidence/evidenceController.ts
> +    if(claim?.case_data?.specResponselistYourEvidenceList?.evidenceItem?.length < INIT_ROW_COUNT) {
updated

2023-03-07 12:32 UTC, kamilewandowski commented on src/main/services/translation/response/convertToCCDResponseTimelineOfEvents.ts
> +    //TODO temporary solution
will do make sense

2023-03-07 13:45 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdAdmitPartRoute.ts
> +export interface RespondToClaim {
I see what do you mean. Just updated it.

2023-03-07 16:40 UTC, laperla11 submitted a review, later dismissed

2023-03-08 09:03 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdResponse.ts
> +  respondent1LiPResponse: CCDRespondentLiPResponse;
updated

2023-03-08 09:40 UTC, portizdev submitted a review, later dismissed

2023-03-08 10:59 UTC, hmcts-version1-domini requested changes

2023-03-08 10:59 UTC, hmcts-version1-domini commented on src/main/common/models/ccdResponse/ccdRespondToClaim.ts
> +export enum PaymentMethod {
Here: It should be
export enum CCDHowWasThisAmountPaid {

2023-03-08 11:00 UTC, hmcts-version1-domini requested changes

2023-03-08 11:00 UTC, hmcts-version1-domini commented on src/main/common/models/ccdResponse/ccdRespondToClaim.ts
> +export interface RespondToClaim {
And this one should be:
export interface CCDRespondToClaim {

2023-03-08 14:45 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdRespondToClaim.ts
> +export interface RespondToClaim {
updated

2023-03-08 14:45 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdRespondToClaim.ts
> +export enum PaymentMethod {
updated

2023-03-09 17:27 UTC, PaulH-HMCTS commented on src/main/common/models/ccdResponse/ccdTimeLineOfEvents.ts
> +export class CCDTimeLineOfEvents {
What was the answer to this?

2023-03-09 17:27 UTC, PaulH-HMCTS commented on src/main/common/models/civilClaimResponse.ts
> +  specResponselistYourEvidenceList?: CCDEvidence[],
```suggestion
  specResponseListYourEvidenceList?: CCDEvidence[],
```

2023-03-09 17:27 UTC, PaulH-HMCTS commented on src/main/common/models/claim.ts
> +    claim.evidence = toCUIEvidence(ccdClaim?.specResponselistYourEvidenceList);
```suggestion
    claim.evidence = toCUIEvidence(ccdClaim?.specResponseListYourEvidenceList);
```

2023-03-09 17:27 UTC, PaulH-HMCTS commented on src/main/services/features/response/evidence/evidenceService.ts
> +const getEvidences = async (claimId: string) => {
Why was this renamed?

2023-03-09 17:27 UTC, PaulH-HMCTS commented on src/main/services/translation/response/ccdTranslation.ts
> +    detailsOfWhyDoesYouDisputeTheClaim: claim.partialAdmission?.whyDoYouDisagree?.text,
```suggestion
    detailsOfWhyDoYouDisputeTheClaim: claim.partialAdmission?.whyDoYouDisagree?.text,
```

2023-03-09 17:27 UTC, PaulH-HMCTS commented on src/main/services/translation/response/ccdTranslation.ts
> +    specResponselistYourEvidenceList: toCCDEvidence(claim.evidence),
```suggestion
    specResponseListYourEvidenceList: toCCDEvidence(claim.evidence),
```

2023-03-09 17:27 UTC, PaulH-HMCTS commented on src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
> +import {CCDRespondentLiPResponse} from '../../../common/models/ccdResponse/ccdRespondentLiPResponse';
Why do we need the ../../../ now? It wasnt needed before?

2023-03-09 17:27 UTC, PaulH-HMCTS commented on src/test/unit/services/translation/response/ccdTranslation.test.ts
> +    it('frequency once one month', () => {
Can you make these more descriptive please?

2023-03-09 17:27 UTC, PaulH-HMCTS commented on src/test/unit/services/translation/response/ccdTranslation.test.ts
> +    //Given
'Given' should be in each test

2023-03-09 17:27 UTC, PaulH-HMCTS commented on src/test/unit/services/translation/response/convertToCCDPaymentOptions.test.ts
> +  describe('UNDEFINED', () => {
Please make these (describe and it) more descriptive

2023-03-09 18:35 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdTimeLineOfEvents.ts
> +export class CCDTimeLineOfEvents {
I need to create the instance of this class/interface. But now I find out that I can do <CCDTimeLineOfEvents>{} so can changes it back to interface

2023-03-09 18:39 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdResponse.ts
> +  detailsOfWhyDoesYouDisputeTheClaim?: string;
These variable names have to be the same as they appear in CCD CaseData/CaseDataParent object so they are translated properly. And some of them do not have proper letter casing or proper English. But we cannot change them in civil-service because that require change in many other places as well.

2023-03-09 18:39 UTC, kamilewandowski commented on src/main/common/models/civilClaimResponse.ts
> +  specResponselistYourEvidenceList?: CCDEvidence[],
the same as `detailsOfWhyDoesYouDisputeTheClaim`

2023-03-09 18:41 UTC, kamilewandowski commented on src/main/common/models/claim.ts
> +    claim.evidence = toCUIEvidence(ccdClaim?.specResponselistYourEvidenceList);
change naming issue as explained with `detailsOfWhyDoesYouDisputeTheClaim`

2023-03-09 18:41 UTC, kamilewandowski commented on src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
> +import {CCDRespondentLiPResponse} from '../../../common/models/ccdResponse/ccdRespondentLiPResponse';
I can test it without it. I have to add it cause sonar was complaining.

2023-03-10 08:32 UTC, TatsyMaslova commented on src/main/common/models/ccdResponse/ccdFinancialDetailsLiP.ts
> +import {YesNoUpperCamelCase} from '../../form/models/yesNo';
good spot this should still be 'form/models/yesNo' @kamilewandowski

2023-03-10 08:32 UTC, TatsyMaslova commented on src/main/common/models/ccdResponse/ccdMediation.ts
> +import {YesNoUpperCamelCase} from '../../form/models/yesNo';
Same here as per Paul's comment

2023-03-10 08:33 UTC, TatsyMaslova commented on src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
> +import {YesNoUpperCamelCase} from '../../../common/form/models/yesNo';
and here

2023-03-10 08:35 UTC, TatsyMaslova commented on src/main/common/models/ccdResponse/ccdResponse.ts
> +  detailsOfWhyDoesYouDisputeTheClaim?: string;
Are those values that you have added to ccd or are they existing ones? if they are the ones that you have introduced then we could fix the name on ccd. if not then unfortunately we would have to go with what we have on ccd

2023-03-10 08:39 UTC, TatsyMaslova commented on src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
> +import {CCDRespondentLiPResponse} from '../../../common/models/ccdResponse/ccdRespondentLiPResponse';
I think Super Neeta has ensured that we import common/models including in test. this also seems to increase performance. In my branch sonar does not complain about the imports. are you sure sonar is complaining about that?

2023-03-10 08:39 UTC, TatsyMaslova commented on src/test/unit/services/translation/response/ccdTranslation.test.ts
> +    const claim = new Claim();
can put this in before each so that you don't  have code repetitions

2023-03-10 08:40 UTC, TatsyMaslova commented on src/test/unit/services/translation/response/convertToCCDPaymentOptions.test.ts
> +      const claim: Claim = new Claim();
can put it in before each so that you don't have code repetitions

2023-03-10 08:40 UTC, TatsyMaslova commented on src/test/unit/services/translation/response/convertToCCDRespondToClaim.test.ts
> +    const claim = new Claim();
given when then please

2023-03-10 08:41 UTC, TatsyMaslova commented on src/test/unit/services/translation/response/convertToCCDRespondentLiPResponse.test.ts
> +    const claim = new Claim();
given when then please

2023-03-10 08:41 UTC, TatsyMaslova commented on src/test/unit/services/translation/response/convertToCCDResponseTimelineOfEvents.test.ts
> +
given when then please

2023-03-10 12:05 UTC, kamilewandowski commented on src/test/unit/services/translation/response/convertToCCDPaymentOptions.test.ts
> +  describe('UNDEFINED', () => {
done

2023-03-10 12:05 UTC, kamilewandowski commented on src/test/unit/services/translation/response/ccdTranslation.test.ts
> +    //Given
updated

2023-03-10 12:05 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdMediation.ts
> +import {YesNoUpperCamelCase} from '../../form/models/yesNo';
removed redundant characters

2023-03-10 12:06 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
> +import {YesNoUpperCamelCase} from '../../../common/form/models/yesNo';
removed

2023-03-10 12:09 UTC, kamilewandowski commented on src/test/unit/services/translation/response/convertToCCDRespondentLiPResponse.test.ts
> +    const claim = new Claim();
updated

2023-03-10 12:09 UTC, kamilewandowski commented on src/test/unit/services/translation/response/convertToCCDResponseTimelineOfEvents.test.ts
> +
updated

2023-03-10 12:15 UTC, kamilewandowski commented on src/test/unit/services/translation/response/convertToCCDPaymentOptions.test.ts
> +      const claim: Claim = new Claim();
updated

2023-03-10 12:18 UTC, kamilewandowski commented on src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
> +import {CCDRespondentLiPResponse} from '../../../common/models/ccdResponse/ccdRespondentLiPResponse';
Not any more.

2023-03-10 13:09 UTC, neeta-hmcts commented on src/main/common/form/models/yesNo.ts
> +import {GenericYesNo} from '../../form/models/genericYesNo';
if possible fix the import warning.

2023-03-10 13:09 UTC, neeta-hmcts commented on src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
> +  partialAdmissionAlreadyPaid: YesNoUpperCamelCase
better to add ? for all fields

2023-03-10 13:46 UTC, hmcts-version1-domini commented on src/main/services/translation/response/ccdTranslation.ts
> +    detailsOfWhyDoesYouDisputeTheClaim: claim.partialAdmission?.whyDoYouDisagree?.text,
@PaulH-HMCTS the thing here is that those fields are defined exactly like this in CCD... Isn't necessary here to put the exact name of the field in CCD?

2023-03-10 13:48 UTC, hmcts-version1-domini commented on src/main/services/translation/response/ccdTranslation.ts
> +    specResponselistYourEvidenceList: toCCDEvidence(claim.evidence),
@PaulH-HMCTS same here... whoever defined this field in CCD, did it that exact way.

2023-03-10 14:08 UTC, kamilewandowski commented on src/main/common/form/models/yesNo.ts
> +import {GenericYesNo} from '../../form/models/genericYesNo';
updated

2023-03-10 14:08 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
> +  partialAdmissionAlreadyPaid: YesNoUpperCamelCase
updated

2023-03-10 14:15 UTC, hmcts-version1-domini approved these changes

2023-03-10 15:19 UTC, neeta-hmcts submitted a review, later dismissed

2023-03-13 17:05 UTC, kenneth-hmcts submitted a review, later dismissed

2023-03-13 17:17 UTC, laperla11 approved these changes

2023-03-13 17:19 UTC, neeta-hmcts approved these changes

2023-03-13 18:40 UTC, PaulH-HMCTS commented on src/main/common/models/ccdResponse/ccdTimeLineOfEvents.ts
> +export class CCDTimeLineOfEvents {
It's still showing as interface here as well as for CCDTimeLineOfEventsItem?

2023-03-13 18:40 UTC, PaulH-HMCTS commented on src/main/routes/features/response/evidence/evidenceController.ts
> +    if(evidences.evidenceItem?.length < INIT_ROW_COUNT) {
```suggestion
    if (evidences.evidenceItem?.length < INIT_ROW_COUNT) {
```

2023-03-13 18:40 UTC, PaulH-HMCTS commented on src/main/services/features/response/evidence/evidenceService.ts
> +    if(claim.evidence)
Add curly brackets please

2023-03-14 08:31 UTC, LeonardoPalmeiro requested changes

2023-03-14 08:31 UTC, LeonardoPalmeiro commented on src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
Please if is possible all files with same look and feel.
line line after imports, imports without empty spaces.

2023-03-14 08:31 UTC, LeonardoPalmeiro commented on src/main/services/translation/response/convertToCCDResponseTimelineOfEvents.ts
> +const formatDate = (date: Date) => {
we have dateUtils.ts may we have this format in somewhere in the application or we can move to dateUtils.ts

2023-03-14 08:31 UTC, LeonardoPalmeiro commented on src/test/unit/services/translation/response/ccdTranslation.test.ts
> +      claim.statementOfMeans = new StatementOfMeans();
this could be a method then we can remove duplicate part.
Something like that:
function getPartialAdmission(claim: Claim, option: YesNo) {
  claim.statementOfMeans = new StatementOfMeans();
  claim.statementOfMeans.explanation = undefined;
  claim.partialAdmission = new PartialAdmission();
  claim.partialAdmission.alreadyPaid = {};
  claim.partialAdmission.alreadyPaid.messageName = 'Some message';
  claim.partialAdmission.alreadyPaid.option = option;
}

2023-03-14 08:31 UTC, LeonardoPalmeiro commented on src/test/unit/services/translation/response/convertToCCDAdmitPartRoute.test.ts
please add //given //when //then

2023-03-14 08:31 UTC, LeonardoPalmeiro commented on src/test/unit/services/translation/response/convertToCCDResponseTimelineOfEvents.test.ts
> +    const events: DefendantTimeline = {
we can use something like:
const timeline: DefendantTimeline = new DefendantTimeline(
        [new TimelineRow('6 November 2022', 'Event 1')],
        '',
      ); then we don't need to add this part   filterOutEmptyRows(): void {
        // require to be override
      },

2023-03-14 08:31 UTC, LeonardoPalmeiro commented on src/test/unit/services/translation/response/convertToCCDRespondentLiPResponse.test.ts
> +      timeline: {
we can use something like:
const timeline: DefendantTimeline = new DefendantTimeline(
[new TimelineRow('6 November 2022', 'Event 1')],
'',
);

2023-03-14 10:20 UTC, kamilewandowski commented on src/test/unit/services/translation/response/convertToCCDResponseTimelineOfEvents.test.ts
> +    const events: DefendantTimeline = {
I do not know all of those CUI classes and methods, so really appreciate your suggestion.

2023-03-14 10:22 UTC, kamilewandowski commented on src/test/unit/services/translation/response/convertToCCDAdmitPartRoute.test.ts
updated

2023-03-14 10:35 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
sure, make sense. Will try to keep it consistent.

2023-03-14 10:37 UTC, kamilewandowski commented on src/main/services/features/response/evidence/evidenceService.ts
> +    if(claim.evidence)
sure.

2023-03-14 11:11 UTC, kamilewandowski commented on src/main/services/translation/response/convertToCCDResponseTimelineOfEvents.ts
> +const formatDate = (date: Date) => {
I have moved my method to the dateUtils.ts since I could not found method which actually return for me formatted date from string as 'dd-mm-yyyy'

2023-03-15 16:02 UTC, TatsyMaslova commented on src/main/services/translation/response/ccdTranslation.ts
> -    respondent1LiPResponse: toCCDRespondentLiPResponse(claim),
why is this removed? wont it cause a bug

2023-03-15 16:03 UTC, PaulH-HMCTS approved these changes

2023-03-15 16:08 UTC, kamilewandowski commented on src/main/services/translation/response/ccdTranslation.ts
> -    respondent1LiPResponse: toCCDRespondentLiPResponse(claim),
there is duplication of this line on line 45

2023-03-15 16:10 UTC, LeonardoPalmeiro approved these changes

2023-03-15 16:11 UTC, TatsyMaslova commented on src/main/services/translation/response/ccdTranslation.ts
> -    respondent1LiPResponse: toCCDRespondentLiPResponse(claim),
thank you!

2023-03-15 16:11 UTC, TatsyMaslova approved these changes

2023-03-15 16:14 UTC, LeonardoPalmeiro commented on src/main/services/translation/response/convertToCCDResponseTimelineOfEvents.ts
> +const formatDate = (date: Date) => {
ok

2023-03-15 17:30 UTC, laperla11 approved these changes

2023-03-24 08:38 UTC, PaulH-HMCTS submitted a review, later dismissed

2023-03-24 08:43 UTC, TatsyMaslova submitted a review, later dismissed

2023-03-24 08:56 UTC, laperla11 submitted a review, later dismissed

2023-03-29 14:43 UTC, PaulH-HMCTS submitted a review, later dismissed

2023-03-29 15:16 UTC, laperla11 approved these changes

2023-04-11 14:12 UTC, PaulH-HMCTS submitted a review, later dismissed

2023-04-11 14:16 UTC, TatsyMaslova approved these changes

2023-04-11 15:25 UTC, laarmada requested changes

2023-04-11 15:25 UTC, laarmada commented on src/main/services/features/response/evidence/evidenceService.ts
> +      return claim.evidence;
or use new Evidence () instead of object.assign

2023-04-12 08:13 UTC, kenneth-hmcts commented on src/main/services/translation/response/ccdTranslation.ts
> +    specDefenceAdmittedRequired: toUpperCaseGenericYesNo(claim.partialAdmission?.alreadyPaid),
Change to use toCCDYesNoFromGenericYesNo instead of creating the new toUpperCaseGenericYesNo

2023-04-12 08:13 UTC, kenneth-hmcts commented on src/main/common/form/models/yesNo.ts
> +export const toUpperCaseGenericYesNo = (yesNo: GenericYesNo): YesNoUpperCamelCase => {
This can be removed if toCCDYesNoFromGenericYesNo is used

2023-04-14 13:55 UTC, kamilewandowski commented on src/main/common/models/ccdResponse/ccdTimeLineOfEvents.ts
> +  timelineDate: string;
done

2023-04-14 13:56 UTC, kamilewandowski commented on src/main/services/features/response/evidence/evidenceService.ts
> +      return claim.evidence;
done

2023-04-17 13:00 UTC, kamilewandowski commented on src/main/common/utils/dateUtils.ts
> +  return `${year}-${month}-${day}`;
renamed, I think that will suits better

2023-04-17 13:06 UTC, kamilewandowski commented on src/main/common/models/claim.ts
> +      return this.partialAdmission?.whyDoYouDisagree?.text;
I do not think I need `return undefined` cause this will be by default undefined which is expected behaviour, cause I do not want to fill that field if is `rejectAllOfClaim` and `partailAdmission` are undefined.

2023-04-17 13:34 UTC, laarmada submitted a review, later dismissed

2023-04-17 13:52 UTC, kenneth-hmcts approved these changes

2023-04-18 12:32 UTC, kenneth-hmcts submitted a review, later dismissed

2023-04-18 12:36 UTC, PaulH-HMCTS approved these changes

2023-04-21 12:59 UTC, kenneth-hmcts approved these changes

2023-04-21 13:17 UTC, PaulH-HMCTS approved these changes

2023-04-21 15:59 UTC, merged