Feature/civ 1110 confirm details
hmcts/civil-citizen-ui pull request #142
Opened 2022-02-09 12:14 UTC by RosDiaf

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-02-09 17:06 UTC, taomoh requested changes
@RosDiaf I've tried to review this to the best of my frontend abilities. I think you should get another reviewer, maybe Maro. Especially around this file:
src/main/controllers/features/response/confirm-details.ts

2022-02-09 18:36 UTC, RosDiaf commented on tsconfig.json
> +  "exclude": ["**/*.test.ts", "**/codecept.conf.ts", "**/__mocks__/*"]
Reverted

2022-02-10 13:44 UTC, RosDiaf commented on src/main/views/features/response/your-details.njk
> +              claimant when you submit your response.</p>
Added

2022-02-10 13:45 UTC, RosDiaf commented on src/main/views/features/response/your-details.njk
> +                  text: "Yes, add a correspondence address",
Added

2022-02-10 14:46 UTC, RosDiaf commented on src/main/controllers/features/response/confirm-details.ts
> +    let citizenDetails = await draftStoreClient.get('000CMC001');
Claim ref retrieved from service

2022-02-10 14:46 UTC, RosDiaf commented on src/main/views/features/response/your-details.njk
> +                  text: "Would you like correspondence sent to a different address?",
Translation function added

2022-02-10 17:10 UTC, commitBlob commented on src/main/controllers/features/response/confirm-details.ts
> +const formHandler = (req:express.Request, res:express.Response) => {
if you make this function async you don't need async wrappers on the lines 139 and 144

2022-02-10 17:13 UTC, commitBlob commented on src/main/views/features/response/your-details.njk
> +            {{ govukInput(
believe this will fail accessibility test as label is not set

2022-02-10 17:13 UTC, commitBlob commented on src/main/views/features/response/your-details.njk
> +                label: {
believe this will fail accessibility test as label is not set

2022-02-11 09:20 UTC, LeonardoPalmeiro requested changes

2022-02-11 09:26 UTC, taomoh commented on src/main/server.ts
> +const port: number = parseInt(process.env.PORT || '3001', 10);
@LeonardoPalmeiro this is not a test assertion. it's an invariant assumption: https://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html

2022-02-11 10:01 UTC, taomoh commented on src/main/app/client/civilServiceClient.ts
> +      throw new AssertionError('Claim details not available.');
@LeonardoPalmeiro this is not a test assertion. it's an invariant assumption. here is the equivalent in Java: https://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html

2022-02-11 10:06 UTC, taomoh commented on src/main/app/client/civilServiceClient.ts
> +import { AssertionError } from 'chai';
@RosDiaf this should not be imported from chai. it's part of typescript: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

I have shared this link in my previous comment

2022-02-11 10:08 UTC, LeonardoPalmeiro commented on src/main/app/client/civilServiceClient.ts
> +      throw new AssertionError('Claim details not available.');
I added the comment because AssertionError is from import { AssertionError } from 'chai'; I need to use from the typescript core  https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

2022-02-11 10:17 UTC, taomoh commented on src/main/app/client/civilServiceClient.ts
> +import { AssertionError } from 'chai';
You can use the function assert:
`assert(response.data);`

2022-02-16 13:53 UTC, taomoh approved these changes

2022-02-16 14:54 UTC, LeonardoPalmeiro approved these changes
looks good to me

2022-02-16 15:04 UTC, mounikahmcts commented on src/test/unit/routes/features/response/confirm-details.test.ts
> +    nock('http://localhost:5000')
This should be from a variable should not directly point to localhost

2022-02-16 15:45 UTC, TatsyMaslova requested changes

2022-02-16 15:45 UTC, TatsyMaslova commented on src/main/common/utils/validator.ts
> +const validator = require('validator');
Are we going to have this validator or are we moving to hmcts validator or will we have both?

2022-02-16 15:45 UTC, TatsyMaslova commented on src/main/controllers/features/response/confirm-details.ts
> +  classes: 'govuk-input--width-20',
would it be better to put all these constants in a model and pass it after to the view in here instead of defining everything here? in case we need to reuse it

2022-02-17 14:04 UTC, merged