Civ 904 confirm details phone number
hmcts/civil-citizen-ui pull request #143
Opened 2022-02-11 10:27 UTC by TatsyMaslova

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-904

### Change description ###
first vertical slice of citizen phone number page

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-02-11 13:09 UTC, LeonardoPalmeiro requested changes

2022-02-11 13:09 UTC, LeonardoPalmeiro commented on src/main/views/macro/contact-us-for-help.njk
> +      <h3 class='govuk-heading-m'>Email</h3>
we've to use the internationalization function

2022-02-11 14:17 UTC, osheaf01 commented on src/main/views/macro/contact-us-for-help.njk
> +      <h3 class='govuk-heading-m'>Email</h3>
What does that involve, Leo? It wasn't present in cmc-citizen-frontend, I don't think

2022-02-11 14:24 UTC, LeonardoPalmeiro commented on src/main/views/macro/contact-us-for-help.njk
> +      <h3 class='govuk-heading-m'>Email</h3>
What I meant  was we need to use something like this {{ t('Email') }} to do the translation

2022-02-11 14:27 UTC, TatsyMaslova commented on package.json
> +    "puppeteer": "^13.2.0",
I think we use it in route test.. at least when it tried to run it without it, it complained. but that was before i merged master

2022-02-11 14:28 UTC, TatsyMaslova commented on package.json
> +    "numeral": "^2.0.6",
yep sorry forgot to remove dependency, probs nodejs-logging needs to be removed as well

2022-02-11 15:36 UTC, LeonardoPalmeiro requested changes

2022-02-11 15:36 UTC, LeonardoPalmeiro commented on src/main/common/form/form.ts
> +import {ValidateNested, ValidationError} from 'class-validator';
we should rename form.ts to more readable name

2022-02-11 15:41 UTC, TatsyMaslova commented on src/main/common/form/form.ts
> +import {ValidateNested, ValidationError} from 'class-validator';
it  has several classes in it. and perhaps these should be put in their own file/class. It represents a form object for the user to fill in. it has validation errors so if the user fills in some fields incorrectly it will have errors for those fields.  Maybe it still should be called form as it represents a form but all the dependant classes should be in their own files and folders probably?

2022-02-14 09:09 UTC, TatsyMaslova commented on src/main/common/form/form.ts
> +import {ValidateNested, ValidationError} from 'class-validator';
i have refactored this and hopefully it will make more sense.

2022-02-14 09:10 UTC, LeonardoPalmeiro commented on src/main/common/form/form.ts
> +import {ValidateNested, ValidationError} from 'class-validator';
maybe formValidators.ts will be the best option on that.

2022-02-14 09:28 UTC, TatsyMaslova commented on src/main/common/form/form.ts
> +import {ValidateNested, ValidationError} from 'class-validator';
hmmm it is clear that this form is not clear at all :(. what it was supposed to be is a model that holds a form and validation errors attached to it. it does not validate the form. there is a separate validator that does it. perhaps it is overengineering - and i should get rid of this form completely and have errors in DefendantDetailsTelephoneNumber class and pass that to the view.

2022-02-14 09:34 UTC, taomoh requested changes
yarn.lock mustn't be deleted.
Also added other comments

2022-02-14 09:34 UTC, taomoh commented on src/main/common/form/models/defendantDetailsTelephoneNumber.ts
> +const NON_NUMERIC_VALUES_NOT_ALLOWED = 'There was a problem. Please enter numeric number';
How would i18n this work with this?

2022-02-14 09:34 UTC, taomoh commented on src/main/routes/routes.ts
> +import defendantRoute from './features/defendant/index';
I think it would make more sense for this route to be under response/phone-details/index

2022-02-14 09:34 UTC, taomoh commented on src/main/views/features/defendant/citizen-phone.njk
> +
Similarly, maybe this view is better under views/features/response/citizen-phone.njk, as the phone details are part of the response journey

2022-02-14 09:34 UTC, taomoh commented on src/main/views/macro/buttons.njk
> +  {{ submitButton('Save and continue', id = 'saveAndContinue') }}
Add translation function t()

2022-02-14 09:34 UTC, taomoh commented on src/main/views/macro/contact-us-for-help.njk
> +{% from "govuk/components/details/macro.njk" import govukDetails %}
Please check with Shirish if the contact-us for help page should also support Welsh translation

2022-02-14 09:34 UTC, taomoh commented on src/main/views/macro/support.njk
> +{% from "externalLink.njk" import externalLink %}
Please check with Shirish if the support page should also support Welsh translation

2022-02-14 09:34 UTC, taomoh commented on src/main/common/form/models/defendantDetailsTelephoneNumber.ts
> +export class DefendantDetailsTelephoneNumber {
Is this model specific to defendant? if not it should be named differently. e.g. citizenPhoneNumber

2022-02-14 09:56 UTC, TatsyMaslova commented on src/main/common/form/models/defendantDetailsTelephoneNumber.ts
> +const NON_NUMERIC_VALUES_NOT_ALLOWED = 'There was a problem. Please enter numeric number';
do you mean for international translation? (sorry for the stupid question) - the the text error is shown in the view that contains the model and we put the error in the view {{ t(error) }} so that it is translated

2022-02-14 10:00 UTC, TatsyMaslova commented on src/main/common/form/models/defendantDetailsTelephoneNumber.ts
> +export class DefendantDetailsTelephoneNumber {
Good point. Thank you Taofik. I am not sure. if the citizen phone number is mandatory for the citizen that raises a claim then they would need a different model as this one allows optional phone number.

2022-02-14 10:36 UTC, taomoh commented on src/main/common/form/models/defendantDetailsTelephoneNumber.ts
> +export class DefendantDetailsTelephoneNumber {
if that is the case, it can have a mandatory boolean attribute and can be used by both claimant and defendant journeys.
Worth checking the requirement

2022-02-14 10:50 UTC, TatsyMaslova commented on src/main/common/form/models/defendantDetailsTelephoneNumber.ts
> +export class DefendantDetailsTelephoneNumber {
perhaps we could just put it for the citizen and once we hit the citizen claimant requirement/journey then we can tackle the issue if the phone number would be mandatory

2022-02-14 15:05 UTC, mounikahmcts commented on src/test/functional/features/phonenumber.feature
> +    Given Load Citizen phone number
Load or Test citizen phone number is not very meaningful.
Scenarios should be something like 
**Given Confirm Details Task selected
Then fill the Name and Address
Click save and continue
Then fill the phone number
Click save and continue**

2022-02-14 15:06 UTC, mounikahmcts commented on src/test/e2e/step_definitions/steps.ts
> +homepage(I);
You are missing a few files which i initially committed
https://github.com/hmcts/civil-citizen-ui/pull/97/files#diff-dff53e9c1cb7ae7acc0266b3ca63c5865a8ec9d647e79b9777d22f7656c6ee6dR3

https://github.com/hmcts/civil-citizen-ui/pull/97/files#diff-b1c1de1374e98b56c39e72e15389d5307b7ec6ae0713182b1aafd5211d3a5b4cR2

But you are referring homepage here.

2022-02-14 15:07 UTC, mounikahmcts commented on src/test/unit/common/form/form.ts
> +    //Given
Is this Given When Then needed for every test. It will add up so many lines of code

2022-02-14 15:25 UTC, TatsyMaslova commented on src/test/unit/common/form/form.ts
> +    //Given
I like given/when/then pattern in unit testing https://martinfowler.com/bliki/GivenWhenThen.html  https://blog.j-labs.pl/2017/02/Given-When-Then-pattern-in-unit-tests :) . I know it takes more screen but I think its more clear what is going on in the unit test

2022-02-14 15:43 UTC, mounikahmcts commented on src/main/common/form/models/defendantDetailsTelephoneNumber.ts
> +  @Validate(OptionalIntegerValidator, {message: NON_NUMERIC_VALUES_NOT_ALLOWED})
Are we sure NON_NUMERIC_VALUES_NOT_ALLOWED on this. if the phone number is 090-9999 what will happen?

2022-02-14 15:44 UTC, TatsyMaslova commented on src/main/common/form/models/defendantDetailsTelephoneNumber.ts
> +  @Validate(OptionalIntegerValidator, {message: NON_NUMERIC_VALUES_NOT_ALLOWED})
I can do a demo for you Mounika if you are free :)  - it does not allow "-" or any special character. so it will show an error message

2022-02-14 15:46 UTC, TatsyMaslova commented on src/main/views/macro/support.njk
> +  {% if featureToggles.webChat %}
I am not sure. the acceptance criteria says we have to have the "ask for help" in, but as discussed in the refinement - it would be in a separate story. So I think the whole support.njk has to be taken out. and acceptance criteria should be changed. But need to confirm with Shirish

2022-02-14 15:50 UTC, mounikahmcts commented on src/main/routes/features/defendant/index.ts
> +router.get('/citizen-phone', (req, res) => {
Hardcording paths is not a good idea. Can we move it to some constants.

2022-02-14 15:52 UTC, mounikahmcts commented on src/main/views/features/defendant/citizen-phone.njk
> +{% from "contact-us-for-help.njk" import contactUsForHelp %}
Are we covering contact us for help here or in a new story?

2022-02-14 15:53 UTC, TatsyMaslova commented on src/main/views/macro/support.njk
> +  {% if featureToggles.webChat %}
Just confirmed with Shirish and this will be removed from acceptance criteria. So I will remove the macro and the reference to it on the page :)

2022-02-14 15:55 UTC, TatsyMaslova commented on src/main/views/features/defendant/citizen-phone.njk
> +{% from "contact-us-for-help.njk" import contactUsForHelp %}
yes, as discussed today in the refinement. I just confirmed with Shirish as well. it will be taken out of the acceptance criteria for this story

2022-02-15 08:23 UTC, TatsyMaslova commented on src/main/views/features/defendant/citizen-phone.njk
> +{% from "contact-us-for-help.njk" import contactUsForHelp %}
taken it out :) thanks Mounika

2022-02-15 09:59 UTC, mounikahmcts commented on src/main/common/form/models/citizenTelephoneNumber.ts
> +export class CitizenTelephoneNumber {
I think it should just be telephone number. Party type can individual /company/ ltd company. So better not to limit it to Citizen. Or you can specify Lip TelephoneNumber. I prefer just TelephoneNumber

2022-02-15 10:01 UTC, mounikahmcts commented on src/main/common/form/validators/optionalIntegerValidator.ts
> +    const numberPattern = /^[0-9]+$/;
You should trim the value string before checking for any condition to remove extra spaces

2022-02-15 10:01 UTC, mounikahmcts commented on src/main/common/form/validators/optionalIntegerValidator.ts
> +    return 'There was a problem. Please enter numeric number';
Can we move all error messages into one constants and access it from there.

2022-02-15 10:04 UTC, mounikahmcts commented on src/main/routes/features/response/phone-details/index.ts
> +import {CITIZEN_PHONE_NUMBER_URL} from '../../../urls';
It should be DEFENDANT_PHONE_NUMBER_URL

2022-02-15 10:05 UTC, osheaf01 commented on src/main/common/form/models/defendantDetailsTelephoneNumber.ts
> +  @Validate(OptionalIntegerValidator, {message: NON_NUMERIC_VALUES_NOT_ALLOWED})
Hi Mounika, Shirish said we were to test for phone numbers as per https://tools.hmcts.net/jira/browse/CIV-514 i.e no special characters, completely numeric.

2022-02-15 10:07 UTC, osheaf01 commented on src/main/views/features/defendant/citizen-phone.njk
> +{% from "contact-us-for-help.njk" import contactUsForHelp %}
Help is now going to be a separate work slate item, ticket.

2022-02-15 10:07 UTC, mounikahmcts commented on src/main/routes/features/response/phone-details/index.ts
> +const citizenPhoneViewPath = 'features/response/phone-details/citizen-phone';
same here it should clearly specify its defendantsPhoneNumberPath

2022-02-15 10:08 UTC, mounikahmcts commented on src/test/a11y/a11y.ts
> +const IGNORED_URLS = [urls.SIGN_IN_URL, urls.SIGN_OUT_URL,urls.CASES_URL,urls.CALLBACK_URL,urls.DASHBOARD_URL,urls.UNAUTHORISED_URL,urls.CITIZEN_PHONE_NUMBER_URL];
Why are we ignoring accessibility for all urls? Are we going to cover them in any other ticket?

2022-02-15 10:10 UTC, osheaf01 commented on src/main/common/form/models/citizenTelephoneNumber.ts
> +export class CitizenTelephoneNumber {
Taoufik suggested CitizenTelephoneNumber, the point was to make it reusable for any citizen. Not everyone will know what LiP is coming fresh to the code. Shall we ask for input on the team Slack channel? This is a teamwide discussion...

2022-02-15 10:12 UTC, mounikahmcts commented on src/test/unit/common/form/form.ts
> +    //Given
I agree, we generally follow given when then in functional tests but was thinking, we will have too many unit tests and make it more lengthier but this is  fine as long as we are not downloading unit tests in production version.

2022-02-15 10:13 UTC, osheaf01 commented on src/test/e2e/step_definitions/steps.ts
> +homepage(I);
Removed in latest checkin.

2022-02-15 10:14 UTC, osheaf01 commented on src/test/functional/features/phonenumber.feature
> +    Given Load Citizen phone number
Functional test removed in latest checkin.
It won't work without resolving the logging in issue.

2022-02-15 10:14 UTC, osheaf01 commented on src/main/views/macro/support.njk
> +{% from "externalLink.njk" import externalLink %}
Support page is now going to be a separate item of work.

2022-02-15 10:15 UTC, osheaf01 commented on src/main/common/form/models/defendantDetailsTelephoneNumber.ts
> +export class DefendantDetailsTelephoneNumber {
Resolved in latest checkin.

2022-02-15 10:15 UTC, osheaf01 commented on src/main/views/macro/contact-us-for-help.njk
> +{% from "govuk/components/details/macro.njk" import govukDetails %}
Separate item of work, no longer in acceptance criteria

2022-02-15 10:15 UTC, osheaf01 commented on src/main/views/macro/buttons.njk
> +  {{ submitButton('Save and continue', id = 'saveAndContinue') }}
Resolved in latest checkin

2022-02-15 10:18 UTC, osheaf01 commented on src/main/routes/routes.ts
> +import defendantRoute from './features/defendant/index';
Done in latest checkin.

2022-02-15 10:18 UTC, osheaf01 commented on src/main/common/form/form.ts
> +import {ValidateNested, ValidationError} from 'class-validator';
Resolved in latest checkin

2022-02-15 10:23 UTC, osheaf01 commented on src/main/common/form/validators/optionalIntegerValidator.ts
> +    const numberPattern = /^[0-9]+$/;
Spaces should throw an error, it's invalid input, so the warning informs the user of that. So I don't think we should trim user input, we should just tell them it's wrong

The acceptance criteria is that any space is erroneous.

2022-02-15 14:07 UTC, TatsyMaslova commented on src/test/a11y/a11y.ts
> +const IGNORED_URLS = [urls.SIGN_IN_URL, urls.SIGN_OUT_URL,urls.CASES_URL,urls.CALLBACK_URL,urls.DASHBOARD_URL,urls.UNAUTHORISED_URL,urls.CITIZEN_PHONE_NUMBER_URL];
these were already in the ignored urls. I only added mine to follow the pattern we already have. I assume we are going to tackle the a11y for these urls later

2022-02-15 14:10 UTC, TatsyMaslova commented on src/main/routes/features/response/phone-details/index.ts
> +import {CITIZEN_PHONE_NUMBER_URL} from '../../../urls';
I think we should agree on the ubiquitous language here - whether it should be LIP or CITIZEN perhaps this is not for this particular story and should be defined as a team we can then rename the constant and associated classes

2022-02-15 14:12 UTC, TatsyMaslova commented on src/main/routes/features/response/phone-details/index.ts
> +const citizenPhoneViewPath = 'features/response/phone-details/citizen-phone';
this is a path for the view. I think since the view does not have the name defendant it will be ambiguous to name the path differently to the view name.

2022-02-17 09:18 UTC, LeonardoPalmeiro approved these changes
LGTM

2022-02-17 10:08 UTC, RosDiaf approved these changes

2022-02-17 12:08 UTC, laarmada approved these changes

2022-02-18 09:45 UTC, merged