CIV-5195 Full Reject Fields to CCD
hmcts/civil-citizen-ui pull request #1433
Opened 2023-03-10 14:32 UTC by hmcts-version1-domini

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-5195

### Change description ###

Develop the mapping between CUI response data and CCD, for 'Reject - I've paid what I believe I owe' and 'Reject - I dispute all of the claim' and 'Reject - I dispute the claim and want to make a counterclaim' response types.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-03-14 09:18 UTC, kenneth-hmcts submitted a review, later dismissed

2023-03-14 10:52 UTC, laperla11 requested changes

2023-03-14 10:52 UTC, laperla11 commented on src/main/services/translation/response/ccdTranslation.ts
> +    detailsOfWhyDoesYouDisputeTheClaim: claim.rejectAllOfClaim?.defence?.text ? claim.rejectAllOfClaim?.defence?.text : claim.rejectAllOfClaim?.whyDoYouDisagree?.text,
you can use this short version:
`detailsOfWhyDoesYouDisputeTheClaim: claim.rejectAllOfClaim?.defence?.text ??claim.rejectAllOfClaim?.whyDoYouDisagree?.text,`

2023-03-14 10:52 UTC, laperla11 commented on src/test/unit/services/translation/response/convertToCCDRejectAllOfClaimType.test.ts
> +describe('translate RejectAllOfClaimType to CCD model', () => {
Pls use Given, When , Then pattern in tests

2023-03-14 11:36 UTC, hmcts-version1-domini commented on src/main/services/translation/response/ccdTranslation.ts
> +    detailsOfWhyDoesYouDisputeTheClaim: claim.rejectAllOfClaim?.defence?.text ? claim.rejectAllOfClaim?.defence?.text : claim.rejectAllOfClaim?.whyDoYouDisagree?.text,
Good! Done. Thanks!

2023-03-14 11:37 UTC, hmcts-version1-domini commented on src/test/unit/services/translation/response/convertToCCDRejectAllOfClaimType.test.ts
> +describe('translate RejectAllOfClaimType to CCD model', () => {
Right! Done. Thanks!

2023-03-14 14:48 UTC, kenneth-hmcts submitted a review, later dismissed

2023-03-14 15:00 UTC, laperla11 approved these changes

2023-03-20 12:24 UTC, dtortolaV1 submitted a review, later dismissed

2023-03-24 09:38 UTC, portizdev approved these changes

2023-03-24 09:39 UTC, hmcts-version1-ignacio approved these changes

2023-03-24 13:26 UTC, merged