CIV-7614 transformdata pt2
hmcts/civil-citizen-ui pull request #1465
Opened 2023-03-22 21:38 UTC by laperla11

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-03-23 17:19 UTC, laperla11 commented on src/main/common/models/civilClaimResponse.ts
>    claimantUserDetails?: IdamUserDetails;
CIV-7614 changes

2023-03-23 17:19 UTC, laperla11 commented on src/main/common/models/claim.ts
>    id: string;
CIV-7614 changes

2023-03-23 17:21 UTC, laperla11 commented on src/main/services/features/response/admission/howMuchHaveYouPaidService.ts
>        if (type === ResponseType.PART_ADMISSION) {
CIV-7614 changes

2023-03-23 17:21 UTC, laperla11 commented on src/main/services/translation/convertToCUI/convertToCUIEvidence.ts
>  import {convertToEvidenceType} from 'models/evidence/evidenceType';
CIV-7614 changes

2023-03-23 17:21 UTC, laperla11 commented on src/main/services/translation/convertToCUI/convertToCUIPartialAdmission.ts
> +import {HowMuchHaveYouPaid} from 'common/form/models/admission/howMuchHaveYouPaid';
CIV-7614 changes

2023-03-23 17:22 UTC, laperla11 commented on src/main/services/translation/response/convertToCCDRecurringIncome.ts
>    if (!otherTransactions?.length) return undefined;
CIV-7614 changes

2023-03-23 17:23 UTC, laperla11 commented on src/test/unit/services/features/claimantResponse/claimantSuggestedInstalmentsService.test.ts
>            paymentAmount: PAYMENT_AMOUNT,
CIV-7614 changes

2023-03-23 17:23 UTC, laperla11 commented on src/test/unit/services/translation/convertToCUI/convertToCUIPartialAdmission.test.ts
> +import {
CIV-7614 changes

2023-03-24 09:22 UTC, TatsyMaslova approved these changes

2023-03-24 14:11 UTC, portizdev requested changes

2023-03-24 16:32 UTC, laperla11 commented on src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
> +  partialAdmissionAlreadyPaid?: YesNoUpperCamelCase;
Thanks Pablo, I'm in contact with Kamil about it

2023-04-06 21:58 UTC, laperla11 commented on src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
> +  partialAdmissionAlreadyPaid?: YesNoUpperCamelCase;
done

2023-04-24 10:16 UTC, portizdev submitted a review, later dismissed

2023-04-24 10:18 UTC, hmcts-version1-domini submitted a review, later dismissed

2023-04-24 16:19 UTC, TatsyMaslova approved these changes

2023-04-24 16:28 UTC, neeta-hmcts approved these changes

2023-04-25 10:06 UTC, merged