CIV-6214 dahsboard status part2
hmcts/civil-citizen-ui pull request #1501
Opened 2023-04-03 11:49 UTC by LeonardoPalmeiro

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-6214

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-04-03 15:08 UTC, laperla11 requested changes

2023-04-03 15:22 UTC, neeta-hmcts commented on src/main/services/features/dashboard/dashboardService.ts
> +export const getClaimsForClaimant = async (appRequest: AppRequest) => {
I believe this service has created to use in controller.

2023-04-04 07:56 UTC, TatsyMaslova commented on src/main/services/features/dashboard/dashboardService.ts
> +export const getClaimsForClaimant = async (appRequest: AppRequest) => {
Removed the service. thanks Kadir for noticing.

2023-04-04 08:05 UTC, laperla11 approved these changes

2023-04-04 08:17 UTC, laarmada approved these changes

2023-04-24 11:55 UTC, TatsyMaslova commented
reopen for deploy

2023-04-24 17:17 UTC, rajakm approved these changes

2023-04-24 17:17 UTC, merged