CIV-7972 welsh translation30
hmcts/civil-citizen-ui pull request #1519
Opened 2023-04-13 10:40 UTC by rhysbeazleyy

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-7972

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-04-13 11:07 UTC, dtortolaV1 approved these changes

2023-04-13 11:24 UTC, kenneth-hmcts approved these changes

2023-04-19 14:40 UTC, kenneth-hmcts submitted a review, later dismissed

2023-04-19 14:41 UTC, TatsyMaslova submitted a review, later dismissed

2023-04-19 14:47 UTC, GorilaNaranja submitted a review, later dismissed

2023-04-20 09:21 UTC, portizdev requested changes

2023-04-20 09:21 UTC, portizdev commented on src/main/modules/i18n/locales/cy.json
> +        "CLAIMANT_REFUSE_MEDIATION": "If they don't want to try media to yoution the court will review the case. You might have to go to a hearing.",
Typo error here?

2023-04-20 09:28 UTC, portizdev approved these changes

2023-04-25 03:53 UTC, laperla11 approved these changes

2023-04-25 07:25 UTC, GorilaNaranja approved these changes

2023-04-25 07:43 UTC, rajakm approved these changes

2023-04-25 07:43 UTC, merged