CIV-7618 CCD to CUI Common Part Admit
hmcts/civil-citizen-ui pull request #1522
Opened 2023-04-14 12:36 UTC by kenneth-hmcts

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-7618

### Change description ###
This PR contains changes for CCD to CUI translation

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-04-14 15:33 UTC, laarmada requested changes

2023-04-14 15:33 UTC, laarmada commented on src/main/common/models/civilClaimResponse.ts
> +  respondent1DQLanguage?: CCDWelshLanguageRequirements;
only to take care of that the size of this number of vbles is near to be out of control and unmanageable... could be group by , for example in that case DQ??

2023-04-14 15:33 UTC, laarmada commented on src/main/services/translation/convertToCUI/convertToCUIHearing.ts
> +    if (ccdClaim.respondent1LiPResponse?.respondent1DQExtraDetails?.whyUnavailableForHearing) {
that is not the same as:
hearing.whyUnavailableForHearing.reason = ccdClaim.respondent1LiPResponse.respondent1DQExtraDetails.whyUnavailableForHearing ? ccdClaim.respondent1LiPResponse?.respondent1DQExtraDetails?.whyUnavailableForHearing : ....;

2023-04-14 15:33 UTC, laarmada commented on src/main/services/translation/convertToCUI/convertToCUIHearing.ts
> +    if (ccdClaim.respondent1LiPResponse?.respondent1DQExtraDetails?.whyUnavailableForHearing) {
the same for each on if...

2023-04-14 15:33 UTC, laarmada commented on src/main/services/translation/convertToCUI/convertToCUIHearing.ts
> +  if (!ccdUnavailableDates?.length) return undefined;
avoid return undefined for lenght reason you can control the return in the place which you call that function

2023-04-14 15:33 UTC, laarmada commented on src/main/services/translation/convertToCUI/convertToCUIVulnerability.ts
> +    const vulnerabilityQuestions: VulnerabilityQuestions = new VulnerabilityQuestions();
here you are mixing the "new" 'OOD' with the json object structure:
vulnerabilityQuestions.vulnerability = {
      option: toCUIYesNo(ccdVulnerability.vulnerabilityAdjustmentsRequired),
      vulnerabilityDetails: ccdVulnerability.vulnerabilityAdjustments,
    };
... I don't like mix it. Only a comment

2023-04-14 15:33 UTC, laarmada commented on src/main/services/translation/convertToCUI/convertToCUIWitnesses.ts
> +    const witness : Witnesses = {
that is the same as:
return new Witnesses (otherWitness);

2023-04-17 13:50 UTC, neeta-hmcts approved these changes

2023-04-19 11:07 UTC, merged