CIV-7836 Evidence upload latest update on claim summary
hmcts/civil-citizen-ui pull request #1550
Opened 2023-04-24 16:21 UTC by jakiurmalik

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-7836

### Change description ###
develop latest update screen for evidence upload

### Screenshot ###
![uploaddocuments](https://user-images.githubusercontent.com/79106600/234057078-ec070aca-2e38-4af9-90e0-b1f268e7732f.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-04-24 18:19 UTC, LeonardoPalmeiro requested changes
we need to use feature toggle.

2023-04-24 20:07 UTC, laarmada requested changes
Nice code :)

2023-04-24 20:07 UTC, laarmada commented on src/main/common/models/civilClaimResponse.ts
> +  sdoOrderDocument?: CaseDocument;
I f we will have more documents or info under latestUpdateSection, we should create a hierarchy for that instead of leave in the root one. On the other hand this sdo document is for the defendant and claimant the same?

2023-04-24 20:07 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +        "TITLE": "Upload documents",
at the beginning in the project we should order in A-Z. :)

2023-04-24 20:07 UTC, laarmada commented on src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/evidenceUploadContent.ts
> +    .addButton('PAGES.LATEST_UPDATE_CONTENT.EVIDENCE_UPLOAD.TITLE', '') //todo: add href
which href do you need?

2023-04-24 20:07 UTC, laarmada commented on src/test/unit/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.test.ts
> +  it('should addLink with text before and after', ()=> {
only one test? what's app if we dont have data?, for example...

2023-04-24 20:07 UTC, laarmada commented on src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
> +    it('should have evidence upload content', () => {
only one test cover all scenarios?

2023-04-25 01:44 UTC, LeonardoPalmeiro commented on src/main/common/models/civilClaimResponse.ts
> +  sdoOrderDocument?: CaseDocument;
SdoDocument in case data is in the root path.
I believe for defendant and claimant the documents are different
![image](https://user-images.githubusercontent.com/93268657/234153960-3d7aef46-f74e-4c7e-b725-d076a816e185.png)

2023-04-27 08:49 UTC, LeonardoPalmeiro commented on src/test/unit/routes/features/dashboard/defendant/claimDefendantSummaryController.test.ts
I like this folder organization but the correct patch should be /dashboard/claimSummaryControlles.test is much more easy to find it.
what do you think?

2023-04-27 12:47 UTC, LeonardoPalmeiro approved these changes
LGTM

2023-04-27 12:49 UTC, hmcts-version1-ignacio commented on src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/evidenceUploadContent.ts
> +    .addButton('PAGES.LATEST_UPDATE_CONTENT.EVIDENCE_UPLOAD.TITLE', '') //todo: add href
Mine would be at case-progression/upload-your-documents

2023-04-27 13:07 UTC, kurt-uk requested changes

2023-04-27 13:07 UTC, kurt-uk commented on src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
> +});
looks like theres another condition to test, if the `lastestUpdateContent.length` is 0 or greater

2023-04-27 15:05 UTC, laarmada submitted a review, later dismissed

2023-04-27 15:05 UTC, laarmada commented on src/main/common/models/claim.ts
> +  sdoOrderDocument?: CaseDocument;
is for claimant or defendant?

2023-04-28 07:16 UTC, LeonardoPalmeiro approved these changes

2023-04-28 09:56 UTC, kurt-uk submitted a review, later dismissed

2023-05-02 08:41 UTC, hmcts-version1-ignacio approved these changes

2023-05-02 08:42 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-05-02 08:52 UTC, kurt-uk submitted a review, later dismissed

2023-05-02 11:22 UTC, hmcts-version1-ignacio approved these changes

2023-05-03 08:18 UTC, LeonardoPalmeiro approved these changes

2023-05-03 09:55 UTC, kurt-uk approved these changes

2023-05-03 10:44 UTC, merged