CIV 7839 evidence upload macro
hmcts/civil-citizen-ui pull request #1551
Opened 2023-04-24 20:09 UTC by laarmada

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-7839

### Change description ###

Framework "Upload documents"

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-04-25 02:53 UTC, LeonardoPalmeiro requested changes

2023-04-25 02:53 UTC, LeonardoPalmeiro commented on src/main/modules/oidc/index.ts
> +      return next();
this would be disable the login, please remove it

2023-04-25 02:53 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/witnessContentBuilder.ts
> +export const buildWitnessSection = (claim: Claim, claimId: string): ClaimSummarySection[] => {
if we build this section in this way we are create 5 different sections the correct would be one section.
if we use the divider this part will be something like:

title
-----
subtitle
------

2023-04-25 02:53 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/witnessSection.ts
> +import {ClaimSummarySection, ClaimSummaryType} from '../../../common/form/models/claimSummarySection';
mi suggestion in here is create a builder like we have in latestUpdateSectionBuilder.ts make more easy our job

2023-04-25 02:53 UTC, LeonardoPalmeiro commented on src/main/views/webpack/js.njk
> +<script src="/main-dev.js"></script>
may we don't need this change

2023-04-25 07:41 UTC, laarmada commented on src/main/views/webpack/js.njk
> +<script src="/main-dev.js"></script>
done

2023-04-25 07:41 UTC, laarmada commented on src/main/modules/oidc/index.ts
> +      return next();
done

2023-04-25 09:46 UTC, kurt-uk commented on src/main/services/features/caseProgression/witnessSection.ts
> +import {ClaimSummarySection, ClaimSummaryType} from '../../../common/form/models/claimSummarySection';
this does look like a builder anyway really, just has `getBLAH` instead of `addBLAH`

2023-04-25 11:01 UTC, kurt-uk commented
we're missing tests on this PR, unit and the start of some functional?

2023-04-26 13:28 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-04-26 14:17 UTC, nagaraju-deekonda approved these changes

2023-04-26 15:52 UTC, LeonardoPalmeiro approved these changes

2023-05-05 08:10 UTC, LeonardoPalmeiro approved these changes

2023-05-05 08:49 UTC, kurt-uk approved these changes

2023-05-05 10:05 UTC, kurt-uk approved these changes

2023-05-05 14:17 UTC, merged