CIV-7837 upload your documents introduction
hmcts/civil-citizen-ui pull request #1571
Opened 2023-04-28 13:08 UTC by ignacio-version1

### [CIV-7837](https://tools.hmcts.net/jira/browse/CIV-7837) ###

### The scope of this ticket is to develop the "upload your documents" introduction screen for both small and fast-track claims. ###

![MicrosoftTeams-image](https://github.com/hmcts/civil-citizen-ui/assets/107860328/d5e938fc-56ce-40e1-9d0b-841197a574eb)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-05-05 10:04 UTC, kurt-uk submitted a review, later dismissed

2023-05-05 11:43 UTC, LeonardoPalmeiro commented on src/main/routes/features/caseProgression/uploadYourDocumentsController.ts
> +      const latestUpdateSection = getUploadYourDocumentsContent(claimId, claim);
this variable name is not reflect correctly the propose. I believe we can use something like uploadYourDocumentsSections 

What do you think?

2023-05-05 12:04 UTC, hmcts-version1-ignacio commented on src/main/routes/features/caseProgression/uploadYourDocumentsController.ts
> +      const latestUpdateSection = getUploadYourDocumentsContent(claimId, claim);
True! I'll change it. Thanks!

2023-05-05 12:11 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-05-05 12:47 UTC, hmcts-version1-ignacio commented on src/main/common/form/models/claimSummarySection.ts
> +  LEAD_PARAGRAPH = 'lead paragraph',
Agree, changed, thanks!

2023-05-05 13:03 UTC, LeonardoPalmeiro approved these changes

2023-05-05 15:22 UTC, kurt-uk approved these changes

2023-05-05 15:26 UTC, laarmada submitted a review, later dismissed

2023-05-05 15:26 UTC, laarmada commented on src/main/routes/features/caseProgression/uploadYourDocumentsController.ts
> +function getUploadYourDocumentsContents(claimId: string, claim: Claim) {
that function should be in a service class

2023-05-08 14:41 UTC, hmcts-version1-ignacio commented on src/main/routes/features/caseProgression/uploadYourDocumentsController.ts
> +function getUploadYourDocumentsContents(claimId: string, claim: Claim) {
Done

2023-05-09 09:11 UTC, kurt-uk requested changes

2023-05-09 09:14 UTC, kurt-uk requested changes

2023-05-09 09:14 UTC, kurt-uk commented on src/main/services/features/caseProgression/uploadYourDocumentsContents.ts
> +  return new LatestUpdateSectionBuilder()
do we want to use LatestUpdateSectionBuilder on something thats not a latest section update? we should potentially create a section builder that contains generic sections and then latest update and this new one for uploading doc section builder can both extend it

2023-05-09 10:38 UTC, hmcts-version1-ignacio commented on src/test/unit/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.test.ts
> +    expect(subTitleObject).toEqual(result);
Yes, true, just because of a copy paste, I'll correct it for all the tests in that file.

2023-05-09 13:43 UTC, hmcts-version1-ignacio commented on src/main/services/features/caseProgression/uploadYourDocumentsContents.ts
> +  return new LatestUpdateSectionBuilder()
Yes, we talked about that with Leo, and yes, it would be better to do that.

2023-05-11 12:58 UTC, kurt-uk requested changes

2023-05-11 12:58 UTC, kurt-uk commented on src/test/unit/common/utils/pageSectionBuilder.test.ts
> +    const textAfter= 'textAfter';
pull these consts out (and others) that are used by multiple tests and have them declared at class level so you dont keep repeating yourself

2023-05-12 07:28 UTC, hmcts-version1-ignacio commented on src/test/unit/common/utils/pageSectionBuilder.test.ts
> +    const textAfter= 'textAfter';
Yes, true. Done!

2023-05-12 10:48 UTC, hmcts-version1-ignacio commented on src/main/common/utils/pageSectionBuilder.ts
> +export class PageSectionBuilder {
Done!

2023-05-12 13:14 UTC, laarmada approved these changes

2023-05-12 13:16 UTC, laarmada commented on src/main/views/features/dashboard/item-content.njk
> +          <p class="govuk-body-l">{{ t(content.data.text,object)}}</p>
why is class="govuk-body-l" instead of class="govuk-body"??

2023-05-15 07:57 UTC, hmcts-version1-ignacio commented on src/main/views/features/dashboard/item-content.njk
> +          <p class="govuk-body-l">{{ t(content.data.text,object)}}</p>
I've taken that from here:

![image](https://github.com/hmcts/civil-citizen-ui/assets/107860328/5494ea69-92ca-43b1-81a9-da6c9771369b)

[https://design-system.service.gov.uk/styles/layout/](https://design-system.service.gov.uk/styles/layout/)

2023-05-15 12:28 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-05-15 13:45 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-05-15 13:55 UTC, kurt-uk submitted a review, later dismissed

2023-05-15 16:14 UTC, kurt-uk approved these changes

2023-05-16 09:26 UTC, kurt-uk approved these changes

2023-05-17 15:32 UTC, m-meulendijks-v1 approved these changes

2023-05-17 15:34 UTC, LeonardoPalmeiro approved these changes

2023-05-18 15:03 UTC, merged