CIV-7729 hearing notice latest update to defendant lip
hmcts/civil-citizen-ui pull request #1584
Opened 2023-05-03 08:05 UTC by LeonardoPalmeiro

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-7729

### Change description ###

![image](https://user-images.githubusercontent.com/93268657/235915594-431f6a56-1b84-4c50-b100-2f50ec4c0679.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-05-03 09:26 UTC, LeonardoPalmeiro commented on src/main/routes/features/dashboard/claimSummaryController.ts
> +  //getHearingTrialUploadLatestUpdateContent
done

2023-05-03 09:29 UTC, LeonardoPalmeiro commented on src/main/routes/features/dashboard/claimSummaryController.ts
> +        }else if(claim.hasSdoOrderDocument()){
I agree with you, I will remove it

2023-05-03 13:19 UTC, laarmada submitted a review, later dismissed

2023-05-03 13:30 UTC, kurt-uk requested changes

2023-05-03 13:30 UTC, kurt-uk commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
should belong in models? the models directory is defining what things should look like, listing fields and their types. This is manipulating data rather than defining a model

2023-05-03 13:30 UTC, kurt-uk commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
would fit better in what we currently have as service/builder

2023-05-04 07:10 UTC, LeonardoPalmeiro commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
@kurt-uk please, let me know what I need to do.

2023-05-04 11:53 UTC, LeonardoPalmeiro commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
done.
thanks for point this.
I really appreciate

2023-05-04 11:55 UTC, kurt-uk approved these changes

2023-05-05 10:06 UTC, kurt-uk approved these changes

2023-05-05 12:13 UTC, hmcts-version1-ignacio approved these changes

2023-05-11 11:10 UTC, hmcts-version1-ignacio approved these changes

2023-05-11 12:47 UTC, kurt-uk approved these changes

2023-05-11 12:59 UTC, merged