Feat/civ 7748 - Button to Hearing Notice in Dashboard
hmcts/civil-citizen-ui pull request #1597
Opened 2023-05-05 13:15 UTC by m-meulendijks-v1

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-7748

### Change description ###

![image](https://user-images.githubusercontent.com/107135537/236466939-81457753-eead-43ec-8dac-1791f7bb8dbf.png)
![image](https://user-images.githubusercontent.com/107135537/236467272-31a7d393-09da-4850-93fa-cf2e0d553db7.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-05-05 13:27 UTC, kurt-uk commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
just an FYI this has changed slightly in that its been separated into a service for the data manipulation, a latest pull from leos branch should sort it

2023-05-05 13:44 UTC, laarmada requested changes

2023-05-05 13:44 UTC, laarmada commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
> +export class CaseProgressionHearing {
only a question, why we don't reuse the CaseDocument.ts file?instead of CaseProgressionHearingDocuments

2023-05-05 13:49 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
> +export class CaseProgressionHearing {
@laarmada That is taken from this PR: https://github.com/hmcts/civil-citizen-ui/pull/1584
This PR builds on that one.

2023-05-05 13:50 UTC, m-meulendijks-v1 commented on src/main/common/models/claim.ts
> +  caseProgressionHearing?: CaseProgressionHearing;
This is from pr: https://github.com/hmcts/civil-citizen-ui/pull/1584
Case progression documents dealt with in this PR apply to both claimant & defendant.

2023-05-05 13:52 UTC, m-meulendijks-v1 commented on src/main/routes/features/document/documentDownloadController.ts
> +    deleteDraftClaimFromStore(req.params.id);
For some reason, the hearing notice does not get found when using the getClaimById method below.
To retrieve the document, the store had to be deleted first, and then the above method is able to retrieve the data. 
This was discussed with Kurt & Leo.

2023-05-05 13:53 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
I've pulled the latest, so could you check it is up to scratch now?

2023-05-05 13:55 UTC, kurt-uk submitted a review, later dismissed

2023-05-05 14:41 UTC, laarmada commented on src/main/common/models/claim.ts
> +  caseProgressionHearing?: CaseProgressionHearing;
![image](https://user-images.githubusercontent.com/23473639/236489949-74addae8-4106-40bb-8c89-66fd6f9e8b05.png)

2023-05-05 14:42 UTC, laarmada commented on src/main/common/models/claim.ts
> +  caseProgressionHearing?: CaseProgressionHearing;
![image](https://user-images.githubusercontent.com/23473639/236490024-e4785022-2b22-4915-a8df-b19e284b814a.png)
inside of this class should be include every case progression data in order to avoid duplications and understanding.....

2023-05-09 09:12 UTC, hmcts-version1-ignacio requested changes

2023-05-09 12:53 UTC, m-meulendijks-v1 commented on src/test/unit/services/features/caseProgression/courtNameExtractor.test.ts
This was taken from https://github.com/hmcts/civil-citizen-ui/pull/1584 and not added here.

2023-05-09 13:49 UTC, m-meulendijks-v1 commented on src/test/unit/services/features/caseProgression/hearingDateTimeFormatter.ts
Test is refactored - should be correct now.

2023-05-09 13:49 UTC, m-meulendijks-v1 commented on src/test/unit/services/features/caseProgression/courtNameExtractor.test.ts
Test is refactored - should be correct now.

2023-05-09 14:31 UTC, laarmada approved these changes

2023-05-09 14:31 UTC, laarmada commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
> +export class CaseProgressionHearing {
ok, we need refactor everything in any point...

2023-05-10 08:20 UTC, hmcts-version1-ignacio approved these changes

2023-05-10 08:40 UTC, kurt-uk submitted a review, later dismissed

2023-05-10 08:42 UTC, kurt-uk commented
Do not merge until `claim` and `caseProgression` model has been resolved to nested structure

2023-05-16 08:45 UTC, kurt-uk approved these changes

2023-05-17 07:49 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-05-17 08:43 UTC, kurt-uk submitted a review, later dismissed

2023-05-18 08:06 UTC, hmcts-version1-ignacio commented on src/test/unit/services/features/caseProgression/courtNameExtractor.test.ts
> +    const countName = 'test - test';
Is it courtName?

2023-05-18 08:06 UTC, hmcts-version1-ignacio commented on src/test/unit/services/features/caseProgression/courtNameExtractor.test.ts
> +    const countNameExpected = 'test';
courtNameExpected?

2023-05-18 08:11 UTC, hmcts-version1-ignacio commented on src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
> +    const hearingNocticeSection = buildDownloadHearingNoticeSection(mockClaim, '1', 'eng');
hearingNoticeSection?

2023-05-18 08:12 UTC, hmcts-version1-ignacio commented on src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
> +  it('should return nothing as correct information missing', ()=>{
should return nothing IF correct information missing?

2023-05-18 08:41 UTC, m-meulendijks-v1 commented on src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
> +  it('should return nothing as correct information missing', ()=>{
corrected

2023-05-18 08:41 UTC, m-meulendijks-v1 commented on src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
> +    const hearingNocticeSection = buildDownloadHearingNoticeSection(mockClaim, '1', 'eng');
corrected

2023-05-18 08:43 UTC, m-meulendijks-v1 commented on src/test/unit/services/features/caseProgression/courtNameExtractor.test.ts
> +    const countName = 'test - test';
renamed

2023-05-18 08:43 UTC, m-meulendijks-v1 commented on src/test/unit/services/features/caseProgression/courtNameExtractor.test.ts
> +    const countNameExpected = 'test';
renamed

2023-05-18 15:34 UTC, hmcts-version1-ignacio approved these changes

2023-07-25 09:10 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-25 10:44 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-07-26 10:28 UTC, kurt-uk submitted a review, later dismissed

2023-07-27 09:00 UTC, LeonardoPalmeiro approved these changes

2023-08-03 14:34 UTC, LeonardoPalmeiro commented on src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
> +        isStartButton: true,
I'm not sure if in this case the button should be like a start button.

2023-08-03 14:35 UTC, LeonardoPalmeiro commented on src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
> +  addButtonOpensNewTab(title: string, href: string) {
why we don't add a new attribute of the button rather create another type of button?

2023-08-03 14:48 UTC, LeonardoPalmeiro commented on src/main/common/models/document/systemGeneratedCaseDocuments.ts
> +    documentId = CaseDocumentInfoExtractor.getSystemGeneratedCaseDocumentIdByType(systemGeneratedCaseDocuments, documentType);
why are we change the name?

2023-08-03 14:48 UTC, LeonardoPalmeiro commented on src/main/common/utils/downloadUtils.ts
> +  retrieveFile(res, fileResponse, 'attachment');
may we can use an enum in here or an constant

2023-08-03 14:48 UTC, LeonardoPalmeiro commented on src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
> +        text: `${t(downloadClaimLabel, lang)} (PDF, ${displayDocumentSizeInKB(document.documentSize)})`,
dump question.. should we translate PDF String ?

2023-08-03 14:52 UTC, m-meulendijks-v1 commented on src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
> +  addButtonOpensNewTab(title: string, href: string) {
To open in a new tab, I use target="_blank", but I think that works only on an <a> element, not a button.
So I created another type of button that in the itemContent.njk translates to a <a> that looks like a button.

2023-08-03 14:53 UTC, m-meulendijks-v1 commented on src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
> +        isStartButton: true,
This bit isn't actually used for the <a> due to the changes that I've made.
Happy to remove it.

2023-08-03 14:54 UTC, m-meulendijks-v1 commented on src/main/common/models/document/systemGeneratedCaseDocuments.ts
> +    documentId = CaseDocumentInfoExtractor.getSystemGeneratedCaseDocumentIdByType(systemGeneratedCaseDocuments, documentType);
I changed the name, as we will also end up using it for Case Documents that are not system generated.
But I can change the name back.

2023-08-03 14:58 UTC, m-meulendijks-v1 commented on src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
> +        text: `${t(downloadClaimLabel, lang)} (PDF, ${displayDocumentSizeInKB(document.documentSize)})`,
The PDF name itself is named on the backend, so we don't wan't to translate that, right?
I think we just want to translate the labels.

2023-08-03 15:11 UTC, m-meulendijks-v1 commented on src/main/common/utils/downloadUtils.ts
> +  retrieveFile(res, fileResponse, 'attachment');
I've put in constants at the top of the file.

2023-08-03 15:12 UTC, maciejmodzelewski approved these changes

2023-08-03 15:33 UTC, maciejmodzelewski submitted a review, later dismissed

2023-08-04 07:41 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-08-08 11:15 UTC, m-meulendijks-v1 commented on src/main/routes/features/document/documentDownloadController.ts
>      const claim: Claim = await getClaimById(req.params.id, req);
No longer relevant

2023-08-08 11:18 UTC, maciejmodzelewski approved these changes

2023-08-08 11:24 UTC, LeonardoPalmeiro approved these changes

2023-08-08 11:29 UTC, merged