CIV-7845 Evidence upload submission confirmation screen
hmcts/civil-citizen-ui pull request #1619
Opened 2023-05-10 13:02 UTC by jakiurmalik

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-7845

### Change description ###
Implemented new documents upload screen for evidence uploads.

![image](https://github.com/hmcts/civil-citizen-ui/assets/107860328/84924a7c-5874-47f7-97d8-88f61421c4a7)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2023-05-10 15:19 UTC, m-meulendijks-v1 approved these changes

2023-05-10 15:31 UTC, kurt-uk submitted a review, later dismissed

2023-05-11 11:38 UTC, hmcts-version1-ignacio requested changes

2023-05-12 09:13 UTC, laarmada requested changes

2023-05-12 09:13 UTC, laarmada commented on src/main/views/features/caseProgression/documents-uploaded.njk
> +{% from "../../macro/contact-us-for-help.njk" import contactUsForHelp %}
move at the bottom

2023-05-12 09:13 UTC, laarmada commented on src/main/views/features/caseProgression/documents-uploaded.njk
> +      <div class="govuk-grid-column-two-thirds govuk-!-margin-top-0">
{{ csrfProtection(csrf) }} is missing

2023-05-12 15:12 UTC, hmcts-version1-ignacio commented on src/main/views/features/caseProgression/documents-uploaded.njk
Done.

2023-05-12 15:44 UTC, hmcts-version1-ignacio commented on src/main/routes/features/caseProgression/documentsUploadedController.ts
> +    if (claim && !claim.isEmpty()) {
Updated to "Something went wrong" message if the claim does not exist.

2023-05-15 13:57 UTC, kurt-uk approved these changes

2023-05-16 08:05 UTC, hmcts-version1-ignacio approved these changes

2023-05-19 11:21 UTC, LeonardoPalmeiro approved these changes

2023-05-19 11:21 UTC, kurt-uk approved these changes

2023-05-19 11:21 UTC, hmcts-version1-ignacio approved these changes

2023-05-19 11:30 UTC, merged