CIV-7838 - Small Claims page for Evidence Upload
hmcts/civil-citizen-ui pull request #1629
Opened 2023-05-12 13:54 UTC by m-meulendijks-v1

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-7838

### Change description ###
Added a small claims page for evidence upload. Underlying values derived from CIV-7857.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-05-12 14:51 UTC, laarmada requested changes

2023-05-12 14:51 UTC, laarmada commented on src/main/views/features/caseProgression/typeOfDocumentsFastTrack.njk
> +{% extends "claim-details-tpl.njk" %}
we can use the same Nunjuck file passing the vble from controller, also we can use the same controller

2023-05-12 14:51 UTC, laarmada commented on src/main/routes/features/caseProgression/typeOfDocumentsController.ts
> +  if(claim.isFastTrackClaim)
instead of do that you can send the claim.isFastTrackClaim to the view and hide or show the related information..... depending on that.

2023-05-12 15:58 UTC, m-meulendijks-v1 commented on src/main/views/features/caseProgression/typeOfDocumentsFastTrack.njk
> +{% extends "claim-details-tpl.njk" %}
Moved claimType logic from controller to view. Have a look.

2023-05-12 15:58 UTC, m-meulendijks-v1 commented on src/main/routes/features/caseProgression/typeOfDocumentsController.ts
> +  if(claim.isFastTrackClaim)
Moved claimType logic from controller to view. Have a look.

2023-05-16 08:27 UTC, LeonardoPalmeiro approved these changes

2023-05-16 08:43 UTC, kurt-uk submitted a review, later dismissed

2023-05-31 10:02 UTC, LeonardoPalmeiro approved these changes

2023-05-31 10:55 UTC, merged