CIV-8562 implement disclosure sections for evidence upload
hmcts/civil-citizen-ui pull request #1684
Opened 2023-05-24 15:25 UTC by jakiurmalik

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-8562

### Change description ###
Fast Track : Upload documents Page - Part 1 -  Disclosure section
![civ-8562](https://github.com/hmcts/civil-citizen-ui/assets/79106600/ad3096a8-fffa-47b6-a951-9bfe7b532135)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2023-05-25 08:31 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-05-25 14:18 UTC, laarmada requested changes

2023-05-25 14:18 UTC, laarmada commented on src/main/common/models/caseProgression/uploadDocumentsSectionBuilder.ts
> +  addTitle(title:string) {
the idea is to use only 1 approach, if you like this approach instead of uploadDocumentsSection.ts please, refactor that file and only use a common approach for all sections :)

2023-05-25 14:18 UTC, laarmada commented on src/main/services/features/caseProgression/disclosureContentBuilder.ts
> +    .addCustomInput('PAGES.UPLOAD_DOCUMENTS.DISCLOSURE.TYPE_OF_DOCUMENT','govuk-!-width-three-half', 'PAGES.UPLOAD_DOCUMENTS.DISCLOSURE.TYPE_OF_DOCUMENT_EXAMPLE','disclosure-documents-type')
the same here refactor the existing one in order to use builder :)

2023-05-25 14:18 UTC, laarmada commented on src/main/views/features/caseProgression/upload-documents.njk
> +                        text: 'Add another',
use a key instead of text

2023-05-25 14:18 UTC, laarmada commented on src/main/services/features/caseProgression/disclosureContentBuilder.ts
> +    .addCustomDateInput('PAGES.UPLOAD_DOCUMENTS.DISCLOSURE.DOCUMENT_ISSUE_DATE', 'PAGES.UPLOAD_DOCUMENTS.DATE_EXAMPLE', 'disclosure-documents')
use a constant or enum for all that names to avoid errors :) ... disclosure-documents

2023-05-25 15:32 UTC, LeonardoPalmeiro approved these changes

2023-05-25 18:03 UTC, hmcts-version1-ignacio approved these changes

2023-05-26 08:36 UTC, LeonardoPalmeiro approved these changes

2023-05-30 09:57 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-05-30 10:09 UTC, hmcts-version1-ignacio approved these changes

2023-05-30 10:46 UTC, kurt-uk submitted a review, later dismissed

2023-05-30 12:00 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-05-30 12:27 UTC, kurt-uk approved these changes

2023-05-31 10:52 UTC, LeonardoPalmeiro commented on src/main/views/features/caseProgression/upload-documents.njk
> -      {{ contactUsForHelp(t) }}
make sure with BI team that we don't need this.

2023-05-31 11:12 UTC, LeonardoPalmeiro approved these changes

2023-05-31 11:13 UTC, hmcts-version1-ignacio approved these changes

2023-06-01 09:06 UTC, kurt-uk approved these changes

2023-06-01 09:18 UTC, merged