CIV-7500 pcq journey check and submit
hmcts/civil-citizen-ui pull request #1743
Opened 2023-06-15 09:00 UTC by GorilaNaranja

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-7500

### Change description ###
PCQ journey on "check and submit your response"

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-04 11:46 UTC, laperla11 requested changes

2023-07-04 11:46 UTC, laperla11 commented on src/main/app/client/pcq/generatePcqToken.ts
> +  console.log('PCQ tokenKey: ', tokenKey);
do we still need this console?

2023-07-04 11:46 UTC, laperla11 commented on src/main/app/client/pcq/pcqClient.ts
> +  console.log('PCQ url: ', pcqBaseUrl);
same here

2023-07-04 11:46 UTC, laperla11 commented on src/main/routes/guards/pcqGuard.ts
> +    console.log('PCQ Guard');
same here

2023-07-04 11:46 UTC, laperla11 commented on src/main/routes/guards/pcqGuard.ts
> +    console.log('PCQ caseData.pcqId', caseData.pcqId);
same here

2023-07-04 11:46 UTC, laperla11 commented on src/main/routes/guards/pcqGuard.ts
> +    console.log('PCQ type', type);
same here

2023-07-04 11:46 UTC, laperla11 commented on src/main/routes/guards/pcqGuard.ts
> +    console.log('PCQ isHealthy', isHealthy);
same here

2023-07-04 11:46 UTC, laperla11 commented on src/main/routes/guards/pcqGuard.ts
> +    console.log('PCQ isElegible', isElegible);
same here

2023-07-04 11:46 UTC, laperla11 commented on src/main/routes/guards/pcqGuard.ts
> +      console.log('PCQ savePcqIdClaim...');
same here

2023-07-04 11:46 UTC, laperla11 commented on src/main/routes/guards/pcqGuard.ts
> +      console.log('PCQ pcqUrl', pcqUrl);
same here

2023-07-04 11:51 UTC, GorilaNaranja commented on src/main/app/client/pcq/generatePcqToken.ts
> +  console.log('PCQ tokenKey: ', tokenKey);
done

2023-07-04 11:51 UTC, GorilaNaranja commented on src/main/app/client/pcq/pcqClient.ts
> +  console.log('PCQ url: ', pcqBaseUrl);
done

2023-07-04 11:51 UTC, laperla11 submitted a review, later dismissed

2023-07-04 11:51 UTC, GorilaNaranja commented on src/main/routes/guards/pcqGuard.ts
> +    console.log('PCQ Guard');
done

2023-07-04 11:51 UTC, GorilaNaranja commented on src/main/routes/guards/pcqGuard.ts
> +    console.log('PCQ caseData.pcqId', caseData.pcqId);
done

2023-07-04 11:51 UTC, GorilaNaranja commented on src/main/routes/guards/pcqGuard.ts
> +    console.log('PCQ type', type);
done

2023-07-04 11:51 UTC, GorilaNaranja commented on src/main/routes/guards/pcqGuard.ts
> +    console.log('PCQ isHealthy', isHealthy);
done

2023-07-04 11:51 UTC, GorilaNaranja commented on src/main/routes/guards/pcqGuard.ts
> +    console.log('PCQ isElegible', isElegible);
done

2023-07-04 11:51 UTC, GorilaNaranja commented on src/main/routes/guards/pcqGuard.ts
> +      console.log('PCQ savePcqIdClaim...');
done

2023-07-04 11:51 UTC, GorilaNaranja commented on src/main/routes/guards/pcqGuard.ts
> +      console.log('PCQ pcqUrl', pcqUrl);
done

2023-07-04 11:54 UTC, TatsyMaslova commented on charts/civil-citizen-ui/values.preview.template.yaml
> +    PCQ_URL: https://pcq.aat.platform.hmcts.net
I dont think you need to define the value here. you already defined it in values. and if it is aat it will replace .Values.global.environment variable

2023-07-04 11:56 UTC, LeonardoPalmeiro approved these changes

2023-07-04 11:59 UTC, TatsyMaslova commented on src/test/unit/routes/features/response/checkAnswersController.test.ts
> +jest.mock('../../../../../main/modules/draft-store');
instead could you please mock await getCaseDataFromStore and then you will not need to set app.locals.draftRedis to draft redis. you will actually mock the required return from the function

2023-07-04 12:19 UTC, GorilaNaranja commented on charts/civil-citizen-ui/values.preview.template.yaml
> +    PCQ_URL: https://pcq.aat.platform.hmcts.net
Sandeep confirmed that you are right, I'm deleting this line.

2023-07-04 12:20 UTC, portizdev approved these changes

2023-07-04 13:14 UTC, LeonardoPalmeiro approved these changes

2023-07-04 13:19 UTC, laperla11 approved these changes

2023-07-04 13:19 UTC, TatsyMaslova approved these changes

2023-07-04 13:21 UTC, portizdev submitted a review, later dismissed

2023-07-07 11:49 UTC, neeta-hmcts approved these changes

2023-07-07 11:49 UTC, portizdev approved these changes

2023-07-07 11:51 UTC, LeonardoPalmeiro approved these changes

2023-07-07 11:53 UTC, TatsyMaslova approved these changes

2023-07-07 11:55 UTC, laperla11 approved these changes

2023-07-07 13:38 UTC, merged