CIV-8881 - CUI to CCD translation for evidence upload.
hmcts/civil-citizen-ui pull request #1747
Opened 2023-06-15 15:51 UTC by m-meulendijks-v1

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-8881

### Change description ###
Translate evidence upload information  from CUI to CCD.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-06-16 09:03 UTC, LeonardoPalmeiro approved these changes

2023-06-16 09:12 UTC, kurt-uk submitted a review, later dismissed

2023-06-16 09:27 UTC, hmcts-version1-ignacio approved these changes

2023-06-19 08:22 UTC, pats-john requested changes

2023-06-19 08:22 UTC, pats-john commented on src/test/unit/services/translation/caseProgression/convertToCCDEvidenceUpload.test.ts
> +
I recommend adding a test for a claim with only some of the document details and thrashing out if empty sections need to be considered for this or not.

2023-06-20 15:04 UTC, hmcts-version1-ignacio approved these changes

2023-06-21 07:59 UTC, m-meulendijks-v1 commented on src/test/unit/services/translation/caseProgression/convertToCCDEvidenceUpload.test.ts
> +
@pats-john I have added another tests that tests whether when ccd lists are only filled partially or with multiple elements.
I have not added a test for what happens when certain document fields are missing, because I think we'll need to change the way the pre-existing Document object is currently implemented to make certain fields mandatory.

2023-06-21 09:02 UTC, kurt-uk approved these changes

2023-06-23 14:26 UTC, pats-john approved these changes

2023-06-24 11:34 UTC, merged