Civ 640 dashboard view cases
hmcts/civil-citizen-ui pull request #175
Opened 2022-02-28 18:09 UTC by osheaf01

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-640

### Change description ###
Citizen Dashboard - citizen can view changes defended

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-01 08:57 UTC, laarmada requested changes
ok

2022-03-01 08:57 UTC, laarmada commented on config/default.yaml
> -    url: 'http://localhost:8765'
you shouldn´t change this value.

2022-03-01 08:57 UTC, laarmada commented on src/main/app/client/civilServiceClient.ts
> -    const response: AxiosResponse<object> = await this.client.get('/cases');
should we add an exception control here to avoid broken then webpage when the communication fails?

2022-03-01 08:57 UTC, laarmada commented on src/main/app/client/civilServiceClient.ts
> +    return this.client.post(CASES_URL,
I don´t like return large piece of code....

2022-03-01 08:59 UTC, laarmada requested changes

2022-03-01 08:59 UTC, laarmada commented on src/main/app/client/civilServiceClient.ts
>      const response: AxiosResponse<object> = await this.client.get(`/cases/${claimId}`);
should we add an exception control here to avoid broken then webpage when the communication fails?

2022-03-01 09:01 UTC, TatsyMaslova commented on src/main/app/client/civilServiceClient.ts
>      const response: AxiosResponse<object> = await this.client.get(`/cases/${claimId}`);
I think this story is not about individual case. so the individual case retrieval is still broken. this story is to retrieve all cases. I think for the individual case we need a different story - as there are quite a bit of changes that are required and adding unit tests

2022-03-01 09:03 UTC, TatsyMaslova commented on config/default.yaml
> -    url: 'http://localhost:8765'
this is url for the civil service. if the civil service runs on port 4000 then the port previously specified is incorrect

2022-03-01 09:05 UTC, laarmada commented on config/default.yaml
> -    url: 'http://localhost:8765'
but in my last PR Mounika ask me that, so maybe it´ll fail on Jenkins

2022-03-01 09:19 UTC, TatsyMaslova commented on src/main/app/client/civilServiceClient.ts
> +    return this.client.post(CASES_URL,
I agree. not very readable

2022-03-01 09:22 UTC, TatsyMaslova commented on config/default.yaml
> -    url: 'http://localhost:8765'
hmm perhaps we need to ask @mounikahmcts about this

2022-03-01 09:29 UTC, TatsyMaslova commented on src/main/app/client/civilServiceClient.ts
> +    return this.client.post(CASES_URL,
also the method should be async because it returns a promise and also the client that is using the method needs to wait for the promise either to succeed or to fail

2022-03-01 09:57 UTC, mounikahmcts commented on config/default.yaml
> -    url: 'http://localhost:8765'
I have asked to update civilService url in preview/aat url of civil service in custom. environment variable like this 
https://github.com/hmcts/div-decree-nisi-frontend/blob/master/config/custom-environment-variables.yml#L67
Without which i cant test anything

2022-03-01 11:24 UTC, osheaf01 commented on src/main/app/client/civilServiceClient.ts
> +    return this.client.post(CASES_URL,
Have pushed changes to make this look nicer, please re-review.

2022-03-01 13:51 UTC, LeonardoPalmeiro requested changes

2022-03-01 13:51 UTC, LeonardoPalmeiro commented on src/main/app/client/civilServiceClient.ts
>      }
we don't need    this if  if (!response.data) {...
because we're using .catch from post. 

My suggestion is:

    await this.client.post(CASES_URL,{ match_all: {} }, config)
      .then(response => {
        claims = response.data.cases.map((claim: CivilClaimResponse) => Object.assign(new Claim(), claim.case_data));
      }).catch(error => {
        throw new AssertionError({message: 'Claim details not available.'});
      });

2022-03-01 13:51 UTC, LeonardoPalmeiro commented on src/main/app/client/civilServiceUrls.ts
> +export const CASES_URL = '/cases/';
in this case we've a file to store all routerscan be found
in  src/main/routes/urls.ts

2022-03-01 13:51 UTC, LeonardoPalmeiro commented on src/main/common/models/claim.ts
> +
in the review version we had:
  individualTitle: string;
  individualLastName: string;
  individualFirstName: string;

do we remove it ?

2022-03-01 13:51 UTC, LeonardoPalmeiro commented on src/main/routes/features/dashboard/index.ts
> +  const claimsAsClaimant : Claim[] = [];
do we need to send an empty object to the page?

2022-03-01 13:54 UTC, TatsyMaslova commented on src/main/app/client/civilServiceUrls.ts
> +export const CASES_URL = '/cases/';
this is an api to civil service so I don't think it belongs in the routes/url.ts which is for routes that are for citizen-ui (i.e navigation through pages in browser)

2022-03-01 13:55 UTC, TatsyMaslova commented on src/main/common/models/claim.ts
> +
yes because they are repeating for respondents and applicant. the the json returned from api these are only defined in applicant and respondent . These are not needed  and are confusing where they belong to

2022-03-01 13:56 UTC, TatsyMaslova commented on src/main/routes/features/dashboard/index.ts
> +  const claimsAsClaimant : Claim[] = [];
yes, in my opinion because then the page will still be built even if there are no claims or if civil service is down

2022-03-01 13:58 UTC, TatsyMaslova commented on src/main/app/client/civilServiceClient.ts
>      }
I think we are not changing this call for now. this call is for another story. the one that would deal with individual cases. this call as is will not work at the moment.

2022-03-01 15:47 UTC, LeonardoPalmeiro commented on src/main/common/models/claim.ts
> +
I agree with you, I was just make sure that not was a mistake

2022-03-02 08:30 UTC, laarmada approved these changes

2022-03-04 14:06 UTC, merged