Feature/civ 8842
hmcts/civil-citizen-ui pull request #1758
Opened 2023-06-20 10:03 UTC by bhagyashreesharma90

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-8842

### Change description ###
Added date validations

![image](https://github.com/hmcts/civil-citizen-ui/assets/114094319/4dc6b557-38ef-4bcf-b138-1f96e46d2876)
![image](https://github.com/hmcts/civil-citizen-ui/assets/114094319/3ac216d9-d99c-423a-aef9-1858094961ca)
![image](https://github.com/hmcts/civil-citizen-ui/assets/114094319/6047be89-3938-4b93-98d9-8407c551009b)
![image](https://github.com/hmcts/civil-citizen-ui/assets/114094319/e5d9d9ef-3046-42da-98a7-0381587c81c6)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-06-22 08:48 UTC, LeonardoPalmeiro approved these changes

2023-06-22 09:45 UTC, hmcts-version1-ignacio approved these changes

2023-06-22 09:59 UTC, LeonardoPalmeiro approved these changes

2023-06-22 10:48 UTC, kurt-uk requested changes

2023-06-22 10:48 UTC, kurt-uk commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +export class DateOnlySection extends  FileOnlySection {
whats the purpose for extending the FileOnlySection? what do you need to use from it?

2023-06-22 10:48 UTC, kurt-uk commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +export class DateOnlySection extends  FileOnlySection {
also i dont think we have any date only sections?

2023-06-22 10:48 UTC, kurt-uk commented on src/main/common/models/caseProgression/uploadDocumentsSectionBuilder.ts
> +  addDateArray(title: string, invalidDayError: string, invalidMonthError: string, invalidYearError: string, invalidDateError: string, hint: string, category: string, field: string, dayValue: string,
could all these not be condensed into a `errorMessage[]` rather than hard coded parameters?

2023-06-22 10:48 UTC, kurt-uk commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +    @ValidateIf(o => ((o.dateDay!==undefined && o.dateMonth!==undefined && o.dateDay && o.dateMonth && o.dateYear && o.dateDay > 0 && o.dateDay < 32 && o.dateMonth > 0 && o.dateMonth < 13 && o.dateYe
How are these checks different to the ones below where you give the min and max? and how come only half of them are put in the form validators while some are coded inline?

2023-06-22 12:43 UTC, bhagyashreesharma90 commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +export class DateOnlySection extends  FileOnlySection {
> whats the purpose for extending the FileOnlySection? what do you need to use from it?

Added  this because we need both FileOnlySection and DateOnlySection in some of Witness, expert and disclosure sections classes and we can't extend multiple classes in ex. TypeOfDocumentSection class

2023-06-22 12:44 UTC, bhagyashreesharma90 commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +export class DateOnlySection extends  FileOnlySection {
> also i dont think we have any date only sections?

yes, we don't. this class gets extended to all classes having date sections.

2023-06-22 12:55 UTC, bhagyashreesharma90 commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +    @ValidateIf(o => ((o.dateDay!==undefined && o.dateMonth!==undefined && o.dateDay && o.dateMonth && o.dateYear && o.dateDay > 0 && o.dateDay < 32 && o.dateMonth > 0 && o.dateMonth < 13 && o.dateYe
This validation is for whole Date field and this o.dateDay > 0 && o.dateDay < 32 was added because we want to display day specific error (which is mentioned in day field ) not whole date error as those messages are different.
Ex. if in day field someone enters 45 then we are displaying different error message not the whole date (day+month+year) error message.
Only one check is added in validator which is to check if date is future date or not and all other are inline.

2023-06-23 07:30 UTC, hmcts-version1-ignacio approved these changes

2023-06-23 10:04 UTC, hmcts-version1-ignacio requested changes

2023-06-23 12:46 UTC, LeonardoPalmeiro approved these changes

2023-06-26 09:42 UTC, bhagyashreesharma90 commented on src/main/services/features/caseProgression/expertContentBuilder.ts
> +    .addDateArray('PAGES.UPLOAD_DOCUMENTS.DOCUMENT_ISSUE_DATE', form?.errorFor(`${errorFieldNamePrefix}[dateDay]`), form?.errorFor(`${errorFieldNamePrefix}[dateMonth]`), form?.errorFor(`${errorFieldN
> I see you changed 'PAGES.UPLOAD_DOCUMENTS.EXPERT.DATE_REPORT_WAS' to 'PAGES.UPLOAD_DOCUMENTS.DOCUMENT_ISSUE_DATE' but they are different.

Done

2023-06-26 09:43 UTC, bhagyashreesharma90 commented on src/main/services/features/caseProgression/expertContentBuilder.ts
> +    .addDateArray('PAGES.UPLOAD_DOCUMENTS.DOCUMENT_ISSUE_DATE', form?.errorFor(`${errorFieldNamePrefix}[dateDay]`), form?.errorFor(`${errorFieldNamePrefix}[dateMonth]`), form?.errorFor(`${errorFieldN
> I see you changed 'PAGES.UPLOAD_DOCUMENTS.DATE' to 'PAGES.UPLOAD_DOCUMENTS.DOCUMENT_ISSUE_DATE' but they are different.

Done

2023-06-26 09:43 UTC, bhagyashreesharma90 commented on src/main/services/features/caseProgression/witnessContentBuilder.ts
> +    .addDateArray('PAGES.UPLOAD_DOCUMENTS.DOCUMENT_ISSUE_DATE', form?.errorFor(`${errorFieldNamePrefix}[dateDay]`, witnessStatement), form?.errorFor(`${errorFieldNamePrefix}[dateMonth]`, witnessState
> I see you changed 'PAGES.UPLOAD_DOCUMENTS.WITNESS.DATE_STATEMENT' to 'PAGES.UPLOAD_DOCUMENTS.DOCUMENT_ISSUE_DATE' but they are different.

Done

2023-06-26 09:43 UTC, bhagyashreesharma90 commented on src/main/services/features/caseProgression/witnessContentBuilder.ts
> +    .addDateArray('PAGES.UPLOAD_DOCUMENTS.DOCUMENT_ISSUE_DATE', form?.errorFor(`${errorFieldNamePrefix}[dateDay]`, witnessSummary), form?.errorFor(`${errorFieldNamePrefix}[dateMonth]`, witnessSummary
> I see you changed 'PAGES.UPLOAD_DOCUMENTS.WITNESS.DATE_SUMMARY' to 'PAGES.UPLOAD_DOCUMENTS.DOCUMENT_ISSUE_DATE' but they are different.

Done

2023-06-26 09:43 UTC, bhagyashreesharma90 commented on src/main/services/features/caseProgression/witnessContentBuilder.ts
> +    .addDateArray('PAGES.UPLOAD_DOCUMENTS.DOCUMENT_ISSUE_DATE', form?.errorFor(`${errorFieldNamePrefix}[dateDay]`, noticeOfIntention), form?.errorFor(`${errorFieldNamePrefix}[dateMonth]`, noticeOfInt
> I see you changed 'PAGES.UPLOAD_DOCUMENTS.WITNESS.DATE_SUMMARY' to 'PAGES.UPLOAD_DOCUMENTS.DOCUMENT_ISSUE_DATE' but they are different.

Done

2023-06-26 13:02 UTC, hmcts-version1-ignacio approved these changes

2023-06-26 13:24 UTC, kurt-uk commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +export class DateOnlySection extends  FileOnlySection {
but none of the sections are date only? every section has at least a file (so file only would be valid) but none have date only? so should the witness section use the date then rather than extend it?

2023-06-27 13:52 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-06-28 11:59 UTC, bhagyashreesharma90 commented on src/main/common/models/caseProgression/uploadDocumentsSectionBuilder.ts
> +  addDateArray(title: string, invalidDayError: string, invalidMonthError: string, invalidYearError: string, invalidDateError: string, hint: string, category: string, field: string, dayValue: string,
> could all these not be condensed into a `errorMessage[]` rather than hard coded parameters?

Done

2023-06-28 12:39 UTC, kurt-uk submitted a review, later dismissed

2023-06-28 13:11 UTC, hmcts-version1-ignacio approved these changes

2023-07-04 10:47 UTC, kurt-uk requested changes

2023-07-04 10:47 UTC, kurt-uk commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +    @ValidateIf(o => ((o.dateDay!==undefined && o.dateMonth!==undefined && o.dateDay && o.dateMonth && o.dateYear && o.dateDay > 0 && o.dateDay < 32 && o.dateMonth > 0 && o.dateMonth < 13 && o.dateYe
can this be removed now you have created the validators for the day month and year?

2023-07-04 10:47 UTC, kurt-uk commented on src/main/common/form/validators/optionalDateDayValidator.ts
> +export class OptionalDateDayValidator implements ValidatorConstraintInterface {
why `Optional` on these? if were using a validator these arent optional, should just be `DateDayValidator` for all etc

2023-07-04 14:15 UTC, bhagyashreesharma90 commented on src/main/common/form/validators/optionalDateDayValidator.ts
> +export class OptionalDateDayValidator implements ValidatorConstraintInterface {
> why `Optional` on these? if were using a validator these arent optional, should just be `DateDayValidator` for all etc

Done

2023-07-04 14:27 UTC, bhagyashreesharma90 commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +    @ValidateIf(o => ((o.dateDay!==undefined && o.dateMonth!==undefined && o.dateDay && o.dateMonth && o.dateYear && o.dateDay > 0 && o.dateDay < 32 && o.dateMonth > 0 && o.dateMonth < 13 && o.dateYe
This is added to validate date field (which has day,month and year), So either day,month,year all fields are missing or if day, month and year all has values which is valid (o.dateDay > 0 && o.dateDay < 32 && o.dateMonth > 0 && o.dateMonth < 13 && o.dateYear > 999) whole date level validation should be shown, if not then day,month and year level validation would be displayed on screen.

2023-07-04 14:29 UTC, bhagyashreesharma90 commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +    @ValidateIf(o => ((o.dateDay!==undefined && o.dateMonth!==undefined && o.dateDay && o.dateMonth && o.dateYear && o.dateDay > 0 && o.dateDay < 32 && o.dateMonth > 0 && o.dateMonth < 13 && o.dateYe
> can this be removed now you have created the validators for the day month and year?

This is added to validate date field (which has day,month and year), So either day,month,year all fields are missing or if day, month and year all has values which is valid (o.dateDay > 0 && o.dateDay < 32 && o.dateMonth > 0 && o.dateMonth < 13 && o.dateYear > 999) whole date level validation should be shown, if not then day,month and year level validation would be displayed on screen.

2023-07-05 08:17 UTC, hmcts-version1-ignacio approved these changes

2023-07-05 08:17 UTC, LeonardoPalmeiro approved these changes

2023-07-05 08:34 UTC, kurt-uk approved these changes

2023-07-11 03:07 UTC, closed without merging