CIV-7951
hmcts/civil-citizen-ui pull request #1795
Opened 2023-06-28 09:02 UTC by m-meulendijks-v1

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-7951

### Change description ###
Added tables for uploaded documents when evidence upload becomes available.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-06-28 10:55 UTC, hmcts-version1-ignacio approved these changes

2023-06-29 15:55 UTC, maciejmodzelewski approved these changes

2023-06-29 16:03 UTC, LeonardoPalmeiro commented on src/main/routes/features/dashboard/claimSummaryController.ts
> +        evidenceUploadDocumentContent = getEvidenceUploadContent(claim);
make sure that when we remove the feature flag of case-progression we don't add any error in CUI release 1.
we can remove the feature flag in here if you don't know
![image](https://github.com/hmcts/civil-citizen-ui/assets/93268657/97bef85c-5139-4d93-a819-9913d7370035)

2023-06-29 16:04 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +  rows.sort((a: UploadDocumentTypes, b: UploadDocumentTypes) => {
please could you create a new method to sort it out to ? I believe the code gonna be more readable

2023-06-29 16:05 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +    return new Date(a.caseDocument?.createdDatetime).getTime() - new Date(b.caseDocument?.createdDatetime).getTime();
big maybe we don't need to use all the time new date, what do you thinking?

2023-06-29 16:07 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +  if('documentUpload' in document.caseDocument)
maybe we can use something like if (obj instanceof UploadEvidenceDocumentType).
what do you think?

2023-06-29 16:10 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +  return {
an option on that could be create an builder like we have LatestUpdateSectionBuilder.ts

2023-06-29 16:17 UTC, LeonardoPalmeiro commented on src/main/services/features/dashboard/claimSummaryService.ts
> +
If we add in the getEvidenceUploadDocuments return claimSummary section then we don't need all those if's.

2023-06-29 18:39 UTC, LeonardoPalmeiro requested changes
if possible increase the coverage.
![image](https://github.com/hmcts/civil-citizen-ui/assets/93268657/eef19298-9762-4e72-bcd8-1eb3acd81e25)

2023-07-02 19:40 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/uploadDocumentsType.ts
>    }
I think it makes more sense in dateUtils.ts, as that is where other date related methods are as well. formatStringDateDMY is generic enough to potentially be reused in a non-evidence upload part of code

2023-07-02 19:43 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +  rows.sort((a: UploadDocumentTypes, b: UploadDocumentTypes) => {
I have not created a new method. I believe that would cost more in time than it would add in clarity. I have added a comment that explains what the line is supposed to be doing.

2023-07-02 19:44 UTC, m-meulendijks-v1 commented on src/main/common/utils/dateUtils.ts
> +export const formatStringDateDMY= (text: string) => {
Formatted it better

2023-07-02 19:44 UTC, m-meulendijks-v1 commented on src/main/routes/features/dashboard/claimSummaryController.ts
> +      let evidenceUploadDocumentContent: ClaimSummaryContent[] = [];
Done - good point

2023-07-02 19:44 UTC, m-meulendijks-v1 commented on src/main/routes/features/dashboard/claimSummaryController.ts
> +        evidenceUploadDocumentContent = getEvidenceUploadContent(claim);
I have tested with feature flag set to false, and found a scenario in which some text showed that shouldn't show. So fixed it!

2023-07-02 19:47 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +    return new Date(a.caseDocument?.createdDatetime).getTime() - new Date(b.caseDocument?.createdDatetime).getTime();
Unfortunately, if I do not use new Date() it won't register createdDateTime as a date. If you look into pre-existing methods in the dateUtils class, you'll see they have a similar issue. Look at this pre-existing method for instance:

```
export const addDaysToDate = (date: Date, value: number) => {
  const updatedDate = new Date(date);
  updatedDate.setDate(updatedDate.getDate() + value);
  return updatedDate;
};
```
A date is put in, but it first has to be instantiated as a new Date to work. I assume it's an issue with typescript.

2023-07-02 19:47 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +  else if('witnessOptionDocument' in document.caseDocument)
Created enum

2023-07-02 19:48 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +  else if('witnessOptionDocument' in document.caseDocument)
I tried to use 'instance of' instead, but that did not work. I have to _explicitly_ declare what type it is either before or within the if statement, so within the if statement makes as much sense as anything.

2023-07-02 19:48 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +  return {
Created a builder

2023-07-02 19:48 UTC, m-meulendijks-v1 commented on src/main/services/features/dashboard/claimSummaryService.ts
> +  const tables: DocumentTab = getEvidenceUploadDocuments(claim);
Done - definitely more readable. I didn't realise Typescript would allow for that.

2023-07-02 19:49 UTC, m-meulendijks-v1 commented on src/main/services/features/dashboard/claimSummaryService.ts
> +
Good shout.

2023-07-04 08:08 UTC, LeonardoPalmeiro requested changes
please we should increase the coverage of the tests.
![image](https://github.com/hmcts/civil-citizen-ui/assets/93268657/8036f886-9ea0-4fdd-9436-608cd5cc50b2)

2023-07-04 08:08 UTC, LeonardoPalmeiro commented on src/main/routes/features/dashboard/claimSummaryController.ts
> +      else
my suggestion in here is
![image](https://github.com/hmcts/civil-citizen-ui/assets/93268657/e421cd6a-711a-4c38-88a3-ef8bb96a933a)

2023-07-04 08:16 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/uploadDocumentsTableSectionBuilder.ts
> +          text: isClaimant == true ? t('PAGES.CLAIM_SUMMARY.CLAIMANT') + header : t('PAGES.CLAIM_SUMMARY.DEFENDANT') + header,
The T function is already used on the header value in the getEvidenceUploadDocuments method before it ends up in this method, but I guess moving it is worthwhile.

2023-07-04 08:21 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +  if(TypesOfEvidenceUploadDocuments.DOCUMENT_TYPE in document.caseDocument)
I tried doing that, but it does not work, because Typescript does not know whether document.caseDocument is an instance of UploadEvidenceWitness or UploadEvidenceExpert or UploadEvidenceDocumentType.
Even if document is populated with all the fields of UploadEvidenceWitness, it does not recognise it as UploadEvidenceWitness. 

I need to call out document.Casedocument as UploadEvidenceWitness for that recognition to occur. 
This may point to a deeper problem, but it means your suggestion unfortunately does not work.

2023-07-04 15:45 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/uploadDocumentsType.ts
>    }
I've added a method like that in. Due to other changes in the method (which instantiate a date for createdDateTime so that we can use the value without having to call upon new Date() every time), it uses a Date directly.

2023-07-04 15:53 UTC, m-meulendijks-v1 commented on src/main/routes/features/dashboard/claimSummaryController.ts
> +      else
Added

2023-07-04 15:56 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/uploadDocumentsTableSectionBuilder.ts
> +          text: isClaimant == true ? t('PAGES.CLAIM_SUMMARY.CLAIMANT') + header : t('PAGES.CLAIM_SUMMARY.DEFENDANT') + header,
Moved.

2023-07-04 19:40 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-04 19:40 UTC, LeonardoPalmeiro commented on src/main/common/models/caseProgression/uploadDocumentsType.ts
>    }
perfect :)

2023-07-05 09:31 UTC, hmcts-version1-ignacio approved these changes

2023-07-10 15:07 UTC, kurt-uk approved these changes

2023-07-10 15:19 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-13 11:52 UTC, hmcts-version1-ignacio approved these changes

2023-07-13 12:36 UTC, merged

2023-07-13 12:37 UTC, laperla11 commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +  //TODO: href will need to be added - dependent on document download API implementation.
when is the href added here?