CIV-8019 Cancel document upload - Yes functionality
hmcts/civil-citizen-ui pull request #1807
Opened 2023-06-29 15:03 UTC by maciejmodzelewski

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-8019

### Change description ###
Cancel document upload logic added for "Yes" option selected.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-06-29 16:30 UTC, LeonardoPalmeiro requested changes

2023-06-30 08:27 UTC, maciejmodzelewski commented on src/main/services/features/caseProgression/cancelDocumentUpload.ts
> +  for (const uploadDocumentValue of Object.values(uploadDocuments)) {
@LeonardoPalmeiro, I don't know. It all depends how this system works. Also, why focusing on defendantUploadDocuments specifically? Just because at the moment we deal only with the defendant? But wouldn't it be better to make the code as universal as it is possible, so to minimise the number of changes required in the future when we will finally deal with the claimant?

2023-06-30 09:22 UTC, kurt-uk requested changes

2023-06-30 09:22 UTC, kurt-uk commented on src/main/routes/features/caseProgression/cancelYourUploadController.ts
> +    } else if(form.model.option === YesNo.YES) {
this is the same as the else that was already created and had the 8019 marker in it

2023-06-30 09:22 UTC, kurt-uk commented on src/main/routes/features/caseProgression/cancelYourUploadController.ts
> +      const claim: Claim = await getCaseDataFromStore(req.params.id);
use `claimId`

2023-06-30 09:22 UTC, kurt-uk commented on src/main/routes/features/caseProgression/cancelYourUploadController.ts
> +      res.redirect(constructResponseUrlWithIdParams(req.params.id, DEFENDANT_SUMMARY_URL));
use `claimId`

2023-06-30 09:22 UTC, kurt-uk commented on src/main/routes/features/caseProgression/cancelYourUploadController.ts
> +      const claimantOrDefendant: ClaimantOrDefendant = ClaimantOrDefendant.DEFENDANT;
why do we need this? were clearing the cache of saved docs

2023-06-30 09:22 UTC, kurt-uk commented on src/main/services/features/caseProgression/cancelDocumentUpload.ts
> +  await saveDraftClaim(claimId, claim);
why are you calling save draft claim? where are you removing the redis cache?

2023-06-30 09:45 UTC, maciejmodzelewski commented on src/main/routes/features/caseProgression/cancelYourUploadController.ts
> +      const claimantOrDefendant: ClaimantOrDefendant = ClaimantOrDefendant.DEFENDANT;
The scenario 1 in the acceptance criteria says:
GIVEN citizen is on "Cancel document upload" page
WHEN  'Yes' option is selected 
AND 'Submit' button is clicked
THEN Remove any documents stored
AND clear from Redis
AND Clear previously selected check boxes

If I understand this correctly, removal of stored documents refers to the documents that are in data-store with ttl and that data-store will take care of removing them if they are not attached to a case. The clearing from Redis happens when the UploadDocumentTypes in claim.caseProgression are removed and the saveDraftClaim method is called, but removing UploadDocumentTypes will also clear previously selected check boxes. That's what I've been told.

2023-06-30 09:47 UTC, maciejmodzelewski commented on src/main/services/features/caseProgression/cancelDocumentUpload.ts
> +  await saveDraftClaim(claimId, claim);
I've been told that to clear documents from Redis I have to remove the UploadDocumentTypes from claim.caseProgression and call the saveDraftClaim method.

2023-07-04 09:06 UTC, LeonardoPalmeiro reviewed
very good!!
100% of coverage.

2023-07-04 09:06 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/cancelDocumentUpload.ts
> +  await getClaimById(claimId, req);
We can remove the await getClaimById(claimId, req); line since it is not necessary. When we access the DEFENDANT_SUMMARY_URL, it will handle the processing.

2023-07-04 09:10 UTC, maciejmodzelewski commented on src/main/services/features/caseProgression/cancelDocumentUpload.ts
> +  await getClaimById(claimId, req);
@LeonardoPalmeiro the await getClaimById(claimId, req); is important. Without that everything crashes. Once the claim is removed from Redis, it is not reinstated there and the page with tick boxes no longer shows any content
![image](https://github.com/hmcts/civil-citizen-ui/assets/18092228/5b5cfed0-60a6-44e1-a811-2acb5b5a878c)

2023-07-04 19:41 UTC, LeonardoPalmeiro approved these changes

2023-07-05 08:38 UTC, LeonardoPalmeiro approved these changes

2023-07-11 16:04 UTC, merged