CIV-9482 corrected cancel page and expert name label
hmcts/civil-citizen-ui pull request #1809
Opened 2023-06-30 08:46 UTC by bhagyashreesharma90

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9482

### Change description ###
Update cancel page to show radio button inline
Corrected experts' names to expert's names
![image](https://github.com/hmcts/civil-citizen-ui/assets/114094319/47fc1c29-b1d7-4a57-babf-aed83393adad)
![image](https://github.com/hmcts/civil-citizen-ui/assets/114094319/77114c8d-7c94-4423-a1c5-88a911dc21ad)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-06-30 13:27 UTC, LeonardoPalmeiro requested changes

2023-06-30 13:27 UTC, LeonardoPalmeiro commented on src/main/views/features/caseProgression/cancel-your-upload.njk
> +            {{ yesNoRadioButton(t, 'option', 'option', '', form, '', {yesHtml: yesHtml, yes: 'COMMON.VARIATION_3.YES', no: 'COMMON.VARIATION_3.NO', classes: 'govuk-radios--inline'}) }}
why do we need this?

2023-06-30 13:27 UTC, LeonardoPalmeiro commented on src/main/modules/i18n/locales/en.json
> +      "CCJ_WHEN_DO_YOU_WANT_TO_BE_PAID_BY": "When you want the defendant to pay?",
why do we have changes in this part?

2023-06-30 13:39 UTC, bhagyashreesharma90 commented on src/main/views/features/caseProgression/cancel-your-upload.njk
> +            {{ yesNoRadioButton(t, 'option', 'option', '', form, '', {yesHtml: yesHtml, yes: 'COMMON.VARIATION_3.YES', no: 'COMMON.VARIATION_3.NO', classes: 'govuk-radios--inline'}) }}
This we need to make both Yes and No radio button in one line.

2023-06-30 13:52 UTC, bhagyashreesharma90 commented on src/main/modules/i18n/locales/en.json
> +      "CCJ_WHEN_DO_YOU_WANT_TO_BE_PAID_BY": "When you want the defendant to pay?",
> why do we have changes in this part?

reverted this. this spaces were removed automatically when I saved file from IDE.

2023-07-03 08:24 UTC, LeonardoPalmeiro approved these changes
LGTM

2023-07-03 08:25 UTC, LeonardoPalmeiro commented on src/main/modules/i18n/locales/en.json
> +      "CCJ_WHEN_DO_YOU_WANT_TO_BE_PAID_BY": "When you want the defendant to pay?",
Cool, thanks

2023-07-03 14:59 UTC, bhagyashreesharma90 commented
Expert's name changes need to be reverted as per latest update on the ticket. https://tools.hmcts.net/jira/browse/CIV-9482

2023-07-04 07:13 UTC, LeonardoPalmeiro approved these changes

2023-07-04 10:37 UTC, kurt-uk approved these changes

2023-07-04 18:10 UTC, merged