CIV-7954 - Adding update to dashboard if new evidence uploaded
hmcts/civil-citizen-ui pull request #1838
Opened 2023-07-05 14:56 UTC by m-meulendijks-v1

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-7954

### Change description ###
Adding update to dashboard if new evidence uploaded

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-06 07:54 UTC, LeonardoPalmeiro requested changes

2023-07-06 07:54 UTC, LeonardoPalmeiro commented on src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
> +  if(checkEvidenceUploaded(claim, false)){
checkEvidenceUploaded(claim, false) is always false in this case, is that correct?

2023-07-06 07:54 UTC, LeonardoPalmeiro commented on src/main/common/utils/dateUtils.ts
> +export const checkEvidenceUploadTime = (date: Date) => {
please, add the return of the method .

2023-07-06 07:54 UTC, LeonardoPalmeiro commented on src/main/common/utils/dateUtils.ts
> +  today.setHours(18, 0, 0, 0);
please, transform 18 into a constant I saw that we're using 18 in another points into the same method.

2023-07-06 07:54 UTC, LeonardoPalmeiro commented on src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
> +export const checkEvidenceUploaded = (claim: Claim, isClaimant: boolean): boolean => {
please, could you add unit test in this part?
Sonar Said.
![image](https://github.com/hmcts/civil-citizen-ui/assets/93268657/f0d0b3fc-6dcd-4808-81f8-96ed99598a24)

2023-07-06 07:58 UTC, m-meulendijks-v1 commented on src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
> +  if(checkEvidenceUploaded(claim, false)){
Yes, because it is not yet possible to log in as the claimant, so I've hardcoded it to defendant for now.
But once we can distinguish between the two we can change this method.

2023-07-06 08:15 UTC, m-meulendijks-v1 commented on src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
> +export const checkEvidenceUploaded = (claim: Claim, isClaimant: boolean): boolean => {
Added tests.

2023-07-06 08:15 UTC, m-meulendijks-v1 commented on src/main/common/utils/dateUtils.ts
> +export const checkEvidenceUploadTime = (date: Date) => {
Added return as boolean

2023-07-06 08:16 UTC, m-meulendijks-v1 commented on src/main/common/utils/dateUtils.ts
> +  today.setHours(18, 0, 0, 0);
Added constant endOfDay = 18

2023-07-06 09:54 UTC, LeonardoPalmeiro commented on src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
> +  if(checkEvidenceUploaded(claim, false)){
may we can add a TODO and create a task do not forget this.

2023-07-06 11:54 UTC, LeonardoPalmeiro commented on src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
> +export const checkEvidenceUploaded = (claim: Claim, isClaimant: boolean): boolean => {
yeah I saw in intellij has 100% of coverage.
I don't think you should invest time in this.

2023-07-06 12:44 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-07 12:12 UTC, hmcts-version1-ignacio approved these changes

2023-07-10 15:43 UTC, kurt-uk commented on src/main/routes/urls.ts
> +export const DEFENDANT_DOCUMENTS_URL = `${DASHBOARD_URL}/:id/defendant#documents`;
```suggestion
export const DEFENDANT_DOCUMENTS_URL = `${DEFENDANT_SUMMARY_URL}#documents`;
```

2023-07-18 08:37 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-18 13:56 UTC, LeonardoPalmeiro approved these changes

2023-07-18 13:58 UTC, bhagyashreesharma90 approved these changes

2023-07-18 13:58 UTC, kurt-uk approved these changes

2023-07-18 14:03 UTC, hmcts-version1-ignacio approved these changes

2023-07-18 15:58 UTC, merged