CIV-7160 Defendant Latest Update Screens
hmcts/civil-citizen-ui pull request #1844
Opened 2023-07-06 13:58 UTC by jeswanth-hmcts

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-7160

### Change description ###

Defendant Latest Update Screens

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-07-06 15:40 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-06 15:51 UTC, hmcts-version1-domini commented on src/main/modules/i18n/locales/en.json
> +      "CLAIM_SETTLED": "This claim is settled.",
We should always consider alphabetical order in this file.

2023-07-06 16:14 UTC, jeswanth-hmcts commented on src/main/modules/i18n/locales/en.json
> +      "CLAIM_SETTLED": "This claim is settled.",
sorted in alphabetical order

2023-07-06 16:20 UTC, kenneth-hmcts approved these changes

2023-07-06 16:33 UTC, hmcts-version1-domini approved these changes

2023-07-06 16:50 UTC, laperla11 requested changes

2023-07-06 16:50 UTC, laperla11 commented on src/main/common/models/claim.ts
> +      if (this?.applicant1PartAdmitConfirmAmountPaidSpec === 'Yes' && this?.applicant1PartAdmitIntentionToSettleClaimSpec === 'Yes') {
better use `YesNo.YES` and `YesNo.NO`

2023-07-06 16:50 UTC, laperla11 commented on src/main/common/models/claim.ts
> +  hasApplicant1DeadlinePassed(): boolean {
you can use this `isPastDeadline` from dateUtils

2023-07-06 17:02 UTC, jeswanth-hmcts commented on src/main/common/models/claim.ts
> +      if (this?.applicant1PartAdmitConfirmAmountPaidSpec === 'Yes' && this?.applicant1PartAdmitIntentionToSettleClaimSpec === 'Yes') {
used enums as mentioned

2023-07-07 08:28 UTC, laperla11 commented on src/main/common/models/claim.ts
> +  hasApplicant1DeadlinePassed(): boolean {
can you check with Simon, as far as I know deadline is passed if the time is after 4pm on the deadline day

2023-07-07 08:32 UTC, laperla11 approved these changes

2023-07-07 08:40 UTC, hmcts-version1-domini approved these changes

2023-07-07 08:46 UTC, LeonardoPalmeiro approved these changes

2023-07-11 14:32 UTC, merged