CIV-8968 Upload document to docstore on file upload (no JS)
hmcts/civil-citizen-ui pull request #1866
Opened 2023-07-10 15:00 UTC by jakiurmalik

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-8968

### Change description ###
Upload document to docstore on file upload (no JS)
![civ-8968](https://github.com/hmcts/civil-citizen-ui/assets/79106600/c98578fa-35fd-4b88-905f-5817b84ead23)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2023-08-23 14:28 UTC, hmcts-version1-ignacio commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +  //@Type(() => FileUpload)
Should this comment be removed?

2023-08-23 14:33 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-08-23 15:02 UTC, maciejmodzelewski requested changes
I ran the system in my local environment and most of the validation works but the following fields are not validated
![image](https://github.com/hmcts/civil-citizen-ui/assets/18092228/617bbe14-f247-4e5f-9e8b-ef78a31ed63f)

![image](https://github.com/hmcts/civil-citizen-ui/assets/18092228/0808f9b8-a2be-45e3-85b0-93431e38da57)

2023-08-24 07:52 UTC, LeonardoPalmeiro commented on src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
> +  //@Type(() => FileUpload)
thanks!!!

2023-08-25 07:50 UTC, hmcts-version1-ignacio approved these changes

2023-08-25 08:37 UTC, kurt-uk approved these changes

2023-08-31 14:11 UTC, maciejmodzelewski submitted a review, later dismissed

2023-08-31 14:15 UTC, kurt-uk submitted a review, later dismissed

2023-08-31 14:53 UTC, sabahirfan approved these changes

2023-10-09 11:00 UTC, maciejmodzelewski submitted a review, later dismissed

2023-10-09 12:14 UTC, miguelMolina3691 approved these changes

2023-10-19 08:54 UTC, closed without merging