CIV-9126 Trial Arrangements - Defendant LiP - Finalise your Trial or Hearing Arrangements - Is the case ready for trial?
hmcts/civil-citizen-ui pull request #1868
Opened 2023-07-11 07:07 UTC by hmcts-version1-ignacio

### [CIV-9126](https://tools.hmcts.net/jira/browse/CIV-9126) ###

### The scope of this ticket is to develop the 'Finalise your trial or hearing arrangements: “Is the case ready for trial” page that appears when the 'Finalise your trial or hearing arrangements' CTA button 'Start now' is clicked. Defendant can select Yes/No to the Question - "Is the case ready for trial or hearing" to continue to the next page/screen. ###

<screenshot here>

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-07-12 13:40 UTC, LeonardoPalmeiro approved these changes

2023-07-12 16:05 UTC, maciejmodzelewski requested changes
![image](https://github.com/hmcts/civil-citizen-ui/assets/18092228/742b9763-17b7-4e46-a90f-30aec58a3d58)
There is an odd input field in the Latest update tab

2023-07-13 11:33 UTC, LeonardoPalmeiro approved these changes

2023-07-13 12:18 UTC, maciejmodzelewski submitted a review, later dismissed

2023-07-14 09:59 UTC, LeonardoPalmeiro approved these changes

2023-07-14 10:19 UTC, bhagyashreesharma90 approved these changes

2023-07-19 07:58 UTC, closed without merging