CIV-9239 Trial Arrangements: Defendant LiP - Confirmation Screen - Case not ready for Trial
hmcts/civil-citizen-ui pull request #1879
Opened 2023-07-12 13:52 UTC by maciejmodzelewski

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9239

### Change description ###
A new screen created for Trial Arrangements to confirm that a case is no ready for trial or hearing

![image](https://github.com/hmcts/civil-citizen-ui/assets/18092228/e9dc7dc4-cf01-4def-b586-81b2fce0d01c)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-12 15:39 UTC, LeonardoPalmeiro approved these changes

2023-07-12 15:53 UTC, kurt-uk submitted a review, later dismissed

2023-07-14 13:25 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-07-14 13:30 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-28 15:23 UTC, kurt-uk requested changes
theres a few test files missing too based on the amount of src youve pushed, eg routes

2023-07-28 15:23 UTC, kurt-uk commented on src/main/common/models/caseProgression/caseProgression.ts
> +  isCaseReadyTrialOrHearing?: IsCaseReadyForm;
can we avoid this based on the team discussion we had on keeping consitency, so creating defendantTrial and claimant

2023-07-28 15:23 UTC, kurt-uk commented on src/main/routes/features/caseProgression/trialArrangementsConfirmationController.ts
> +      const readyForTrialOrHearing:boolean = claim.caseProgression.isCaseReadyTrialOrHearing.option === YesNo.YES;      const trialArrangementsConfirmationContent = getTrialArrangementsConfirmationCo
not sure if github is glitching but is this all on 1 line? if so can we split appropiately

2023-07-28 15:23 UTC, kurt-uk commented on src/main/services/features/caseProgression/trialArrangements/trialArrangementsConfirmationContent.ts
> +}
should this use the builders?

2023-07-31 07:44 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/trialArrangements/trialArrangementsConfirmationContent.ts
> +}
yes..
but I didn't develop this part initially.
because of that I didn't change.

2023-07-31 08:02 UTC, LeonardoPalmeiro commented on src/main/common/models/caseProgression/caseProgression.ts
> +  isCaseReadyTrialOrHearing?: IsCaseReadyForm;
yes definitely we should to avoid this.
but this https://tools.hmcts.net/jira/browse/CIV-9126 added in this way I'm just reused in the same way.
I believe the best option is create a new task to refactor in the best way.
what do you think ?

2023-07-31 08:05 UTC, LeonardoPalmeiro commented on src/main/routes/features/caseProgression/trialArrangementsConfirmationController.ts
> +      const readyForTrialOrHearing:boolean = claim.caseProgression.isCaseReadyTrialOrHearing.option === YesNo.YES;      const trialArrangementsConfirmationContent = getTrialArrangementsConfirmationCo
in the code is correct.

![image](https://github.com/hmcts/civil-citizen-ui/assets/93268657/3f69f11d-e5ec-47a9-b7f9-09f39e0db2fc)

2023-07-31 11:04 UTC, kurt-uk commented on src/main/common/models/caseProgression/caseProgression.ts
> +  isCaseReadyTrialOrHearing?: IsCaseReadyForm;
I think we should clean up as we go if possible, would be less work to change now rather than when we have a few stories built like this

2023-08-01 10:21 UTC, closed without merging

2023-08-01 10:21 UTC, LeonardoPalmeiro commented
we will use just one PR https://github.com/hmcts/civil-citizen-ui/pull/1881