CIV-9204 Trial Arrangements: Defendant LiP - Confirmation screen - Case ready for Trial
hmcts/civil-citizen-ui pull request #1881
Opened 2023-07-12 14:55 UTC by maciejmodzelewski

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9204

### Change description ###
A new screen created for Trial Arrangements to confirm that a case is ready for trial or hearing

![image](https://github.com/hmcts/civil-citizen-ui/assets/18092228/dde5dde9-6bc1-470a-8e6f-6a7f9c8b8b96)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-12 15:39 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-12 15:53 UTC, kurt-uk submitted a review, later dismissed

2023-07-13 08:25 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-07-14 13:26 UTC, hmcts-version1-ignacio approved these changes

2023-07-14 13:29 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-28 08:10 UTC, bhagyashreesharma90 submitted a review, later dismissed

2023-08-01 11:02 UTC, kurt-uk requested changes

2023-08-01 14:34 UTC, LeonardoPalmeiro commented on src/main/common/models/caseProgression/caseProgression.ts
> +  isCaseReadyTrialOrHearing?: IsCaseReadyForm;
definitely I can do it but in another task because is out of scope of this task. for this specific task I reuse the variable that has been create in the previous screen.

2023-08-02 13:51 UTC, kurt-uk requested changes

2023-08-10 14:45 UTC, LeonardoPalmeiro commented on src/main/common/models/caseProgression/caseProgression.ts
> +  isCaseReadyTrialOrHearing?: IsCaseReadyForm;
has been removed by [CIV-7748](https://tools.hmcts.net/jira/browse/CIV-7748)

2023-08-10 14:45 UTC, LeonardoPalmeiro commented on src/main/common/models/caseProgression/caseProgression.ts
> +  isCaseReadyTrialOrHearing?: IsCaseReadyForm;
has been removed by [CIV-7748](https://tools.hmcts.net/jira/browse/CIV-7748)

2023-08-11 08:10 UTC, m-meulendijks-v1 approved these changes

2023-08-15 09:48 UTC, kurt-uk approved these changes

2023-08-15 10:52 UTC, m-meulendijks-v1 approved these changes

2023-08-15 11:15 UTC, merged