Feature/civ 1125 postcode finder
hmcts/civil-citizen-ui pull request #189
Opened 2022-03-02 23:05 UTC by RosDiaf

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-03-03 08:58 UTC, TatsyMaslova requested changes

2022-03-03 08:58 UTC, TatsyMaslova commented on src/main/common/form/models/form.ts
> +  public getTextError(errors: ValidationError[], property: string) {
not very sure what this method does. looking at the code it seems it checks whether the property has errors - so returns a boolean. but the method signature says it gets text error - so by method signature you would assume it returns a text for the error

2022-03-03 09:24 UTC, laarmada requested changes
very good work!

2022-03-03 09:24 UTC, laarmada commented on src/main/common/form/validationErrors/errorMessageConstants.ts
> +export const NON_ADDRESS_VALUE_NOT_ALLOWED = 'Enter first address line';
so length const name "NON_ADDRESS_VALUE_NOT_ALLOWED" I will change something like: VALID_ADDRESS_LINE... also for the others: VALID_CITY.
NON and NOT_ALLOWED is confusing but is my opinion :)

2022-03-03 09:24 UTC, laarmada commented on src/main/common/models/correspondenceAddress.ts
> +  County: string;
lower case? in each vble?

2022-03-03 09:24 UTC, laarmada commented on src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
> +const { Logger } = require('@hmcts/nodejs-logging');
we are using logger? great news!

2022-03-03 09:24 UTC, laarmada commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +      try {
amazing using try/catch...

2022-03-03 09:55 UTC, sampankumar commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +          JSON.parse(data).primaryAddressLine1,
We are doing a lot of JSON.parse(data).
Can we parse the data once and then use it later? May be saving it in a const?

2022-03-03 12:17 UTC, RosDiaf commented on src/main/common/form/models/citizenCorrespondenceAddress.ts
> +    correspondenceAddressLine1?: string;
Yes, we have the same space on citizenTelephoneNumber.ts and citizenDob.ts. 

If I remove it Lint will show an error saying 'Expected indentation of 4 spaces but found 2  indent'

2022-03-03 12:31 UTC, RosDiaf commented on src/main/common/form/models/form.ts
> +  public getTextError(errors: ValidationError[], property: string) {
Yes, it filters through the ValidationError[] by the property (form field id) and returns the object where the error text is for that particular form field. Then I just extract and return the text for the error.

2022-03-03 12:50 UTC, RosDiaf commented on src/main/common/form/validationErrors/errorMessageConstants.ts
> +export const NON_ADDRESS_VALUE_NOT_ALLOWED = 'Enter first address line';
All updated

2022-03-03 13:01 UTC, RosDiaf commented on src/main/common/models/correspondenceAddress.ts
> +  County: string;
Changed to lowercase both primary and correspondence models

2022-03-03 13:18 UTC, TatsyMaslova commented on src/main/common/form/models/form.ts
> +  public getTextError(errors: ValidationError[], property: string) {
sorry for more questions - so isNotEmpty returns a boolean isn't it so the errors then contain only those that has the propery. why o we then return error? Just ambiguous that it does not actually return a text for the error i think. I would rename it propertyHasErrors or something.. in addition did you add a test for this. i didn't see

2022-03-03 13:44 UTC, RosDiaf commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +          JSON.parse(data).primaryAddressLine1,
Done

2022-03-04 08:21 UTC, TatsyMaslova commented on src/main/common/form/models/citizenCorrespondenceAddress.ts
> +    correspondenceAddressLine1?: string;
Great thank you Rosario!!

2022-03-04 15:24 UTC, RosDiaf commented on src/main/common/form/models/form.ts
> +  public getTextError(errors: ValidationError[], property: string) {
Test added

2022-03-07 09:05 UTC, TatsyMaslova commented on sonar-project.properties
> +sonar.exclusions=src/main/app.ts,src/main/development.ts,src/main/index.js,src/main/server.ts,src/main/assets/js/postcode-lookup.js
would it mean that we could potentially introduce code smells by excluding post-code.js from sonar?

2022-03-07 11:34 UTC, mounikahmcts commented on config/custom-environment-variables.yaml
> +  cmc:
secrets cannot be commited like this. Please add them to vaults

2022-03-07 14:40 UTC, RosDiaf commented on config/custom-environment-variables.yaml
> +  cmc:
Changes added

2022-03-07 15:02 UTC, taomoh commented on config/custom-environment-variables.yaml
> +     ordnanceSurveyApiKey: ORDNANCE_SURVEY_API_KEY
Is this needed?

2022-03-07 15:14 UTC, taomoh commented on src/main/modules/properties-volume/index.ts
> +      this.setSecret('secrets.civil.ordnance-survey-api-key', 'services.civil.ordnanceSurveyApiKey');
I suggest you rename `services.civil.ordnanceSurveyApiKey` to `services.postecodeLookup.ordnanceSurveyApiKey` , as this is service doesn't fit under civil: it's an external one

2022-03-08 09:21 UTC, taomoh commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +        console.log(e);
use logger instead of console

2022-03-08 09:23 UTC, taomoh commented on src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
> +const logger = Logger.getLogger('postcode-lookup');
Should be named after the class: postcodeLookupController

2022-03-08 09:23 UTC, taomoh commented on src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
> +          console.log('Ordnance Survey keys stopped working', { error: err });
use logger instead of console

2022-03-08 19:34 UTC, RosDiaf commented on src/main/app/client/civilServiceClient.ts
> +      console.log(err);
Added

2022-03-08 19:34 UTC, RosDiaf commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +        console.log(e);
Added

2022-03-08 19:34 UTC, RosDiaf commented on src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
> +          console.log('Ordnance Survey keys stopped working', { error: err });
Added

2022-03-08 20:56 UTC, RosDiaf commented on src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
> +const logger = Logger.getLogger('postcode-lookup');
changed to postcodeLookupController

2022-03-10 10:02 UTC, RosDiaf commented on src/main/modules/properties-volume/index.ts
> +      this.setSecret('secrets.civil.ordnance-survey-api-key', 'services.civil.ordnanceSurveyApiKey');
Renamed to: services.postcodeLookup.ordnanceSurveyApiKey

2022-03-11 10:27 UTC, TatsyMaslova approved these changes

2022-03-11 10:51 UTC, laarmada commented on sonar-project.properties
> +sonar.exclusions=src/main/app.ts,src/main/development.ts,src/main/index.js,src/main/server.ts,src/main/assets/js/postcode-lookup.js
we should create a ticket about that... Which ones are the guidelines?

2022-03-11 10:57 UTC, LeonardoPalmeiro approved these changes

2022-03-11 11:21 UTC, mounikahmcts commented on config/default.yaml
> +    ordnanceSurveyApiKey: GUxlyepby9OASq8fqSg9rLxuTyMzMQqT
@LeonardoPalmeiro Please remove secrets from default.yml

2022-03-11 11:23 UTC, laarmada requested changes
we can discuss about json test files

2022-03-11 11:23 UTC, laarmada commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +      addressLine1Error: errorList.getTextError(citizenAddress.getErrors(), 'primaryAddressLine1'),
we should to add a new constantClaimData? to include that all names?

2022-03-11 11:23 UTC, laarmada commented on src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
> +          message: 'Postcode not provided',
in error constant file?

2022-03-11 11:23 UTC, laarmada commented on src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
> +          throw new Error('Invalid post code');
in error constant file?

2022-03-11 11:23 UTC, laarmada commented on src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
> +        if (err.message === 'Authentication failed') {
in error constant file?

2022-03-11 11:23 UTC, laarmada commented on src/test/unit/common/form/models/form.test.ts
> +const _errors = [
I think we can create an external json and do something like that:
const errorMock = require('./errorMock .json');
.... xxxx= JSON.stringify(civilClaimResponseMock);
const errorsMock = [ xxxx]

2022-03-11 11:23 UTC, laarmada commented on src/test/unit/common/form/models/form.test.ts
> +    CitizenAddress: {
the same of previous comment

2022-03-11 11:23 UTC, laarmada commented on src/test/unit/common/form/models/form.test.ts
> +const _correspondenceAddressErrors = [
also..... we can discuss about that

2022-03-11 11:23 UTC, laarmada commented on src/test/unit/common/form/models/form.test.ts
> +    const textError = form.getTextError(_errors, 'primaryAddressLine1');
const message

2022-03-11 11:23 UTC, laarmada commented on src/test/unit/common/form/models/form.test.ts
> +    const textError = form.getTextError(_correspondenceAddressErrors, 'correspondencePostCode');
const message

2022-03-11 11:23 UTC, laarmada commented on src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
> +    const mockDraftStore = {
you can create the const (const mockDraftStore = ) on the top and reuse it to avoid Lint warning....

2022-03-11 11:23 UTC, laarmada commented on src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
> +        primaryAddressLine1: '',
could we create a JSON and Mock it in the redis? or we can figure out how avoid so much string data directly in the test... we will have similar text in the next screens....

2022-03-11 11:23 UTC, laarmada commented on src/test/unit/routes/features/response/citizenDetails/postcodeLookupController.test.ts
> +const mockPostcodeLookupResponse = {
sholud have in a Json file?

2022-03-11 11:23 UTC, laarmada commented on src/test/utils/mockClaim.ts
> +const respondent1: Respondent = {
same here of previous comment external json file.

2022-03-11 11:27 UTC, LeonardoPalmeiro commented on config/default.yaml
> +    ordnanceSurveyApiKey: GUxlyepby9OASq8fqSg9rLxuTyMzMQqT
ok I removed

2022-03-11 11:28 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +      res.redirect('/case/1643033241924739/response/your-dob');
it's fixed

2022-03-11 11:28 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +        console.log(e);
done

2022-03-11 11:33 UTC, LeonardoPalmeiro approved these changes

2022-03-11 11:33 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +
I removed

2022-03-11 11:34 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +      addressLine1Error: errorList.getTextError(citizenAddress.getErrors(), 'primaryAddressLine1'),
I agree with you.
https://tools.hmcts.net/jira/browse/CIV-1552

2022-03-11 11:34 UTC, LeonardoPalmeiro commented on infrastructure/main.tf
> +  key_vault_id = "${data.azurerm_key_vault.cmc_key_vault.id}"
done.

2022-03-11 11:36 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
> +          throw new Error('Invalid post code');
https://tools.hmcts.net/jira/browse/CIV-1553

2022-03-11 11:36 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
> +        if (err.message === 'Authentication failed') {
https://tools.hmcts.net/jira/browse/CIV-1553

2022-03-11 11:41 UTC, LeonardoPalmeiro commented on src/test/unit/common/form/models/form.test.ts
> +const _errors = [
https://tools.hmcts.net/jira/browse/CIV-1554

2022-03-11 11:41 UTC, LeonardoPalmeiro commented on src/test/unit/common/form/models/form.test.ts
> +const _correspondenceAddressErrors = [
https://tools.hmcts.net/jira/browse/CIV-1554

2022-03-11 11:41 UTC, LeonardoPalmeiro commented on src/test/unit/common/form/models/form.test.ts
> +    const textError = form.getTextError(_errors, 'primaryAddressLine1');
I've create a new task to do that.

2022-03-11 11:42 UTC, LeonardoPalmeiro commented on src/test/unit/common/form/models/form.test.ts
> +    const textError = form.getTextError(_correspondenceAddressErrors, 'correspondencePostCode');
I've created a new task to do that.

2022-03-11 11:46 UTC, LeonardoPalmeiro commented on src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
> +    const mockDraftStore = {
in this case it's specific for this test.

2022-03-11 11:49 UTC, LeonardoPalmeiro commented on src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
> +        primaryAddressLine1: '',
I've created a new task to do this in the correct way.

2022-03-11 11:51 UTC, laarmada commented on src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
> +    const mockDraftStore = {
I want to say... you have the same constant repeated in several test.... you can avoid that creating only one on the top and reusing it

2022-03-11 11:52 UTC, laarmada commented on src/test/unit/common/form/models/form.test.ts
> +    const textError = form.getTextError(_correspondenceAddressErrors, 'correspondencePostCode');
ok great

2022-03-11 11:55 UTC, LeonardoPalmeiro commented on src/test/unit/routes/features/response/citizenDetails/postcodeLookupController.test.ts
> +const mockPostcodeLookupResponse = {
then all mocks should be in .json. 
we could discuss with the team

2022-03-11 11:57 UTC, LeonardoPalmeiro commented on src/test/utils/mockClaim.ts
> +const respondent1: Respondent = {
let's make a meeting.

2022-03-11 12:00 UTC, laarmada commented on src/test/unit/routes/features/response/citizenDetails/postcodeLookupController.test.ts
> +const mockPostcodeLookupResponse = {
yes an if it necessary create a ticket to do that also....

2022-03-11 12:42 UTC, laarmada approved these changes
ok

2022-03-11 13:45 UTC, merged