CIV-9613 Trial Arrangements - CTA “Finalise your Trial or Hearing Arrangements” - Latest Updates Screen
hmcts/civil-citizen-ui pull request #1891
Opened 2023-07-14 14:43 UTC by maciejmodzelewski

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9613

### Change description ###
A new tail created with information on the due date of finalising the trial or hearing arrangements and a button that redirects to the “start now” screen to start the process of finalising my trial arrangements (IMPORTANT - the button will not work until CIV-9124 is merged into master)

![image](https://github.com/hmcts/civil-citizen-ui/assets/18092228/de4c88a3-8e1b-4813-bd0c-cc353d58fcf3)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-14 14:58 UTC, LeonardoPalmeiro commented on src/main/common/models/claim.ts
> +  get finalisingTrialArrangementsDeadline(): string {
basically we're reusing 
the same code of
  get bundleStitchingDeadline(): string {
    const hearingDateTime = new Date(this.caseProgressionHearing.hearingDate).getTime();
    const threeWeeksMilli = 21 * 24 * 60 * 60 * 1000;
    const options: DateTimeFormatOptions = { day: 'numeric', month: 'long', year: 'numeric' };
    return new Date(hearingDateTime - threeWeeksMilli).toLocaleDateString('en-GB', options);
  }
  
can we reuse the same method?

2023-07-14 14:58 UTC, LeonardoPalmeiro commented on src/main/routes/urls.ts
> +
please remove this blank space.

2023-07-14 15:05 UTC, kurt-uk commented on src/main/common/models/claim.ts
> +  get finalisingTrialArrangementsDeadline(): string {
can we also then rename it to what it represents rather to what its used for if were putting in multiple places? something more along the lines of `threeWeeksBeforeHearing()`

2023-07-14 15:21 UTC, LeonardoPalmeiro commented on src/main/common/models/claim.ts
> +  get finalisingTrialArrangementsDeadline(): string {
My suggestion in here is create another ticket(technical) for refactor this part.

2023-07-14 15:25 UTC, maciejmodzelewski commented on src/main/common/models/claim.ts
> +  get finalisingTrialArrangementsDeadline(): string {
@kurt-uk it's done.

2023-07-17 08:03 UTC, LeonardoPalmeiro approved these changes

2023-07-17 08:38 UTC, miguelMolina3691 approved these changes

2023-07-17 08:52 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-07-17 08:57 UTC, kurt-uk requested changes

2023-07-17 08:57 UTC, kurt-uk commented on src/main/common/utils/pageSectionBuilder.ts
there is a test file for this file, that would be good to add this method to

2023-07-17 08:57 UTC, kurt-uk commented on src/main/common/models/claim.ts
There are tests for this file, you have logic in here that youve added for the finalising trial arrangements

2023-07-17 10:03 UTC, maciejmodzelewski commented on src/main/common/utils/pageSectionBuilder.ts
Tests added

2023-07-17 10:03 UTC, maciejmodzelewski commented on src/main/common/models/claim.ts
Tests added

2023-07-17 10:34 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-17 10:48 UTC, kurt-uk submitted a review, later dismissed

2023-07-17 10:55 UTC, hmcts-version1-ignacio approved these changes

2023-07-17 11:09 UTC, LeonardoPalmeiro approved these changes

2023-07-17 12:40 UTC, kurt-uk approved these changes

2023-07-18 07:49 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-19 10:37 UTC, hmcts-version1-ignacio commented on src/main/modules/i18n/locales/en.json
> +          "DUE_BY": "Due by: Midnight, {{ finalisingTrialArrangementsDeadline }}",
This line is different in the other translation file.

2023-07-19 10:52 UTC, maciejmodzelewski commented on src/main/modules/i18n/locales/en.json
> +          "DUE_BY": "Due by: Midnight, {{ finalisingTrialArrangementsDeadline }}",
You are right. Good call. It's fixed now :-)

2023-07-19 11:03 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-07-19 11:08 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-19 15:30 UTC, kurt-uk submitted a review, later dismissed

2023-07-19 15:33 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-07-20 06:06 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-26 12:55 UTC, LeonardoPalmeiro approved these changes

2023-07-26 13:16 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-26 13:36 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-07-27 15:19 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-08-01 13:03 UTC, LeonardoPalmeiro approved these changes

2023-08-02 08:28 UTC, LeonardoPalmeiro approved these changes

2023-08-10 11:47 UTC, LeonardoPalmeiro approved these changes

2023-08-10 11:48 UTC, miguelMolina3691 approved these changes

2023-08-11 13:34 UTC, LeonardoPalmeiro approved these changes

2023-08-14 07:40 UTC, miguelMolina3691 approved these changes

2023-08-14 07:43 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-08-22 11:24 UTC, m-meulendijks-v1 approved these changes

2023-08-22 11:31 UTC, hmcts-version1-ignacio approved these changes

2023-08-22 11:32 UTC, merged