Civ 1264 are you disabled
hmcts/civil-citizen-ui pull request #190
Opened 2022-03-04 13:19 UTC by laarmada

### JIRA link ###

https://[tools.hmcts.net](https://tools.hmcts.net/jira/browse/CIV-1264)/jira/browse/CIV-1264

### Change description ###

citizen is viewing 'Are you disabled' screen

**Does this PR introduce a breaking change?** (check one with "x")

```
[x ] Yes
[ ] No
```

2022-03-04 14:25 UTC, osheaf01 approved these changes
LGTM

2022-03-07 08:47 UTC, LeonardoPalmeiro requested changes

2022-03-07 08:47 UTC, LeonardoPalmeiro commented on src/main/common/form/models/statement-of-means/disability.ts
> +}
Is it worth to create an enum for YES/NO?

2022-03-07 08:47 UTC, LeonardoPalmeiro commented on src/main/views/features/response/statement-of-means/disability.njk
> +{% endblock %}
maybe this could be a reusable component, because we've a lot of screen with the same type of information . what do you think about it?

2022-03-07 09:26 UTC, sampankumar commented on src/main/common/form/models/statement-of-means/disability.ts
> +}
We have a lot of Yes No questions in all the forms, is it worth creating one common type called YesNo Type and then we can re use that type/class everywhere.
Just an idea... if it is not difficult to implement, then we can look at that approach.

2022-03-07 10:18 UTC, TatsyMaslova reviewed
I like it. I think Leo and Sampan is right and we need to  make the yes no component reusable. I.e. create a macro with yes no and error and perhaps a reusable model.  otherwise I would approve :)

2022-03-07 12:12 UTC, laarmada commented on src/main/views/features/response/statement-of-means/disability.njk
> +{% endblock %}
I have create a new macro yesNoForm.njk, have a look...

2022-03-09 08:18 UTC, laarmada commented on src/main/common/form/models/statement-of-means/disability.ts
> +}
done

2022-03-10 16:25 UTC, sampankumar commented on src/main/modules/statementOfMeans/disabilityService.ts
> +    if (civilClaimResponse.case_data.statementOfMeans) {
You might have to check `civilClaimResponse && civilClaimResponse.case_data`
before this condition just to check if case_data is there.

2022-03-11 08:00 UTC, laarmada commented on src/main/modules/statementOfMeans/disabilityService.ts
> +    if (civilClaimResponse.case_data.statementOfMeans) {
you are totally right I have do the same in other part... I will do the same here..

2022-03-11 12:29 UTC, LeonardoPalmeiro requested changes

2022-03-11 12:29 UTC, LeonardoPalmeiro commented on src/main/modules/statementOfMeans/disabilityService.ts
> +  public async saveDisability(claimId: string, disability: Disability) {
add the return of the method

2022-03-11 12:29 UTC, LeonardoPalmeiro commented on src/main/views/features/response/statement-of-means/disability.njk
> +          "titleText": "There was a problem",
may we need to add the t{}

2022-03-11 13:25 UTC, RosDiaf approved these changes

2022-03-11 14:55 UTC, LeonardoPalmeiro approved these changes

2022-03-15 09:44 UTC, mounikahmcts commented
Changes are moved to master as part of https://github.com/hmcts/civil-citizen-ui/pull/218/files (CIV-1265)

2022-03-15 09:44 UTC, closed without merging