CIV-9409 Trial Arrangements: Defendant LiP – Latest Updates Tile Notification for Defendant LiP
hmcts/civil-citizen-ui pull request #1914
Opened 2023-07-18 15:45 UTC by maciejmodzelewski

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9409

![image](https://github.com/hmcts/civil-citizen-ui/assets/18092228/6a8e5ab1-bed5-48d2-82dc-0216337ce78b)

### Change description ###
New tiles created that show information about trial arrangements being finalised for each of the two parties

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-19 11:11 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-07-19 11:57 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-07-20 09:57 UTC, kurt-uk requested changes

2023-07-20 09:57 UTC, kurt-uk commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
> +  trialReadyApplicant?: YesNoUpperCamelCase;
can we move this into a trial object sat at caseProgression level?

2023-07-20 14:23 UTC, maciejmodzelewski commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
> +  trialReadyApplicant?: YesNoUpperCamelCase;
Done

2023-07-20 15:44 UTC, kurt-uk requested changes

2023-07-20 15:44 UTC, kurt-uk commented on src/main/common/models/caseProgression/caseProgression.ts
> +  trialReadyApplicant?: YesNoUpperCamelCase;
With this being part of trial arrangements, i think it would be best to create a trial arrangements object that has a ready yes or no in it rather than this being placed out of feature in its parent feature. we should try keep all trial arrangement together

2023-07-20 15:44 UTC, kurt-uk commented on src/main/common/models/caseProgression/caseProgression.ts
> +  trialReadyApplicant?: YesNoUpperCamelCase;
also try match the other fields naming, youve called it applicant but the other instnaces refer as claimant, likewise with def, and place them first
`claimantTrialArrangements`

2023-07-21 08:49 UTC, kurt-uk requested changes

2023-07-21 08:49 UTC, kurt-uk commented on src/main/common/models/civilClaimResponse.ts
> +  trialReadyRespondent1?: YesNoUpperCamelCase;
remember to keep variable naming consistent

2023-07-21 08:49 UTC, kurt-uk commented on src/main/common/models/caseProgression/trialArrangements.ts
> +  defendantTrialArrangementsReady?: YesNoUpperCamelCase;
These should exist in CaseProgression to make TrialArrangements a reusable and extendable class regardless of user

2023-07-21 08:59 UTC, maciejmodzelewski commented on src/main/common/models/caseProgression/trialArrangements.ts
> +  defendantTrialArrangementsReady?: YesNoUpperCamelCase;
@kurt-uk I'm not sure I follow. Can we discuss?

2023-07-21 09:57 UTC, maciejmodzelewski commented on src/main/common/models/caseProgression/trialArrangements.ts
> +  defendantTrialArrangementsReady?: YesNoUpperCamelCase;
Done

2023-07-21 09:59 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-21 10:24 UTC, hmcts-version1-ignacio approved these changes

2023-07-21 10:55 UTC, kurt-uk approved these changes

2023-08-04 08:54 UTC, hmcts-version1-ignacio approved these changes

2023-08-04 13:24 UTC, kurt-uk approved these changes

2023-10-11 09:49 UTC, maciejmodzelewski commented on Jenkinsfile_CNP
> +def ccdBranch = "feat/CIV-9409"
For testing purposes only. Change back to master before merging.

2023-10-16 09:11 UTC, laarmada submitted a review, later dismissed

2023-10-16 10:37 UTC, miguelMolina3691 approved these changes

2023-10-23 15:39 UTC, dharmendrak approved these changes

2023-10-23 15:56 UTC, m-meulendijks-v1 approved these changes

2023-10-23 15:57 UTC, merged