Civ-9198 - finalise trial arrangements - hearing duration & other info
hmcts/civil-citizen-ui pull request #1925
Opened 2023-07-19 15:50 UTC by m-meulendijks-v1

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9198

### Change description ###
Page for hearing duration & other information input fields.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-20 08:57 UTC, LeonardoPalmeiro approved these changes

2023-07-20 09:39 UTC, hmcts-version1-ignacio commented on src/main/modules/i18n/locales/cy.json
> +      "MINUTES_150": "2 and a half hour",
"MINUTES_120": "2 hour", 
 "MINUTES_150": "2 and a half hour",
 
 Missing "s"?

2023-07-20 09:41 UTC, hmcts-version1-ignacio commented on src/main/modules/i18n/locales/en.json
> +      "MINUTES_150": "2 and a half hour",
"MINUTES_120": "2 hour",
"MINUTES_150": "2 and a half hour",

Missing "s"?

2023-07-20 09:54 UTC, m-meulendijks-v1 commented on src/main/modules/i18n/locales/cy.json
> +      "MINUTES_150": "2 and a half hour",
Added the 's' - well spotted!

2023-07-20 09:55 UTC, m-meulendijks-v1 commented on src/main/modules/i18n/locales/en.json
> +      "MINUTES_150": "2 and a half hour",
Added the 's' - well spotted!

2023-07-20 09:55 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-07-20 09:57 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-20 10:15 UTC, kurt-uk submitted a review, later dismissed

2023-07-26 16:10 UTC, LeonardoPalmeiro approved these changes

2023-07-27 10:44 UTC, miguelMolina3691 approved these changes

2023-07-31 09:57 UTC, LeonardoPalmeiro commented on src/main/common/models/caseProgression/HearingDuration.ts
> +  return t('COMMON.HEARING_DURATION.'+hearingDuration.toString());
please format this file

2023-07-31 09:59 UTC, LeonardoPalmeiro commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
> +    return formatHearingDuration(this.hearingDuration);
can we use the same approach of line 47?
![image](https://github.com/hmcts/civil-citizen-ui/assets/93268657/9c045e83-fc0a-47bc-a4d8-fb4c8cad7103)

2023-07-31 10:03 UTC, LeonardoPalmeiro commented on src/main/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.ts
> +    const claim = await civilServiceClient.retrieveClaimDetails(claimId, <AppRequest>req);
I'm not surewe should to use retrieveClaimDetails or const claim = await getClaimById(claimId, req);

2023-07-31 10:07 UTC, LeonardoPalmeiro commented on src/main/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.ts
> +    //TODO: check your answers URL will have to be checked as part of CIV-9201
I'm not sure why we are not save the information on redis.
should we save or not?

2023-08-02 14:32 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/HearingDuration.ts
> +  return t('COMMON.HEARING_DURATION.'+hearingDuration.toString());
Formatted

2023-08-02 14:32 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/caseProgressionHearing.ts
> +    return formatHearingDuration(this.hearingDuration);
I have added the HearingDurationFormatter file to get a similar style.

2023-08-02 14:32 UTC, m-meulendijks-v1 commented on src/main/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.ts
> +    const claim = await civilServiceClient.retrieveClaimDetails(claimId, <AppRequest>req);
I've switched to await getClaimById

2023-08-02 14:33 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/trialArrangements/TrialArrangements.ts
renamed

2023-08-03 08:03 UTC, LeonardoPalmeiro requested changes
please add a test to getHearingDurationFormatted method.

2023-08-03 08:03 UTC, LeonardoPalmeiro commented on src/main/common/models/caseProgression/trialArrangements/trialArrangements.ts
> +  isCaseReady?: YesNo;
I believe in this part is   isCaseReady?: IsCaseReadyForm;

2023-08-03 08:03 UTC, LeonardoPalmeiro commented on src/main/common/utils/pageSectionBuilder.ts
I'm not sure why we're change the methods of position. do we really want to do that?

2023-08-03 08:50 UTC, m-meulendijks-v1 commented on src/main/common/form/models/caseProgression/trialArrangements/OtherTrialInformation.ts
Changed to camelCase

2023-08-03 08:50 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/HearingDuration.ts
Changed to camelCase

2023-08-03 08:52 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/trialArrangements/trialArrangements.ts
> +  isCaseReady?: YesNo;
IsCaseReadyForm just contains a YesNo, so I retrieve that YesNo when saving to TrialArrangements.
I use the form only when sending/retrieving things from the view.

2023-08-03 08:53 UTC, m-meulendijks-v1 commented on src/main/common/utils/pageSectionBuilder.ts
I think it makes more sense to have mainTitle & leadParagraph before title & paragraph, or not?
I think I added them in, and then someone else added them in a different place as part of their PR, and their PR got merged first.

2023-08-03 09:18 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/trialArrangements/finaliseYourTrialSectionBuilder.ts
> +  addInsetText(text: string, variables?: unknown) {
I have moved it to pageSectionBuilder - I think that was a good idea.

2023-08-03 09:24 UTC, hmcts-version1-ignacio approved these changes

2023-08-03 14:33 UTC, bhagyashreesharma90 approved these changes

2023-08-08 12:39 UTC, hmcts-version1-ignacio approved these changes

2023-08-08 12:50 UTC, bhagyashreesharma90 approved these changes

2023-08-08 12:52 UTC, LeonardoPalmeiro approved these changes

2023-08-08 13:51 UTC, merged