CIV-8213 claim submission payment requirement
hmcts/civil-citizen-ui pull request #1947
Opened 2023-07-24 10:10 UTC by GorilaNaranja

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-8213

### Change description ###
Claim Submission - Confirmation Screen where payment is required

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-24 14:19 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-07-24 14:26 UTC, laperla11 requested changes

2023-07-24 14:26 UTC, laperla11 commented on src/main/routes/features/claim/claimSubmittedController.ts
> +        helpWithFee, downloadHref, claimFeeUrl,
I confirmed with Simon that we don't have download sealed claim link on confirmation page so need for `downloadHref`. You also need to remove it from view. you can check my PR for it:
https://github.com/hmcts/civil-citizen-ui/pull/1937

2023-07-25 08:47 UTC, GorilaNaranja commented on src/main/routes/features/claim/claimSubmittedController.ts
> +        helpWithFee, downloadHref, claimFeeUrl,
Fixed

2023-07-25 08:50 UTC, laperla11 approved these changes

2023-07-25 08:51 UTC, LeonardoPalmeiro approved these changes

2023-07-25 08:55 UTC, TatsyMaslova approved these changes

2023-07-25 09:07 UTC, portizdev approved these changes

2023-08-15 10:24 UTC, merged