CIV-8199  Pay your claim fee - Front End
hmcts/civil-citizen-ui pull request #1981
Opened 2023-08-01 14:03 UTC by jeswanth-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-08-02 09:13 UTC, jeswanth-hmcts commented on sonar-project.properties
> +src/main/routes/features/claim/claimSubmittedController.ts,src/main/routes/features/claim/payment/claimFeeBreakDownController.ts,src/main/routes/features/claim/checkAnswersController.ts,\
Even though tests are present, in sonar analysis for coverage, they are not showing, so they are excluded. Mainly it is for callback functions on the controller show that has been uncovered. Also happy to implement any other solution for this

2023-08-02 10:34 UTC, TatsyMaslova submitted a review, later dismissed

2023-08-02 10:49 UTC, laperla11 requested changes

2023-08-02 10:49 UTC, laperla11 commented on src/main/routes/features/claim/checkAnswersController.ts
> +        const paymentUrlWithId = constructResponseUrlWithIdParams(userId, paymentUrl);
if helpWithFees is yes, whne do we delete the draft claim from redis after your change?

2023-08-02 10:49 UTC, laperla11 commented on src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
> +    res.render(viewPath, { csrf: res.locals.csrf, totalClaimAmount: claim.totalClaimAmount, interest: claim.totalInterest, claimFee, hasInterest: !!claim.totalInterest, totalAmount });
why we're passing `csrf` here?

2023-08-02 10:56 UTC, jeswanth-hmcts commented on src/main/routes/features/claim/checkAnswersController.ts
> +        const paymentUrlWithId = constructResponseUrlWithIdParams(userId, paymentUrl);
In else, we are deleting. if help with fees is yes,

2023-08-02 11:09 UTC, jeswanth-hmcts commented on src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
> +    res.render(viewPath, { csrf: res.locals.csrf, totalClaimAmount: claim.totalClaimAmount, interest: claim.totalInterest, claimFee, hasInterest: !!claim.totalInterest, totalAmount });
removing this

2023-08-02 11:15 UTC, laperla11 approved these changes

2023-08-02 11:38 UTC, laperla11 approved these changes

2023-08-02 12:45 UTC, neeta-hmcts submitted a review, later dismissed

2023-08-02 12:45 UTC, TatsyMaslova submitted a review, later dismissed

2023-08-03 08:04 UTC, portizdev approved these changes

2023-08-07 13:05 UTC, portizdev approved these changes

2023-08-07 13:32 UTC, laperla11 submitted a review, later dismissed

2023-08-17 14:28 UTC, laperla11 approved these changes

2023-08-18 15:10 UTC, neeta-hmcts submitted a review, later dismissed

2023-08-21 08:40 UTC, portizdev submitted a review, later dismissed

2023-09-07 14:34 UTC, GorilaNaranja approved these changes

2023-09-07 14:35 UTC, ElifDenizEsea approved these changes

2023-09-07 14:36 UTC, merged