CIV-9718 Upload Documents - Date Validation error messages improved
hmcts/civil-citizen-ui pull request #1982
Opened 2023-08-01 15:03 UTC by maciejmodzelewski

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9718

### Change description ###
Error messages made more specific, so each date field has a dedicated error message instead of a generic one that is displayed three times as it was originally.

![image](https://github.com/hmcts/civil-citizen-ui/assets/18092228/91aa7809-38d0-44a4-8d55-7518f0e01ab5)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-08-02 08:26 UTC, bhagyashreesharma90 submitted a review, later dismissed

2023-08-02 13:57 UTC, kurt-uk requested changes

2023-08-02 13:57 UTC, kurt-uk commented on src/main/modules/i18n/locales/cy.json
>      "VALID_REAL_DATE": "Date of document must be a real date",
we no longer need this one anymore then, can you clean up removed items please

2023-08-03 08:09 UTC, maciejmodzelewski commented on src/main/modules/i18n/locales/cy.json
>      "VALID_REAL_DATE": "Date of document must be a real date",
Done

2023-08-03 08:22 UTC, hmcts-version1-ignacio approved these changes

2023-08-03 08:35 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-08-03 10:50 UTC, hmcts-version1-ignacio approved these changes

2023-08-04 09:09 UTC, merged