CIV-8202 - CIV-9831 - Claim task-list guard and eligibility cookie
hmcts/civil-citizen-ui pull request #1988
Opened 2023-08-03 09:04 UTC by portizdev

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9831
https://tools.hmcts.net/jira/browse/CIV-8202

### Change description ###
Creation of a cookie to be set when entering eligibility/eligible and to expire in 1h.
As long as the cookie exists, the user can access claim/task-list. 
If after 1h the user has not started to create the claim (no action has been taken in claim/task-list) they will have to go through the whole eligibility process again. If they try to access claim/task-list they will be redirected to /eligibility.

Also included is that if the user is not logged in when trying to access claim/task-list, they will be redirected after the IDAM to claim/task-list instead of /dashboard.

Use code from #1889 to be able to use the task-list.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-08-04 09:05 UTC, laperla11 requested changes
Should we also need to implement R2 flag?

2023-08-04 09:05 UTC, laperla11 commented on src/main/modules/oidc/index.ts
> +        app.locals.claimIssueTasklist = true;
`app.locals` is not shared with instances so this'll work on local, preview but might fail on demo and master instead either assign this value to `req.sesion` or use approach on line 99:
`app.locals.assignClaimId = appReq.session.assignClaimId = <string>req.query.id;`

2023-08-04 12:06 UTC, laperla11 approved these changes

2023-08-04 12:57 UTC, laperla11 approved these changes

2023-08-04 12:57 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-08-04 13:01 UTC, GorilaNaranja approved these changes

2023-08-11 07:06 UTC, GorilaNaranja approved these changes

2023-08-11 07:26 UTC, LeonardoPalmeiro approved these changes

2023-08-14 17:20 UTC, merged