Feat/civ 9201
hmcts/civil-citizen-ui pull request #2010
Opened 2023-08-07 20:03 UTC by bhagyashreesharma90

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9201

### Change description ###
(It has changes from hearing duration other information page)
Check your answers for finalise trial arrangements
Save data to CCD on submit

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-08-09 08:15 UTC, LeonardoPalmeiro approved these changes

2023-08-09 08:46 UTC, hmcts-version1-ignacio commented on src/main/routes/features/caseProgression/trialArrangements/checkAnswersController.ts
> +  }catch (error) {
Space between "}" and "catch" missing.

2023-08-09 08:47 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-08-09 08:59 UTC, bhagyashreesharma90 commented on src/main/routes/features/caseProgression/trialArrangements/checkAnswersController.ts
> +  }catch (error) {
> Space between "}" and "catch" missing.

done

2023-08-09 09:38 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-08-09 09:49 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-08-11 09:53 UTC, LeonardoPalmeiro requested changes

2023-08-11 09:53 UTC, LeonardoPalmeiro commented on src/main/services/features/response/checkAnswers/caseProgression/trialArrangements/buildTrialReadyConfirmationSection.ts
> +  trialReadySummarySections.summaryList.rows.push(summaryRow(t('PAGES.FINALISE_TRIAL_ARRANGEMENTS.ARE_THERE_ANY_CHANGES', { lng: getLng(lang) }), '<p class="govuk-section-break--visible" >'+t(`${clai
my suggestion in here
  trialReadySummarySections.summaryList.rows.push(summaryRow(t('PAGES.FINALISE_TRIAL_ARRANGEMENTS.ARE_THERE_ANY_CHANGES', { lng: getLng(lang) }), '<p >'+t(`${claim.caseProgression.defendantTrialArrangements.hasAnythingChanged.option}`, { lng: getLng(lang) }) +'</p><hr class="govuk-section-break--visible"><p>' + t(`${claim.caseProgression.defendantTrialArrangements.hasAnythingChanged.textArea}`, { lng: getLng(lang) })+'</p>', constructResponseUrlWithIdParams(claimId, HAS_ANYTHING_CHANGED_URL), changeLabel(lang)));

then we will have the spacing of the divider correctly.
![image](https://github.com/hmcts/civil-citizen-ui/assets/93268657/b8ce33bf-c3b2-488d-94dd-5e533b3da8aa)

2023-08-11 10:39 UTC, bhagyashreesharma90 commented on src/main/services/features/response/checkAnswers/caseProgression/trialArrangements/buildTrialReadyConfirmationSection.ts
> +  trialReadySummarySections.summaryList.rows.push(summaryRow(t('PAGES.FINALISE_TRIAL_ARRANGEMENTS.ARE_THERE_ANY_CHANGES', { lng: getLng(lang) }), '<p class="govuk-section-break--visible" >'+t(`${clai
> my suggestion in here `trialReadySummarySections.summaryList.rows.push(summaryRow(t('PAGES.FINALISE_TRIAL_ARRANGEMENTS.ARE_THERE_ANY_CHANGES', { lng: getLng(lang) }), '<p >'+t(`${claim.caseProgression.defendantTrialArrangements.hasAnythingChanged.option}`, { lng: getLng(lang) }) +'</p><hr class="govuk-section-break--visible"><p>' + t(`${claim.caseProgression.defendantTrialArrangements.hasAnythingChanged.textArea}`, { lng: getLng(lang) })+'</p>', constructResponseUrlWithIdParams(claimId, HAS_ANYTHING_CHANGED_URL), changeLabel(lang)));`
> 
> then we will have the spacing of the divider correctly. ![image](https://user-images.githubusercontent.com/93268657/259976042-b8ce33bf-c3b2-488d-94dd-5e533b3da8aa.png)

Done

2023-08-15 14:25 UTC, kurt-uk submitted a review, later dismissed

2023-08-15 14:29 UTC, maciejmodzelewski requested changes
You have some issues in your build
![image](https://github.com/hmcts/civil-citizen-ui/assets/18092228/9d25c0c3-88ce-41e6-8abf-0df29e4f2c78)

2023-08-16 10:19 UTC, LeonardoPalmeiro approved these changes

2023-08-16 10:20 UTC, maciejmodzelewski approved these changes

2023-09-01 15:25 UTC, closed without merging