CIV-9015 Code for Claimant Intent: Task List - Full Defence Full Reject
hmcts/civil-citizen-ui pull request #2020
Opened 2023-08-08 12:29 UTC by jeswanth-hmcts

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-9015

### Change description ###

Claimant Intent: Task List - Full Defence Full Reject (dispute all)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-08-08 14:36 UTC, laperla11 requested changes

2023-08-08 16:17 UTC, jeswanth-hmcts commented on src/main/common/models/claim.ts
> +  responseClaimMediationSpecRequired: string;
used translated varibles

2023-08-08 16:49 UTC, laperla11 approved these changes

2023-08-09 08:12 UTC, GorilaNaranja commented on src/main/common/models/claim.ts
> +    return Object.entries(this.mediation.canWeUse).length > 0 || Object.entries(this.mediation.companyTelephoneNumber).length > 0;
mediation could be undefined so it will throw an error "can not read canWeUse from undefined".

You have to use question marks: this.mediation?.canWeUse
Same for companyTelephoneNumber

2023-08-09 08:28 UTC, jeswanth-hmcts commented on src/main/common/models/claim.ts
> +    return Object.entries(this.mediation.canWeUse).length > 0 || Object.entries(this.mediation.companyTelephoneNumber).length > 0;
No, it always returned an empty object in meditation for all the properties in case of no value

2023-08-09 08:32 UTC, GorilaNaranja submitted a review, later dismissed

2023-08-22 06:22 UTC, portizdev approved these changes

2023-08-23 08:24 UTC, kamilewandowski submitted a review, later dismissed

2023-08-24 08:05 UTC, kenneth-hmcts submitted a review, later dismissed

2023-08-24 08:05 UTC, portizdev approved these changes

2023-09-11 10:05 UTC, laperla11 approved these changes

2023-09-11 10:06 UTC, rajakm approved these changes

2023-09-11 10:06 UTC, merged