CIV-9921 add redis expire time
hmcts/civil-citizen-ui pull request #2030
Opened 2023-08-10 07:16 UTC by kamilewandowski

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9921

### Change description ###
add expire time for drafts stored in redis

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-08-10 07:24 UTC, TatsyMaslova commented
The story says it should save the draft claim as soon as the claim is navigated from eligibility page according to the ACs of your story. does it do that?

2023-08-10 07:34 UTC, TatsyMaslova commented on src/main/modules/draft-store/draftStoreService.ts
> +const DRAFT_EXPIRE_TIME = 24 * 60 * 60 * 180;
why do you need to do multiplication instead of just writing a result there? also perhaps we could put this value in the config so that we could change it in the config instead of going to the code

2023-08-10 08:21 UTC, kamilewandowski commented on src/main/modules/draft-store/draftStoreService.ts
> +const DRAFT_EXPIRE_TIME = 24 * 60 * 60 * 180;
15552000 seems to be random, and it is not clear exactly how long expire time is, and also if someone needs to change that in the future will have to calculate that again. With multiplication in place, you need to update 180 to whatever will be required.

2023-08-11 10:32 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimTaskListController.ts
> +      if(caseData.id == undefined) {
here i can see several bugs: 
1. a draft claim will never have an id so every time the claimant is navigated to task list, we override existing claim with a new claim.
2. we only want to save the claim if it does not exist in draft store (i.e. there is no claim against the user) and when the user navigated from eligibility page (i.e. we need to check for the cookies/session from eligibility page)

2023-08-11 10:36 UTC, TatsyMaslova commented on config/default.yaml
> +      expireInDays: 180
default.yaml is for our local environment. so it will work on our local but not for Raja in test or in live. You need to introduce a variable and add it to custom-evnironment-variables.yaml .

2023-08-11 10:39 UTC, TatsyMaslova commented on config/default.yaml
> +      expireInDays: 180
Then add it to values.yaml

2023-08-16 16:17 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimTaskListController.ts
> +        const claim = new Claim();
no this is not right. we dont have to check release 2 here. we just need to check whether casedata is undefined or not and whether the eligiblity check has been done. what we need to do is check whether release2 is enabled in getCaseDataFromStore function and if it is enabled and there is no claim for the user id then return undefined

2023-08-17 07:47 UTC, TatsyMaslova commented on src/main/modules/draft-store/draftStoreService.ts
> +  if(isReleasedTwoEnabled) {
no it should not just return undefined all the time. it should check whether the case is there or not and if it is not there then return undefined

2023-08-17 07:50 UTC, TatsyMaslova commented on src/main/modules/draft-store/draftStoreService.ts
>    const civilClaimResponse = await getDraftClaimFromStore(claimId);
so your check should be here after you called getDraftClaimFromStore. and instead of callind const claim = new Claim - check if civilClaimResponse is undefined or civilClaimRespnse.case_data is undefined  and release2 enabled then return undefined. otherwise carry on as normal

2023-08-17 07:53 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimTaskListController.ts
> +        saveDraftClaim(null, undefined);
this is incorrect as well if caseData is undefined then save the caseData to draft store under the user id . no need to set dates etc. it should be done in the logic where we save the case (outside the controller). if it is defined then we dont do anything. otherwise we will override existing data

2023-08-17 08:44 UTC, TatsyMaslova commented on src/main/modules/draft-store/draftStoreService.ts
> +    draftStoreClient.expire(claimId, addDaysToDate(claim.createAt, DRAFT_EXPIRE_TIME_IN_DAYS).getTime());
as discussed previously you need to set createAt date if the claim is a new claim. this should happen in the service for redis because this field is redis related - defines the expiration of the claim

2023-08-17 08:45 UTC, TatsyMaslova commented on src/main/modules/draft-store/draftStoreService.ts
> +    draftStoreClient.expire(claimId, addDaysToDate(claim.createAt, DRAFT_EXPIRE_TIME_IN_DAYS).getTime());
you are setting it in the new draft claim response but checking on the claim you are saving

2023-08-17 08:47 UTC, TatsyMaslova commented on src/main/modules/draft-store/draftStoreService.ts
> +  storedClaimResponse.case_data.createAt = new Date();
would not this throw a null pointer or equivalent exception?

2023-08-18 07:51 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimTaskListController.ts
> +        saveDraftClaim(userId, caseData);
aren't we saving undefined here?

2023-08-18 07:53 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimTaskListController.ts
> +        saveDraftClaim(userId, caseData);
perhaps if caseData is undefined we can create a new CaseData then save it under userid.

2023-08-18 08:04 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimTaskListController.ts
> +        saveDraftClaim(userId, caseData);
perhaps should be this:
` if(caseData == undefined) {
        saveDraftClaim(userId, new CaseData());
}`

2023-08-18 08:16 UTC, TatsyMaslova submitted a review, later dismissed

2023-08-18 08:30 UTC, laperla11 approved these changes

2023-08-22 10:38 UTC, LeonardoPalmeiro requested changes

2023-08-22 10:38 UTC, LeonardoPalmeiro commented on src/main/routes/features/claim/claimTaskListController.ts
> +        saveDraftClaim(userId, new Claim());
maybe we're missing await in here

2023-09-01 10:20 UTC, laperla11 commented on src/main/routes/features/claim/claimTaskListController.ts
> +      if(caseData === undefined || caseData.id === undefined) {
`caseData.?id === undefined` is covering both conditions

2023-09-01 10:20 UTC, laperla11 submitted a review, later dismissed

2023-09-01 14:40 UTC, kenneth-hmcts submitted a review, later dismissed

2023-09-12 08:56 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimTaskListController.ts
> +      await creteDraftClaimInStoreWithExpiryTime(userId);
spelling mistake on the function - create not crete 😄 . i also do lots of spelling mistakes

2023-09-12 09:00 UTC, TatsyMaslova commented on src/main/modules/draft-store/draftStoreService.ts
> +export async function creteDraftClaimInStoreWithExpiryTime(claimId: string) {
spelling mistake on the method. should be create

2023-09-12 09:18 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-09-12 09:44 UTC, GorilaNaranja approved these changes

2023-09-12 10:23 UTC, neeta-hmcts approved these changes

2023-09-12 11:36 UTC, laperla11 commented on src/main/routes/features/claim/claimTaskListController.ts
> +      await creteDraftClaimInStoreWithExpiryTime(userId);
good spot - fixed the spelling

2023-09-12 11:36 UTC, laperla11 commented on src/main/modules/draft-store/draftStoreService.ts
> +export async function creteDraftClaimInStoreWithExpiryTime(claimId: string) {
fixed the spelling

2023-09-12 11:38 UTC, TatsyMaslova approved these changes

2023-09-15 11:53 UTC, closed without merging

2023-09-15 11:53 UTC, laperla11 commented
replaced ny PR-2158