CIV-8109 Save documents to redis
hmcts/civil-citizen-ui pull request #2061
Opened 2023-08-16 12:15 UTC by miguelMolina3691

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-8109

### Change description ###
Save documents uploaded in "Upload your documents" screen on redis.
Backend development.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-08-16 14:45 UTC, LeonardoPalmeiro requested changes

2023-08-16 14:45 UTC, LeonardoPalmeiro commented on src/main/routes/features/caseProgression/checkAnswersController.ts
>        const userId = req.session?.user?.id;
maybe we don't need to use this variable.

2023-08-16 14:45 UTC, LeonardoPalmeiro commented on src/main/views/features/caseProgression/check-answers.njk
I'm not sure if we need to add this fix. 
this should be fixed in another task

2023-08-16 14:55 UTC, hmcts-version1-ignacio approved these changes

2023-08-16 15:12 UTC, kurt-uk submitted a review, later dismissed

2023-08-21 08:44 UTC, kurt-uk submitted a review, later dismissed

2023-08-21 08:51 UTC, maciejmodzelewski approved these changes

2023-08-21 08:52 UTC, LeonardoPalmeiro approved these changes

2023-08-23 08:17 UTC, kurt-uk submitted a review, later dismissed

2023-08-23 08:17 UTC, maciejmodzelewski approved these changes

2023-08-23 08:59 UTC, maciejmodzelewski submitted a review, later dismissed

2023-08-23 09:15 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-08-23 10:20 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-08-23 10:37 UTC, kurt-uk approved these changes

2023-08-30 09:59 UTC, kurt-uk approved these changes

2023-08-30 10:01 UTC, hmcts-version1-ignacio approved these changes

2023-08-30 10:01 UTC, LeonardoPalmeiro approved these changes

2023-08-30 13:45 UTC, LeonardoPalmeiro approved these changes

2023-08-31 10:58 UTC, merged