CIV-9800 - Bundles tab + content
hmcts/civil-citizen-ui pull request #2063
Opened 2023-08-16 15:23 UTC by m-meulendijks-v1

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9800

### Change description ###
Edits: simplifed the pre-existing src/main/services/features/caseProgression/documentTableBuilder.ts to use the table builder.

Bundles tab 
![image](https://github.com/hmcts/civil-citizen-ui/assets/107135537/01a4bdd7-ef93-4654-8d1b-5c1c0d95e850)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-08-16 15:24 UTC, m-meulendijks-v1 commented on src/main/assets/scss/main.scss
> +.tableWrap {
This already exists as part of https://tools.hmcts.net/jira/browse/CIV-10068.
But I've placed it in here as well, otherwise it would be impossible to tell how the table would look.

2023-08-16 15:24 UTC, m-meulendijks-v1 commented on src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
> +  addTable(tableHeaders?: TableCell[], tableRows?: TableCell[][], classes?: string){
Added a table option to the builder.

2023-08-16 15:25 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/bundles/bundle.ts
> +export class Bundle {
Used for cui side

2023-08-16 15:28 UTC, m-meulendijks-v1 commented on src/main/routes/urls.ts
> +export const MAKE_APPLICATION_TO_COURT = 'https://www.gov.uk/government/publications/form-n244-application-notice';
This exists hard coded on the front end in several locations - but for this ticket it makes more sense to place on the backend.

2023-08-16 15:30 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +import {LatestUpdateSectionBuilder} from 'models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder';
The uploadDocumentsTableSectionBuilder was removed as it was very specific to the table for the evidence upload tab.
Instead, this class is now refactored to use the more universal builder that was introduced to latestUpdateSectionBuilder.

2023-08-17 08:44 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +  orderBundlesNewToOld(bundles);
I saw that in another part of CUI we're using like same approache to ordering.
maybe we could move orderBundlesNewToOld(bundles); to domain and/or create a another class like ordering utility or something like that.

2023-08-17 08:44 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +  return `<a class="govuk-link" href="${url}">${fileName}</a>`;
maybe we could move to domain to make easier if we need to use in another part of the application.

2023-08-17 08:44 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +    const hearingDateFormatted = formatStringDateDMY(bundle.bundleHearingDate);
probably we could move to domain if we need to use in another part of the application.

2023-08-17 08:44 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +export function orderBundlesNewToOld(documentsWithDates: Bundle[]): Bundle[] {
same here. 
we can create a ordering class or some utility class or something like that.

2023-08-17 08:57 UTC, hmcts-version1-ignacio approved these changes

2023-08-17 08:59 UTC, kurt-uk requested changes

2023-08-17 08:59 UTC, kurt-uk commented on src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
> +  addTable(tableHeaders?: TableCell[], tableRows?: TableCell[][], classes?: string){
does the latest updates builder need a table? could we create a new builder either specific for `BundleTabSectionBuilder` extending latest update section builder, or something more generic - `TableSectionBuilder` extending the same?

2023-08-17 08:59 UTC, kurt-uk commented on src/main/common/models/caseProgression/bundles/bundleId.ts
> +export class BundleId {
would a name that reflects this be better?

2023-08-17 08:59 UTC, kurt-uk commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +import {LatestUpdateSectionBuilder} from 'models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder';
which is good, we want something thats reusable, but could it be extracted to its own again and extend the class that you need the remainder of functions from?

2023-08-17 13:13 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +function getTableRows(claim: Claim): TableCell[][] {
Doesn't it make more sense to add something like this once the https://tools.hmcts.net/jira/browse/CIV-9803 is picked up?

2023-08-17 13:14 UTC, m-meulendijks-v1 commented on src/main/common/models/caseProgression/bundles/bundleId.ts
> +export class BundleId {
Changed name to CCDBundle

2023-08-17 13:14 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/documentTableBuilder.ts
> +import {LatestUpdateSectionBuilder} from 'models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder';
Created a new builder called TabSectionBuilder, which extends PageSectionBuilder.

2023-08-17 13:14 UTC, m-meulendijks-v1 commented on src/main/routes/tabs.ts
> +  BUNDLES = 'Bundles'
Ah, I missed one - well spotted!

2023-08-17 13:15 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +  orderBundlesNewToOld(bundles);
I've moved orderBundlesNewToOld to its own BundlesFormatter class.

2023-08-17 13:17 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +export function orderBundlesNewToOld(documentsWithDates: Bundle[]): Bundle[] {
Created BundlesFormatter for this.

2023-08-17 13:28 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +    const hearingDateFormatted = formatStringDateDMY(bundle.bundleHearingDate);
I've moved formatting to within bundle.ts, to cut down on lines like 48-50.

2023-08-17 13:28 UTC, m-meulendijks-v1 commented on src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
> +  addTable(tableHeaders?: TableCell[], tableRows?: TableCell[][], classes?: string){
I guess not, have now created TabSectionBuilder for this purpose. Multiple tabs use tables.

2023-08-17 14:10 UTC, kurt-uk approved these changes

2023-08-18 09:46 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-09-07 10:11 UTC, closed without merging