Civ 1263 list bancks savings accounts
hmcts/civil-citizen-ui pull request #207
Opened 2022-03-11 12:38 UTC by TatsyMaslova

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-03-11 16:22 UTC, sampankumar commented on src/main/assets/js/append-row.js
> +  function cloneRow() {
Will it be beneficial to make this method parameterised, where class name can be passed may be?

2022-03-11 16:23 UTC, sampankumar commented on src/main/assets/js/append-row.js
> +  function getLastRow(){
Will it be beneficial to make this method parameterised, where class name can be passed may be?

2022-03-11 16:25 UTC, TatsyMaslova commented on src/main/assets/js/append-row.js
> +  function cloneRow() {
this happens on dom /page load similar to Rosario's approach. so it works so that if we want to add multiple rows then we just use specific class to the button and place our row in a div with a specific class.

2022-03-11 16:25 UTC, TatsyMaslova commented on src/main/assets/js/append-row.js
> +  function getLastRow(){
this happens on dom /page load similar to Rosario's approach. so it works so that if we want to add multiple rows then we just use specific class to the button and place our row in a div with a specific class.

2022-03-11 16:27 UTC, TatsyMaslova commented on src/main/assets/js/append-row.js
> +  function getLastRow(){
so it is reusable - we reuse classes rather then the method. as it is called on load and assigns the functionality to the button with the class

2022-03-14 09:20 UTC, laarmada requested changes
we need discuss about that.

2022-03-14 09:20 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/bankAccounts/bankAccountsController.test.ts
> +      const data = {
should we have a const data in a external file?....

2022-03-14 09:20 UTC, laarmada commented on src/main/views/features/response/statementOfMeans/citizenBankAndSavings/citizen-bank-accounts.njk
> +              <p class="govuk-body">
could we think in a generic component? to create a generic macro to reuse it?

2022-03-14 09:20 UTC, laarmada commented on src/main/routes/features/response/statementOfMeans/bankAccounts/bankAccountsController.ts
> +    res.redirect(getBaseUrlWithIdParam(claimId) + CITIZEN_SEVERELY_DISABLED_URL);
I will change the method including the concat url to avoid "+", for example: getBaseUrlWithIdParam(claimId,CITIZEN_SEVERELY_DISABLED_URL)

2022-03-14 09:20 UTC, laarmada commented on src/main/common/form/models/bankAndSavings/bankAccountType.ts
> +  selected: boolean;
in which case is used "selected" parameter?

2022-03-14 10:35 UTC, LeonardoPalmeiro requested changes

2022-03-14 10:44 UTC, TatsyMaslova commented on src/main/views/features/response/statementOfMeans/citizenBankAndSavings/citizen-bank-accounts.njk
> +              <p class="govuk-body">
do you mean like a generic macro for adding lots of rows? i don't think it is possible. however I do use a macro for account data which can be reusable

2022-03-14 10:46 UTC, TatsyMaslova commented on src/main/common/form/models/bankAndSavings/bankAccountType.ts
> +  selected: boolean;
when there is existing data and the data value is the same as the bank account types then the selected parameter is set to true so that we can see it selected in the drop down

2022-03-14 10:46 UTC, TatsyMaslova commented on src/main/routes/baseUrlConstants.ts
> +export const BASE_CASE_RESPONSE_URL = '/case/:id/response';
done :) good spot

2022-03-14 11:08 UTC, LeonardoPalmeiro requested changes

2022-03-14 11:08 UTC, LeonardoPalmeiro commented on src/main/common/utils/urlFormatter.ts
> +  return `/case/${id}/response`;
should use information from constant, but probably will came with another problem which is replace the **:id**.
I did something in the https://github.com/hmcts/civil-citizen-ui/blob/676363d7ebe6f14ca11c760e35bed28d625f87d3/src/main/common/utils/urlPatchReplace.ts#L1.

2022-03-14 11:37 UTC, laarmada requested changes
other thing

2022-03-14 11:37 UTC, laarmada commented on src/main/modules/statementOfMeans/bankAccounts/bankAccountService.ts
> +  public async getBankAccounts(claimId: string) {
we should add the return type?

2022-03-14 12:25 UTC, TatsyMaslova commented on src/test/unit/routes/features/response/statementOfMeans/bankAccounts/bankAccountsController.test.ts
> +      const data = {
it is debatable. because in this case data for every test is different. and also one would want to see what data is there. if i put it in a different file it would sort of hide the actual data when you look at the test. So I think in this case it should be visible in the test rather then be in the external file

2022-03-14 12:29 UTC, sampankumar commented on src/main/assets/js/append-row.js
> +  function cloneRow() {
Can this then also be used to add lets say another dropdown? or is it just for the button, because we are using the button css class?

2022-03-14 12:32 UTC, TatsyMaslova commented on src/main/assets/js/append-row.js
> +  function cloneRow() {
it has nothing to do with drop downs - its only to do with button that would "clone" all elements that are in specific div. and it assigns this functionality after dom elements are loaded

2022-03-14 12:35 UTC, TatsyMaslova commented on src/main/assets/js/append-row.js
> +  function cloneRow() {
so if we have a button and it has a specific class then it will have the functionality to clone elements in the div with also specific class. it works similar to Rosario's lookup code where the functionality is assigned to a button with a specific class

2022-03-14 13:05 UTC, TatsyMaslova commented on src/main/routes/features/response/statementOfMeans/bankAccounts/bankAccountsController.ts
> +    res.redirect(getBaseUrlWithIdParam(claimId) + CITIZEN_SEVERELY_DISABLED_URL);
done :)

2022-03-14 13:26 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/bankAccounts/bankAccountsController.test.ts
> +      const data = {
Maybe we can create a generic data but we don´t have enough time.... thanks @TatsyMaslova

2022-03-14 13:28 UTC, laarmada approved these changes
great job.

2022-03-15 14:53 UTC, merged