CIV-10129 settlement agreement removed from conformation screen
hmcts/civil-citizen-ui pull request #2087
Opened 2023-08-24 12:56 UTC by ElifDenizEsea

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [X] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-10129

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-08-25 06:51 UTC, portizdev requested changes
I think you are missing the last part of the ticket. You have deleted what needs to be deleted but you have not replaced it with what is indicated.

`Replace circled content with:

"Because you've said you won't pay immediately, <<claimant name>> can request a County Court Judgment against you"`

2023-08-25 12:01 UTC, portizdev submitted a review, later dismissed

2023-08-29 09:01 UTC, laperla11 submitted a review, later dismissed

2023-08-31 10:44 UTC, sankhajuria approved these changes

2023-08-31 10:53 UTC, neeta-hmcts approved these changes

2023-08-31 13:00 UTC, merged