CIV-10367 add caseRoles and service to get the information from civil-service
hmcts/civil-citizen-ui pull request #2110
Opened 2023-08-31 08:12 UTC by LeonardoPalmeiro

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-10367

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-08-31 10:15 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-08-31 10:30 UTC, kurt-uk requested changes

2023-08-31 10:30 UTC, kurt-uk commented on src/main/app/client/civilServiceClient.ts
> +        .replace(':documentId', documentId)
why are we using document Id? this is the case Id, not really anything to do with documents

2023-08-31 10:30 UTC, kurt-uk commented on src/main/common/models/claim.ts
> +    return this.caseRole === CaseRole.APPLICANTSOLICITORONE;
this isnt fully reflective of a claimant, in a LIP v LIP the role wouldnt be APPLICANTSOLICITORONE,

2023-08-31 10:30 UTC, kurt-uk commented on src/main/app/client/civilServiceClient.ts
> +      caseDetails.case_data.caseRole = await this.getUserCaseRoles(claimId, req);
CaseData doesnt seem to have a caseRole, do we need to keep it limited to Claim in CUI space so that data submission doesnt error with missing data fields?

2023-08-31 10:57 UTC, hmcts-version1-ignacio approved these changes

2023-08-31 11:44 UTC, LeonardoPalmeiro commented on src/main/app/client/civilServiceClient.ts
> +        .replace(':documentId', documentId)
I'm asking myself why is documentId!!
I fixed!

2023-08-31 14:24 UTC, kurt-uk approved these changes

2023-09-01 08:53 UTC, kurt-uk approved these changes

2023-09-01 09:12 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-09-01 09:37 UTC, sabahirfan approved these changes

2023-09-07 10:38 UTC, miguelMolina3691 approved these changes

2023-09-08 09:45 UTC, maciejmodzelewski requested changes

2023-09-08 09:45 UTC, maciejmodzelewski commented on src/test/unit/common/models/claim.test.ts
> +    it('should return true when is not APPLICANTSOLICITORONE', () => {
The text should have 'false' and not 'true' in it.

2023-09-08 09:50 UTC, m-meulendijks-v1 commented on src/test/unit/common/models/claim.test.ts
> +    it('should return true when is not APPLICANTSOLICITORONE', () => {
Change made

2023-09-08 09:50 UTC, maciejmodzelewski submitted a review, later dismissed

2023-09-08 09:50 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-09-08 18:06 UTC, pats-john approved these changes

2023-09-11 08:05 UTC, miguelMolina3691 submitted a review, later dismissed

2023-09-11 08:09 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-09-11 11:22 UTC, m-meulendijks-v1 approved these changes

2023-09-11 11:36 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-09-11 14:46 UTC, m-meulendijks-v1 approved these changes

2023-09-11 18:36 UTC, bhagyashreesharma90 approved these changes

2023-09-11 20:40 UTC, merged