CIV-7844 - check your answers for evidence upload
hmcts/civil-citizen-ui pull request #2131
Opened 2023-09-06 07:58 UTC by m-meulendijks-v1

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-7844

### Change description ###
Created check your answers page for evidence upload + submit functionality.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-09-06 09:24 UTC, miguelMolina3691 approved these changes

2023-09-06 09:49 UTC, maciejmodzelewski requested changes
The pipeline build failed on build step 
![image](https://github.com/hmcts/civil-citizen-ui/assets/18092228/1754277c-34c0-416f-a4a8-c6dba47c8626)

2023-09-06 09:56 UTC, miguelMolina3691 requested changes

2023-09-06 09:56 UTC, miguelMolina3691 commented on src/main/common/models/events/caseEvent.ts
> +  EVIDENCE_UPLOAD_APPLICANT = 'EVIDENCE_UPLOAD_APPLICANT'
a comma is missing here

2023-09-06 10:18 UTC, miguelMolina3691 submitted a review, later dismissed

2023-09-06 12:14 UTC, maciejmodzelewski commented on src/main/common/form/models/caseProgression/documentUploadSubmission.ts
> +  @IsNotEmpty({message: 'Tell us if you confirm the documents are correct'})
Why this message is hardcoded instead of using constants from language jsons?

2023-09-06 13:12 UTC, maciejmodzelewski commented on src/main/modules/i18n/locales/cy.json
>        "CASE_REFERENCE_NUMBER": "Case reference:",
{{ caseNumber }} variable is missing.

2023-09-06 13:21 UTC, m-meulendijks-v1 commented on src/main/modules/i18n/locales/cy.json
>        "CASE_REFERENCE_NUMBER": "Case reference:",
Add now

2023-09-06 13:21 UTC, m-meulendijks-v1 commented on src/main/common/form/models/caseProgression/documentUploadSubmission.ts
> +  @IsNotEmpty({message: 'Tell us if you confirm the documents are correct'})
Added to language jsons.

2023-09-06 14:37 UTC, miguelMolina3691 approved these changes

2023-09-06 14:44 UTC, hmcts-version1-ignacio approved these changes

2023-09-08 09:48 UTC, maciejmodzelewski approved these changes

2023-09-08 13:18 UTC, bhagyashreesharma90 approved these changes

2023-09-08 13:21 UTC, maciejmodzelewski submitted a review, later dismissed

2023-09-11 10:22 UTC, miguelMolina3691 approved these changes

2023-09-11 10:40 UTC, bhagyashreesharma90 approved these changes

2023-09-11 10:41 UTC, hmcts-version1-ignacio submitted a review, later dismissed

2023-09-13 15:36 UTC, miguel3691 approved these changes

2023-09-13 15:38 UTC, miguel3691 approved these changes

2023-09-13 15:46 UTC, miguelMolina3691 approved these changes

2023-09-13 16:06 UTC, merged