CIV-10497 Fix by a set date - accept repayment plan
hmcts/civil-citizen-ui pull request #2271
Opened 2023-10-04 13:33 UTC by portizdev

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-10497

### Change description ###
Fix different content for by a set date (FA and PA).

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-10-05 06:34 UTC, LeonardoPalmeiro approved these changes

2023-10-05 08:21 UTC, laperla11 requested changes

2023-10-05 08:21 UTC, laperla11 commented on src/main/routes/features/claimantResponse/acceptRepaymentPlanController.ts
> +    const details = await getFullAdmitSetDatePaymentDetails(claimId);
There is another call `getCaseDataFromStore` inside `getFullAdmitSetDatePaymentDetails`, so it's duplication. I believe we need to refactor `getFullAdmitSetDatePaymentDetails` by passing `claim` as a parameter so prevent duplication. Additionally `getFullAdmitSetDatePaymentDetails` doesn't provide the required proposed date for part admission scenario.
`const proposedSetDate = formatDateToFullDate(claim.fullAdmission?.paymentIntention?.paymentDate);`

2023-10-05 13:48 UTC, portizdev commented on src/main/routes/features/claimantResponse/acceptRepaymentPlanController.ts
> +    const details = await getFullAdmitSetDatePaymentDetails(claimId);
Well spotted Kadir, sorted! Missing the change tests (Rhys is in charge).

2023-10-05 16:58 UTC, laperla11 submitted a review, later dismissed

2023-10-06 08:22 UTC, kenneth-hmcts approved these changes

2023-10-10 10:18 UTC, ElifDenizEsea approved these changes

2023-10-10 10:19 UTC, rajakm approved these changes

2023-10-10 10:19 UTC, merged