Civ 1271 is your partner disabled
hmcts/civil-citizen-ui pull request #228
Opened 2022-03-17 15:13 UTC by laarmada

### JIRA link ###
https://[tools.hmcts.net](https://tools.hmcts.net/jira/browse/CIV-1271)/jira/browse/CIV-1271

### Change description ###

create view 'Is your partner disabled'

**Does this PR introduce a breaking change?** (check one with "x")

```
[ x] Yes
[ ] No
```

2022-03-17 17:05 UTC, taomoh requested changes

2022-03-17 17:05 UTC, taomoh commented on src/test/unit/routes/features/response/statementOfMeans/partner/partnerDisabilityController.test.ts
> +    test('should redirect page when "no" and haven´t statementOfMeans', async () => {
there is a special character here. You can use the backward slash `\` to escape the single quote like this: `haven\'t`
P.S. should be `doesn\'t have`

2022-03-17 17:05 UTC, taomoh commented on src/test/unit/routes/features/response/statementOfMeans/partner/partnerDisabilityController.test.ts
> +    test('should show partner page when haven´t statementOfMeans', async () => {
the same comment as above

2022-03-18 07:34 UTC, laarmada commented on src/main/modules/statementOfMeans/partner/partnerDisabilityService.ts
> +    } catch (err) {
it doesn´t file but I will add the same type as in controller

2022-03-18 07:36 UTC, laarmada commented on src/main/routes/routes.ts
> +import partnerDisability from './features/response/statementOfMeans/partner/partnerDisabilityController';
any one have controller in the name.....

2022-03-18 07:41 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/partner/partnerDisabilityController.test.ts
> +    test('should redirect page when "no" and haven´t statementOfMeans', async () => {
it´s a " ´ " no  " ' " character so doesn´t work " \´ " .....

2022-03-18 08:02 UTC, laarmada commented on src/main/views/features/response/statementOfMeans/partner/partner-disability.njk
> +          "titleText": "There was a problem",
done

2022-03-18 08:07 UTC, laarmada commented on src/main/routes/features/response/statementOfMeans/partner/partnerDisabilityController.ts
> +router.get(CITIZEN_PARTNER_DISABILITY_URL.toString(), async (req, res) => {
I do before to merge url branch and I forget to remove it... thanks!

2022-03-18 08:10 UTC, laarmada commented on src/main/routes/features/response/statementOfMeans/partner/partnerDisabilityController.ts
> +    partnerDisability.option = currentPartnerDisability.option;
currentPartnerDisability hasen´t error parameter, and the partnerDisability has an undefined error parameter to avoid view error when "getErrors".... That the reason.

2022-03-18 08:13 UTC, laarmada reviewed
Thanks @taomoh very good code review!!!

2022-03-18 09:14 UTC, taomoh commented on src/main/routes/features/response/statementOfMeans/partner/partnerDisabilityController.ts
> +    partnerDisability.option = currentPartnerDisability.option;
I'd like to discuss this. maybe during the show and tell

2022-03-18 09:20 UTC, taomoh commented on src/main/routes/features/response/statementOfMeans/partner/partnerDisabilityController.ts
> +    const validator = new Validator();
I still see the validator built inside the post function

2022-03-18 09:26 UTC, taomoh commented on src/main/routes/routes.ts
> +import partnerDisability from './features/response/statementOfMeans/partner/partnerDisabilityController';
most of the entries in the table have Route in the name, only a few are named like an entity. So I think they should be named *Route or *Controller for consistency and to reflect the nature of the object. Name of variables and constants should be descriptive and accurate

2022-03-18 09:29 UTC, taomoh commented on src/test/unit/routes/features/response/statementOfMeans/partner/partnerDisabilityController.test.ts
> +    test('should redirect page when "no" and haven´t statementOfMeans', async () => {
I think you're using a different character `´` (it's slightly bent). This is the one I meant: `'` and with this one the escape character `\'` works

2022-03-18 14:00 UTC, taomoh approved these changes
Thanks for your patience @laarmada !

2022-03-21 11:13 UTC, merged