CIV-10370 Make available Claimant Lip
hmcts/civil-citizen-ui pull request #2282
Opened 2023-10-05 14:37 UTC by miguelMolina3691

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-10370

### Change description ###
![ClaimantDocuments](https://github.com/hmcts/civil-citizen-ui/assets/93722947/7863211f-8e2c-4135-bd4e-004e4b6dd87a)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-10-06 11:17 UTC, m-meulendijks-v1 approved these changes

2023-10-06 12:42 UTC, LeonardoPalmeiro requested changes
if possible increase coverage https://sonarcloud.io/summary/new_code?id=civil-citizen-ui&pullRequest=2282
because the new methods that we're distinguish if is claimant or defendant is not being test>
![image](https://github.com/hmcts/civil-citizen-ui/assets/93268657/646f8bd9-83c9-4817-93ae-3548a89f17c3)

2023-10-06 12:44 UTC, LeonardoPalmeiro commented on src/main/routes/features/caseProgression/typeOfDocumentsController.ts
> +      const claim = await getCaseDataFromStore(claimId);
inside the **_await getDocument_**s we're getting const caseData = await getCaseDataFromStore(claimId); as well.
do we really need to fetch twice?

2023-10-06 12:46 UTC, LeonardoPalmeiro commented on src/main/routes/features/caseProgression/typeOfDocumentsController.ts
> +      await saveCaseProgression(claimId, form.model, claim.isClaimant() ? dqPropertyNameClaimant : dqPropertyName);
My suggestion in here is create a variable before then we don't need to access all the time claim.isClaimant() will be much more clear :)

2023-10-06 12:48 UTC, LeonardoPalmeiro commented on src/main/routes/features/caseProgression/uploadDocumentsController.ts
> +    const claim: Claim = await getCaseDataFromStore(claimId);
in **_await renderView(res, claimId, form)_**; we are making another call to the data base, it is really necessary ?

2023-10-06 12:52 UTC, LeonardoPalmeiro commented on src/main/services/features/caseProgression/disclosureService.ts
> +  let uploadDocuments: UploadDocuments;
my suggestion in here is
const uploadDocuments: UploadDocuments = claim.isClaimant() : claim.caseProgression?.claimantUploadDocuments ? claim.caseProgression?.defendantUploadDocuments;

2023-10-09 12:33 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-10-09 14:59 UTC, miguelMolina3691 commented on src/main/routes/features/caseProgression/typeOfDocumentsController.ts
> +      await saveCaseProgression(claimId, form.model, claim.isClaimant() ? dqPropertyNameClaimant : dqPropertyName);
Modified

2023-10-09 15:00 UTC, miguelMolina3691 commented on src/main/routes/features/caseProgression/typeOfDocumentsController.ts
> +      const claim = await getCaseDataFromStore(claimId);
Solved

2023-10-10 07:03 UTC, LeonardoPalmeiro approved these changes

2023-11-13 10:31 UTC, dharmendrak approved these changes

2023-11-13 10:33 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-11-13 10:34 UTC, m-meulendijks-v1 submitted a review, later dismissed

2023-11-17 09:42 UTC, laarmada submitted a review, later dismissed

2023-11-17 09:43 UTC, m-meulendijks-v1 approved these changes

2023-11-17 09:55 UTC, LeonardoPalmeiro approved these changes

2023-11-17 12:32 UTC, miguelMolina3691 commented on src/main/routes/features/caseProgression/documentsUploadedController.ts
> +    const claim = await civilServiceClient.retrieveClaimDetails(claimId, <AppRequest>req);
as no further code was needed, I thought I didn't need to create a service to call the client, in other controllers it is done in the same way

2023-11-22 11:42 UTC, dharmendrak approved these changes

2023-11-22 11:44 UTC, m-meulendijks-v1 approved these changes

2023-11-22 17:54 UTC, merged