CIV-10830 fix bug
hmcts/civil-citizen-ui pull request #2303
Opened 2023-10-10 07:53 UTC by laarmada

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-10830

### Change description ###

fix bug in the cancel button

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-10 07:57 UTC, LeonardoPalmeiro requested changes

2023-10-10 07:57 UTC, LeonardoPalmeiro commented on src/main/routes/features/caseProgression/typeOfDocumentsController.ts
> +export function cancelDoc() {
do we need to use this?

2023-10-10 08:24 UTC, dharmendrak approved these changes

2023-10-10 08:38 UTC, laarmada commented on src/main/routes/features/caseProgression/typeOfDocumentsController.ts
> +export function cancelDoc() {
removed

2023-10-11 13:41 UTC, portizdev approved these changes

2023-10-18 18:34 UTC, merged