CIV-9023 Claimant Intent: CCJ after Part Admit or Full Admit Pay Immediately - Submit Function
hmcts/civil-citizen-ui pull request #2304
Opened 2023-10-10 08:02 UTC by jeswanth-hmcts

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-9023

### Change description ###

Claimant Intent: CCJ after Part Admit or Full Admit Pay Immediately - Submit Function

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-10 14:03 UTC, laarmada requested changes
please improve the coverage:
![image](https://github.com/hmcts/civil-citizen-ui/assets/23473639/c5f0ed5b-abb0-47b1-98e2-db54d366835e)

2023-10-10 14:03 UTC, laarmada commented on src/main/services/translation/convertToCUI/cuiTranslation.ts
> +    interest.interestStartDate = new InterestStartDate((ccdInterestDate.getDay() + 1).toString(), (ccdInterestDate.getMonth() + 1).toString(), ccdInterestDate.getFullYear().toString(), ccdClaim.inter
to avoid errors maybe we need ? here: ccdClaim.interestFromSpecificDateDescription

2023-10-10 14:07 UTC, jeswanth-hmcts commented on src/main/services/translation/convertToCUI/cuiTranslation.ts
> +    interest.interestStartDate = new InterestStartDate((ccdInterestDate.getDay() + 1).toString(), (ccdInterestDate.getMonth() + 1).toString(), ccdInterestDate.getFullYear().toString(), ccdClaim.inter
To avoid error if condition is added like  **if (ccdClaim?.interestFromSpecificDate)**

2023-10-10 15:51 UTC, jeswanth-hmcts commented on src/main/services/translation/convertToCUI/cuiTranslation.ts
> +    interest.interestStartDate = new InterestStartDate((ccdInterestDate.getDay() + 1).toString(), (ccdInterestDate.getMonth() + 1).toString(), ccdInterestDate.getFullYear().toString(), ccdClaim.inter
also added a few more scenarios to the unit test increased to 89% 
![image](https://github.com/hmcts/civil-citizen-ui/assets/134285996/bdcb70c3-b49d-44a9-acb1-598666a78762)

2023-10-10 16:25 UTC, neeta-hmcts approved these changes

2023-10-31 11:58 UTC, neeta-hmcts approved these changes

2023-10-31 11:59 UTC, rajakm approved these changes

2023-10-31 11:59 UTC, merged