CIV-10903 claim fee and timeline added
hmcts/civil-citizen-ui pull request #2305
Opened 2023-10-10 12:00 UTC by ElifDenizEsea

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-10903

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-10 13:39 UTC, TatsyMaslova submitted a review, later dismissed

2023-10-10 13:54 UTC, laarmada requested changes

2023-10-10 13:54 UTC, laarmada commented on src/main/common/models/ccdResponse/ccdClaimFee.ts
> +  if (!claimFee || !claimFee.calculatedAmountInPence) return undefined;
I think you can use; !claimFee?.calculatedAmountInPence instead of  !claimFee || !claimFee.calculatedAmountInPence with question mark

2023-10-10 13:54 UTC, laarmada commented on src/main/common/models/ccdResponse/ccdClaimFee.ts
> +    calculatedAmountInPence: claimFee.calculatedAmountInPence.toString(),
why use toString if the vble is string?

2023-10-10 13:54 UTC, laarmada commented on src/main/common/models/civilClaimResponse.ts
> +  timelineOfEvents?:CCDTimeLineOfEvent[];
If Im not wrong we are near to have a problem 160vbles and I think the maximun is 254????

2023-10-10 14:04 UTC, laarmada commented
please have a look the code smell and the coverage:
![image](https://github.com/hmcts/civil-citizen-ui/assets/23473639/c7fd3100-75b1-4c47-88a7-ade75d7daa2f)

2023-10-10 14:24 UTC, ElifDenizEsea commented on src/main/common/models/civilClaimResponse.ts
> +  timelineOfEvents?:CCDTimeLineOfEvent[];
these fields are already defined on casedata, we just added them to translation logic

2023-10-10 14:26 UTC, ElifDenizEsea commented on src/main/common/models/ccdResponse/ccdClaimFee.ts
> +    calculatedAmountInPence: claimFee.calculatedAmountInPence.toString(),
the one on claim is number, the one on ccdclaim is string

2023-10-10 14:26 UTC, ElifDenizEsea commented on src/main/common/models/ccdResponse/ccdClaimFee.ts
> +  if (!claimFee || !claimFee.calculatedAmountInPence) return undefined;
done

2023-10-10 15:55 UTC, neeta-hmcts submitted a review, later dismissed

2023-10-11 08:13 UTC, laarmada commented on src/main/common/models/civilClaimResponse.ts
> +  timelineOfEvents?:CCDTimeLineOfEvent[];
yes I know but we need to take care of it....

2023-10-11 13:31 UTC, laarmada submitted a review, later dismissed

2023-10-11 13:52 UTC, laperla11 approved these changes

2023-10-23 12:40 UTC, jarekPierchala requested changes

2023-10-23 12:40 UTC, jarekPierchala commented on src/main/routes/features/claim/totalAmountController.ts
> +    await saveClaimFee(userId,claimFee);
Should this be behind f2 flag?

2023-10-23 12:40 UTC, jarekPierchala commented on src/main/services/translation/claim/ccdTranslation.ts
> -    // specResponseTimelineOfEvents: toCCDTimeline(claim.claimDetails?.timeline),
So we overriding the R1 behaviour here? Should this be behind f2 flag?

2023-10-23 13:26 UTC, ElifDenizEsea commented on src/main/routes/features/claim/totalAmountController.ts
> +    await saveClaimFee(userId,claimFee);
done

2023-10-23 13:26 UTC, ElifDenizEsea commented on src/main/services/translation/claim/ccdTranslation.ts
> -    // specResponseTimelineOfEvents: toCCDTimeline(claim.claimDetails?.timeline),
done

2023-10-23 13:32 UTC, jarekPierchala approved these changes

2023-10-24 08:12 UTC, laarmada approved these changes

2023-10-24 08:20 UTC, kenneth-hmcts approved these changes

2023-10-24 09:07 UTC, merged