CIV-9112 RPA for Mediation in Lip Claimant Response
hmcts/civil-citizen-ui pull request #2328
Opened 2023-10-12 09:37 UTC by kenneth-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9112

### Change description ###
Set Up RPA for Lip Claimant Response

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-10-30 13:40 UTC, neeta-hmcts submitted a review, later dismissed

2023-10-30 13:41 UTC, neeta-hmcts reviewed
plz verify this flow locally too.. as many changes are merged for task list since this ticket is created,

2023-10-30 13:55 UTC, jarekPierchala requested changes

2023-10-30 13:55 UTC, jarekPierchala commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
> +  if (claim?.claimantResponse?.hasPartPaymentBeenAccepted?.option === YesNo.NO && claim.isFullDefence() && claim.responseStatus === ClaimResponseStatus.RC_PAID_FULL) {
please put that condition to separate func

2023-10-30 13:55 UTC, jarekPierchala commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistService.ts
> +  if(claim.isPartialAdmissionNotPaid() || (claim.isFullDefence() && (claim.isRejectAllOfClaimDispute() || claim.responseStatus === ClaimResponseStatus.RC_PAID_FULL)) || claim.isFullAdmission()) {
condition to separate function please

2023-10-30 13:55 UTC, jarekPierchala commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistService.ts
> +  if(claim.isPartialAdmissionPaid() || (claim.isFullDefence() && !claim.isRejectAllOfClaimDispute() && claim.responseStatus === ClaimResponseStatus.RC_PAID_LESS))
same here

2023-11-02 14:17 UTC, kenneth-hmcts commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
> +  if (claim?.claimantResponse?.hasPartPaymentBeenAccepted?.option === YesNo.NO && claim.isFullDefence() && claim.responseStatus === ClaimResponseStatus.RC_PAID_FULL) {
Changes made

2023-11-02 14:17 UTC, kenneth-hmcts commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistService.ts
> +  if(claim.isPartialAdmissionNotPaid() || (claim.isFullDefence() && (claim.isRejectAllOfClaimDispute() || claim.responseStatus === ClaimResponseStatus.RC_PAID_FULL)) || claim.isFullAdmission()) {
Changes made

2023-11-02 14:17 UTC, kenneth-hmcts commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistService.ts
> +  if(claim.isPartialAdmissionPaid() || (claim.isFullDefence() && !claim.isRejectAllOfClaimDispute() && claim.responseStatus === ClaimResponseStatus.RC_PAID_LESS))
Changes made

2023-11-02 17:00 UTC, jarekPierchala approved these changes

2023-11-06 09:21 UTC, ElifDenizEsea approved these changes

2023-11-06 09:22 UTC, kalachandrasekar1 approved these changes

2023-11-06 09:24 UTC, neeta-hmcts approved these changes

2023-11-06 09:25 UTC, jeswanth-hmcts approved these changes

2023-11-13 03:02 UTC, closed without merging