CIV-10634 Added message for claimant reject confirmation
hmcts/civil-citizen-ui pull request #2337
Opened 2023-10-16 10:43 UTC by manish14836

Please remove this line and everything above and fill the following sections:

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-10634

### Change description ###

Claimant Intent – Confirmation screen - Rejected the response + NO MEDIATION

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-16 11:54 UTC, TatsyMaslova commented on src/main/common/models/civilClaimResponse.ts
> +  applicant1PartAdmitConfirmAmountPaidSpec?: YesNoUpperCamelCase;
perhaps we should have a claimantPartAdmit model and have those fields in partAdmit? we should not copy what is there in civil service as the model there is not the best. 😉

2023-10-16 11:55 UTC, TatsyMaslova commented on src/main/common/models/civilClaimResponse.ts
> +  applicant1PartAdmitConfirmAmountPaidSpec?: YesNoUpperCamelCase;
also we should not have spec postifxes in our fields because we don't have the concept of spec and unspec claim in cui

2023-10-17 09:11 UTC, manish14836 commented on src/main/common/models/civilClaimResponse.ts
> +  applicant1PartAdmitConfirmAmountPaidSpec?: YesNoUpperCamelCase;
As discussed with Tanya and Neeta, this is ccd civil service model which should have same name. Moved new to ClaimantUpdate model as  CCDClaim is growing

2023-10-17 15:15 UTC, laarmada requested changes
Please you can improve the coverage including some unit test more...

2023-10-17 15:15 UTC, laarmada commented on src/main/common/models/claimantResponse/ccdClaimantResponse.ts
> -import {CCDExpert} from 'models/ccdResponse/ccdExpert';
please change your ide check style in order to avoid wrong file changes.....

2023-10-17 15:15 UTC, laarmada commented on src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
> +import { ClaimResponseStatus } from 'common/models/claimResponseStatus';
same here, spaces ....

2023-10-17 15:15 UTC, laarmada commented on src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
> +    if ((claim.isFullDefence() && claim.hasClaimantRejectedDefendantPaid()) || claim.responseStatus === ClaimResponseStatus.PA_NOT_PAID_NOT_ACCEPTED || claim.responseStatus === ClaimResponseStatus.PA
please review this if condition is longer than expected and it's so hard to understand.....

2023-10-18 09:16 UTC, laarmada requested changes

2023-10-18 09:16 UTC, laarmada commented on src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
> +    } else if (claim.responseStatus === ClaimResponseStatus.PA_NOT_PAID_NOT_ACCEPTED || claim.responseStatus === ClaimResponseStatus.PA_ALREADY_PAID_NOT_ACCEPTED
this if condition is not easy to understand, could we extract to a simples functions?

2023-10-19 14:07 UTC, laarmada approved these changes

2023-10-19 14:09 UTC, laarmada commented on src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
> +    if ((claim.isFullDefence() && claim.hasClaimantRejectedDefendantPaid()) || claim.responseStatus === ClaimResponseStatus.PA_NOT_PAID_NOT_ACCEPTED || claim.responseStatus === ClaimResponseStatus.PA
is pending yet

2023-10-19 14:10 UTC, laarmada requested changes
2 comments pending

2023-10-19 14:20 UTC, laarmada submitted a review, later dismissed

2023-10-19 14:26 UTC, kenneth-hmcts submitted a review, later dismissed

2023-10-19 14:27 UTC, paul-pearson requested changes

2023-10-19 14:27 UTC, paul-pearson commented on src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
> +      await deleteDraftClaimFromStore(req.params.id);
As discussed, we should probably not delete the draft claim at this point because we need it on the confirmation screen.

2023-10-19 14:29 UTC, paul-pearson submitted a review, later dismissed

2023-10-19 14:30 UTC, neeta-hmcts commented on src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
> +      await deleteDraftClaimFromStore(req.params.id);
done.

2023-10-19 14:31 UTC, kenneth-hmcts approved these changes

2023-10-20 07:45 UTC, laarmada approved these changes

2023-10-20 08:11 UTC, paul-pearson approved these changes

2023-10-24 14:08 UTC, laarmada approved these changes

2023-10-27 15:11 UTC, laarmada requested changes

2023-10-27 15:11 UTC, laarmada commented on src/main/common/models/claimantResponse.ts
> +  get isClaimantIntendedToProceed(): boolean {
please have a look line 48......

2023-10-30 10:12 UTC, laarmada requested changes

2023-10-30 10:12 UTC, laarmada commented on src/main/common/models/claimantResponse.ts
> +  get isClaimantIntendedToProceed(): boolean {
we are duplicating function unnecessary no?
<img width="532" alt="image" src="https://github.com/hmcts/civil-citizen-ui/assets/23473639/b5e452af-4880-4f8d-8b76-8538195f174a">

2023-10-30 10:12 UTC, laarmada commented on src/main/common/models/claimantResponse.ts
> +  get isClaimantIntendedToProceed(): boolean {
we can use only one and cover 2 cases no?????

2023-10-30 10:13 UTC, laarmada requested changes

2023-10-30 10:13 UTC, laarmada commented on src/main/common/models/claimantResponse/ccdClaimantResponse.ts
> +export interface CCDClaimantResponse extends ClaimUpdate {
remove the space, please

2023-10-30 10:46 UTC, laarmada approved these changes

2023-10-30 11:16 UTC, paul-pearson submitted a review, later dismissed

2023-11-01 12:18 UTC, jeswanth-hmcts approved these changes

2023-11-01 12:18 UTC, neeta-hmcts approved these changes

2023-11-01 12:20 UTC, paul-pearson approved these changes

2023-11-02 12:28 UTC, merged