CIV-8785 -Claimant Intent – Confirmation Screen - County Court Judgment requested (Accept plan)
hmcts/civil-citizen-ui pull request #2342
Opened 2023-10-16 16:12 UTC by neeta-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-8785

### Change description ###
Added a code changes to enable confirmation page for following Scenario

Defendant response - Full/Part admit (Pay be set date or Instalment)
Claimant - accepts repayment plan and Request for CCJ

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-17 13:45 UTC, laarmada approved these changes

2023-10-18 08:16 UTC, ElifDenizEsea approved these changes

2023-10-18 08:16 UTC, jeswanth-hmcts commented on src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
> +function toCCDChoosesHowToProceed(option: ChooseHowProceed | undefined) {
Instead of switch statement  both key and value are known constants, so we can create an enum toCCDChoosesHowToProceed ={ 'SIGN_A_SETTLEMENT_AGREEMENT':CCDChoosesHowToProceed.SIGN_A_SETTLEMENT_AGREEMENT}and toCCDChoosesHowToProceed[option] can be selected the valve  based on the option we passed

2023-10-18 08:16 UTC, jeswanth-hmcts commented on src/main/services/translation/convertToCUI/convertToCUICCJRequest.ts
> +export const toCUIChoosesHowToProceed = (option: CCDChoosesHowToProceed) : ChooseHowProceed => {
same here

2023-10-18 08:26 UTC, laarmada requested changes

2023-10-18 08:26 UTC, laarmada commented on src/main/services/translation/convertToCUI/cuiTranslation.ts
> +  claim.claimantResponse.chooseHowToProceed.option = toCUIChoosesHowToProceed(ccdClaim?.applicant1LiPResponse?.applicant1ChoosesHowToProceed);
make the same for ccdClaim --> const claim: Claim = Object.assign(new Claim(), ccdClaim); and you can save every ? in the ccdClaim?.

2023-10-18 08:27 UTC, neeta-hmcts commented on src/main/services/translation/convertToCUI/cuiTranslation.ts
> +  claim.claimantResponse.chooseHowToProceed.option = toCUIChoosesHowToProceed(ccdClaim?.applicant1LiPResponse?.applicant1ChoosesHowToProceed);
Yes.. sure.

2023-10-18 08:41 UTC, laarmada submitted a review, later dismissed

2023-10-18 10:27 UTC, neeta-hmcts commented on src/main/services/translation/convertToCUI/convertToCUICCJRequest.ts
> +export const toCUIChoosesHowToProceed = (option: CCDChoosesHowToProceed) : ChooseHowProceed => {
fixed.

2023-10-18 10:27 UTC, neeta-hmcts commented on src/main/services/translation/convertToCUI/cuiTranslation.ts
> +  claim.claimantResponse.chooseHowToProceed.option = toCUIChoosesHowToProceed(ccdClaim?.applicant1LiPResponse?.applicant1ChoosesHowToProceed);
done

2023-10-18 10:32 UTC, jeswanth-hmcts submitted a review, later dismissed

2023-10-18 10:47 UTC, laarmada approved these changes

2023-11-03 14:34 UTC, ElifDenizEsea submitted a review, later dismissed

2023-11-03 14:36 UTC, kalachandrasekar1 submitted a review, later dismissed

2023-11-03 14:58 UTC, portizdev commented on src/main/common/models/claim.ts
> +  isClaimantAcceptPaymentPlan() {
I think it would be a good idea to create a service for all things related to the claimant's response to avoid making the claim.ts file even bigger. 

Now that we are starting to add methods it is a good idea. Jeswanth has implemented it in a few places.

2023-11-03 16:02 UTC, neeta-hmcts commented on src/main/common/models/claim.ts
> +  isClaimantAcceptPaymentPlan() {
yes.. agree moved this  method to claimantResponse.ts

2023-11-07 07:08 UTC, laarmada approved these changes
minor comment

2023-11-07 07:08 UTC, laarmada commented on src/main/services/translation/convertToCUI/cuiTranslation.ts
> +  claim.interest = claim?.interest ? claim?.interest : translateCCDInterestDetailsToCUI(ccdClaim);
claim? ---> this ? is not necessary we always return a claim object

2023-11-07 09:05 UTC, manish14836 approved these changes

2023-11-07 09:50 UTC, neeta-hmcts commented on src/main/services/translation/convertToCUI/cuiTranslation.ts
> +  claim.interest = claim?.interest ? claim?.interest : translateCCDInterestDetailsToCUI(ccdClaim);
oh.. yes.. I will update in my ongoing review. Thank you.

2023-11-24 17:36 UTC, merged