CIV-10916 Claimant Intent – Check your Answers: How do you wish to pr…
hmcts/civil-citizen-ui pull request #2348
Opened 2023-10-17 10:01 UTC by ElifDenizEsea

…oceed

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-10916

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-17 10:24 UTC, jarekPierchala approved these changes

2023-10-17 10:28 UTC, laarmada submitted a review, later dismissed
minor comment

2023-10-17 10:28 UTC, laarmada commented on src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
> +  const selectedOption = claim?.claimantResponse?.chooseHowToProceed?.option;
you can remove the ? here in claim? always we will return a claim

2023-10-17 10:44 UTC, laarmada approved these changes

2023-10-17 12:27 UTC, portizdev approved these changes

2023-10-27 15:16 UTC, laarmada requested changes

2023-10-27 15:16 UTC, laarmada commented on src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
> +    return claim.isFullDefence() || claim.isPartialAdmission() || claim.isFullAdmission()
which more options we have? ..... you are covering the 3 existing options right?

2023-10-31 08:57 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
> +    return claim.isFullDefence() || claim.isPartialAdmission() || claim.isFullAdmission()
I added parts for full admission. and it is covering

2023-10-31 11:01 UTC, laarmada submitted a review, later dismissed

2023-10-31 15:32 UTC, laarmada submitted a review, later dismissed

2023-10-31 16:47 UTC, jeswanth-hmcts submitted a review, later dismissed

2023-11-13 09:19 UTC, closed without merging