Civ 1270 does your partner receive a pension
hmcts/civil-citizen-ui pull request #237
Opened 2022-03-21 21:45 UTC by laarmada

### JIRA link ###
https://[tools.hmcts.net](https://tools.hmcts.net/jira/browse/CIV-1270)/jira/browse/CIV-1270

### Change description ###

create a view "does your partner receive a pension?"

**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[ ] No
```

2022-03-23 09:00 UTC, LeonardoPalmeiro requested changes

2022-03-23 09:00 UTC, LeonardoPalmeiro commented on src/main/modules/statementOfMeans/partner/partnerPensionService.ts
> +      logger.error(`${err as Error || err}`);
should add   ` res.status(500).send({error: error.message});` to achieve 100% of coverage on test

2022-03-23 09:00 UTC, LeonardoPalmeiro commented on src/main/modules/statementOfMeans/partner/partnerPensionService.ts
> +      logger.error(`${err as Error || err}`);
should add   ` res.status(500).send({error: error.message});` to achieve 100% of coverage on test

2022-03-23 13:06 UTC, laarmada commented on src/main/routes/features/response/statementOfMeans/partner/partnerPensionController.ts
> +        logger.error(`${err as Error || err}`);
done

2022-03-23 13:06 UTC, laarmada commented on src/main/routes/features/response/statementOfMeans/partner/partnerPensionController.ts
> +  }
done

2022-03-23 13:10 UTC, laarmada commented on src/main/modules/statementOfMeans/partner/partnerPensionService.ts
> +      logger.error(`${err as Error || err}`);
done

2022-03-23 14:05 UTC, GorilaNaranja commented on package.json
> +    "**/sass-lint/**/minimist": "^1.2.5",
Why did you update that module? I think Mounika fixed the problem on master upgrading minimist to 1.2.6

2022-03-24 15:14 UTC, GorilaNaranja approved these changes
Nice work!

2022-03-29 08:00 UTC, merged