Civ 8026 respond to settlement agreement screen
hmcts/civil-citizen-ui pull request #2373
Opened 2023-10-20 16:16 UTC by paul-pearson

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-8026

### Change description ###

Implement respond to settlement agreement screen

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-25 08:42 UTC, jarekPierchala submitted a review, later dismissed

2023-10-27 13:45 UTC, jarekPierchala requested changes

2023-10-27 13:45 UTC, jarekPierchala commented on src/main/common/utils/repaymentUtils.ts
> +  if (claim.isFullAdmission()) {
```suggestion
  return claim.isFullAdmission() ? claim.fullAdmission?.paymentIntention?.paymentOption : claim.partialAdmission?.paymentIntention?.paymentOption
```

2023-10-27 14:54 UTC, manish14836 commented on src/main/common/utils/repaymentUtils.ts
> +  if (claim.isFullAdmission()) {
Updated as suggested

2023-10-27 14:56 UTC, jarekPierchala submitted a review, later dismissed

2023-10-27 15:01 UTC, laarmada requested changes

2023-10-27 15:01 UTC, laarmada commented on src/main/views/features/settlementAgreement/respond-settlement-agreement.njk
> +{% if data.paymentOption === PaymentOptionType.BY_SET_DATE %}
the most part of that logic should be done in the controller/service side...... not here, because is so hard to debug and understand.

2023-10-30 09:22 UTC, paul-pearson commented on src/main/routes/features/settlementAgreement/respondSettlementAgreementController.ts
> +      res.redirect(constructResponseUrlWithIdParams(claimId, '<Next page>>'));
That's correct, there is no AC on the ticket stating the correct behaviour for when the form is submitted.  The ticket is only about rendering this page correctly. If it is required to redirect to a particular page on submission then there needs to be an Acceptance Criterion on the ticket for this.

2023-10-30 09:23 UTC, paul-pearson commented on src/main/routes/features/settlementAgreement/respondSettlementAgreementController.ts
> +      // TODO : Save respondSettlementAgreement.model.option value and redirect to next page
As above.  This ticket is for rendering the page correctly.  Any additional requirements should be captured as ACs on the ticket.

2023-10-30 09:23 UTC, paul-pearson commented on src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementController.test.ts
> +          // TODO: Add expectations when save has been implemented
As above.

2023-10-30 09:28 UTC, paul-pearson commented on src/main/views/features/settlementAgreement/respond-settlement-agreement.njk
> +{% if data.paymentOption === PaymentOptionType.BY_SET_DATE %}
The logic is handled in the template because this is how it has already been implemented for claimant sign settlement agreement page, which has already been developed and reviewed, and we should be consistent with that.  I agree this would have been done better handling the logic in the controller but if a refactor is required then this should be done in the existing page as well.

2023-10-30 09:32 UTC, laarmada commented on src/main/routes/features/settlementAgreement/respondSettlementAgreementController.ts
> +      res.redirect(constructResponseUrlWithIdParams(claimId, '<Next page>>'));
ok, no probs

2023-10-30 09:33 UTC, laarmada commented on src/main/routes/features/settlementAgreement/respondSettlementAgreementController.ts
> +      // TODO : Save respondSettlementAgreement.model.option value and redirect to next page
the translation is never added in the AC... we need to remark that on the refinement sessions

2023-10-30 09:33 UTC, laarmada commented on src/main/views/features/settlementAgreement/respond-settlement-agreement.njk
> +{% if data.paymentOption === PaymentOptionType.BY_SET_DATE %}
ok understand

2023-10-30 09:34 UTC, laarmada approved these changes

2023-10-31 15:40 UTC, laarmada approved these changes

2023-10-31 15:43 UTC, neeta-hmcts approved these changes

2023-10-31 16:52 UTC, jarekPierchala submitted a review, later dismissed

2023-11-01 11:27 UTC, laarmada submitted a review, later dismissed

2023-11-01 11:35 UTC, manish14836 submitted a review, later dismissed

2023-11-01 11:43 UTC, neeta-hmcts approved these changes

2023-11-01 11:48 UTC, kalachandrasekar1 submitted a review, later dismissed

2023-11-16 15:22 UTC, jarekPierchala commented
Will be part of post-case-progression-tasks branch

2023-11-16 15:22 UTC, closed without merging