Feature/civ 1471 create to get information from redis
hmcts/civil-citizen-ui pull request #238
Opened 2022-03-21 21:56 UTC by LeonardoPalmeiro

### JIRA link ###

CIV-1471

### Change description ###
Added the call to Redis in screens that didn't have.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-03-22 11:44 UTC, osheaf01 commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +    res.redirect(constructResponseUrlWithIdParams(req.params.id,DOB_URL));
Nitpicking, but space between the 2 parameters in () ?

2022-03-22 11:46 UTC, osheaf01 commented on src/main/routes/features/response/citizenDob/citizenDobController.ts
> +      citizenDob.month = (dateOfBirth.getMonth() + 1);
Why the +1?

2022-03-22 11:47 UTC, osheaf01 commented on src/main/routes/features/response/citizenPhoneNumber/citizenPhoneController.ts
> +    const citizenTelephoneNumber = !(responseDataRedis && responseDataRedis.respondent1.telephoneNumber) ? new CitizenTelephoneNumber() : new CitizenTelephoneNumber(responseDataRedis.respondent1.tele
Indent this? Line is too long, have to scroll over...

2022-03-22 11:49 UTC, osheaf01 commented on src/main/routes/features/response/citizenPhoneNumber/citizenPhoneController.ts
> +        const claim = await getCaseDataFromStore(req.params.id) || new Claim();
FMI, when does it instantiate a new Claim()? If it returns null, or times out?

2022-03-22 11:52 UTC, sampankumar commented on src/main/routes/features/response/responseType/citizenResponseType.ts
> +    if (responseDataRedis && responseDataRedis.respondent1.responseType) {
Might want to add `responseDataRedis.respondent1` in the condition

2022-03-22 12:03 UTC, osheaf01 approved these changes
LGTM

2022-03-22 12:15 UTC, laarmada requested changes
minor changes.

2022-03-22 12:15 UTC, laarmada commented on src/main/routes/features/response/citizenDob/citizenDobController.ts
> +    const validator = new Validator();
we can move above the class to avoid new instance in each post call...

2022-03-22 12:15 UTC, laarmada commented on src/main/routes/features/response/citizenPhoneNumber/citizenPhoneController.ts
> +      const validator = new Validator();
move to above....

2022-03-22 12:15 UTC, laarmada commented on src/main/routes/features/response/responseType/citizenResponseType.ts
> +      const validator = new Validator();
move to above...

2022-03-22 15:23 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +    res.redirect(constructResponseUrlWithIdParams(req.params.id,DOB_URL));
done :) thanks

2022-03-22 15:27 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenDob/citizenDobController.ts
> +      citizenDob.month = (dateOfBirth.getMonth() + 1);
https://www.w3schools.com/js/js_date_methods.asp
In JavaScript month is an array so start with 0 if I want to get correct information I need to add +1 .

2022-03-22 15:29 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenPhoneNumber/citizenPhoneController.ts
> +    const citizenTelephoneNumber = !(responseDataRedis && responseDataRedis.respondent1.telephoneNumber) ? new CitizenTelephoneNumber() : new CitizenTelephoneNumber(responseDataRedis.respondent1.tele
done!
I agree with you :)

2022-03-22 15:34 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenPhoneNumber/citizenPhoneController.ts
> +        const claim = await getCaseDataFromStore(req.params.id) || new Claim();
yes I used when getCaseDataFromStore is null/undefined.
Basically to set a default value 
I did find a good page to explain when use or not.
https://stackoverflow.com/questions/2802055/what-does-the-construct-x-x-y-mean

2022-03-22 15:35 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/responseType/citizenResponseType.ts
> +    if (responseDataRedis && responseDataRedis.respondent1.responseType) {
you're right..
Thanks

2022-03-23 08:33 UTC, laarmada reviewed
ok

2022-03-23 08:34 UTC, laarmada approved these changes

2022-03-23 08:36 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenDob/citizenDobController.ts
> +    const validator = new Validator();
done

2022-03-23 08:36 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/citizenPhoneNumber/citizenPhoneController.ts
> +      const validator = new Validator();
done.
Thanks :)

2022-03-23 10:50 UTC, GorilaNaranja approved these changes

2022-03-23 16:18 UTC, merged