Merge pull request #2298 from hmcts/CIV-10849-dashboard-design-structure
hmcts/civil-citizen-ui pull request #2381
Opened 2023-10-23 11:50 UTC by LeonardoPalmeiro

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-10849

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-23 12:23 UTC, jarekPierchala requested changes
impacts R1 - should we expect that?

2023-10-24 11:43 UTC, LeonardoPalmeiro commented
> impacts R1 - should we expect that?

It won't mess with R1, but it'll mess with the release 2 tickets. Keep in mind that the first version is just placeholders, and there's no actual functionality in there, so responding to claims, for example, won't work.

For your peace of mind, we've created a branch called "dashboard_dev," and you can rest assured that it won't disrupt any aspect of the CUI.

2023-10-24 13:20 UTC, maciejmodzelewski commented on src/main/common/models/taskList/TaskStatus.ts
> +  [TaskStatus.COMPLETE]: '',
What is the colour for this task status?

2023-10-24 13:20 UTC, maciejmodzelewski commented on src/main/modules/i18n/locales/cy.json
> +      "DONE": "DONE",
Why this particular entry is capitalised?

2023-10-24 13:20 UTC, maciejmodzelewski commented on src/main/modules/i18n/locales/en.json
> +      "DONE": "DONE",
Why this particular entry is capitalised?

2023-10-24 13:23 UTC, LeonardoPalmeiro commented on src/main/common/models/taskList/TaskStatus.ts
> +  [TaskStatus.COMPLETE]: '',
without specific colour as I told this is just a place holder and this code had been merged to master then revert because broke all CUI Release 2 tests.

2023-10-24 13:29 UTC, maciejmodzelewski commented on src/main/common/models/taskList/TaskStatus.ts
> +  [TaskStatus.COMPLETE]: '',
But if it doesn't have any specific colour assigned then is there some default colour that will be applied or the code is going to break when this status is used?

2023-10-24 13:33 UTC, GorilaNaranja commented on src/main/common/models/taskList/TaskStatus.ts
> +  [TaskStatus.COMPLETE]: '',
If we don't specify a color it will use the default color of the tag component, and the default color is the correct one for this status.

2023-10-24 13:34 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/cy.json
> +      "DONE": "DONE",
Good point, my bad. It should be "Done"

2023-10-24 13:34 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/en.json
> +      "DONE": "DONE",
Good point, my bad. It should be "Done"

2023-10-24 13:54 UTC, maciejmodzelewski approved these changes

2023-10-30 13:36 UTC, merged