CIV-11181 CCJ Navigation
hmcts/civil-citizen-ui pull request #2385
Opened 2023-10-24 09:20 UTC by portizdev

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-11181

### Change description ###
Fix for redirection bug in CCJ flows by creating a new controller to differentiate flow 'county-court-judgement' and 'ccj' in paid amount summary screen

- county-court-judgement : redirects to claimant response task-list
- ccj: redirects to payment options

Fix tests

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-10-24 10:10 UTC, neeta-hmcts approved these changes

2023-10-24 10:17 UTC, laarmada approved these changes
minor comment

2023-10-24 10:17 UTC, laarmada commented on src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.ts
> +    const claimFee = await civilServiceClient.getClaimAmountFee(claim?.totalClaimAmount, req);
this ? in claim?. is not necessary we always return a claim

2023-10-24 10:17 UTC, kenneth-hmcts submitted a review, later dismissed

2023-10-24 10:18 UTC, laarmada requested changes
you have a important sonar problems:
https://sonarcloud.io/summary/new_code?id=civil-citizen-ui&pullRequest=2385

2023-10-24 11:24 UTC, portizdev commented on src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.ts
> +    const claimFee = await civilServiceClient.getClaimAmountFee(claim?.totalClaimAmount, req);
Done

2023-10-24 11:30 UTC, laarmada approved these changes

2023-10-27 10:34 UTC, kenneth-hmcts approved these changes

2023-10-27 10:34 UTC, ElifDenizEsea approved these changes

2023-10-27 10:36 UTC, merged