CIV-10893 - Court Calculator Trigger and Navigation
hmcts/civil-citizen-ui pull request #2391
Opened 2023-10-24 14:38 UTC by neeta-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-10893

### Change description ###
Integrated the courtDecision API and based upon calculated decision user will navigate to the respective screens.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-25 06:35 UTC, LeonardoPalmeiro approved these changes

2023-10-25 15:31 UTC, jeswanth-hmcts submitted a review, later dismissed

2023-11-01 15:51 UTC, kenneth-hmcts approved these changes

2023-11-01 15:54 UTC, jarekPierchala requested changes

2023-11-01 15:54 UTC, jarekPierchala commented on src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/availabilityDates.js
>  const newDate = new Date(new Date().setMonth(new Date().getMonth()+2));
+2 twice?

2023-11-01 15:54 UTC, jarekPierchala commented on src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/availabilityDates.js
>  const newDate = new Date(new Date().setMonth(new Date().getMonth()+2));
const newDate =new Date(new Date().setMonth(new Date().getMonth()+2));
and 
const month = newDate.getMonth()+2;

2023-11-01 15:57 UTC, neeta-hmcts commented on src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/availabilityDates.js
>  const newDate = new Date(new Date().setMonth(new Date().getMonth()+2));
just a temporary changes for FT fix. Later Raja will add a proper fix.

2023-11-01 16:03 UTC, jeswanth-hmcts commented on src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/availabilityDates.js
>  const newDate = new Date(new Date().setMonth(new Date().getMonth()+2));
can't we use this method  existing method for adding months src\main\common\utils\dateUtils.ts   addMonths

2023-11-01 16:16 UTC, neeta-hmcts commented on src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/availabilityDates.js
>  const newDate = new Date(new Date().setMonth(new Date().getMonth()+2));
> can't we use existing method for adding months src\main\common\utils\dateUtils.ts addMonths

ok sure.. I will ask raja to check this while implementing proper fix.

2023-11-01 16:34 UTC, neeta-hmcts commented on src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/availabilityDates.js
>  const newDate = new Date(new Date().setMonth(new Date().getMonth()+2));
Thanks Jeswanth for adding the fix.

2023-11-01 17:07 UTC, jeswanth-hmcts submitted a review, later dismissed

2023-11-02 09:09 UTC, jarekPierchala requested changes

2023-11-02 09:09 UTC, jarekPierchala commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +  if ((claim.respondent1.type === 'ORGANISATION' || claim.respondent1.type === 'COMPANY')
`claim.respondent1.type === 'ORGANISATION' || claim.respondent1.type === 'COMPANY')
     || claim.claimantResponse?.suggestedPaymentIntention?.paymentOption !== undefined`
     
     To separate method please

2023-11-02 09:09 UTC, laarmada approved these changes

2023-11-02 09:21 UTC, jarekPierchala approved these changes

2023-11-02 09:54 UTC, laarmada commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +  if ((claim.respondent1.type === 'ORGANISATION' || claim.respondent1.type === 'COMPANY')
you can use existing function:
![image](https://github.com/hmcts/civil-citizen-ui/assets/23473639/88a219e6-22a2-4e43-9c2d-effb0e4be5c0)
On the other hand that is not necessary: 
![image](https://github.com/hmcts/civil-citizen-ui/assets/23473639/2e649aa3-ba1b-43bf-a48b-00f153cd8aa8)

2023-11-02 10:57 UTC, neeta-hmcts commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +  if ((claim.respondent1.type === 'ORGANISATION' || claim.respondent1.type === 'COMPANY')
Yes.. I will fix this in my ongoing ticket CIV-8785 . Considering this PR will unblock others ticket.

2023-11-02 10:59 UTC, merged