Feature/civ 1361 financially support
hmcts/civil-citizen-ui pull request #240
Opened 2022-03-22 11:43 UTC by RosDiaf

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-03-22 12:18 UTC, TatsyMaslova requested changes

2022-03-22 12:18 UTC, TatsyMaslova commented on src/main/common/form/validators/numberOfPeopleValidator.ts
> +@ValidatorConstraint({name: 'customInt', async: false})
i think we already have 'customInt' validator. I think the name has to be unique for our validators. In addition can't we use existing library validators such as @Min(1,{message: NUMBER_OF_PEOPLE_REQUIRED}) @Integer({message: VALID_NUMBER_OF_PEOPLE}) ?

2022-03-22 12:18 UTC, TatsyMaslova commented on src/main/routes/routes.ts
> +  citizenPartnerAgeRoute,
I think Sergio has asked us to name these as controllers.

2022-03-22 12:18 UTC, TatsyMaslova commented on src/main/routes/routes.ts
> +  otherDependantsRoute,
same here

2022-03-22 16:00 UTC, GorilaNaranja requested changes

2022-03-22 16:00 UTC, GorilaNaranja commented on src/main/modules/statementOfMeans/otherDependants/otherDependantsService.ts
> +      if (civilClaimResponse && civilClaimResponse.case_data && civilClaimResponse.case_data.statementOfMeans && civilClaimResponse.case_data.statementOfMeans.otherDependants) {
We can use the library lodash to check nested object like this. It´s correct like that and works perfectly but lodash give us a shorter way to do that.


`import { get } from 'lodash'`

`if (get(civilClaimResponse, 'case_data.statementOfMeans.otherDependants')) {`

2022-03-22 16:00 UTC, GorilaNaranja commented on src/main/routes/features/response/statementOfMeans/partner/partnerAgeController.ts
> +    await partnerService.getPartnerAge(req.params.id).then((data) => {
If we use async / await we don´t should mix with .then(). It will be something like this instead:

const response = await partnerService.getPartnerAge(req.params.id);
const partner = response ? new Partner(response .option) : new Partner();
renderView(partner, res);

2022-03-22 16:00 UTC, GorilaNaranja commented on src/main/modules/statementOfMeans/otherDependants/otherDependantsService.ts
> +      if (civilClaimResponse && civilClaimResponse.case_data && civilClaimResponse.case_data.statementOfMeans) {
We can use get from lodash here also

2022-03-22 16:00 UTC, GorilaNaranja commented on src/main/modules/statementOfMeans/partner/partnerService.ts
> +      if (civilClaimResponse && civilClaimResponse.case_data && civilClaimResponse.case_data.statementOfMeans && civilClaimResponse.case_data.statementOfMeans.partnerAge) {
We can use get from lodash here also

2022-03-23 08:48 UTC, LeonardoPalmeiro requested changes

2022-03-23 08:48 UTC, LeonardoPalmeiro commented on src/main/common/form/validators/numberOfPeopleValidator.ts
> +    if (value !== undefined && value !== null && value == 0) {
maybe is the best option this if (!value && value == 0) you should test before apply :)

2022-03-23 09:36 UTC, laarmada commented on src/main/routes/routes.ts
> +  citizenPartnerAgeRoute,
yes exactly also you should merge the master into the branch asap....

2022-03-23 09:54 UTC, laarmada requested changes
merge master because there are a lot of changes...

2022-03-23 09:54 UTC, laarmada commented on src/main/modules/statementOfMeans/partner/partnerService.ts
> +export class PartnerService {
change the class name to PartnerAgeService to avoid problem

2022-03-23 09:54 UTC, laarmada commented on src/main/modules/statementOfMeans/partner/partnerService.ts
> +import {Partner} from '../../../common/form/models/statementOfMeans/partner';
It should be partnerAge?

2022-03-23 09:54 UTC, laarmada commented on src/main/modules/statementOfMeans/partner/partnerService.ts
> +import {Partner} from '../../../common/form/models/statementOfMeans/partner';
merge master to replace all and I will review the code...

2022-03-23 10:09 UTC, GorilaNaranja approved these changes
Ok for me if the comments from the rest of colleagues are resolved!

2022-03-23 16:41 UTC, TatsyMaslova approved these changes

2022-03-24 08:39 UTC, laarmada requested changes
some minor changes....

2022-03-24 08:39 UTC, laarmada commented on src/main/common/form/models/statementOfMeans/otherDependants.ts
> +export class OtherDependantsOption extends Form {
Remove the OtherDependantsOption not used.

2022-03-24 08:39 UTC, laarmada commented on src/main/modules/statementOfMeans/otherDependants/otherDependantsService.ts
> +      throw new Error(err);
not necessary new only "throw err" ... also I'll change err for error.

2022-03-24 08:39 UTC, laarmada commented on src/main/modules/statementOfMeans/partner/partnerService.ts
> +      throw new Error(err);
not necessary new only "throw err" ... also I'll change err for error.

2022-03-24 08:39 UTC, laarmada commented on src/main/modules/statementOfMeans/partner/partnerService.ts
> +      logger.error(`${err.stack || err}`);
why we don´t have throw error? also I'll change err for error.

2022-03-24 08:39 UTC, laarmada commented on src/test/unit/common/form/models/form.test.ts
> -    expect(textError).toContain('Enter first address line');
use export const VALID_ADDRESS_LINE_1 instead of text...

2022-03-24 08:39 UTC, laarmada commented on src/test/unit/common/form/models/form.test.ts
> -    expect(textError).toContain('Postcode must be in England or Wales');
add message constant file

2022-03-24 08:39 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/civilClaimResponseMock.json
> +        "numberOfPeople": 1,
it should be "1" instead of 1?

2022-03-24 08:39 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
> +      get: jest.fn(() => {throw new Error('Redis DraftStore failure.');})};
I'm using export const REDIS_FAILURE = 'Redis DraftStore failure.'; in my current branch, so you can create the same.... we have the same text in a lot of test.

2022-03-24 08:39 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
> +        expect(res.text).toContain('Choose option: Yes or No');
use existing constant

2022-03-24 08:39 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
> +        expect(res.text).toContain('Enter a number higher than 0');
use existing constant

2022-03-24 08:39 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
> +        expect(res.text).toContain('Enter details');
use existing constant

2022-03-24 08:39 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
> +});
please use necessary constant message instead of literal text

2022-03-24 09:03 UTC, GorilaNaranja commented on src/main/modules/statementOfMeans/otherDependants/otherDependantsService.ts
> +      throw new Error(err);
Same Sergio´s comment here: "not necessary new only "throw err" ... also I'll change err for error."

2022-03-24 11:01 UTC, osheaf01 commented on src/main/routes/routes.ts
> +  citizenPartnerAgeRoute,
That's confusing - some of them are Routes, some of them - 'employmentStatusController' above - are still Controllers. Can we decide on one or the other?

2022-03-24 11:03 UTC, osheaf01 approved these changes
LGTM

2022-03-24 11:45 UTC, laarmada requested changes
minor changes

2022-03-24 11:45 UTC, laarmada commented on src/main/modules/statementOfMeans/partner/partnerAgeService.ts
> +      throw Error(error);
throw error; .... I mean

2022-03-24 11:45 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
> +        expect(res.text).toContain('Do you support anyone else financially?');
should we use a constant instead of  text?

2022-03-24 11:45 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
> +        expect(res.text).toContain('Number of people');
should we use a constant instead of  text?

2022-03-24 11:45 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
> +        expect(res.body).toEqual({error: 'Error: ' + REDIS_FAILURE});
it should be works at this way: expect(res.body).toEqual({error: REDIS_FAILURE});

2022-03-24 11:45 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
> +    const mockRedisException = {
it should be create above

2022-03-24 11:45 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
> +        expect(res.body).toEqual({error: 'Error: ' + REDIS_FAILURE});
it should be works at this way: expect(res.body).toEqual({error: REDIS_FAILURE});

2022-03-24 12:37 UTC, laarmada approved these changes
ok, thanks

2022-03-29 14:35 UTC, LeonardoPalmeiro approved these changes

2022-03-29 14:35 UTC, merged