Civ 1662 fix disability bug
hmcts/civil-citizen-ui pull request #241
Opened 2022-03-22 14:28 UTC by TatsyMaslova

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-1662

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-03-22 14:39 UTC, laarmada requested changes
need to review the redis behaviour

2022-03-22 14:39 UTC, laarmada commented on src/main/views/features/response/statementOfMeans/disability.njk
>        {% set id = "disability" %}
maybe redis doent work properly....

2022-03-22 15:05 UTC, TatsyMaslova commented on src/main/views/features/response/statementOfMeans/disability.njk
>        {% set id = "disability" %}
no just checked redis saves it. it saves the model not the view ;)

2022-03-23 08:56 UTC, LeonardoPalmeiro requested changes

2022-03-23 08:56 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/statementOfMeans/severeDisabilityController.ts
is it worth add try and catch?

2022-03-23 08:56 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/statementOfMeans/partner/partnerSevereDisabilityController.ts
is it worth add try and catch?

2022-03-23 08:56 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/statementOfMeans/partner/partnerSevereDisabilityController.ts
is it worth add try and catch?

2022-03-23 08:56 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/statementOfMeans/partner/partnerDisabilityController.ts
is it worth add try and catch?

2022-03-23 08:56 UTC, LeonardoPalmeiro commented on src/main/routes/features/response/statementOfMeans/partner/partnerDisabilityController.ts
is it worth add try and catch?

2022-03-23 09:00 UTC, TatsyMaslova commented on src/main/routes/features/response/statementOfMeans/severeDisabilityController.ts
For some reason i thought it was done in refactoring disability branch but now can see it is moved to done and hence it should be in master. I will pull master again just to double check. there are a lot of things in these controllers that need fixing - for example they don't redirect to url with the claim id. but i thought for some reason it was being fixed elsewhere

2022-03-23 10:00 UTC, TatsyMaslova commented on src/main/routes/features/response/statementOfMeans/partner/partnerSevereDisabilityController.ts
done with super Sergio's refactor. i merged it from master :)

2022-03-23 10:00 UTC, TatsyMaslova commented on src/main/views/features/response/statementOfMeans/disability.njk
>        {% set id = "disability" %}
can demo it to you if you want but as discussed it is working as expected :)

2022-03-23 10:29 UTC, LeonardoPalmeiro approved these changes
Perfect :)

2022-03-23 10:44 UTC, GorilaNaranja approved these changes

2022-03-23 14:07 UTC, laarmada approved these changes
works fine

2022-03-23 16:21 UTC, merged