CIV-11219 Wrong page loads on full admit
hmcts/civil-citizen-ui pull request #2423
Opened 2023-10-27 13:45 UTC by jeswanth-hmcts

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-11219

### Change description ###

defendant selects full defence, already paid
on claimant response message should be fixed as miro 

 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-27 14:23 UTC, laarmada requested changes

2023-10-27 14:23 UTC, laarmada commented on src/main/routes/features/claimantResponse/settleClaimController.ts
> +        await saveClaimantResponse(redisKey, form.model, 'hasFullDefenceStatesPaidClaimSettled') :
use a constant instead a text

2023-10-27 14:23 UTC, laarmada commented on src/main/routes/features/claimantResponse/settleClaimController.ts
> +    const isClaimSettled = claim.isFullDefence() && claim.hasPaidInFull() ? claim.claimantResponse?.hasFullDefenceStatesPaidClaimSettled : claim.claimantResponse?.hasPartPaymentBeenAccepted;
from 29 until 36 is logic that should be in the service class.... only my opinion ... something like:

function getSettleClaim(){}

2023-10-27 14:23 UTC, laarmada commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/yourResponseSectionTasks.ts
> +  if (claim?.hasClaimantSettleTheClaimForDefendantPartlyPaidAmount() || claim.claimantResponse?.hasFullDefenceStatesPaidClaimSettled?.option ||
remove the unnecessaries ? in claim?

2023-10-27 14:23 UTC, laarmada commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
> +  const isSettleTheClaimTaskEnable = (isRespondentPartialPaid && claim.hasClaimantConfirmedDefendantPaid()) || isFullDefencePaidTotal;
try to cut the vbles names are so long...

2023-10-27 14:23 UTC, laarmada commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
> +  const isSettleTheClaimTaskEnable = (isRespondentPartialPaid && claim.hasClaimantConfirmedDefendantPaid()) || isFullDefencePaidTotal;
isFullDefencePaidTotal 
 isRespondentPartialPaid
 
we are under claimantResponse journey so defendant/respodent is redundant please use something like:

isPartialPaid
isFullPaid

2023-10-27 14:23 UTC, laarmada commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
> +  const isFreeTelePhoneMediationTaskEnable = (isRespondentPartialPaid && (claim.hasClaimantRejectedDefendantPaid() || claim.hasClaimantRejectedPartAdmitPayment())) || claim.hasClaimantRejectedDefenda
is redundant TaskEnable, from my point of view:

isFreePhoneMediation

we are under TaskListService folder so task is redundant an also is with enable .....

2023-10-27 14:55 UTC, jeswanth-hmcts commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
> +  const isSettleTheClaimTaskEnable = (isRespondentPartialPaid && claim.hasClaimantConfirmedDefendantPaid()) || isFullDefencePaidTotal;
shorted the names to 'isPartialPaid'
'isFullPaid'

2023-10-27 14:55 UTC, jeswanth-hmcts commented on src/main/routes/features/claimantResponse/settleClaimController.ts
> +        await saveClaimantResponse(redisKey, form.model, 'hasFullDefenceStatesPaidClaimSettled') :
moved to constants

2023-10-30 11:27 UTC, laarmada approved these changes

2023-10-30 14:00 UTC, jarekPierchala approved these changes

2023-11-08 03:02 UTC, closed without merging

2023-11-16 15:15 UTC, jarekPierchala commented
Will be part of post-case-progression-tasks branch