CIV-10441 Limit number of characters entered on the text boxes are not working as expected
hmcts/civil-citizen-ui pull request #2450
Opened 2023-10-31 15:57 UTC by jeswanth-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-10441

### Change description ###

Limit number of characters entered on the text boxes are not working as expected

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-10-31 16:28 UTC, ElifDenizEsea approved these changes

2023-10-31 16:31 UTC, manish14836 submitted a review, later dismissed

2023-10-31 16:56 UTC, jarekPierchala requested changes

2023-10-31 16:56 UTC, jarekPierchala commented on src/main/modules/i18n/locales/en.json
> +    "ADDRESS_LINE1_TOO_MANY": "Address line1 must no longer than 70 characters",
Address line1 must no longer than 70 characters - isn't it missing "be"? as
Address line1 must **be** no longer than 70 characters?

2023-10-31 19:03 UTC, jeswanth-hmcts commented on src/main/modules/i18n/locales/en.json
> +    "ADDRESS_LINE1_TOO_MANY": "Address line1 must no longer than 70 characters",
Good spot 'be'  is missing  added 'be' in text

2023-11-01 09:13 UTC, neeta-hmcts commented on src/main/modules/i18n/locales/cy.json
> +    "JOB_TITLE_TOO_LONG": "Job title must be no longer that 70 characters",
must be no longer **than** .. same for following statements

2023-11-01 09:15 UTC, jeswanth-hmcts commented on src/main/modules/i18n/locales/cy.json
> +    "JOB_TITLE_TOO_LONG": "Job title must be no longer that 70 characters",
![image](https://github.com/hmcts/civil-citizen-ui/assets/134285996/4b4bbe42-75a4-4b54-bf7d-8806cb11c14a)
it is done As per AC text

2023-11-01 09:18 UTC, laarmada requested changes
where are the unit test to cover all that validations?

2023-11-01 10:01 UTC, jeswanth-hmcts commented
> where are the unit test to cover all that validations?
 

> where are the unit test to cover all that validations?

added unit test

2023-11-01 10:07 UTC, laarmada approved these changes

2023-11-01 10:09 UTC, jarekPierchala requested changes

2023-11-01 10:09 UTC, jarekPierchala commented on src/main/modules/i18n/locales/cy.json
> +    "JOB_TITLE_TOO_LONG": "Job title must be no longer that 70 characters",
"that" is obviously a mistake. Correct it to **than** please. Ill speak to Kiera to update ACs

2023-11-01 10:17 UTC, jarekPierchala approved these changes

2023-11-01 10:20 UTC, laarmada submitted a review, later dismissed

2023-11-01 10:20 UTC, kalachandrasekar1 submitted a review, later dismissed

2023-11-02 12:43 UTC, portizdev approved these changes

2023-11-03 17:18 UTC, neeta-hmcts approved these changes

2023-11-03 17:25 UTC, kenneth-hmcts approved these changes

2023-11-07 14:12 UTC, jarekPierchala approved these changes

2023-11-11 15:09 UTC, jarekPierchala approved these changes

2023-11-12 10:38 UTC, merged