CIV-11151 CUI Request a CCJ - Confirmation Screen
hmcts/civil-citizen-ui pull request #2455
Opened 2023-11-01 12:45 UTC by kenneth-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-11151

### Change description ###
Fix the page redirection

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-11-13 14:43 UTC, manish14836 submitted a review, later dismissed

2023-11-13 14:44 UTC, GorilaNaranja approved these changes

2023-11-13 15:22 UTC, portizdev requested changes
Pls apply the changes from the PR: https://github.com/hmcts/civil-citizen-ui/pull/2385 that were overwritten by an erroneous conflict resolution. This way we avoid introducing more bugs. We have a controller for each of the URLS, just use the judgementAmountController version of PR 2385.

2023-11-14 12:46 UTC, ElifDenizEsea approved these changes

2023-11-14 12:58 UTC, portizdev approved these changes

2023-11-14 12:59 UTC, portizdev approved these changes

2023-11-16 14:36 UTC, jarekPierchala commented
Will be part of post-case-progression-tasks branch

2023-11-16 14:36 UTC, closed without merging