CIV-11327 Propose an alternative repayment plan appears as COMPLETE o…
hmcts/civil-citizen-ui pull request #2456
Opened 2023-11-01 12:52 UTC by ElifDenizEsea

…n task-list

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-11327

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-11-02 12:20 UTC, jarekPierchala requested changes

2023-11-02 12:20 UTC, jarekPierchala commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +  if ((claim.isPAPaymentOptionPayImmediately() && claim.claimantResponse?.courtProposedDate?.decision) ||
```
(claim.isPAPaymentOptionPayImmediately() && claim.claimantResponse?.courtProposedDate?.decision) ||
    (claim.isPAPaymentOptionByDate() && claim.partialAdmission?.paymentIntention?.paymentDate
     && claim.claimantResponse?.suggestedPaymentIntention?.paymentOption)
```
Put that snake in spearate method please!

2023-11-02 12:45 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +  if ((claim.isPAPaymentOptionPayImmediately() && claim.claimantResponse?.courtProposedDate?.decision) ||
done

2023-11-02 13:05 UTC, jarekPierchala approved these changes

2023-11-02 13:12 UTC, jarekPierchala submitted a review, later dismissed

2023-11-02 13:18 UTC, jeswanth-hmcts approved these changes

2023-11-03 13:58 UTC, neeta-hmcts commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +  if ((claim.isPAPaymentOptionPayImmediately() && claim.claimantResponse?.courtProposedDate?.decision) ||
I am not sure why you are using defendant response here to mark the claimant intention task complete. 
I believe you should use claim.claimantResponse?.suggestedPaymentIntention?.paymentOption , then based upon payment option selected by the claimant they get set of next screens. So you have to check all those asked questions are answered or not to mark this task complete.

one variation would be
1. Claimant select repayment plan set-by date 
2. then claimant ask for setDate details
3. Court decision screen comes
4. based upon claimants response next screen comes

2023-11-06 09:06 UTC, jeswanth-hmcts commented on bin/utils/process-definition.sh
> +  -e CCD_DEF_CASE_SERVICE_BASE_URL=${CCD_DEF_CASE_SERVICE_BASE_URL:-http://192.168.0.11:4000} \
is this expected to push ?

2023-11-06 09:06 UTC, jeswanth-hmcts commented on package.json
> +    "startwin": "NODE_ENV=production && ./node_modules/.bin/ts-node -r tsconfig-paths/register src/main/server.ts",
this one also

2023-11-06 09:06 UTC, jeswanth-hmcts commented on config/default.yaml
> +    url: 'http://192.168.0.11:4000'
this one also?

2023-11-06 09:06 UTC, jeswanth-hmcts commented on src/main/app.ts
> +//const productionMode = env === 'production';
this one also

2023-11-06 09:06 UTC, jeswanth-hmcts commented on src/main/app.ts
> +  resave: true,
this one also?

2023-11-06 09:06 UTC, jeswanth-hmcts commented on src/main/app/auth/launchdarkly/launchDarklyClient.ts
> +  return true;
this one also

2023-11-06 09:06 UTC, jeswanth-hmcts commented on src/main/routes/features/claim/totalAmountController.ts
> +    console.log('user'); console.log(user);
Is a console needed here?

2023-11-06 09:12 UTC, ElifDenizEsea commented on config/default.yaml
> +    url: 'http://192.168.0.11:4000'
done

2023-11-06 09:12 UTC, ElifDenizEsea commented on src/main/app.ts
> +//const productionMode = env === 'production';
done

2023-11-06 09:12 UTC, ElifDenizEsea commented on src/main/app.ts
> +  resave: true,
done

2023-11-06 09:12 UTC, ElifDenizEsea commented on src/main/app/auth/launchdarkly/launchDarklyClient.ts
> +  return true;
done

2023-11-06 09:13 UTC, ElifDenizEsea commented on src/main/routes/features/claim/totalAmountController.ts
> +    console.log('user'); console.log(user);
done

2023-11-06 09:13 UTC, ElifDenizEsea commented on package.json
> +    "startwin": "NODE_ENV=production && ./node_modules/.bin/ts-node -r tsconfig-paths/register src/main/server.ts",
done

2023-11-06 09:22 UTC, jeswanth-hmcts approved these changes

2023-11-07 10:01 UTC, laarmada requested changes

2023-11-07 10:01 UTC, laarmada commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +    (claim.isPAPaymentOptionByDate() && claim.partialAdmission?.paymentIntention?.paymentDate
please redo all that part in order to achieve more clear code: 
Have a look that piece of the code, is wrong also because we have for that claim.respondent1.type === 'ORGANISATION' || claim.respondent1.type === 'COMPANY' an specific function...... but is using the similar action.,
![image](https://github.com/hmcts/civil-citizen-ui/assets/23473639/d4c3e60e-d4bb-4e11-bacd-739630776144)

2023-11-07 10:29 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +    (claim.isPAPaymentOptionByDate() && claim.partialAdmission?.paymentIntention?.paymentDate
done

2023-11-07 11:26 UTC, laarmada requested changes

2023-11-07 11:26 UTC, laarmada commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +    (claim.isPAPaymentOptionByDate() && claim.partialAdmission?.paymentIntention?.paymentDate
I cant see the change, imposible to undestarnd that piece of the code:
<img width="617" alt="image" src="https://github.com/hmcts/civil-citizen-ui/assets/23473639/1a596ce6-dd8a-4dc5-bc13-226696789d1e">

2023-11-07 13:31 UTC, neeta-hmcts commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +      && claim.claimantResponse?.suggestedPaymentIntention?.paymentOption
I suggest create a small util function something like this

taskCoveredForNewPaymentPlan() {
  if (PaymentOptionType.BY_SET_DATE) {
     claim.claimantResponse?.suggestedPaymentIntention?.paymentDate && courtDetermination if applicable
} else if {... }
}

2023-11-07 15:12 UTC, ElifDenizEsea commented on src/main/routes/features/claim/yourDetails/claimantPhoneController.ts
> +        await saveClaimantProperty(claimId, 'emailAddress', user.email);
Removed that part, I used claimantuserdetails for email

2023-11-07 15:13 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +    (claim.isPAPaymentOptionByDate() && claim.partialAdmission?.paymentIntention?.paymentDate
I will go by Neeta's suggestion below, to make it more readable

2023-11-07 17:14 UTC, jarekPierchala requested changes

2023-11-07 17:14 UTC, jarekPierchala commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +  if (claim.claimantResponse?.suggestedPaymentIntention?.paymentOption) {
notice that `claim.claimantResponse?.suggestedPaymentIntention`
is very redundant here.
Why dont you put this as 
`const paymentIntention = claim.claimantResponse?.suggestedPaymentIntention;`
and reuse it instead? 
It's way more efficient and cleaner

2023-11-07 17:15 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +      && claim.claimantResponse?.suggestedPaymentIntention?.paymentOption
done

2023-11-07 18:00 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +  if (claim.claimantResponse?.suggestedPaymentIntention?.paymentOption) {
done

2023-11-08 07:35 UTC, portizdev reviewed
As Sergio has already said, I do not agree with the code either. There are many conditions and functions that can be refactored to improve the readability of the code and make it more efficient and cleaner.

2023-11-08 09:18 UTC, jarekPierchala approved these changes

2023-11-08 12:42 UTC, jarekPierchala submitted a review, later dismissed

2023-11-09 10:34 UTC, neeta-hmcts commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +    && claim.claimantResponse.rejectionReason)) {
claim.claimantResponse.rejectionReason - this condition is valid only for JUDGE_REPAYMENT_DATE

2023-11-16 09:27 UTC, neeta-hmcts commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +    } else if (paymentIntention?.paymentOption == PaymentOptionType.IMMEDIATELY) {
When Claimant selects Payment Option = Immediately..  this the flow

![image](https://github.com/hmcts/civil-citizen-ui/assets/115545612/c96eeaf9-174a-4e35-ba06-57249397655b)

I believe we have to consider court calculator decision screen too here

2023-11-16 10:52 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +    } else if (paymentIntention?.paymentOption == PaymentOptionType.IMMEDIATELY) {
done

2023-11-16 16:22 UTC, neeta-hmcts approved these changes

2023-11-16 16:43 UTC, paul-pearson submitted a review, later dismissed

2023-12-17 03:02 UTC, closed without merging