CIV-11516 Content change for LiP Small Claims DQs
hmcts/civil-citizen-ui pull request #2529
Opened 2023-11-10 11:01 UTC by jeswanth-hmcts

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-11516

### Change description ###

CUI R1 - Content change for LiP Small Claims DQs

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-11-10 13:27 UTC, portizdev commented on src/main/views/features/directionsQuestionnaire/witnesses/otherWitnesses/other-witnesses.njk
> +{% set notificationHtml %}
I think we use the same DQs for the claimant, does this change apply to both parties?

2023-11-10 13:31 UTC, LeonardoPalmeiro commented on src/main/views/features/directionsQuestionnaire/witnesses/otherWitnesses/other-witnesses.njk
> +{% set notificationHtml %}
in the src/main/views/features/directionsQuestionnaire/support-required-list.njk you're name html of notification with another string
![image](https://github.com/hmcts/civil-citizen-ui/assets/93268657/3602b17b-f9bd-4a42-8bfe-24d9bf55a3d0)

2023-11-10 13:54 UTC, LeonardoPalmeiro requested changes
please make sure you're using same formatting of the rest of the team

2023-11-10 14:22 UTC, jeswanth-hmcts commented on src/main/views/features/directionsQuestionnaire/witnesses/otherWitnesses/other-witnesses.njk
> +{% set notificationHtml %}
Added condition for the defendant only and changed the name to notificationHtml  to keep consistency

2023-11-10 15:25 UTC, jeswanth-hmcts commented
> please make sure you're using same formatting of the rest of the team

fixed formatting issues

2023-11-10 16:17 UTC, neeta-hmcts approved these changes

2023-11-10 17:54 UTC, kenneth-hmcts approved these changes

2023-11-10 17:56 UTC, kalachandrasekar1 approved these changes

2023-11-10 17:56 UTC, ElifDenizEsea approved these changes

2023-11-13 13:32 UTC, LeonardoPalmeiro submitted a review, later dismissed

2023-11-13 13:36 UTC, portizdev submitted a review, later dismissed

2023-11-13 14:43 UTC, portizdev approved these changes

2023-11-13 16:47 UTC, kenneth-hmcts approved these changes

2023-11-13 16:47 UTC, jarekPierchala approved these changes

2023-11-13 16:47 UTC, merged