Claimant Intent – Check your Answers: How do you wish to proceed
hmcts/civil-citizen-ui pull request #2541
Opened 2023-11-13 09:19 UTC by ElifDenizEsea

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-10916

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-11-13 15:21 UTC, jarekPierchala requested changes

2023-11-13 15:21 UTC, jarekPierchala commented on src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
> +  if ((claim.isPAPaymentOptionPayImmediately() && claim.claimantResponse?.courtProposedDate?.decision)
codition to separate method please

2023-11-13 15:25 UTC, GorilaNaranja commented on src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
> +    return claim.isFullDefence() || claim.isPartialAdmission() || claim.isFullAdmission()
I'm not sure but here we are going to call always buildYourResponseSection right?
If is full defence, is partial admission or is full admission cover all the possibilities if I'm not wrong. So maybe we don't need this conditions and we can return directly buildYourResponseSection()

2023-11-13 15:27 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
> +    return claim.isFullDefence() || claim.isPartialAdmission() || claim.isFullAdmission()
I think they're being added one by one

2023-11-13 16:46 UTC, jarekPierchala approved these changes

2023-11-16 14:29 UTC, jarekPierchala commented
Will be part of post-case-progression-tasks branch

2023-11-16 14:29 UTC, closed without merging