Civ 1274 children aged 16 19
hmcts/civil-citizen-ui pull request #255
Opened 2022-03-23 16:22 UTC by TatsyMaslova

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-1274

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-03-24 09:10 UTC, taomoh commented on src/main/views/features/response/statementOfMeans/dependants/dependant-teenagers.njk
> +          <form method="post">
I think it's safer to add novalidate as per this:  https://design-system.service.gov.uk/patterns/validation/#turn-off-html5-validation

2022-03-24 09:12 UTC, sampankumar commented on src/main/common/form/models/statementOfMeans/dependants/dependantTeenagers.ts
> +import {Form} from '../../form';
Teenager can also mean age 13-15 so may be we can name the file something else?

2022-03-24 09:14 UTC, LeonardoPalmeiro requested changes
I guess we could have 100% of coverage in those files, what do you think?

2022-03-24 09:14 UTC, LeonardoPalmeiro commented on src/main/modules/statementOfMeans/dependants/dependantTeenagersService.ts
> +    return undefined;
should return a throw

2022-03-24 09:14 UTC, LeonardoPalmeiro commented on src/main/modules/statementOfMeans/dependants/dependantTeenagersService.ts
> +  }
should return a throw

2022-03-24 09:21 UTC, TatsyMaslova commented on src/main/common/form/validationErrors/formValidationError.ts
> +    this.text = constraintMessages ? constraintMessages[0] : '';
this is so that it shows the first error. it fixes a lot of issues like Rosario and Taoufik were facing when it shows all errors separated by comma when the field is undefined.

2022-03-24 09:22 UTC, TatsyMaslova commented on src/main/common/form/validators/postcodeValidator.ts
> + * Validates that the input value is in correct post code format
yeah i jut noticed that it was a copy paste and changed it. i did not change the name which should be changed too because it is the same as customInt where as this one is to do a post.

2022-03-24 09:22 UTC, TatsyMaslova commented on src/main/common/form/validationErrors/errorMessageConstants.ts
> -export const POSTCODE_NOT_VALID = 'Postcode must be in United Kingdom';
yes it was never used anywhere :)

2022-03-24 09:23 UTC, TatsyMaslova commented on src/main/common/form/validationErrors/formValidationError.ts
> +    this.text = constraintMessages ? constraintMessages[0] : '';
no it fixes the issue when the field is undefined and it goes off showing all errors instead of the relative first one ;) . Actually this is what they did in ocmc and now i understand why

2022-03-24 09:25 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/dependants/dependantTeenagersService.ts
> +    return Number(claim.statementOfMeans.dependants.numberOfChildren.between16and19);
yes. in theory it should never go to this page when the number of children between 16 and 19 are not set. But if it does then the page will still show. it will jut not allow any number in the text field - the validation will say the number should be less than in the previous page

2022-03-24 09:49 UTC, laarmada requested changes
minor comments

2022-03-24 09:49 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/dependants/dependantTeenagersController.test.ts
> +          expect(res.body).toEqual({error: 'Error: Redis DraftStore failure.'});
please create this message, I have created also in my branch:
export const VALID_ADDRESS_LINE_1 = 'Enter first address line';

2022-03-24 09:49 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/dependants/dependantTeenagersController.test.ts
> +          throw new Error('Redis DraftStore failure.');
please create this message, I have created also in my branch:
export const VALID_ADDRESS_LINE_1 = 'Enter first address line';

2022-03-24 09:49 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/dependants/dependantTeenagersController.test.ts
> +      const mockErrorDraftStore = {
you could declare above instead of inside....

2022-03-24 09:49 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/dependants/dependantTeenagersController.test.ts
> +          expect(res.text).toContain('Children aged 16 to 19 living with you');
could we use a constant message for that?

2022-03-24 09:50 UTC, taomoh commented on src/main/common/form/validationErrors/formValidationError.ts
> +    this.text = constraintMessages ? constraintMessages[0] : '';
This is the same as OCMC

2022-03-24 09:52 UTC, taomoh commented on src/main/common/form/validationErrors/errorMessageConstants.ts
> -export const POSTCODE_NOT_VALID = 'Postcode must be in United Kingdom';
constant unused

2022-03-24 11:21 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/dependants/dependantTeenagersService.ts
> +  }
done

2022-03-24 11:37 UTC, TatsyMaslova commented on src/main/views/features/response/statementOfMeans/dependants/dependant-teenagers.njk
> +          <form method="post">
done thank you!

2022-03-24 11:38 UTC, TatsyMaslova commented on src/test/unit/routes/features/response/statementOfMeans/dependants/dependantTeenagersController.test.ts
> +          expect(res.body).toEqual({error: 'Error: Redis DraftStore failure.'});
done put it const on the same test though

2022-03-24 11:38 UTC, TatsyMaslova commented on src/test/unit/routes/features/response/statementOfMeans/dependants/dependantTeenagersController.test.ts
> +          throw new Error('Redis DraftStore failure.');
done but put error message on the same test as expected error and error to throw

2022-03-24 11:48 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/dependants/dependantTeenagersController.test.ts
> +      const mockErrorDraftStore = {
we should use in post and get right?

2022-03-24 11:50 UTC, laarmada commented on src/test/unit/routes/features/response/statementOfMeans/dependants/dependantTeenagersController.test.ts
> +          throw new Error('Redis DraftStore failure.');
throw new Error('Redis DraftStore failure.');   I have create in my branch that: export const REDIS_FAILURE = 'Redis DraftStore failure.';

2022-03-24 13:02 UTC, TatsyMaslova commented on src/test/unit/routes/features/response/statementOfMeans/dependants/dependantTeenagersController.test.ts
> +          throw new Error('Redis DraftStore failure.');
oops sorry missed this one

2022-03-24 13:22 UTC, TatsyMaslova commented on src/main/common/form/models/statementOfMeans/dependants/dependantTeenagers.ts
> +import {Form} from '../../form';
renamed :) thanks

2022-03-24 13:25 UTC, TatsyMaslova commented on src/test/unit/routes/features/response/statementOfMeans/dependants/dependantTeenagersController.test.ts
> +      const mockErrorDraftStore = {
yep you are right lol. i forgot about the get. done

2022-03-24 13:45 UTC, taomoh approved these changes

2022-03-24 14:30 UTC, TatsyMaslova commented on src/main/common/form/models/statementOfMeans/dependants/numberOfChildren.ts
> +export class NumberOfChildren {
this is a copy of Taoufik's model, it will change once Taofik's changes will go in. it will have methods and validations etc :) . it is needed because i am dependant on his model. i copied it from his branch

2022-03-24 14:31 UTC, TatsyMaslova commented on src/main/common/form/validationErrors/formValidationError.ts
> +    this.href = '#' + this.property;
ah got you, you want me to change it to avoid concatination with +?
this would be refactoring really. not sure whether it is to do with my story though

2022-03-24 14:45 UTC, TatsyMaslova commented on src/main/common/form/models/statementOfMeans/dependants/dependants.ts
> +export class Dependants {
this is a copy of Taoufik story's model. so it will change and will have validations and stuff once his changes go in :) . so no it shouldn't be an interface

2022-03-24 14:45 UTC, TatsyMaslova commented on src/main/common/form/validationErrors/formValidationError.ts
> +    this.href = '#' + this.property;
done :)

2022-03-24 15:12 UTC, GorilaNaranja approved these changes
Nice work!

2022-03-25 08:37 UTC, laarmada approved these changes

2022-03-25 08:39 UTC, LeonardoPalmeiro approved these changes
Very good.

2022-03-29 09:59 UTC, taomoh commented on src/main/routes/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenController.ts
> +const router = express.Router();
@TatsyMaslova, you could rename `router` this to `betweenSixteenAndNineteenController` to avoid code smell in sonarcloud

2022-03-29 10:10 UTC, TatsyMaslova commented on src/main/routes/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenController.ts
> +const router = express.Router();
goof point. Thanks Taoufik

2022-03-29 10:11 UTC, taomoh commented on src/main/routes/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenController.ts
> +const router = express.Router();
You're a star Tanya!

2022-03-29 12:15 UTC, merged