Added terraform files
hmcts/civil-citizen-ui pull request #26
Opened 2021-11-05 09:42 UTC by LeonardoPalmeiro

### JIRA link ###
ROC-9706

### Change description ###
Added terraform files for infrastructure

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2021-11-05 10:47 UTC, laarmada approved these changes
all correct

2021-11-05 14:16 UTC, taomoh commented on infrastructure/state.tf
> +      version = "=2.49.0"
This is behind the version referred to in the good example: https://github.com/hmcts/draft-store/tree/master/infrastructure

2021-11-05 14:16 UTC, taomoh commented on infrastructure/output.tf
> +}
@mounikahmcts thinks this file isn't required

2021-11-05 14:16 UTC, taomoh commented on infrastructure/main.tf
> +data "azurerm_key_vault" "cmc_key_vault" {
change all `cmc_` prefixes to `civil_`

2021-11-05 14:16 UTC, taomoh commented on infrastructure/main.tf
> +data "azurerm_key_vault" "cmc_key_vault" {
At this stage we may not need all the keys copied from CMC. We can also ask platop to confirm what is the minimum set of key that have to be defined for a skeleton application

2021-11-09 08:29 UTC, taomoh commented on infrastructure/output.tf
> +}
@LeonardoPalmeiro , can you please double-check with @mounikahmcts if this file is required? if it's not please remove it

2021-11-09 10:45 UTC, mounikahmcts commented on infrastructure/main.tf
> +resource "azurerm_key_vault_secret" "POSTGRES-USER-CIVIL" {
Quite not sure why do we need postgress here

2021-11-09 12:37 UTC, LeonardoPalmeiro commented on infrastructure/output.tf
> +}
all project has this file for now I'll keep it.

2021-11-09 12:39 UTC, LeonardoPalmeiro commented on infrastructure/main.tf
> +resource "azurerm_key_vault_secret" "POSTGRES-USER-CIVIL" {
you're right we don't use this I just added for test propose I'll remove in the next PR.

2021-11-11 11:31 UTC, taomoh approved these changes

2021-11-11 12:02 UTC, timja requested changes
What do you need infra wise here? Does this frontend application need infrastructure? (as you aren't adding any in this PR)

2021-11-11 12:02 UTC, timja commented on infrastructure/variables.tf
> +
```suggestion
```

2021-11-11 12:02 UTC, timja commented on infrastructure/state.tf
> +      version = "2.50"
always start with the latest version

2021-11-11 12:02 UTC, timja commented on infrastructure/.terraform-version
> +0.13.2
use the latest version

2021-11-11 12:08 UTC, LeonardoPalmeiro commented on infrastructure/state.tf
> +      version = "2.50"
I used from drat-store.
The last one from [registry](https://registry.terraform.io/providers/hashicorp/azurerm/latest) is 2.84.0, then I'll this one.

2021-11-11 12:09 UTC, LeonardoPalmeiro commented on infrastructure/.terraform-version
> +0.13.2
I'll use the 1.0.11, is there ok?

2021-11-11 12:19 UTC, LeonardoPalmeiro commented
> What do you need infra wise here? Does this frontend application need infrastructure? (as you aren't adding any in this PR)

for now we don't need but in the next stages we will.

2021-11-11 12:56 UTC, timja reviewed
better can you clean these up too please

2021-11-11 12:56 UTC, timja commented on infrastructure/variables.tf
> +
this is not needed either
```suggestion
```

2021-11-11 12:56 UTC, timja commented on infrastructure/variables.tf
> +
```suggestion
```

2021-11-11 12:56 UTC, timja commented on infrastructure/.terraform-version
> +0.13.2
yup

2021-11-11 13:00 UTC, timja approved these changes
can you update terraform-version file as well, once done then this is ok

2021-11-11 13:00 UTC, timja commented on infrastructure/.terraform-version
> +0.13.2
```suggestion
1.0.11
```

2021-11-11 13:00 UTC, timja commented
> for now we don't need but in the next stages we will.

what are you planning to add?

2021-11-11 13:02 UTC, LeonardoPalmeiro commented on infrastructure/.terraform-version
> +0.13.2
is in this commit https://github.com/hmcts/civil-citizen-ui/pull/26/commits/02d0f6fa8be1ad945

2021-11-11 13:05 UTC, taomoh commented
> > for now we don't need but in the next stages we will.
> 
> what are you planning to add (out of interest)?

@timja we anticipate we will be adding key vault resources like secrets and application variables, if by infrastructure you mean items like a database for example, then we don't anticipate this will be needed

2021-11-11 13:13 UTC, laarmada approved these changes

2021-11-11 13:18 UTC, taomoh commented on infrastructure/main.tf
> +  resource_group_name = "${var.product}-service-${var.env}"
@LeonardoPalmeiro, this tells me civil-citizen-ui component is reusing another existing component's (civil-service) resource group: civil-service-<env>. Not sure this is sensible. Not a big deal just now, but we will probably need to revisit this in the future so civil-citizen-ui component has its own resource group: civil-citizen-ui-<env>
@timja , would you agree?

2021-11-11 13:43 UTC, timja requested changes
> > > for now we don't need but in the next stages we will.
> > 
> > 
> > what are you planning to add (out of interest)?
> 
> @timja we anticipate we will be adding key vault resources like secrets and application variables, if by infrastructure you mean items like a database for example, then we don't anticipate this will be needed

You won't need any of these in a frontend repo normally (generally the only service frontend apps deploy is redis).

Don't anticipate when adding something like this, it will add time to your pipeline unecessarily.

Either you'll need infra or you won't.

But better to add in a just in time manner.

2021-11-11 13:44 UTC, timja commented on infrastructure/main.tf
> +  resource_group_name = "${var.product}-service-${var.env}"
i'm not sure exactly how your project is setup but normally a set of [components](https://hmcts.github.io/glossary/#component) will use a [products](https://hmcts.github.io/glossary/#product) infrastrucutre, for shared components anyway like key vaults.

2021-11-19 12:55 UTC, timja requested changes
not sure why you are updating this, you aren't using the terraform at all

2021-11-19 13:48 UTC, taomoh approved these changes
LGTM

2021-11-19 14:15 UTC, LeonardoPalmeiro commented
> 



> not sure why you are updating this, you aren't using the terraform at all

we created a shared infrastructure for civil, now we will use that one.

2021-11-22 10:13 UTC, timja requested changes
This PR does nothing, your application will read secrets via CSI driver https://hmcts.github.io/ways-of-working/new-component/secrets-management.html#secrets-management

not via terraform

2021-11-22 10:55 UTC, closed without merging