CIV-11209 Help with fees reference number
hmcts/civil-citizen-ui pull request #2624
Opened 2023-11-21 14:23 UTC by miguelMolina3691

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-11209

### Change description ###
![image](https://github.com/hmcts/civil-citizen-ui/assets/93722947/b85bd9b0-cb01-4bac-8820-6bad9fe80824)
![image](https://github.com/hmcts/civil-citizen-ui/assets/93722947/b3ee3526-8573-490b-9c61-3ec4e519d5bb)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-11-22 12:30 UTC, m-meulendijks-v1 commented on src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
> +                  <a class="govuk-link" target="_blank" rel="noreferrer noopener" href="https://www.gov.uk/government/publications/fees-in-the-civil-and-family-courts-main-fees-ex50" class="govuk-lin
Can we have this link in the urls.ts, and the value of that passed on via controller?
Would be better than hardcoding on the page.

2023-11-22 14:29 UTC, laarmada requested changes

2023-11-22 14:29 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +    "APPLY_HELP_WITH_FEES": {
it should be under case progression page?

2023-11-22 14:29 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +    "APPLY_HELP_WITH_FEES": {
![image](https://github.com/hmcts/civil-citizen-ui/assets/23473639/5c816af1-c51f-45d2-a180-9803b998c5e6)

2023-11-22 14:29 UTC, laarmada commented on src/main/routes/features/caseProgression/hearingFee/applyHelpFeeReferenceController.ts
> +    await renderView(res, req, null, claimId, redirectUrl);
instead of null that one ....  new GenericForm(new ApplyHelpFeesReferenceForm());

2023-11-22 14:29 UTC, laarmada commented on src/main/routes/features/caseProgression/hearingFee/applyHelpFeeReferenceController.ts
> +      form = new GenericForm(claim.caseProgression.helpFeeReferenceNumberForm);
you should remove that logic could be more simple....

2023-11-22 14:29 UTC, laarmada commented on src/main/routes/features/caseProgression/hearingFee/applyHelpFeeReferenceController.ts
> +      await saveCaseProgression(redisClaimId, form.model, 'helpFeeReferenceNumberForm');
extrat to a constant 'helpFeeReferenceNumberForm'

2023-11-22 14:29 UTC, laarmada commented on src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
> +{% from "govuk/components/textarea/macro.njk" import govukTextarea %}
Do you need that one import?

2023-11-22 14:29 UTC, laarmada commented on src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
> +{% from "govuk/components/textarea/macro.njk" import govukTextarea %}
Do you need that one import?

2023-11-22 14:29 UTC, laarmada commented on src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
> +{% from "govuk/components/tabs/macro.njk" import govukTabs %}
review the unused imports

2023-11-23 12:18 UTC, miguelMolina3691 commented on src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
> +{% from "govuk/components/tabs/macro.njk" import govukTabs %}
removed

2023-11-23 12:20 UTC, miguelMolina3691 commented on src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
> +                  <a class="govuk-link" target="_blank" rel="noreferrer noopener" href="https://www.gov.uk/government/publications/fees-in-the-civil-and-family-courts-main-fees-ex50" class="govuk-lin
Modified

2023-11-28 09:51 UTC, laarmada approved these changes

2024-01-09 10:15 UTC, laarmada approved these changes

2024-01-09 10:26 UTC, dharmendrak approved these changes

2024-01-12 10:32 UTC, merged