Civ 11485 confirmation business
hmcts/civil-citizen-ui pull request #2641
Opened 2023-11-23 11:43 UTC by GorilaNaranja

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-11485

### Change description ###
Claimant Intent – Confirmation screens : Reject the defendant plan + Defendant = ORG or LTD Company

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-11-23 13:23 UTC, paul-pearson requested changes

2023-11-23 13:23 UTC, paul-pearson commented on src/main/modules/i18n/locales/cy.json
> +        "CCJ_WILL_BE_ISSUED": "A County Court Judgement (CCJ) will be issued. This requires the defendant to pay according to the terms of the plan."
Typo - should  be "Judgment".

2023-11-23 13:23 UTC, paul-pearson commented on src/main/modules/i18n/locales/en.json
> +        "CCJ_WILL_BE_ISSUED": "A County Court Judgement (CCJ) will be issued. This requires the defendant to pay according to the terms of the plan."
As above - "Judgment".

2023-11-23 14:08 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/en.json
> +        "CCJ_WILL_BE_ISSUED": "A County Court Judgement (CCJ) will be issued. This requires the defendant to pay according to the terms of the plan."
Fixed

2023-11-23 14:08 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/cy.json
> +        "CCJ_WILL_BE_ISSUED": "A County Court Judgement (CCJ) will be issued. This requires the defendant to pay according to the terms of the plan."
Fixed

2023-11-23 15:03 UTC, paul-pearson approved these changes

2023-11-24 08:25 UTC, portizdev approved these changes

2023-11-24 09:02 UTC, laarmada submitted a review, later dismissed

2023-12-13 19:18 UTC, merged