CIV-7824 Pay hearing fee payment unsuccessful screen
hmcts/civil-citizen-ui pull request #2642
Opened 2023-11-23 11:52 UTC by kannan-v-hmcts

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-7824

### Change description ###

Payment unsuccessful screen when hearing fees payment has failed

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```
![Payment_unsuccessful](https://github.com/hmcts/civil-citizen-ui/assets/148557022/ca306c63-a96c-4d90-a24c-cf19269a5569)

2023-11-23 14:23 UTC, laarmada requested changes
Good job :)

2023-11-23 14:23 UTC, laarmada commented on src/main/routes/features/caseProgression/hearingFee/paymentUnsuccessfulController.ts
> +        const claimDashboardUrl = DASHBOARD_CLAIMANT_URL.replace(':id', claimId);
it's better to add a post function (claimDashboardUrl) to cover the next page action button and also it will be necessary for future actions.

2023-11-23 14:23 UTC, laarmada commented on src/main/routes/features/caseProgression/hearingFee/paymentUnsuccessfulController.ts
> +          claimId,
unuser claimId  you can remove it

2023-11-23 14:23 UTC, laarmada commented on src/main/routes/features/caseProgression/hearingFee/paymentUnsuccessfulController.ts
> +      if (!claim.isEmpty()) {
claim always be an Claim object so the function will be work with out problem... so that "if" is not necessary here.

2023-11-23 16:00 UTC, m-meulendijks-v1 commented on src/main/views/features/caseProgression/hearingFee/payment-unsuccessful.njk
> +          class="govuk-heading-m">{{ t('PAGES.LATEST_UPDATE_CONTENT.CASE_PROGRESSION.HEARING_FEE.PAYMENT.UNSUCCESSFUL.WHAT_HAPPENS_NEXT') }}</h2>
Would it be neater to use the src/main/common/utils/pageSectionBuilder.ts to pass the info underneath the govukPanel, rather than hardcode the whole page?

2023-11-23 16:11 UTC, kannan-v-hmcts commented on src/main/views/features/caseProgression/hearingFee/payment-unsuccessful.njk
> +          class="govuk-heading-m">{{ t('PAGES.LATEST_UPDATE_CONTENT.CASE_PROGRESSION.HEARING_FEE.PAYMENT.UNSUCCESSFUL.WHAT_HAPPENS_NEXT') }}</h2>
Will have a look at the pageSectionBuilder.ts implementation. Thanks !

2023-11-24 10:57 UTC, kannan-v-hmcts commented on src/main/views/features/caseProgression/hearingFee/payment-unsuccessful.njk
> +          class="govuk-heading-m">{{ t('PAGES.LATEST_UPDATE_CONTENT.CASE_PROGRESSION.HEARING_FEE.PAYMENT.UNSUCCESSFUL.WHAT_HAPPENS_NEXT') }}</h2>
Had a conversation with the team and we decided that since its a simple static screen, we will not go ahead with page builder implementation as we need to create more classes and test cases.

2023-11-24 12:13 UTC, laarmada submitted a review, later dismissed

2023-11-27 10:53 UTC, miguelMolina3691 submitted a review, later dismissed

2023-11-27 11:05 UTC, dharmendrak submitted a review, later dismissed

2023-11-28 13:04 UTC, dharmendrak approved these changes

2023-11-28 13:18 UTC, laarmada approved these changes

2023-11-30 09:17 UTC, merged