Refactor/civ 1740 remove code smells
hmcts/civil-citizen-ui pull request #271
Opened 2022-03-29 10:04 UTC by taomoh

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-1740

### Change description ###

First iteration removing code smells listed here: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=civil-citizen-ui

- Rename router constant to match file name (xxxController)
- Clear variable scope confusion

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-03-29 10:18 UTC, osheaf01 approved these changes
LGTM.
Have incorporated those changes into my branch...

2022-03-29 10:28 UTC, LeonardoPalmeiro requested changes

2022-03-29 10:28 UTC, LeonardoPalmeiro commented on src/main/routes/routes.ts
> +import homeController from './homeController';
There is no test into this Controller.
Maybe it's unnecessary. what do you think?

2022-03-29 10:28 UTC, LeonardoPalmeiro commented on src/main/routes/unauthorisedController.ts
> +import {Router} from 'express';
There is no test into this Controller.
Maybe it's unnecessary. what do you think?

2022-03-29 10:38 UTC, taomoh commented on src/main/routes/routes.ts
> +import homeController from './homeController';
This task is not about adding test coverage. The home page will eventually be removed anyway

2022-03-29 10:40 UTC, taomoh commented on src/main/routes/unauthorisedController.ts
> +import {Router} from 'express';
This task is not about adding test coverage. This page could also be removed once we add standard error handling

2022-03-29 10:42 UTC, LeonardoPalmeiro commented on src/main/routes/unauthorisedController.ts
> +import {Router} from 'express';
I got you.
Thanks.

2022-03-29 10:42 UTC, LeonardoPalmeiro commented on src/main/routes/routes.ts
> +import homeController from './homeController';
thanks.

2022-03-29 10:43 UTC, LeonardoPalmeiro approved these changes

2022-03-29 12:08 UTC, GorilaNaranja approved these changes

2022-03-30 13:54 UTC, laarmada approved these changes

2022-04-01 09:05 UTC, merged