CIV-8940 Claimant Intent: Submit Function - Change state to PROCEEDS_IN_HERITAGE_SYSTEM
hmcts/civil-citizen-ui pull request #2734
Opened 2023-12-06 17:11 UTC by jeswanth-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-8940

### Change description ###

 Claimant Intent: Submit Function - Change state to PROCEEDS_IN_HERITAGE_SYSTEM

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-12-07 09:23 UTC, jarekPierchala requested changes

2023-12-07 09:23 UTC, jarekPierchala commented on src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
> +import { CourtProposedDateOptions } from 'common/form/models/claimantResponse/courtProposedDate';
remove spaces

2023-12-08 10:15 UTC, ElifDenizEsea approved these changes

2023-12-08 12:18 UTC, jeswanth-hmcts commented on src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
> +    claimantResponseOnCourtDecision: claimantResponse?.courtProposedDate?.decision,
![image](https://github.com/hmcts/civil-citizen-ui/assets/134285996/9402239d-b47a-41ff-90cf-655e2731bff6)

this translation is about claimant response on court decision ,

2023-12-08 13:42 UTC, manish14836 submitted a review, later dismissed

2023-12-12 09:18 UTC, portizdev approved these changes

2023-12-13 09:31 UTC, portizdev submitted a review, later dismissed

2023-12-18 11:13 UTC, closed without merging