Feat/civ 7829
hmcts/civil-citizen-ui pull request #2764
Opened 2023-12-11 15:39 UTC by miguelMolina3691

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-12-13 14:57 UTC, laarmada requested changes
please talk with kannan about his changes if exist @kannan-v-hmcts

2023-12-13 14:57 UTC, laarmada commented on src/main/common/models/claim.ts
> +  hearingFeePaymentDetails: PaymentDetails;
it should be under caseProgression ---> xxx---..... no in tue root of claim

2023-12-13 14:57 UTC, laarmada commented on src/main/routes/urls.ts
> +export const HEARING_FEE_MAKE_PAYMENT_AGAIN = `${BASE_CASE_PROGRESSION_URL}/make-payment-again`;
add _URL at the end

2023-12-13 14:57 UTC, laarmada commented on src/main/services/dashboard/getDashboardContent.ts
> +    .addTitle(t('PAGES.LATEST_UPDATE_CONTENT.CASE_PROGRESSION.HEARING_FEE.PAID_NOTIFICATION_TITLE', { lng }))
I think we dont need {} could you check it?

2023-12-13 14:57 UTC, laarmada commented on src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionService.ts
> +  const redisClaimId = generateRedisKey(<AppRequest>req);
where is the try/catch function?

2023-12-13 14:57 UTC, laarmada commented on src/main/services/features/caseProgression/hearingFee/makePaymentAgainService.ts
> +  const redisClaimId = generateRedisKey(<AppRequest>req);
try/catch also missing

2023-12-13 14:57 UTC, laarmada commented on src/main/services/features/caseProgression/hearingFee/paymentConfirmationService.ts
> +  const redisClaimId = generateRedisKey(<AppRequest>req);
try/catch function to manage and exception control

2023-12-13 15:40 UTC, kannan-v-hmcts commented on src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionService.ts
> +  const redisClaimId = generateRedisKey(<AppRequest>req);
Hi @laarmada This function is called within a try block from the controller and the exception is caught there. Do we still need try catch in this service class ?

2023-12-14 09:32 UTC, kannan-v-hmcts commented on src/main/routes/urls.ts
> +export const HEARING_FEE_MAKE_PAYMENT_AGAIN = `${BASE_CASE_PROGRESSION_URL}/make-payment-again`;
This code is part of my PR - https://github.com/hmcts/civil-citizen-ui/pull/2709. I will make the changes there

2023-12-14 09:57 UTC, laarmada commented on src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionService.ts
> +  const redisClaimId = generateRedisKey(<AppRequest>req);
once we have a await/ database/ redis/ etc external service is mandatory to create a try cath block in order to follow the exception thread and also add specific log message..... that is the correct way to do, if you have controller ---> service ---> model (call external function) we need to create in the 3 parts try /catch block in order to have an exception control .... else we dont know exactly where is the causing of root cause

2023-12-14 10:01 UTC, kannan-v-hmcts commented on src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionService.ts
> +  const redisClaimId = generateRedisKey(<AppRequest>req);
Thanks for the explanation @laarmada. I will address this in my PR https://github.com/hmcts/civil-citizen-ui/pull/2709

2023-12-14 10:02 UTC, kannan-v-hmcts commented on src/main/services/features/caseProgression/hearingFee/paymentConfirmationService.ts
> +  const redisClaimId = generateRedisKey(<AppRequest>req);
Will be addressed in https://github.com/hmcts/civil-citizen-ui/pull/2709

2023-12-14 10:02 UTC, kannan-v-hmcts commented on src/main/services/features/caseProgression/hearingFee/makePaymentAgainService.ts
> +  const redisClaimId = generateRedisKey(<AppRequest>req);
Will be addressed in https://github.com/hmcts/civil-citizen-ui/pull/2709

2023-12-14 10:32 UTC, kannan-v-hmcts commented
@laarmada @miguelMolina3691  Changes suggested by Sergio are done and pushed to my PR - https://github.com/hmcts/civil-citizen-ui/pull/2709/commits/578f024a1f6286af86eacb607e0aa4ef2182ee80

2023-12-21 15:48 UTC, dharmendrak approved these changes

2024-01-03 09:14 UTC, m-meulendijks-v1 reviewed
I am noticing a lot of references to alternative contact person + Carm. Should those changes be in here if they are not already in feature/Dashboard_dev?

2024-01-08 12:32 UTC, kannan-v-hmcts commented on src/main/services/dashboard/getDashboardContent.ts
> +  if (claim.caseProgression?.hearing?.paymentInformation?.status === success || claim.caseProgressionHearing?.hearingFeePaymentDetails?.status === PaymentStatus.SUCCESS) {
As discussed, the status is saved differently in Redis and CCD. Ignoring this comment as agreed

2024-01-08 12:32 UTC, kannan-v-hmcts commented on src/main/common/models/claim.ts
> +  helpWithFeesRequested: string;
Done. Moved it under caseProgression -> Hearing

2024-01-09 10:12 UTC, laarmada approved these changes

2024-01-09 14:37 UTC, m-meulendijks-v1 approved these changes

2024-01-23 13:22 UTC, dharmendrak approved these changes

2024-01-23 13:22 UTC, merged