Feat/civ 8950
hmcts/civil-citizen-ui pull request #2765
Opened 2023-12-11 15:52 UTC by ElifDenizEsea

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-8950

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-12-13 09:15 UTC, jeswanth-hmcts commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanSummaryClaimantController.ts
> +    const title = t('PAGES.REPAYMENT_PLAN_SUMMARY.REPAYMENT_PLAN');
Is lng option missed  for this translation, otherwise text will not translate upon change  like {lng:lang} or it is not required

2023-12-13 09:15 UTC, jeswanth-hmcts commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanSummaryDefendantController.ts
> +    const title = t('PAGES.REPAYMENT_PLAN_SUMMARY.CLAIMANTS_REPAYMENT_PLAN');
same here

2023-12-13 09:18 UTC, portizdev requested changes

2023-12-13 09:18 UTC, portizdev commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanSummaryClaimantController.ts
> +    const claim = await getClaimById(generateRedisKey(<AppRequest>req), req);
The req object is already an AppRequest object, you don't need to cast it.

2023-12-13 09:18 UTC, portizdev commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanSummaryDefendantController.ts
> +    const claim = await getClaimById(generateRedisKey(<AppRequest>req), req);
Same here with the AppRequest

2023-12-13 09:18 UTC, portizdev commented on src/main/views/features/claimantResponse/ccj/repayment-plan-summary.njk
> +{% from "govuk/components/button/macro.njk" import govukButton %}
Check the components you use and only import the necessary ones.

2023-12-13 09:18 UTC, portizdev commented on src/main/views/features/claimantResponse/ccj/repayment-plan-summary-claimant.njk
> +{% from "govuk/components/date-input/macro.njk" import govukDateInput %}
Check the components you use and only import the necessary ones.

2023-12-13 09:18 UTC, portizdev commented on src/test/unit/services/features/claimantResponse/ccj/repaymentPlanSummaryService.test.ts
> +});
Please try to reach 100% coverage on sonar.

2023-12-13 10:42 UTC, ElifDenizEsea commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanSummaryClaimantController.ts
> +    const title = t('PAGES.REPAYMENT_PLAN_SUMMARY.REPAYMENT_PLAN');
done

2023-12-13 10:42 UTC, ElifDenizEsea commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanSummaryDefendantController.ts
> +    const title = t('PAGES.REPAYMENT_PLAN_SUMMARY.CLAIMANTS_REPAYMENT_PLAN');
done

2023-12-13 10:42 UTC, ElifDenizEsea commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanSummaryClaimantController.ts
> +    const claim = await getClaimById(generateRedisKey(<AppRequest>req), req);
done

2023-12-13 10:42 UTC, ElifDenizEsea commented on src/main/routes/features/claimantResponse/ccj/repaymentPlanSummaryDefendantController.ts
> +    const claim = await getClaimById(generateRedisKey(<AppRequest>req), req);
done

2023-12-13 10:44 UTC, ElifDenizEsea commented on src/main/views/features/claimantResponse/ccj/repayment-plan-summary.njk
> +{% from "govuk/components/button/macro.njk" import govukButton %}
done

2023-12-13 10:44 UTC, ElifDenizEsea commented on src/main/views/features/claimantResponse/ccj/repayment-plan-summary-claimant.njk
> +{% from "govuk/components/date-input/macro.njk" import govukDateInput %}
done

2023-12-13 11:04 UTC, jeswanth-hmcts submitted a review, later dismissed

2023-12-13 14:15 UTC, jeswanth-hmcts submitted a review, later dismissed

2023-12-13 14:52 UTC, GorilaNaranja submitted a review, later dismissed

2023-12-13 14:52 UTC, kalachandrasekar1 approved these changes

2023-12-14 14:50 UTC, kenneth-hmcts submitted a review, later dismissed

2023-12-14 15:40 UTC, kenneth-hmcts approved these changes

2023-12-14 16:04 UTC, manish14836 approved these changes

2023-12-14 16:06 UTC, neeta-hmcts approved these changes

2023-12-14 21:08 UTC, merged