CIV-8903 dashboard status for sign settlement
hmcts/civil-citizen-ui pull request #2835
Opened 2023-12-21 14:15 UTC by manish14836

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-8903

### Change description ###

 Claimant Dashboard Status - Part4 Settlement Agreements

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-12-21 15:54 UTC, jeswanth-hmcts submitted a review, later dismissed

2023-12-22 09:14 UTC, kalachandrasekar1 approved these changes

2024-01-02 10:35 UTC, paul-pearson approved these changes

2024-01-04 14:41 UTC, paul-pearson requested changes

2024-01-04 14:41 UTC, paul-pearson commented on src/main/common/models/dashboard/dashboardItem.ts
> +      DEFENDANT_REJECTED_SETTLEMENT_AGREEMENT: {translationKey: 'PAGES.DASHBOARD.STATUS_DEFENDANT.DEFENDANT_REJECTED_SETTLEMENT_AGREEMENT' },
Probably best to change the order of these to match the DashboardClaimantItem.

2024-01-04 15:28 UTC, manish14836 commented on src/main/common/models/dashboard/dashboardItem.ts
> +      DEFENDANT_REJECTED_SETTLEMENT_AGREEMENT: {translationKey: 'PAGES.DASHBOARD.STATUS_DEFENDANT.DEFENDANT_REJECTED_SETTLEMENT_AGREEMENT' },
Updated as suggested

2024-01-05 09:15 UTC, paul-pearson approved these changes

2024-01-05 12:50 UTC, neeta-hmcts approved these changes

2024-01-11 10:18 UTC, merged