Civ 1360 children live with you disabled
hmcts/civil-citizen-ui pull request #284
Opened 2022-03-30 15:24 UTC by osheaf01

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-1360

### Change description ###

Asking if children are disabled screen - but only when certain preceding conditions are met.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-03-31 07:56 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/dependants/childrenDisabilityService.ts
> +      if ((statementOfMeans?.disability?.option == YesNo.NO) || (statementOfMeans?.disability?.option == YesNo.YES &&
this is a bit hard to read. perhaps you could put the business logic into the model rather then in the service. for example put the knowlege whether the disability option is set to yes in the disability model for example disability.isOptionYesSelected(). The same with severeDisability and partnerDisablitity then in your service you can just return without if eg. return statementOfMeans?.disability?.isOptionYesSelected || (statementOfMeans?.disability?.isOptionYesSelected && statementOfMeans?.severedisability?.isOptionYesSelected && s(statementOfMeans?.partnerDisability?.isOptionYesSelected )

2022-03-31 07:59 UTC, TatsyMaslova commented on src/main/common/form/models/statementOfMeans/dependants/numberOfChildren.ts
> +export function totalNumberOfChildren(numberOfChildren: NumberOfChildren) {
not sure it is clean to put an export function inside a class. could be a method inside a class and have that business logic inside the model

2022-03-31 08:02 UTC, TatsyMaslova commented on src/main/common/form/models/statementOfMeans/dependants/numberOfChildren.ts
> +export function totalNumberOfChildren(numberOfChildren: NumberOfChildren) {
in addition this needs a unit test :)

2022-03-31 09:04 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/dependants/betweenSixteenAndNineteenService.ts
> +    return claim;
Why should it return claim?

2022-03-31 09:07 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/dependants/dependantsService.ts
> +      return civilClaimResponse.case_data;
again i don't think it should return anything when it is saving data.

2022-03-31 12:49 UTC, osheaf01 commented on src/main/modules/statementOfMeans/dependants/betweenSixteenAndNineteenService.ts
> +    return claim;
Controller needs Claim to decide which redirect to use.
I can look at moving the logic about asking whether to ask if children are disabled into Claim itself.

2022-03-31 12:51 UTC, osheaf01 commented on src/main/modules/statementOfMeans/dependants/childrenDisabilityService.ts
> +      if ((statementOfMeans?.disability?.option == YesNo.NO) || (statementOfMeans?.disability?.option == YesNo.YES &&
Unit tests added. Will refactor to make it slightly easier to read. 
It's not a terribly simple algorithm.

2022-03-31 13:24 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/dependants/childrenDisabilityService.ts
> +    return (statementOfMeans?.dependants?.numberOfChildren && numberOfChildren.totalNumberOfChildren() > 0 &&
you only need to check whether you numberOfChildren is not undefined. so i think it would be `numberOfChildren?.totalNumberOfChildren()>0 && ...`

2022-03-31 13:41 UTC, osheaf01 commented on src/main/modules/statementOfMeans/dependants/childrenDisabilityService.ts
> +    return (statementOfMeans?.dependants?.numberOfChildren && numberOfChildren.totalNumberOfChildren() > 0 &&
I'll check and rerun

2022-03-31 13:42 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/dependants/childrenDisabilityService.ts
> +    form.errors = validator.validateSync(form.model);
in my opinion validation can be inside the generic form. because it contains model. and also i don't think it should be validateSync. so we could have a const validator outside the generic form and then a method validate but that is just my opionion. For example inside GenericModel:
` public async validate() {
    this.errors = await validator.validate(this.model as unknown as object);
  }`

2022-03-31 14:31 UTC, osheaf01 commented on src/main/modules/statementOfMeans/dependants/childrenDisabilityService.ts
> +    form.errors = validator.validateSync(form.model);
Moved to genericForm.

2022-03-31 14:44 UTC, TatsyMaslova approved these changes

2022-04-01 07:47 UTC, LeonardoPalmeiro requested changes

2022-04-01 07:47 UTC, LeonardoPalmeiro commented on src/main/common/form/models/statementOfMeans/dependants/numberOfChildren.ts
>    const numberValue: number = parseFloat(value);
maybe in this part we could use parseInt
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt
what do you think ?

2022-04-01 07:49 UTC, LeonardoPalmeiro requested changes
there are some spots untested.
![image](https://user-images.githubusercontent.com/93268657/161219168-6cabd337-912a-4e16-848b-f9d9a5953dc9.png)

2022-04-01 08:35 UTC, osheaf01 commented on src/main/common/form/models/statementOfMeans/dependants/numberOfChildren.ts
>    const numberValue: number = parseFloat(value);
I thought so, too, I think it's definitely an Integer. Taoufik wrote this so reluctant to change it too much.

2022-04-04 17:53 UTC, LeonardoPalmeiro approved these changes

2022-04-07 12:24 UTC, merged