CIV-9939 Payment url
hmcts/civil-citizen-ui pull request #2840
Opened 2023-12-22 14:55 UTC by ElifDenizEsea

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-9939
### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-12-22 15:12 UTC, jeswanth-hmcts submitted a review, later dismissed

2023-12-22 15:12 UTC, jeswanth-hmcts commented on src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
> +    const claim = await getCaseDataFromStore(claimId);
Correct me  if I am wrong , but are we not  using here to get  case details with userid+caseid as key

2024-01-02 09:44 UTC, neeta-hmcts commented on src/main/common/form/models/helpWithFees/feeType.ts
> +  CLAIM = 'CLAIM',
In Civil service the feeType used is 'CLAIMISSUED'.. we should use the same in CUI for consistency

2024-01-02 12:40 UTC, paul-pearson requested changes

2024-01-02 12:40 UTC, paul-pearson commented on src/main/common/form/models/helpWithFees/feeType.ts
> +  CLAIM = 'CLAIMISSUED',
It would be best to use `CLAIMISSUED = 'CLAIMISSUED',`

2024-01-02 12:52 UTC, neeta-hmcts commented on src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
> +    const paymentRedirectInformation = await getFeePaymentRedirectInformation(claimId, FeeType.CLAIM, req);
type is incorrect

2024-01-02 13:19 UTC, ElifDenizEsea commented on src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
> +    const claim = await getCaseDataFromStore(claimId);
done

2024-01-02 13:19 UTC, ElifDenizEsea commented on src/main/common/form/models/helpWithFees/feeType.ts
> +  CLAIM = 'CLAIMISSUED',
done

2024-01-02 13:19 UTC, ElifDenizEsea commented on src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
> +    const paymentRedirectInformation = await getFeePaymentRedirectInformation(claimId, FeeType.CLAIM, req);
done

2024-01-02 15:23 UTC, ElifDenizEsea commented on src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
> +    const claimId = req.params.id;
it is used

2024-01-02 15:23 UTC, ElifDenizEsea commented on src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
> +
done

2024-01-03 10:45 UTC, neeta-hmcts approved these changes

2024-01-03 12:58 UTC, neeta-hmcts requested changes
As discussed this will need backend changes too,

2024-01-04 10:24 UTC, neeta-hmcts approved these changes

2024-01-04 10:53 UTC, closed without merging