Civ 1374 are you behind on tax payments
hmcts/civil-citizen-ui pull request #285
Opened 2022-03-31 13:09 UTC by TatsyMaslova

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-1374

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-03-31 15:57 UTC, osheaf01 commented on config/default.yaml
> +    clientSecret: 'citizen-ui-secret'
My PR does this too! Let's see who gets there first! ;)

2022-03-31 16:11 UTC, TatsyMaslova commented on config/default.yaml
> +    clientSecret: 'citizen-ui-secret'
😛

2022-03-31 16:13 UTC, osheaf01 commented on src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
> +  @IsDefined({message: VALID_REASON_REQUIRED})
As above

2022-03-31 16:15 UTC, osheaf01 commented on src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
> +  }
Maybe use a regex here? 
According to doc, Number.isNaN is more robust than plain isNaN.

2022-03-31 16:17 UTC, osheaf01 commented on src/main/common/utils/yesNoOptionConverter.ts
> +  }
If declared is undefined, are you intending to return convertedYesNoValue as undefined?

2022-03-31 16:18 UTC, TatsyMaslova commented on src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
> +  }
regex wont work here - this.amountYouOwe is a number Number.isNaN() expects a string 😸

2022-03-31 16:19 UTC, TatsyMaslova commented on src/main/common/utils/yesNoOptionConverter.ts
> +  }
yes

2022-03-31 16:19 UTC, osheaf01 commented on src/main/common/utils/yesNoOptionConverter.ts
> +  if (option) {
What if option is undefined?

2022-03-31 16:19 UTC, osheaf01 commented on src/main/modules/statementOfMeans/dependants/betweenSixteenAndNineteenService.ts
My PR fixed this too :)

2022-03-31 16:21 UTC, TatsyMaslova commented on src/main/common/utils/yesNoOptionConverter.ts
> +  if (option) {
it will return undefined

2022-03-31 16:21 UTC, osheaf01 commented on src/main/modules/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.ts
> +    }
`taxPayments?.owed), taxPayments?.amountOwed, taxPayments?.reason` ?

2022-03-31 16:22 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.ts
> +    }
it already checked that that taxPayments exist in the if statement above

2022-03-31 16:26 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/dependants/betweenSixteenAndNineteenService.ts
lets race who gets there first 😝

2022-03-31 16:29 UTC, TatsyMaslova commented on src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
> +  @IsDefined({message: VALID_OWED_AMOUNT_REQUIRED})
no. because its inside the model. o will never be undefined. o is a model 😉

2022-03-31 16:29 UTC, TatsyMaslova commented on src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
> +  @IsDefined({message: VALID_REASON_REQUIRED})
as above no. because o is a model it will never be undefined

2022-03-31 16:29 UTC, osheaf01 commented on src/main/modules/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.ts
> +    claim.statementOfMeans.taxPayments = {
conditional chaining to check statementOfMeans?

2022-03-31 16:30 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.ts
> +    claim.statementOfMeans.taxPayments = {
no because they will never be null or undefined 😄

2022-03-31 16:38 UTC, osheaf01 commented on src/test/unit/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.test.ts
> +    it('should return string 1.22 when amount you owe is 1.22', () => {
What if the number is negative? Probably shouldn't be allowable input? Can you owe -£5?

2022-03-31 16:40 UTC, osheaf01 commented on src/test/unit/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.test.ts
> +      //When
Make this `const form = new OnTaxPayments(YesNo.YES, undefined, undefined);` so that it's obvious you're testing for expected input that isn't present?

2022-03-31 16:41 UTC, osheaf01 commented on src/test/unit/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.test.ts
> +      //When
As above, 3rd argument undefined?

2022-03-31 16:42 UTC, osheaf01 commented on src/test/unit/common/utils/yesNoOptionConverter.test.ts
> +    });
Expecting false for `convertFromYesNo(undefined);` ?

2022-03-31 16:44 UTC, osheaf01 commented on src/test/unit/modules/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.test.ts
> +      //Then
What's '123'? Is that a claimId?

2022-03-31 17:17 UTC, TatsyMaslova commented on src/test/unit/modules/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.test.ts
> +      //Then
yep it is. can be anything really. just a string

2022-03-31 17:18 UTC, TatsyMaslova commented on src/test/unit/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.test.ts
> +      //When
no need because if you don't put the third argument it will already be undefined

2022-03-31 17:18 UTC, TatsyMaslova commented on src/test/unit/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.test.ts
> +      //When
no need because if you don't specify arguments they will be undefined

2022-03-31 17:37 UTC, TatsyMaslova commented on src/test/unit/common/utils/yesNoOptionConverter.test.ts
> +    });
thanks good point! done

2022-04-01 07:36 UTC, LeonardoPalmeiro approved these changes

2022-04-01 08:14 UTC, RosDiaf approved these changes

2022-04-01 08:14 UTC, RosDiaf commented on src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
> +  @Min(0.01, {message: VALID_OWED_AMOUNT_REQUIRED})
Should we put 0.01 in the validationConstraints.ts ? 
As export const MIN_AMOUNT_VALUE = 0.01;
Because I have the same on my screen

2022-04-01 08:20 UTC, laarmada requested changes
minor change

2022-04-01 08:20 UTC, laarmada commented on src/main/modules/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.ts
> +  let claim = await getCaseDataFromStore(claimId);
could we change that code for this one?:
let claim = await getCaseDataFromStore(claimId) || new Claim();
if (!claim.statementOfMeans) {
  claim.statementOfMeans = new StatementOfMeans();
}
return claim;
};

2022-04-01 08:27 UTC, TatsyMaslova commented on src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
> +  @Min(0.01, {message: VALID_OWED_AMOUNT_REQUIRED})
good point Rosario

2022-04-01 10:53 UTC, laarmada approved these changes

2022-04-04 12:54 UTC, merged