CIV-8792 Fee & Pay integration - POSTPayment Status API and Navigation
hmcts/civil-citizen-ui pull request #2851
Opened 2024-01-02 15:23 UTC by manish14836

Please remove this line and everything above and fill the following sections:

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-8792

### Change description ###

 Fee & Pay integration - POSTPayment Status API and Navigation

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2024-01-03 10:56 UTC, jeswanth-hmcts approved these changes

2024-01-03 10:56 UTC, jeswanth-hmcts commented on src/main/routes/features/claim/payment/claimFeePaymentConfirmationController.ts
> +  try {
The proper type is missing for req; res call back handler parameters

2024-01-03 11:04 UTC, ElifDenizEsea submitted a review, later dismissed

2024-01-03 15:41 UTC, kalachandrasekar1 approved these changes

2024-01-05 09:30 UTC, jarekPierchala requested changes

2024-01-05 09:30 UTC, jarekPierchala commented on src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
> +import { CLAIM_FEE_BREAKUP, CLAIM_FEE_URL} from 'routes/urls';
remove space

2024-01-05 09:30 UTC, jarekPierchala commented on src/main/routes/features/claim/payment/claimFeePaymentConfirmationController.ts
> +import { getRedirectUrl } from 'services/features/claim/payment/claimFeePaymentConfirmationService';
remove space. Keep the code consistant as much as you can

2024-01-05 12:25 UTC, manish14836 commented on src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
> +import { CLAIM_FEE_BREAKUP, CLAIM_FEE_URL} from 'routes/urls';
done

2024-01-05 12:25 UTC, manish14836 commented on src/main/routes/features/claim/payment/claimFeePaymentConfirmationController.ts
> +import { getRedirectUrl } from 'services/features/claim/payment/claimFeePaymentConfirmationService';
done.

2024-01-05 15:18 UTC, neeta-hmcts submitted a review, later dismissed

2024-01-05 15:38 UTC, kannan-v-hmcts commented on src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
After the payment status is fetch, is it saved in redis cache ?

2024-01-05 15:43 UTC, kannan-v-hmcts commented on src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
After the payment status is fetch, is it saved in redis cache ?

2024-01-05 16:13 UTC, manish14836 commented on src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
As discussed, we are not saving status in cache as part of this story. If required in future story it can be added.

2024-01-05 17:33 UTC, paul-pearson approved these changes

2024-01-08 16:00 UTC, manish14836 commented on src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
> +    claim.claimDetails.claimFeePayment=paymentRedirectInformation;
We cannot assign value to optional.

2024-01-08 16:00 UTC, manish14836 commented on src/main/routes/features/claim/payment/claimFeePaymentConfirmationController.ts
> +claimFeePaymentConfirmationController.get([CLAIM_FEE_PAYMENT_CONFIRMATION_URL, CLAIM_FEE_PAYMENT_CONFIRMATION_URL_WITH_UNIQUE_ID], (async (req:any, res, next: NextFunction) => {
Added type

2024-01-08 16:01 UTC, manish14836 commented on src/main/common/form/models/claim/details/claimDetails.ts
> +  constructor(reason?: Reason, timeline?: ClaimantTimeline, helpWithFees?: HelpWithFees, evidence?: Evidence,breathingSpace?: BreathingSpace, statementOfTruth?: QualifiedStatementOfTruth, claimFeePay
Removed claimFeePayment?: PaymentInformation from constructor as not being used in any scenario

2024-01-08 16:58 UTC, paul-pearson submitted a review, later dismissed

2024-01-08 17:06 UTC, jarekPierchala submitted a review, later dismissed

2024-01-19 16:19 UTC, merged