CIV-11812
hmcts/civil-citizen-ui pull request #2854
Opened 2024-01-03 09:23 UTC by portizdev

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2024-01-04 10:43 UTC, paul-pearson requested changes

2024-01-04 10:43 UTC, paul-pearson commented on src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.ts
> +  const totalClaimAmount: number = claim.hasClaimantSettleTheClaimForDefendantPartlyPaidAmount() ? claim.partialAdmissionPaymentAmount() : claim.totalClaimAmount;
Might be better to call this just `claimAmount` or similar (as has been done below) so as not to confuse it with `claim.totalClaimAmount`.

2024-01-08 08:58 UTC, portizdev commented on src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.ts
> +  const totalClaimAmount: number = claim.hasClaimantSettleTheClaimForDefendantPartlyPaidAmount() ? claim.partialAdmissionPaymentAmount() : claim.totalClaimAmount;
Done!

2024-01-08 09:09 UTC, GorilaNaranja approved these changes

2024-01-08 09:10 UTC, manish14836 approved these changes

2024-01-08 09:37 UTC, neeta-hmcts approved these changes

2024-01-08 09:43 UTC, paul-pearson submitted a review, later dismissed

2024-02-02 14:04 UTC, manish14836 approved these changes

2024-02-05 14:01 UTC, merged