CIV-12106 - Fix of Final Orders test
hmcts/civil-citizen-ui pull request #2883
Opened 2024-01-08 16:36 UTC by m-meulendijks-v1

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-12106

### Change description ###
Fixing final order test for CUI

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-01-09 12:08 UTC, mounikahmcts submitted a review, later dismissed

2024-01-09 12:26 UTC, marianadpereira requested changes
Hi Max, all good, just need to also reenable this one https://github.com/hmcts/civil-citizen-ui/pull/2880/files#diff-8c9aeef82724497b6f2e789c4d25ed4a6c732df911d6b0b047210707b7848958

2024-01-12 16:16 UTC, laarmada approved these changes

2024-01-12 16:30 UTC, dharmendrak approved these changes

2024-01-17 09:55 UTC, marianadpereira approved these changes

2024-01-17 10:02 UTC, merged