CIV-11845 Court accepted claimants plan
hmcts/civil-citizen-ui pull request #2929
Opened 2024-01-15 10:38 UTC by ElifDenizEsea

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-11845

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-01-16 09:06 UTC, manish14836 commented on src/main/services/features/claimantResponse/signSettlmentAgreementService.ts
> +  console.log(claim.claimantResponse.suggestedPaymentIntention.paymentDate);
Remove this or use logger.

2024-01-16 09:09 UTC, manish14836 commented on src/main/common/utils/repaymentUtils.ts
> +
Remove this

2024-01-16 09:10 UTC, manish14836 commented on src/main/common/utils/repaymentUtils.ts
> +
Remove this

2024-01-16 14:57 UTC, jarekPierchala requested changes

2024-01-16 14:57 UTC, jarekPierchala commented on src/main/common/utils/repaymentUtils.ts
> +};
empty line below please

2024-01-16 14:57 UTC, jarekPierchala commented on src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
> +
no need for that empty line

2024-01-16 15:17 UTC, GorilaNaranja commented on src/main/common/utils/repaymentUtils.ts
> +export const getNumberOfInstalmentsForClaimantPlan = (claim: Claim): number => {
Try to pass something instead the full object (Claim) to optimize the function. For example: (amount, repaymentPlan)

2024-01-16 15:43 UTC, GorilaNaranja commented on src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
> +export const buildSummaryForPayByInstallments = (claim: Claim, claimId: string, lng: string,isClaimantPlanAccepted: boolean): SummarySection => {
Instalments instead Installments

2024-01-16 15:47 UTC, GorilaNaranja commented on src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
> +  const instalmentAmount = isClaimantPlanAccepted ? getPaymentAmountClaimantPlan(claim) : getPaymentAmount(claim);
Same condition twice, we can refactor this to have only one condition:
if (isClaimantPlanAccepted) {
  getPaymentAmountClaimantPlan(claim);
  getRepaymentFrequencyForClaimantPlan(claim) :
} else { ... }

2024-01-16 15:48 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
> +export const buildSummaryForPayByInstallments = (claim: Claim, claimId: string, lng: string,isClaimantPlanAccepted: boolean): SummarySection => {
done

2024-01-16 15:48 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
> +
done

2024-01-16 15:48 UTC, ElifDenizEsea commented on src/main/common/utils/repaymentUtils.ts
> +};
done

2024-01-16 15:50 UTC, GorilaNaranja commented on src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
> +    if (claim.claimantResponse.suggestedPaymentIntention.paymentOption == PaymentOptionType.BY_SET_DATE) {
use ===

2024-01-16 15:51 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
> +  const instalmentAmount = isClaimantPlanAccepted ? getPaymentAmountClaimantPlan(claim) : getPaymentAmount(claim);
I tried that but with more if and using let instead of const made it harder to read

2024-01-16 16:06 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
> +    if (claim.claimantResponse.suggestedPaymentIntention.paymentOption == PaymentOptionType.BY_SET_DATE) {
done

2024-01-16 16:29 UTC, ElifDenizEsea commented on src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
> +    } else if (claim.claimantResponse.suggestedPaymentIntention.paymentOption == PaymentOptionType.INSTALMENTS) {
done

2024-01-17 11:27 UTC, ElifDenizEsea commented on src/main/common/utils/repaymentUtils.ts
> +
done

2024-01-17 11:31 UTC, jarekPierchala submitted a review, later dismissed

2024-01-17 11:39 UTC, GorilaNaranja submitted a review, later dismissed

2024-01-22 17:27 UTC, merged