CIV-12143 QuickLipClaimCreationTesting
hmcts/civil-citizen-ui pull request #2937
Opened 2024-01-15 17:00 UTC by rhysbeazleyy

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-12143

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2024-01-24 09:22 UTC, neeta-hmcts commented on src/main/routes/features/claim/createDraftClaim.ts
> +    const userId = req.session?.user?.id;
move the business logic out of the controller.

2024-01-24 09:25 UTC, neeta-hmcts commented on src/main/routes/features/claim/createDraftClaim.ts
> +const draftClaim = {
Move this Mock Json in the common file as it's being used in two places hence can be re-used the same.

2024-01-24 09:26 UTC, neeta-hmcts commented on src/main/routes/features/claim/createDraftClaim.ts
> +    draftClaimCreatedAt: '2023-12-05T11:33:43.386Z',
instead of hardcoding it use now date

2024-01-24 10:30 UTC, manish14836 commented on src/main/routes/features/claim/createDraftClaim.ts
> +        individualFirstName: 'ss',
Suggestion:Give proper name. For ex:- 'Claimant Guy', 'Defendant Guy'

2024-01-24 12:44 UTC, paul-pearson requested changes

2024-01-24 12:44 UTC, paul-pearson commented on src/main/views/features/claim/create-draft.njk
> +  {{ setPageTitle('PAGES.FEE_CHANGE.PAGE_TITLE') }}
I think this is the wrong page title.

2024-01-24 12:44 UTC, paul-pearson commented on src/main/routes/features/claim/createDraftClaim.ts
> +const checkAnswersViewPath = 'features/claim/create-draft';
Probably const should be named `createDraftViewPath` or similar.

2024-01-24 14:03 UTC, jeswanth-hmcts commented on src/main/modules/draft-store/draftClaimCache.ts
> +  draftClaim.case_data.claimFee.calculatedAmountInPence = '45500';
duplicate value , exists same in mock data

2024-01-24 14:11 UTC, jeswanth-hmcts commented on src/main/modules/draft-store/draftClaimCache.ts
> +        emailAddress: 'citizen.user1@gmail.com',
To receive the emails, it would be better to replace the white-listed email 'civilmoneyclaimsdemo@gmail.com'.

2024-01-26 11:15 UTC, jarekPierchala submitted a review, later dismissed

2024-02-02 11:27 UTC, jeswanth-hmcts commented on src/test/functionalTests/specClaimHelpers/api/apiRequest.js
> +      .then(response => response.json());
Since await is used no need to use .then instead of  can return directly response.json().id once promise is resolved

2024-02-02 11:34 UTC, manish14836 commented on src/test/functionalTests/specClaimHelpers/api/steps.js
> +    caseId = null;
Seems unnecessary , plz check

2024-02-02 11:47 UTC, jeswanth-hmcts commented on src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaim.js
> +            [Object]: undefined,
is this expected

2024-02-02 11:47 UTC, jeswanth-hmcts commented on src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaim.js
> +            [Object]: undefined,
is this expected value

2024-02-07 09:26 UTC, ElifDenizEsea approved these changes

2024-02-07 15:17 UTC, rhysbeazleyy commented on src/test/functionalTests/specClaimHelpers/api/apiRequest.js
> +    Logger.info('The value of the Auth Token from the startEventForCitizen() : '+tokens.userAuth);
remove line 83 + 84

2024-02-08 09:13 UTC, jarekPierchala approved these changes

2024-02-08 09:15 UTC, ElifDenizEsea submitted a review, later dismissed

2024-02-16 10:34 UTC, ElifDenizEsea submitted a review, later dismissed

2024-02-16 10:52 UTC, neeta-hmcts commented on src/test/config.js
> +    type: 'defendant',
type should be claimant

2024-02-16 10:55 UTC, neeta-hmcts approved these changes

2024-02-16 10:56 UTC, jarekPierchala approved these changes

2024-02-22 17:47 UTC, merged