Feature/civ 1469/debts you are behind
hmcts/civil-citizen-ui pull request #297
Opened 2022-04-07 12:16 UTC by laperla11

**Before creating a pull request make sure that:**

- [X] commit messages are meaningful and follow good commit message guidelines
- [X] README and other documentation has been updated / added (if needed)
- [X] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-04-07 13:53 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/priorityDebtsService.ts
> +export const convertToForm = (debts: any): PriorityDebts => {
should we specify a type there instead of any?

2022-04-07 14:09 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/priorityDebtsService.ts
> +  const convertedData: PriorityDebts = new PriorityDebts();
don't think its good to have any as parameter. also don't think this logic belongs in this service. perhaps a converter?

2022-04-07 14:12 UTC, TatsyMaslova commented on src/main/modules/statementOfMeans/priorityDebtsService.ts
> +  formattedErrors: DebtsError,
this too. no need to have it in the service. and also can do it simpler with generic form

2022-04-07 14:21 UTC, TatsyMaslova requested changes

2022-04-07 14:21 UTC, TatsyMaslova commented on src/main/routes/features/response/statementOfMeans/priorityDebtsController.ts
> +const router = express.Router();
perhaps rename router to priorityDebptController

2022-04-07 14:29 UTC, LeonardoPalmeiro approved these changes
brilliant

2022-04-07 14:54 UTC, laarmada commented on src/main/common/form/models/statementOfMeans/priorityDebtDetails.ts
> +const generateErrorMessageForValidTwoDecimalNumber = (name: string): string =>
shoul we add to Error message constant file?

2022-04-07 14:54 UTC, laarmada commented on src/main/modules/statementOfMeans/priorityDebtsService.ts
> +  if (claim === undefined || claim === null) {
I think claim never will be null or undefined....

2022-04-07 15:03 UTC, TatsyMaslova commented on src/main/views/macro/conditional-checkBoxHTML.njk
> +      text: "4 weeks",
need translation function

2022-04-07 15:03 UTC, TatsyMaslova commented on src/main/views/macro/conditional-checkBoxHTML.njk
> +      text: "2 weeks",
need translation function

2022-04-07 15:09 UTC, TatsyMaslova requested changes

2022-04-07 15:09 UTC, TatsyMaslova commented on src/main/views/question-template.njk
> +            {% if errors %}
i would prefer to find out whether we have errors from generic form form.hasErrors rather then putting errors in the view

2022-04-07 15:09 UTC, TatsyMaslova commented on src/main/routes/features/response/statementOfMeans/priorityDebtsController.ts
> +      await validateForm(convertedDebtValues);
if you look generic form has a method validate you can call validate there if you are using generic form

2022-04-07 15:09 UTC, TatsyMaslova commented on src/main/routes/features/response/statementOfMeans/priorityDebtsController.ts
> +        const errorList = listFormErrors(priorityDebtErrors);
i am not sure about the formatFormErrors i think the knowledge about errors should be only in the form rather then in the service and the form.

2022-04-08 08:10 UTC, TatsyMaslova commented on src/main/views/features/response/statementOfMeans/priority-debts.njk
> +              text: checkBoxField.text,
need translate function here

2022-04-08 08:14 UTC, TatsyMaslova commented on src/main/views/question-template.njk
> +{% from "govuk/components/back-link/macro.njk" import govukBackLink %}
Not very sure what this question -template njk is and where it is used going to be used?

2022-04-11 09:57 UTC, laarmada approved these changes
Ok

2022-04-11 11:06 UTC, TatsyMaslova approved these changes

2022-04-11 16:16 UTC, merged