CIV-11541 Bilingual check on state control
hmcts/civil-citizen-ui pull request #2971
Opened 2024-01-18 11:20 UTC by ElifDenizEsea

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-11541

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-01-18 11:35 UTC, kalachandrasekar1 approved these changes

2024-01-18 11:58 UTC, jarekPierchala requested changes

2024-01-18 11:58 UTC, jarekPierchala commented on src/main/routes/guards/claimantResponseConfirmationGuard.ts
> +    if (claim.isClaimantIntentionPending() && ((!claim.claimantBilingualLanguagePreference) || claim.claimantBilingualLanguagePreference === ClaimBilingualLanguagePreference.ENGLISH)) {
i think that condition is long enough to put in separate method ;)

2024-01-19 09:06 UTC, laarmada approved these changes

2024-01-22 16:18 UTC, merged