Civ 1135 what date pay on
hmcts/civil-citizen-ui pull request #300
Opened 2022-04-08 17:46 UTC by osheaf01

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-1135

### Change description ###
Admit and Pay By date - what date will you pay on?

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-04-11 07:23 UTC, LeonardoPalmeiro requested changes

2022-04-11 07:23 UTC, LeonardoPalmeiro commented on src/main/common/form/models/admission/fullAdmission/paymentOption/paymentDate.ts
> +// const yesterday : Date = new Date(Date.now() - 1000*60*60*24);
please remove the comment

2022-04-11 07:23 UTC, LeonardoPalmeiro commented on src/main/modules/admission/fullAdmission/paymentOption/paymentDateService.ts
> +      return new Date();
it is worth return like paymentDate with all information that you need?

2022-04-11 07:34 UTC, commitBlob commented on src/main/modules/admission/fullAdmission/paymentOption/paymentDateService.ts
> +      const case_data = await getCaseDataFromStore(claimId);
are we using snake_case for local variables or camelCase?

2022-04-11 08:35 UTC, osheaf01 commented on src/main/modules/admission/fullAdmission/paymentOption/paymentDateService.ts
> +      const case_data = await getCaseDataFromStore(claimId);
We seem to be using `case_data` as standard in the code right now, but happy to amend if we all think caseData is more appropriate?

2022-04-11 08:39 UTC, osheaf01 commented on src/main/modules/admission/fullAdmission/paymentOption/paymentDateService.ts
> +      return new Date();
I thought of returning the PaymentDate object but not sure we need to store the whole thing? I was doing that in an earlier iteration but thought it was overkill, once I noticed we're storing `respondent1ResponseDeadline` in Claim as a Date.

2022-04-11 08:50 UTC, commitBlob commented on src/main/modules/admission/fullAdmission/paymentOption/paymentDateService.ts
> +      const case_data = await getCaseDataFromStore(claimId);
I don't mind either way, happy for team to decide

2022-04-11 08:56 UTC, TatsyMaslova commented on src/main/modules/admission/fullAdmission/paymentOption/paymentDateService.ts
> +      const case_data = await getCaseDataFromStore(claimId);
i think we don't use usually snake case for the variables. the snake case for caseData in the actual json is because it came to us like that from ccd, does not mean though that for variables that represent case data we need to maintain the snake case. I actually think it would be cleaner to stick to our coding standards that Sergio defined in confluence and have it in camelCase

2022-04-11 11:29 UTC, osheaf01 commented on src/main/modules/admission/fullAdmission/paymentOption/paymentDateService.ts
> +      const case_data = await getCaseDataFromStore(claimId);
Going to call it `claim`

2022-04-12 10:37 UTC, TatsyMaslova approved these changes

2022-04-12 10:46 UTC, LeonardoPalmeiro approved these changes

2022-04-12 12:02 UTC, GorilaNaranja approved these changes

2022-04-26 14:59 UTC, merged