CIV-11411 Logout button problem
hmcts/civil-citizen-ui pull request #3084
Opened 2024-02-05 15:52 UTC by ElifDenizEsea

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-11411

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-02-06 10:58 UTC, portizdev requested changes

2024-02-06 10:58 UTC, portizdev commented on src/main/views/features/public/eligibility/apply-for-help-with-fees.njk
> -{% set hideLogout = true  %}
Are you sure we need these changes? In eligibility we don't have a logOut icon because the user doesn't have to log in, they are public pages.  Same for cookies pages.

2024-02-06 11:36 UTC, ElifDenizEsea commented on src/main/views/features/public/eligibility/apply-for-help-with-fees.njk
> -{% set hideLogout = true  %}
it is added in log in, so if there is no log in there won't be logout button

2024-02-07 08:36 UTC, portizdev approved these changes

2024-02-07 09:05 UTC, jeswanth-hmcts approved these changes

2024-02-07 09:06 UTC, manish14836 approved these changes

2024-02-08 14:21 UTC, merged