Feature/CIV-1892/Part admit - how much do you admit you owe?
hmcts/civil-citizen-ui pull request #323
Opened 2022-04-14 14:12 UTC by laperla11

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-1892

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-04-14 15:20 UTC, TatsyMaslova approved these changes

2022-04-14 16:15 UTC, osheaf01 commented on src/main/common/form/validators/equalToOrLessThanPropertyValueValidator.ts
>        const propertyValue = (validationArguments.object as any | Form)[property];
Typo - 'strictComparison'

2022-04-14 16:17 UTC, osheaf01 approved these changes
LGTM

2022-04-14 16:28 UTC, osheaf01 commented on src/main/common/models/PartialAdmission.ts
> +import {HowMuchDoYouOwe} from '../form/models/admission/partialAdmission/howMuchDoYouOwe';
Filename should be partialAdmission.ts to be consistent with all the other typescript filename nomenclature?

2022-04-14 16:33 UTC, osheaf01 commented on src/main/modules/admission/partialAdmission/howMuchDoYouOweService.ts
> +      const addmittedAmount = claim.partialAdmission.howMuchDoYouOwe.amount;
Pretty sure claim can never be undefined here, due to what getCaseDataFromStore returns, so can remove the '?'

2022-04-14 16:33 UTC, osheaf01 commented on src/main/modules/admission/partialAdmission/howMuchDoYouOweService.ts
> +      const addmittedAmount = claim.partialAdmission.howMuchDoYouOwe.amount;
Typo - 'addmittedAmount'.

2022-04-14 16:44 UTC, osheaf01 commented on src/test/unit/common/form/models/admission/partialAdmission/howMuchDoYouOwe.test.ts
> +    it('should return errors when no input is provided', () => {
Remove the comment?

2022-04-18 07:25 UTC, laarmada commented on src/main/modules/admission/partialAdmission/howMuchDoYouOweService.ts
> +      const addmittedAmount = claim.partialAdmission.howMuchDoYouOwe.amount;
what mean "{ }" in the { totalClaimAmount } .... on the other hand :  const { totalClaimAmount } = await getCaseDataFromStore(claimId); to avoid extra lines....

2022-04-18 07:41 UTC, laarmada requested changes
good job!

2022-04-18 07:41 UTC, laarmada commented on src/main/common/form/validators/equalToOrLessThanPropertyValueValidator.ts
>        const propertyValue = (validationArguments.object as any | Form)[property];
why we need this validator?

2022-04-18 07:41 UTC, laarmada commented on src/main/common/form/validators/equalToOrLessThanPropertyValueValidator.ts
>        const propertyValue = (validationArguments.object as any | Form)[property];
could you explain me in a quick call, please? :)

2022-04-18 07:41 UTC, laarmada commented on src/main/modules/admission/partialAdmission/howMuchDoYouOweService.ts
> +    return new HowMuchDoYouOwe(null,totalClaimAmount);
we should avoid use null parameters...

2022-04-19 09:27 UTC, laarmada approved these changes

2022-04-19 09:54 UTC, laperla11 commented on src/main/common/form/validators/equalToOrLessThanPropertyValueValidator.ts
>        const propertyValue = (validationArguments.object as any | Form)[property];
> good job!

thanks

2022-04-19 09:55 UTC, laperla11 commented on src/main/common/models/PartialAdmission.ts
> +import {HowMuchDoYouOwe} from '../form/models/admission/partialAdmission/howMuchDoYouOwe';
I agree with you and changed the filename as partialAdmission.

2022-04-19 09:56 UTC, laperla11 commented on src/main/common/form/validators/equalToOrLessThanPropertyValueValidator.ts
>        const propertyValue = (validationArguments.object as any | Form)[property];
> Typo - 'strictComparison'

fixed typo

2022-04-26 17:36 UTC, merged