Features/CIV-1122 - part admin have you paid claimant
hmcts/civil-citizen-ui pull request #324
Opened 2022-04-14 14:21 UTC by commitBlob

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-04-18 07:29 UTC, LeonardoPalmeiro requested changes
I believe that we could get 100% of coverage.

2022-04-18 07:29 UTC, LeonardoPalmeiro commented on src/main/views/features/response/admission/partialAdmission/already-paid.njk
> +            {{ yesNoRadioButton(t, 'alreadyPaid', 'alreadyPaid', '', form, '', {classes: 'govuk-radios--inline'}) }}
may yesNoRadioButton doesn't work with generic form because checked code is         checked: true if form.option=="yes" else false,
when we use generic form all attributes will be like form.model.<attribute>

2022-04-20 10:21 UTC, commitBlob commented on src/main/views/features/response/admission/partialAdmission/already-paid.njk
> +            {{ yesNoRadioButton(t, 'alreadyPaid', 'alreadyPaid', '', form, '', {classes: 'govuk-radios--inline'}) }}
Not sure if I understand, radio selection will come as `form.alreadyPaid = boolean`. As I am re-using yesNoRadioButton component I didn't want to change any of the logic.

2022-04-20 11:23 UTC, taomoh reviewed
I particularly like the view test you introduced 👍 
I only have a couple of minor comments

2022-04-20 11:23 UTC, taomoh commented on src/main/routes/urls.ts
> +export const CITIZEN_ALREADY_PAID_URL = `${BASE_CASE_RESPONSE_URL}/already-paid`;
should be `${BASE_CASE_RESPONSE_URL}/partial-admission/already-paid`

2022-04-20 11:23 UTC, taomoh commented on src/test/unit/views/features/response/admission/partialAdmission/already-paid.test.ts
> +  let htmlRes: Document;
Maybe this can be named htmlDocument?

2022-04-20 13:05 UTC, commitBlob commented on src/main/routes/urls.ts
> +export const CITIZEN_ALREADY_PAID_URL = `${BASE_CASE_RESPONSE_URL}/already-paid`;
added partial-admission to the url 👍

2022-04-20 13:36 UTC, taomoh approved these changes

2022-04-21 07:24 UTC, LeonardoPalmeiro requested changes
In your screen the checkbox is alight horizontally and the error message is different that we've in the previous screens.
I've attached your screen and response/statement-of-means/debts
![image](https://user-images.githubusercontent.com/93268657/164398886-9dd2b6f0-0456-4906-8dfb-b5fec00032f8.png)

![image](https://user-images.githubusercontent.com/93268657/164398653-7a2fd012-231e-4c04-b50a-6fd7c104c447.png)

2022-04-21 07:24 UTC, LeonardoPalmeiro commented on src/main/views/features/response/admission/partialAdmission/already-paid.njk
> +            {{ yesNoRadioButton(t, 'alreadyPaid', 'alreadyPaid', '', form, '', {classes: 'govuk-radios--inline'}) }}
I will try explain better.(sorry about that)
when we use generic form our object will change in your case will be form.model.alreadyPaid = boolean in this case you check box never will be checked when use yesno with genericForm.
![image](https://user-images.githubusercontent.com/93268657/164396111-048db1bf-11a2-425d-b97e-87b6664b480a.png)
if you want test it by your self.
1) access http://localhost:3001/case/1645882162449409/response/partial-admission/already-paid
2) save it
3) access again http://localhost:3001/case/1645882162449409/response/partial-admission/already-paid
we expected that your check box should be checked.

2022-04-21 07:32 UTC, laarmada requested changes

2022-04-21 07:32 UTC, laarmada commented on src/main/modules/admission/partialAdmission/partialAdmissionService.ts
> +      return claim?.partialAdmission?.claimAlreadyPaid;
you can remove ? from claim

2022-04-21 07:32 UTC, laarmada commented on src/main/routes/features/response/admision/partialAdmission/alreadyPaidController.ts
> +    const alreadyPaidData = new AlreadyPaid(req.body.alreadyPaid);
you can save code here:
const alreadyPaidForm = new GenericForm(new AlreadyPaid(req.body.alreadyPaid));

2022-04-21 07:32 UTC, laarmada commented on src/test/unit/routes/features/response/admission/partialAdmission/alreadyPaidController.test.ts
> +const mockGetExceptionDraftStore = {
we have reusable mocks created that you can reuse it.

2022-04-21 07:32 UTC, laarmada commented on src/test/unit/routes/features/response/admission/partialAdmission/alreadyPaidController.test.ts
> +const mockDraftStore = {
we have reusable mocks created that you can reuse it.

2022-04-21 07:32 UTC, laarmada commented on src/main/views/features/response/admission/partialAdmission/already-paid.njk
> +            {{ yesNoRadioButton(t, 'alreadyPaid', 'alreadyPaid', '', form, '', {classes: 'govuk-radios--inline'}) }}
I agree with leo: when you call the screen with get, you send a generic form structure.  renderView(alreadyPaidForm , res); for this reason: form.option doesn´t work you should use form.model instead of form... , '', form, '',

2022-04-21 09:57 UTC, commitBlob commented on src/main/views/features/response/admission/partialAdmission/already-paid.njk
> +            {{ yesNoRadioButton(t, 'alreadyPaid', 'alreadyPaid', '', form, '', {classes: 'govuk-radios--inline'}) }}
ah I see, sorry didn't understand initially, pushed up a fix for that

2022-04-21 09:58 UTC, commitBlob commented
> In your screen the checkbox is alight horizontally and the error message is different that we've in the previous screens. I've attached your screen and response/statement-of-means/debts ![image](https://user-images.githubusercontent.com/93268657/164398886-9dd2b6f0-0456-4906-8dfb-b5fec00032f8.png)
> 
> ![image](https://user-images.githubusercontent.com/93268657/164398653-7a2fd012-231e-4c04-b50a-6fd7c104c447.png)

screenshots provided in the ticket are displaying radios in line

2022-04-21 10:08 UTC, commitBlob commented on src/main/routes/features/response/admision/partialAdmission/alreadyPaidController.ts
> +    const alreadyPaidData = new AlreadyPaid(req.body.alreadyPaid);
sure, I think I've seen it done on the other place same way I did initially and for the consistency kept it the same
https://github.com/hmcts/civil-citizen-ui/blob/e310454b50af0582714c71e37911250ba149db07/src/main/routes/features/response/statementOfMeans/dependants/childrenDisabilityController.ts#L39

2022-04-21 10:10 UTC, commitBlob commented on src/test/unit/routes/features/response/admission/partialAdmission/alreadyPaidController.test.ts
> +const mockGetExceptionDraftStore = {
mind sending the link for reusable mock please?

2022-04-21 10:20 UTC, commitBlob commented on src/test/unit/routes/features/response/admission/partialAdmission/alreadyPaidController.test.ts
> +const mockGetExceptionDraftStore = {
Is this what you meant? `const mockGetCaseData = draftStoreService.getCaseDataFromStore as jest.Mock;`

2022-04-21 13:00 UTC, commitBlob commented on src/test/unit/routes/features/response/admission/partialAdmission/alreadyPaidController.test.ts
> +const mockGetExceptionDraftStore = {
pushed up refactor, was not aware of the mock

2022-04-21 13:01 UTC, commitBlob commented on src/test/unit/routes/features/response/admission/partialAdmission/alreadyPaidController.test.ts
> +const mockDraftStore = {
refactor should be pushed up now

2022-04-22 07:58 UTC, laarmada requested changes

2022-04-22 07:58 UTC, laarmada commented on src/main/common/models/partialAdmission.ts
> +  claimAlreadyPaid?: boolean;
thats no correct model structure: alreadyPaid?: AlreadyPaid it should be:
alreadyPaid?: AlreadyPaid

2022-04-22 07:58 UTC, laarmada commented on src/main/common/form/models/admission/partialAdmission/alreadyPaid.ts
> +    alreadyPaid?: boolean;
that´s no correct model structure. It should be:
option?: YesNoOption/string as the other screens instead of  alreadyPaid?: boolean;

2022-04-25 09:13 UTC, LeonardoPalmeiro approved these changes

2022-04-25 09:29 UTC, laarmada approved these changes

2022-04-26 18:27 UTC, merged