CIV-12895 CCJ url for settlement
hmcts/civil-citizen-ui pull request #3336
Opened 2024-03-14 12:52 UTC by ElifDenizEsea

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-12895

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-03-14 17:06 UTC, m-meulendijks-v1 approved these changes

2024-03-21 14:18 UTC, m-meulendijks-v1 approved these changes

2024-03-21 15:16 UTC, kalachandrasekar1 approved these changes

2024-03-22 07:29 UTC, laarmada requested changes
Please show the screen shot of the claim with the new changes "/:id/claimant" I think you are missing some data here...

2024-03-22 07:29 UTC, laarmada commented on src/main/routes/features/dashboard/claimantDashboardController.ts
>        caseRole = claim.isClaimant()?ClaimantOrDefendant.CLAIMANT:ClaimantOrDefendant.DEFENDANT;
If im not wrong here this vble will be undefined: "caseRole". Please test the issue as user.

2024-03-22 10:04 UTC, jeswanth-hmcts commented on src/main/routes/features/dashboard/claimantDashboardController.ts
>        caseRole = claim.isClaimant()?ClaimantOrDefendant.CLAIMANT:ClaimantOrDefendant.DEFENDANT;
In the retriveClaimDetails, we are calling an API call for roles setting  the role  in  case_data , in cui translation , we setting the value  in claim , and tested the scenario , it is working fine. PF the SS for reference
![image](https://github.com/hmcts/civil-citizen-ui/assets/134285996/959191f6-94c2-480c-9c8a-b42c2e83517c)

2024-03-22 10:11 UTC, ElifDenizEsea commented on src/main/routes/features/dashboard/claimantDashboardController.ts
>        caseRole = claim.isClaimant()?ClaimantOrDefendant.CLAIMANT:ClaimantOrDefendant.DEFENDANT;
It was coming from master I rolled back it now.

2024-03-22 10:11 UTC, ElifDenizEsea commented
<img width="476" alt="dashboard" src="https://github.com/hmcts/civil-citizen-ui/assets/61947470/5802c41e-0e3f-4dfb-b72e-3cb424463ebc">

2024-03-22 10:15 UTC, laarmada approved these changes

2024-03-25 14:15 UTC, dharmendrak approved these changes

2024-03-25 14:23 UTC, merged