Civ 1563 other expenses
hmcts/civil-citizen-ui pull request #339
Opened 2022-04-20 14:44 UTC by TatsyMaslova

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-1563

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-04-21 07:57 UTC, LeonardoPalmeiro requested changes
I've some things 
1) the add another expense button is just below in the month combobox
![image](https://user-images.githubusercontent.com/93268657/164406466-62f35bd1-18b0-4ea1-9053-c36bb7a7f893.png)
2) when we've error on other seems like the errors keep in all set of "Source of expense"
![image](https://user-images.githubusercontent.com/93268657/164406877-423dc2c0-9566-482b-8a5c-73c512db6256.png)
3) sometime the amount is no sum correctly like 100.23 and sometimes total stay with zero.

2022-04-21 07:57 UTC, LeonardoPalmeiro commented on src/main/assets/js/append-row.js
> +  function removeRowButtonEventListener(element) {
how could I test it?

2022-04-21 11:57 UTC, TatsyMaslova commented on src/main/assets/js/append-row.js
> +  function removeRowButtonEventListener(element) {
the sreenshot was probably from not updated version and also fixed the calculation now and the layout. I hope the demo explained about the remove button :) if not i can show you again

2022-04-21 12:00 UTC, TatsyMaslova commented
> I've some things
> 
> 1. the add another expense button is just below in the month combobox
>    ![image](https://user-images.githubusercontent.com/93268657/164406466-62f35bd1-18b0-4ea1-9053-c36bb7a7f893.png)
> 2. when we've error on other seems like the errors keep in all set of "Source of expense"
>    ![image](https://user-images.githubusercontent.com/93268657/164406877-423dc2c0-9566-482b-8a5c-73c512db6256.png)
> 3. sometime the amount is no sum correctly like 100.23 and sometimes total stay with zero.

As discussed these issues were from an older version. and the code was not quite up to date 😃

2022-04-21 12:02 UTC, TatsyMaslova commented
oops accidentally closed, reopening

2022-04-22 07:35 UTC, LeonardoPalmeiro approved these changes

2022-04-22 08:48 UTC, laarmada approved these changes
Amazing job!!!

2022-04-22 13:47 UTC, GorilaNaranja approved these changes

2022-04-26 16:09 UTC, merged