Feature/civ 1523 repayment plan
hmcts/civil-citizen-ui pull request #342
Opened 2022-04-21 15:04 UTC by RosDiaf

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-04-22 08:15 UTC, laarmada requested changes

2022-04-22 08:15 UTC, laarmada commented on src/main/modules/repaymentPlan/repaymentPlanService.ts
> +  const claim = await getCaseDataFromStore(claimId) || new Claim();
that is not necessary now:  || new Claim(); now getCaseDataFromStore return always a claim

2022-04-22 11:21 UTC, GorilaNaranja commented on src/main/common/form/validators/optionalDateNotInPastValidator.ts
> +    if (inputDate !== null && (inputDate < (new Date(Date.now())))) {
I'm not sure at all but maybe we can change `inputDate !== null` to `inputDate`.

2022-04-22 11:21 UTC, GorilaNaranja commented on src/main/routes/features/response/repaymentPlan/repaymentPlanController.ts
> +      if (errors && errors.length > 0) {
I think we can use `if (errors?.length) {`. Shorter and readable don't you think?

2022-04-22 11:21 UTC, GorilaNaranja commented on src/main/assets/js/calculate-length-repayment.js
> +      const plural = num < 2 ? '' : 's';
In this case it works! This is only a thought that I wanted to share with you .
That doesn't include the exceptions of the grammar. For example if the word is "Entry" the plural will be "Entrys" instead "Entries" or "Foot" will be "Foots" instead "Feet".

2022-04-22 11:58 UTC, laperla11 approved these changes

2022-04-22 11:58 UTC, laperla11 commented on src/main/common/form/models/repaymentPlan/repaymentPlanForm.ts
> +    errors?: ValidationError[]) {
Do we need `errors` property here as it is inherited from `Form`?

2022-04-22 15:40 UTC, TatsyMaslova commented on src/main/assets/js/calculate-length-repayment.js
> +(function () {
perhaps we should have a doc to explain how this can be reused (what classes we need to use so we can reuse this etc)

2022-04-22 15:42 UTC, TatsyMaslova commented on src/main/assets/js/calculate-length-repayment.js
> +      let numberOfInstalments = parseFloat(paymentAmount.value) > 0 ? Math.ceil(parseFloat(totalClaimAmount.value) / parseFloat(paymentAmount.value)) : undefined;
Could this be a const?

2022-04-22 15:44 UTC, TatsyMaslova commented on src/main/common/form/validators/optionalDateNotInPastValidator.ts
> + * Validates that the input value is not a date in the future
the doc says it validates that the date is not in the future and at the validator says DateNotInPast.. a bit confusing

2022-04-22 15:47 UTC, TatsyMaslova commented on src/main/common/form/validators/optionalDateNotInPastValidator.ts
> +@ValidatorConstraint({name: 'customDateNotInPast', async: false})
Also there is an existing validator from the library MaxDate and MinDate have you tried with them?

2022-04-22 15:50 UTC, TatsyMaslova requested changes

2022-04-22 15:50 UTC, TatsyMaslova commented on src/main/routes/features/response/repaymentPlan/repaymentPlanController.ts
> +      const validator = new Validator();
there is a validator.ts that does the validation and sets the errors in the form that you can use

2022-04-25 08:19 UTC, laarmada approved these changes

2022-04-25 09:05 UTC, TatsyMaslova approved these changes

2022-04-26 18:41 UTC, merged