CIV-13143 Claim Fee Checking
hmcts/civil-citizen-ui pull request #3480
Opened 2024-04-04 10:27 UTC by kenneth-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-13143

### Change description ###
Set up change for the claim fee checking part

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-04-05 07:00 UTC, laarmada requested changes

2024-04-05 09:16 UTC, laarmada approved these changes

2024-04-10 08:37 UTC, jeswanth-hmcts approved these changes

2024-04-10 08:37 UTC, portizdev approved these changes
Super work Kenneth!

2024-04-21 03:02 UTC, closed without merging