CIV-11710 - bundles page
hmcts/civil-citizen-ui pull request #3528
Opened 2024-04-10 15:24 UTC by m-meulendijks-v1

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-11710

### Change description ###
Add page that displays bundles info + claimant or defendant uploaded documents

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-04-10 15:32 UTC, kannan-v-hmcts approved these changes

2024-04-11 07:57 UTC, laarmada requested changes

2024-04-11 07:57 UTC, laarmada commented on src/main/routes/features/caseProgression/bundlesController.ts
> +    if (claim.isClaimant()) {
you can use a ternary expression instead of if else

2024-04-11 07:57 UTC, laarmada commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +  claimSummaryContent.push(getUploadedAfterBundle(claimId, claim, lang, true));
Is the same order for claimant and defendant view?

2024-04-11 07:57 UTC, laarmada commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +        {html: t('PAGES.CLAIM_SUMMARY.BUNDLES.DOCUMENT_TITLE', lng) + ' ' + bundleNumber},
why do you need to add a number? bundleNumber

2024-04-11 08:15 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +        {html: t('PAGES.CLAIM_SUMMARY.BUNDLES.DOCUMENT_TITLE', lng) + ' ' + bundleNumber},
Because the rows are published in reverse (latest addition at the top) and the name of the file is 'Trial Bundle'.
Yet the client wants Bundle names to now show as 'Bundle 3', 'Bundle 2', 'Bundle 1'. So I need to add the number.

2024-04-11 08:16 UTC, m-meulendijks-v1 commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +  claimSummaryContent.push(getUploadedAfterBundle(claimId, claim, lang, true));
I'm not sure what you mean? The only thing I have changed here is adding the claimId separately, rather than deriving claimId from the claim.

2024-04-11 08:25 UTC, m-meulendijks-v1 commented on src/main/routes/features/caseProgression/bundlesController.ts
> +    if (claim.isClaimant()) {
Switched to Ternary expression

2024-04-11 08:37 UTC, laarmada commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +        {html: t('PAGES.CLAIM_SUMMARY.BUNDLES.DOCUMENT_TITLE', lng) + ' ' + bundleNumber},
ok cool.

2024-04-11 08:38 UTC, laarmada commented on src/main/services/features/caseProgression/bundles/bundlesService.ts
> +  claimSummaryContent.push(getUploadedAfterBundle(claimId, claim, lang, true));
I will call you, it's better to explain by call

2024-04-11 09:40 UTC, laarmada approved these changes

2024-04-17 16:45 UTC, merged