CIV-13203 Update contact-them page
hmcts/civil-citizen-ui pull request #3541
Opened 2024-04-11 14:50 UTC by paul-pearson

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-13203

### Change description ###

Update contact-them page

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-04-11 15:32 UTC, jeswanth-hmcts approved these changes

2024-04-11 16:24 UTC, kalachandrasekar1 approved these changes

2024-04-16 08:39 UTC, LeonardoPalmeiro commented on src/main/views/features/dashboard/contact-them-new.njk
> +    <div>
would be good to have ` govuk-body govuk-!-margin-bottom-6` in here instead to add into <p>

2024-04-17 08:16 UTC, neeta-hmcts approved these changes

2024-04-17 08:25 UTC, laarmada requested changes

2024-04-17 08:25 UTC, laarmada commented on src/main/routes/urls.ts
> +export const VIEW_CLAIMANT_INFO = `${DASHBOARD_URL}/:id/information-claimant`;
please add _URL at the end

2024-04-17 08:31 UTC, jeswanth-hmcts commented on src/main/routes/urls.ts
> +export const VIEW_CLAIMANT_INFO = `${DASHBOARD_URL}/:id/information-claimant`;
added at the end

2024-04-17 08:35 UTC, portizdev submitted a review, later dismissed

2024-04-19 15:27 UTC, jarekPierchala submitted a review, later dismissed

2024-04-24 15:32 UTC, merged