CIV-13261 Settlement agreement displaying inconsistent dates
hmcts/civil-citizen-ui pull request #3557
Opened 2024-04-15 08:10 UTC by kalachandrasekar1

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-13261

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-04-15 08:41 UTC, jeswanth-hmcts commented on src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementController.test.ts
> +      //(getClaimById as jest.Mock).mockResolvedValueOnce(mockClaim);
if comment is not required, please remove the commented code

2024-04-15 09:17 UTC, kalachandrasekar1 commented on src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementController.test.ts
> +      //(getClaimById as jest.Mock).mockResolvedValueOnce(mockClaim);
removed the commented code

2024-04-15 09:23 UTC, laarmada requested changes

2024-04-15 09:23 UTC, laarmada commented on src/main/routes/features/settlementAgreement/respondSettlementAgreementController.ts
> +    const claim = await civilServiceClient.retrieveClaimDetails(claimId, <AppRequest>req);
with this call we are ignoring the current changes in redis, if exist. Please take care.

2024-04-15 09:23 UTC, laarmada commented on src/main/services/features/settlementAgreement/respondSettlementAgreementService.ts
> +    const date = claim.claimantResponse.suggestedPaymentIntention.paymentDate as unknown as PaymentDate;
as unknown... Is no so good to have that in the code, could we discuss on the code review meeting?

2024-04-25 08:35 UTC, laarmada submitted a review, later dismissed

2024-04-25 08:45 UTC, manish14836 commented on src/main/services/features/claimantResponse/signSettlmentAgreementService.ts
> +    } else if (claim.getSuggestedPaymentIntentionOptionFromClaimant() == PaymentOptionType.IMMEDIATELY) {
Use === instead of ==

2024-04-25 09:44 UTC, manish14836 submitted a review, later dismissed

2024-04-25 09:46 UTC, paul-pearson submitted a review, later dismissed

2024-04-25 10:10 UTC, kalachandrasekar1 commented on src/main/services/features/claimantResponse/signSettlmentAgreementService.ts
> +    } else if (claim.getSuggestedPaymentIntentionOptionFromClaimant() == PaymentOptionType.IMMEDIATELY) {
fixed

2024-04-25 10:13 UTC, jeswanth-hmcts submitted a review, later dismissed

2024-04-30 11:38 UTC, merged