CIV-13207 Content changes to the view the claim screen
hmcts/civil-citizen-ui pull request #3566
Opened 2024-04-16 16:24 UTC by manish14836

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-13207

### Change description ###
Content changes to the view the claim screen

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2024-04-17 10:37 UTC, jarekPierchala requested changes

2024-04-17 10:37 UTC, jarekPierchala commented on src/main/common/utils/interestUtils.ts
> +  if(interestFromDate) { return new Date(interestFromDate).toISOString(); }
return interestFromDate ? new Date(interestFromDate).toISOString() : undefined;

2024-04-17 10:57 UTC, manish14836 commented on src/main/common/utils/interestUtils.ts
> +  if(interestFromDate) { return new Date(interestFromDate).toISOString(); }
done.

2024-04-17 14:02 UTC, jeswanth-hmcts approved these changes

2024-04-17 14:13 UTC, GorilaNaranja submitted a review, later dismissed

2024-04-17 14:13 UTC, jeswanth-hmcts submitted a review, later dismissed

2024-04-17 14:14 UTC, kalachandrasekar1 approved these changes

2024-04-22 08:26 UTC, jeswanth-hmcts approved these changes

2024-04-22 08:29 UTC, neeta-hmcts submitted a review, later dismissed

2024-04-23 08:28 UTC, neeta-hmcts approved these changes

2024-04-23 08:47 UTC, jeswanth-hmcts approved these changes

2024-04-25 18:24 UTC, merged