CIV-13311 Create View orders and notices page
hmcts/civil-citizen-ui pull request #3741
Opened 2024-05-08 12:45 UTC by kenneth-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-13311

### Change description ###
Create View orders and notices page

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-05-09 09:45 UTC, jarekPierchala submitted a review, later dismissed

2024-05-09 12:51 UTC, paul-pearson approved these changes

2024-05-10 11:23 UTC, jarekPierchala approved these changes

2024-05-13 09:01 UTC, neeta-hmcts approved these changes

2024-05-13 09:34 UTC, m-meulendijks-v1 approved these changes

2024-05-13 09:52 UTC, m-meulendijks-v1 requested changes
Please add a mock for the accessibility tests.

2024-05-13 11:37 UTC, m-meulendijks-v1 submitted a review, later dismissed

2024-05-13 11:39 UTC, neeta-hmcts approved these changes

2024-05-15 20:06 UTC, merged