CIV-13650 - reformatting Dashboard page
hmcts/civil-citizen-ui pull request #3757
Opened 2024-05-09 16:55 UTC by m-meulendijks-v1

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-13650

### Change description ###
![image](https://github.com/hmcts/civil-citizen-ui/assets/107135537/a3590f43-6951-4fe8-96a7-0e87079b0303)
![image](https://github.com/hmcts/civil-citizen-ui/assets/107135537/6d23d471-ac5b-4edd-bc2f-26b871b99361)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-05-10 07:12 UTC, miguelMolina3691 approved these changes

2024-05-10 07:28 UTC, laarmada requested changes

2024-05-10 07:28 UTC, laarmada commented on src/main/views/features/dashboard/claim-summary-redesign.njk
> +{% from "govuk/components/breadcrumbs/macro.njk" import govukBreadcrumbs %}
Please remove the unnecessary imports

2024-05-10 07:28 UTC, laarmada commented on src/main/views/features/dashboard/claim-summary-redesign.njk
>    <div class="govuk-width-container govuk-!-padding-top-0">
if you use the new claim-details-tpl-dashboard.njk template we can remove that div lines

2024-05-10 07:28 UTC, laarmada commented on src/main/views/features/dashboard/claim-summary-redesign.njk
> +                   classes: "govuk-!-margin-bottom-4"
we can remove the contact us for help macro, exist in the new tamplate.

2024-05-10 07:28 UTC, laarmada commented on src/main/views/features/dashboard/claim-summary-redesign.njk
> +        <div class="govuk-grid-row govuk-!-margin-top-0">
we can remove every div with style classes.

2024-05-10 07:28 UTC, laarmada commented on src/main/views/features/dashboard/claim-summary-redesign.njk
> +                   classes: "govuk-!-margin-bottom-4"
review also if the right "support" section exist in the current template or create a reusable macro.

2024-05-10 08:30 UTC, m-meulendijks-v1 commented on src/main/views/features/dashboard/claim-summary-redesign.njk
> +        <div class="govuk-grid-row govuk-!-margin-top-0">
I am the 'content' block rather than the 'nestedContent', because otherwise the 1-3rd column won't contain the information it needs. I will detail that more in your other comment. This also means I need to keep these divs, because I overwrite the ones from the template.

2024-05-10 08:34 UTC, m-meulendijks-v1 commented on src/main/views/features/dashboard/claim-summary-redesign.njk
> +                   classes: "govuk-!-margin-bottom-4"
It is different in the new template. The new template looks like this:
```
{% block content %}
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    {% block nestedContent %}{% endblock %}
  </div>
  <div class="govuk-grid-column-one-third">
    {{ contactUsForHelp(t) }}
  </div>
</div>
{% endblock %}
```
But as you can see, that means the second column only contains the contactUsForHelp, while there needs to be more information in the column like so:
```
{# TODO: Right side #}
        <div class="govuk-grid-column-one-third">
          <div class="border-small-top"></div>
          {% if iWantToLinks.length %}
            <div class="govuk-!-margin-bottom-8">
              {{ supportLinks(t, iWantToTitle, iWantToLinks) }}
            </div>
          {% endif %}
          {% if helpSupportLinks.length %}
            {{ supportLinks(t, helpSupportTitle, helpSupportLinks) }}
          {% endif %}
          <div class="govuk-!-padding-top-8">
            {{ contactUsForHelp(t) }}
          </div>
        </div>
```
So I need to overwrite the the content block from the template. I am still using the new template in case other elements on the template get changed, it is better that all pages use a similar template rather than some using one, and others using another.

2024-05-10 08:35 UTC, m-meulendijks-v1 commented on src/main/views/features/dashboard/claim-summary-redesign.njk
> +{% from "govuk/components/breadcrumbs/macro.njk" import govukBreadcrumbs %}
Removed several unnecessary imports, many thanks.

2024-05-10 08:35 UTC, m-meulendijks-v1 commented on src/main/views/features/dashboard/claim-summary-redesign.njk
>    <div class="govuk-width-container govuk-!-padding-top-0">
I've removed two div lines that could indeed be removed.

2024-05-10 08:58 UTC, laarmada commented on src/main/views/features/dashboard/claim-summary-redesign.njk
> +                   classes: "govuk-!-margin-bottom-4"
Could we move that block of code to a Macro and reuse in other pages? or not make sense?

2024-05-10 08:59 UTC, laarmada approved these changes

2024-05-10 09:13 UTC, miguelMolina3691 approved these changes

2024-05-10 09:31 UTC, m-meulendijks-v1 commented on src/main/views/features/dashboard/claim-summary-redesign.njk
> +                   classes: "govuk-!-margin-bottom-4"
We could do it, but with the rush behind this ticket I'm not keen to do it, right now.
If another ticket for dashboard pops up, I will try and put this in a macro.

2024-05-14 07:49 UTC, dharmendrak approved these changes

2024-05-14 07:49 UTC, merged