CIV-10455 Claimant LiP screen: mark Judgment as Paid in Full
hmcts/civil-citizen-ui pull request #3764
Opened 2024-05-10 15:17 UTC by hmcts-version1-ignacio

### [CIV-10455](https://tools.hmcts.net/jira/browse/CIV-10455) ###

### Claimant LiP screen: mark Judgment as Paid in Full ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-05-27 08:32 UTC, hmcts-version1-ignacio commented on src/test/utils/mockDraftStore.ts
This change is to fix an error spotted by @m-meulendijks-v1

2024-05-28 09:34 UTC, laarmada requested changes

2024-05-28 09:46 UTC, m-meulendijks-v1 commented on src/main/routes/features/judgmentOnline/confirmYouHaveBeenPaidConfirmationController.ts
> +  const claimantDashboardUrl = constructResponseUrlWithIdParams(claimId,DASHBOARD_CLAIMANT_URL);
I think these items title/paragraph/button all get translated in the item-content.njk file, so should be fine.
For example, for title you see the 't' is in there:
```
  {% if content.type === ClaimSummaryType.TITLE %}
    {% set object = '' %}
    {% if  content.data.variables %}
      {% set object = content.data.variables %}
      <h3 class="govuk-heading-m {{ content.data.classes }}">{{ t(content.data.text,object) }}</h3>
    {% else %}
      <h3 class="govuk-heading-m {{ content.data.classes }}">{{ t(content.data.text) }}</h3>
    {% endif %}
  {% endif %}
```

2024-05-28 09:46 UTC, m-meulendijks-v1 commented on src/main/routes/features/judgmentOnline/confirmYouHaveBeenPaidConfirmationController.ts
> +export const getContent = (claimId: string): ClaimSummarySection[] => {
Agreed with Sergio

2024-05-28 09:53 UTC, m-meulendijks-v1 commented on src/main/routes/features/judgmentOnline/confirmYouHaveBeenPaidController.ts
> +    const claim = await getClaimById(claimId, req);
getClaimById saves things in Redis.
Once you no longer need Redis (because an event has finished, and case data has been updated, for instance), it's generally preferred that you delete it. You might want to use: `await deleteDraftClaimFromStore(redisKey);`

2024-05-28 13:19 UTC, hmcts-version1-ignacio commented on src/main/routes/features/judgmentOnline/confirmYouHaveBeenPaidConfirmationController.ts
> +export const getContent = (claimId: string): ClaimSummarySection[] => {
Done

2024-05-28 13:20 UTC, hmcts-version1-ignacio commented on src/main/routes/features/judgmentOnline/confirmYouHaveBeenPaidConfirmationController.ts
> +  const claimantDashboardUrl = constructResponseUrlWithIdParams(claimId,DASHBOARD_CLAIMANT_URL);
Yes, working, translated on the template.

2024-05-28 13:20 UTC, hmcts-version1-ignacio commented on src/main/views/features/judgmentOnline/confirm-you-have-been-paid.njk
> +{% extends "claim-details-tpl.njk" %}
Done

2024-05-28 15:00 UTC, m-meulendijks-v1 submitted a review, later dismissed

2024-05-29 08:15 UTC, m-meulendijks-v1 approved these changes

2024-05-29 08:52 UTC, laarmada approved these changes
Well done

2024-05-29 16:50 UTC, merged