Feature/civ 1309 create preview env
hmcts/civil-citizen-ui pull request #377
Opened 2022-04-28 11:06 UTC by LeonardoPalmeiro

### JIRA link ###

civ 1309

### Change description ###
Create the preview environment with all container 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-04-28 11:29 UTC, laarmada approved these changes

2022-04-28 11:30 UTC, TatsyMaslova approved these changes

2022-04-28 11:39 UTC, taomoh requested changes
I think we need someone with AKS/Kubernetes/Docker expertise review this
Also
`bin/generate-ssl-options.sh` and `bin/init.sh` shouldn't have been modified

2022-04-28 11:39 UTC, taomoh commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
This shouldn't have been committed

2022-04-28 11:47 UTC, LeonardoPalmeiro commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
Yes. you're right!! my  bad..
I fixed.

2022-04-28 11:53 UTC, LeonardoPalmeiro commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
bin/generate-ssl-options.sh and bin/init.sh shouldn't have been modified =>  I didn't change them

2022-04-28 11:55 UTC, LeonardoPalmeiro commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
![image](https://user-images.githubusercontent.com/93268657/165746612-f61c91de-78bb-425d-b463-f2347ccdb5a5.png)

2022-04-28 11:55 UTC, LeonardoPalmeiro commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
![image](https://user-images.githubusercontent.com/93268657/165746699-2caebdf3-6ab0-4e73-8095-c81459a7b7ab.png)

2022-04-28 11:56 UTC, taomoh commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
> Yes. you're right!! my bad.. I fixed.

It looks like it's still there

2022-04-28 11:59 UTC, taomoh commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
> bin/generate-ssl-options.sh and bin/init.sh shouldn't have been modified => I didn't change them

That's strange. Why are they showing on the PR then?

2022-04-28 12:00 UTC, LeonardoPalmeiro commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
it's was because I got some delay in my network
![image](https://user-images.githubusercontent.com/93268657/165747331-e3d0986b-ecf9-46cc-8526-4feb20ea319b.png)

2022-04-28 12:06 UTC, LeonardoPalmeiro commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
bin/generate-ssl-options.sh and bin/init.sh shouldn't have been modified => I didn't change them

That's strange. Why are they showing on the PR then?

I've no idea why this happened.
do you have any idea how to fix that?

2022-04-28 12:14 UTC, taomoh commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
You changed it. It was a permission change 😃 

https://github.com/hmcts/civil-citizen-ui/commit/90cde5a32ff3f87815d4f9565c60f0ee54c0a982

2022-04-29 07:08 UTC, LeonardoPalmeiro commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
In this case I fixed a potencial bug.  As far as I know in Linux when we have script without permission of execution will fail.

2022-04-29 07:10 UTC, LeonardoPalmeiro commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
in this case what I should to do keep as is( with the fixed of a potencial bug) or should I keep as  was?

2022-04-29 10:48 UTC, timja commented on bin/add-roles.sh
> +./bin/utils/ccd-add-role.sh "citizen"
personally I would do all of these with a loop like you did below

2022-04-29 11:24 UTC, taomoh commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
You can keep it

2022-04-29 11:49 UTC, LeonardoPalmeiro commented on bin/add-roles.sh
> +./bin/utils/ccd-add-role.sh "citizen"
I agree with you. I changed

2022-04-29 11:52 UTC, LeonardoPalmeiro commented on package.json
> +    "test:smoke": "jest -c jest.smoketest.config.js --detectOpenHandles",
Ok thanks

2022-05-03 15:58 UTC, timja approved these changes
few comments

2022-05-03 15:58 UTC, timja commented on Jenkinsfile_CNP
> +    pipelineConf = config
why do you need this?

2022-05-03 15:58 UTC, timja commented on Jenkinsfile_CNP
> +    enableSlackNotifications('#civil_notifications')
you shouldn't need this, this is only for overriding, it's defaulted at https://github.com/hmcts/cnp-jenkins-config/blob/master/team-config.yml#L561

2022-05-03 15:58 UTC, timja commented on Jenkinsfile_CNP
> +        sh """
Better to extract this to a shell script as it's easier to reproduce issues locally than in Jenkins

2022-05-03 15:58 UTC, timja commented on Jenkinsfile_CNP
> +      env.URL="https://xui-civil-citizen-ui-pr-${CHANGE_ID}.service.core-compute-preview.internal"
```suggestion
      env.URL = "https://xui-civil-citizen-ui-pr-${CHANGE_ID}.service.core-compute-preview.internal"
```

2022-05-03 15:58 UTC, timja commented on Jenkinsfile_CNP
> +      env.CIVIL_SERVICE_URL="http://civil-service-civil-citizen-ui-pr-${CHANGE_ID}.service.core-compute-preview.internal"
```suggestion
      env.CIVIL_SERVICE_URL = "http://civil-service-civil-citizen-ui-pr-${CHANGE_ID}.service.core-compute-preview.internal"
```

2022-05-03 15:58 UTC, timja commented on bin/add-roles.sh
> +roles=("caseworker-civil-solicitor" "caseworker-civil-systemupdate" "caseworker-civil-admin" "caseworker-civil-staff" "caseworker-civil-judge" "caseworker-civil" "caseworker-caa" "caseworker-approver
you can probably do one role per line which would be easier to read, or group them together

2022-05-04 10:17 UTC, taomoh approved these changes

2022-05-05 10:04 UTC, merged