CIV-9455 Application Hearing Preferences and contact details
hmcts/civil-citizen-ui pull request #3775
Opened 2024-05-13 13:36 UTC by kalachandrasekar1

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-9455

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-05-14 14:10 UTC, laarmada requested changes

2024-05-15 08:15 UTC, kalachandrasekar1 commented on src/main/views/features/generalApplication/hearing-contact-details.njk
> +{% from "../../macro/citizen-telephone.njk" import citizenTelephone %}
removed

2024-05-15 08:15 UTC, kalachandrasekar1 commented on src/main/views/features/generalApplication/hearing-arrangement.njk
> +{% from "govuk/components/textarea/macro.njk" import govukTextarea %}
removed

2024-05-15 08:15 UTC, kalachandrasekar1 commented on src/main/views/features/generalApplication/hearing-contact-details.njk
> +              {{ govukButton({
added addbutton macro

2024-05-15 08:15 UTC, kalachandrasekar1 commented on src/main/views/features/generalApplication/hearing-arrangement.njk
> +            <div class="govuk-button-group">
added addbutton macro

2024-05-15 12:41 UTC, jeswanth-hmcts approved these changes

2024-05-15 12:57 UTC, kenneth-hmcts submitted a review, later dismissed

2024-05-16 15:27 UTC, laarmada commented on src/main/views/features/generalApplication/hearing-contact-details.njk
> +{% extends "claim-details-tpl-dashboard.njk" %}
that should be refactor on the ticket: https://tools.hmcts.net/jira/browse/CIV-13893

2024-05-16 15:28 UTC, laarmada approved these changes
we will fix the design errors in: https://github.com/hmcts/civil-citizen-ui/pull/3775

2024-05-20 09:59 UTC, merged