CIV-1981 - Free Telephone Mediation
hmcts/civil-citizen-ui pull request #380
Opened 2022-04-29 08:14 UTC by commitBlob

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-04-29 09:12 UTC, laarmada requested changes

2022-04-29 09:12 UTC, laarmada commented on src/main/routes/features/response/mediation/freeTelephoneMediationController.ts
> +      { isBusiness: (civilClaim.case_data.applicant1.type === 'ORGANISATION' || civilClaim.case_data.applicant1.type === 'COMPANY') },
it will be fail if the case_data is empty you should check it before to access to that variables.
Also you can send to njk the civilClaim directly and check there....

2022-04-29 09:12 UTC, laarmada commented on src/main/routes/features/response/mediation/freeTelephoneMediationController.ts
> +
you should add the navigation logic. (Post?)
We have several scenarios not cover for this controller. For example:

Scenario: Save and continue + Yes + Claimant type = Company or Organisation
Given citizen is viewing 'You chose not to try free mediation' screen
When Save and continue selected
And 'Yes' selected
And defendant type = Organisation' Or 'Company'
Then display 'Who should the mediation service call' screen IF contact name for company or organisation is Null 
Or display 'The right person for mediation service to call' screen IF contact name for company or organisation is Not Null

2022-04-29 09:12 UTC, laarmada commented on src/main/routes/features/response/mediation/freeTelephoneMediationController.ts
> +      { isBusiness: (civilClaim.case_data.applicant1.type === 'ORGANISATION' || civilClaim.case_data.applicant1.type === 'COMPANY') },
I just to check it:
![image](https://user-images.githubusercontent.com/23473639/165916680-1a91a69e-60fd-4c8e-bb0a-7febfa4d9f24.png)

2022-04-29 09:21 UTC, commitBlob commented on src/main/views/macro/page-title.njk
> +    {{ dynamicTitle }}
this is for the tab title, not the page title
![pageTitle](https://user-images.githubusercontent.com/25640912/165918017-d8fe9fd2-4159-41c5-9410-494d05c5edc7.png)

2022-04-29 09:23 UTC, commitBlob commented on src/main/routes/features/response/mediation/freeTelephoneMediationController.ts
> +      { isBusiness: (civilClaim.case_data.applicant1.type === 'ORGANISATION' || civilClaim.case_data.applicant1.type === 'COMPANY') },
But you should not be able to see this page at all if there is no applicant as this page is displayed when you click an item from the task list

2022-04-29 09:25 UTC, laarmada commented on src/main/routes/features/response/mediation/freeTelephoneMediationController.ts
> +      { isBusiness: (civilClaim.case_data.applicant1.type === 'ORGANISATION' || civilClaim.case_data.applicant1.type === 'COMPANY') },
if for any reason the applicant hasn´t type... it will be fail, we have the applicant but without type....

2022-04-29 09:29 UTC, commitBlob commented on src/main/routes/features/response/mediation/freeTelephoneMediationController.ts
> +
There is no save and continue here? I am not updating any data on this page

2022-05-03 07:21 UTC, laarmada approved these changes

2022-05-03 10:47 UTC, GorilaNaranja commented on src/main/routes/urls.ts
> +const MEDIATION_URL = '/case/:id/mediation';
Check this file to avoid conflicts, we are using this approach in a couple of PRs [url file](https://github.com/hmcts/civil-citizen-ui/blob/c440adb2de0934d078a87d311e9db846d2c7e63a/src/main/routes/urls.ts)

2022-05-03 10:55 UTC, laarmada commented on src/main/routes/urls.ts
> +const MEDIATION_URL = '/case/:id/mediation';
done :)

2022-05-03 15:12 UTC, merged