CIV-9475 respondent agreement screen added
hmcts/civil-citizen-ui pull request #3821
Opened 2024-05-17 13:59 UTC by david-jeronimo

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-9475

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-05-20 10:55 UTC, portizdev requested changes

2024-05-20 10:55 UTC, portizdev commented on src/main/routes/urls.ts
> +export const RESPONDENT_AGREEMENT_URL = `${BASE_GENERAL_APPLICATION_URL}/respondent-agreement`;
Pls change the URL. We are using this as the basis for the respondent's response: 
`export const BASE_GENERAL_APPLICATION_RESPONSE_URL = `${BASE_CASE_RESPONSE_URL}/general-application`;`
https://hmcts-reform.slack.com/archives/C02J4Q3QKLZ/p1715937364168269

2024-05-20 10:55 UTC, portizdev commented on src/main/services/features/generalApplication/generalApplicationService.ts
> +    claim.generalApplication = Object.assign(new GeneralApplication(), claim.generalApplication);
For the response of the application, in order not to mix the fields of the creation of the application with the response.
Create a separate class (even inside generalApplication) to include all the fields from the response to the application.

2024-05-22 11:02 UTC, portizdev approved these changes

2024-05-22 11:05 UTC, laarmada requested changes

2024-05-22 11:05 UTC, laarmada commented on src/test/a11y/ignored-urls.ts
> +  urls.GA_RESPONDENT_AGREEMENT_URL,
avoid ignore the URL if the accessibility test fail, please add the html under the correct folder:
![image](https://github.com/hmcts/civil-citizen-ui/assets/23473639/addd587d-a0e5-4685-9330-62a724c130f1)

2024-05-22 11:05 UTC, laarmada commented on src/main/views/features/generalApplication/respondent-agreement.njk
> +{% extends "claim-details-tpl-dashboard.njk" %}
please refactor the njk as the follow PR: https://github.com/hmcts/civil-citizen-ui/pull/3828

2024-05-22 11:12 UTC, laarmada requested changes

2024-05-22 11:12 UTC, laarmada commented on src/main/common/models/generalApplication/response/response.ts
> +export type Response = {
is better create a class instead of type

2024-05-23 06:30 UTC, david-jeronimo commented on src/main/common/models/generalApplication/response/response.ts
> +export type Response = {
done

2024-05-23 06:30 UTC, david-jeronimo commented on src/main/views/features/generalApplication/respondent-agreement.njk
> +{% extends "claim-details-tpl-dashboard.njk" %}
Done

2024-05-23 06:30 UTC, david-jeronimo commented on src/test/a11y/ignored-urls.ts
> +  urls.GA_RESPONDENT_AGREEMENT_URL,
Done. Thanks for the info!

2024-05-23 08:40 UTC, portizdev submitted a review, later dismissed

2024-05-28 09:48 UTC, jarekPierchala submitted a review, later dismissed

2024-05-29 08:33 UTC, neeta-hmcts submitted a review, later dismissed

2024-05-30 10:24 UTC, merged