CIV-13607 Applicant Defendant upload N245 form
hmcts/civil-citizen-ui pull request #3851
Opened 2024-05-23 08:21 UTC by jeswanth-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-13607

### Change description ###

Applicant Defendant upload N245 form

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-05-24 14:24 UTC, jeswanth-hmcts commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +        {% set idValue = errors.fieldName %}
for upload function one filed ui but underwood model has four properties  different validations for 4 models , because of  that errors come has array get the zero index so because of that overriding the content block

2024-05-27 08:40 UTC, laarmada requested changes

2024-05-27 08:40 UTC, laarmada commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +  {% if form.hasErrors() %}
claim-details-tpl-dashboard.njk merge the latest and I think dont need the error...

2024-05-27 08:40 UTC, laarmada commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +{% block pageTitle %}
you can remove and use the template one passing the vble, also can remove the import

2024-05-27 08:40 UTC, laarmada commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +    <div class="govuk-button-group">
I think is not necessary the div

2024-05-27 09:06 UTC, laarmada requested changes

2024-05-27 09:06 UTC, laarmada commented on src/main/routes/features/generalApplication/uploadN245FormController.ts
> +    const claim: Claim = await getCaseDataFromStore(redisKey);
you can use getClaimById and save code...

2024-05-28 08:06 UTC, jeswanth-hmcts commented on src/main/routes/features/generalApplication/uploadN245FormController.ts
> +    const claim: Claim = await getCaseDataFromStore(redisKey);
if data not  to be fetched from backed , to get saved  data only  from Redis we use  getCaseDataFromStore(redisKey); instead of getClaimById , is there any  specific reason to use getClaimById

2024-05-28 08:13 UTC, jeswanth-hmcts commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +    <div class="govuk-button-group">
we use this` <div class="govuk-button-group">`  this class in  all general application pages  to maintain same style  I am using the div to look same

2024-05-28 08:13 UTC, jeswanth-hmcts commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +  {% if form.hasErrors() %}
i am using claim-details-tpl-dashboard.njk to shows  error summary list , the above errors are not to show error summary list  it is to attach to element property  .

2024-05-28 08:13 UTC, jeswanth-hmcts commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +{% block pageTitle %}
I am following the same approach as other pages in the GA application template,

2024-05-28 08:18 UTC, laarmada commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +    <div class="govuk-button-group">
we need to keep the same style across all new pages in CUI not different depending of the journey

2024-05-28 08:23 UTC, laarmada requested changes

2024-05-28 08:23 UTC, laarmada commented on src/main/routes/features/generalApplication/uploadN245FormController.ts
> +    const claim: Claim = await getCaseDataFromStore(redisKey);
you can remove that line (const redisKey = generateRedisKey(req);) and we align the code to other similar ones...

2024-05-28 08:25 UTC, laarmada requested changes

2024-05-28 08:25 UTC, laarmada commented on src/main/services/features/generalApplication/uploadN245FormService.ts
> +export const getUploadFormContent = (lng: string) => {
were is the related test?

2024-05-28 08:25 UTC, laarmada commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +{% block pageTitle %}
we need to keep the same style across all new pages in CUI not different depending of the journey

2024-05-28 08:36 UTC, jeswanth-hmcts commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +{% block pageTitle %}
this pagetitle we are following same approach in most of the pages

2024-05-28 08:36 UTC, jeswanth-hmcts commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +    <div class="govuk-button-group">
we are following same in all GA pages

2024-05-28 08:41 UTC, jeswanth-hmcts commented on src/main/routes/features/generalApplication/uploadN245FormController.ts
> +    const claim: Claim = await getCaseDataFromStore(redisKey);
```
export const getClaimById = async (claimId: string, req: Request, useRedisKey = false): Promise<Claim> => {
  const redisKey = useRedisKey ? generateRedisKey(<AppRequest>req) : claimId;
  let claim: Claim = await getCaseDataFromStore(redisKey, true);
  const userId = (<AppRequest>req)?.session?.user?.id;
  **if (claim.isEmpty() && redisKey != userId) {
    claim = await civilServiceClient.retrieveClaimDetails(claimId, <AppRequest>req);
    if (claim) {
      await saveDraftClaim(redisKey, claim, true);
    } else {
      throw new Error('Case not found...');
    }
  }**
  return claim;
}; 
```
 getClaimById  has some extra code which is not required in my case , also it internally uses getCaseDataFromStore to  get data from redis ,so  to make it more redable using getCaseDataFromStore

2024-05-28 08:44 UTC, jeswanth-hmcts commented on src/main/services/features/generalApplication/uploadN245FormService.ts
> +export const getUploadFormContent = (lng: string) => {
test is covered as part of controller test scenarios

2024-05-28 08:47 UTC, laarmada commented on src/main/services/features/generalApplication/uploadN245FormService.ts
> +export const getUploadFormContent = (lng: string) => {
@jarekPierchala @dharmendrak that's correct? we have done always service test independent.

2024-05-28 08:48 UTC, laarmada commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +    <div class="govuk-button-group">
@jarekPierchala @dharmendrak, please can you have a look?

2024-05-28 08:48 UTC, laarmada commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +{% block pageTitle %}
@jarekPierchala @dharmendrak, please can you have a look?

2024-05-28 09:24 UTC, jeswanth-hmcts commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +{% block pageTitle %}
passing pageTitle has variable

2024-05-28 11:26 UTC, jarekPierchala requested changes

2024-05-28 11:26 UTC, jarekPierchala commented on src/main/services/features/generalApplication/uploadN245FormService.ts
> +export const getUploadFormContent = (lng: string) => {
@laarmada it shouldnt matter if its a specificly service injected with singleton or static utility class. Each file should have its unit tests coverage. Discussed with @jeswanth-hmcts he will make appropriate changes

2024-05-28 11:26 UTC, jarekPierchala commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +    <div class="govuk-button-group">
@jeswanth-hmcts there is no need to use button group unless there is more then one button in specific area.

Example from gov uk docs:

```
<div class="govuk-button-group">
  {{ govukButton({
    text: "Save and continue"
  }) }}

  {{ govukButton({
    text: "Save as draft",
    classes: "govuk-button--secondary"
  }) }}
</div>
```

more here:
https://design-system.service.gov.uk/components/button/

2024-05-28 11:55 UTC, laarmada commented on src/main/views/features/generalApplication/upload-n245-form.njk
> +{% block pageTitle %}
Jesswant, Dario was working on refactor the template in parallel of other pages and to avoid block a lot of pages we have refactor a lot of general application pages in that issue https://tools.hmcts.net/jira/browse/CIV-13893, so if we are missing something, please let me know and we can create a tech debt ticket in order to align all design and WOW else se sill have the same alignment, padding and styles problem as now. Thanks so much for you patience :)

2024-05-28 14:11 UTC, jarekPierchala submitted a review, later dismissed

2024-05-28 14:50 UTC, portizdev submitted a review, later dismissed

2024-05-31 13:48 UTC, merged