CIV-13857 Lip Defendant response to application - upload documents
hmcts/civil-citizen-ui pull request #3873
Opened 2024-05-24 16:43 UTC by kalachandrasekar1

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-13857

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-05-27 08:51 UTC, laarmada requested changes

2024-05-27 08:51 UTC, laarmada commented on src/main/views/features/generalApplication/respondent-hearing-preference.njk
> +{% block content %}
please merge the latest of claim-details-tpl-dashboard.njk and refactor

2024-05-27 08:51 UTC, laarmada commented on src/main/views/features/generalApplication/respondent-upload-documents.njk
> +{% block content %}
please merge the latest of claim-details-tpl-dashboard.njk and refactor

2024-05-27 08:51 UTC, laarmada commented on src/main/views/features/generalApplication/respondent-want-to-upload-documents.njk
> +{% block content %}
please merge the latest of claim-details-tpl-dashboard.njk and refactor

2024-05-27 08:51 UTC, laarmada commented on src/main/services/features/generalApplication/response/respondentUploadEvidenceDocumentsService.ts
> +const {Logger} = require('@hmcts/nodejs-logging');
where is the related test?

2024-05-27 08:51 UTC, laarmada commented on src/main/modules/nunjucks/index.ts
> +      }).filter(item => item);
which is the reason of that?

2024-05-27 08:59 UTC, laarmada requested changes

2024-05-27 08:59 UTC, laarmada commented on src/main/routes/features/generalApplication/respondentUploadEvidenceDocmentsController.ts
> +    if (req?.session?.fileUpload) {
is possible to extract to a function?

2024-05-27 08:59 UTC, laarmada commented on src/main/routes/features/generalApplication/respondentUploadEvidenceDocmentsController.ts
> +    if (req.query?.id) {
also this one.....

2024-05-27 08:59 UTC, laarmada commented on src/main/routes/features/generalApplication/respondentUploadEvidenceDocmentsController.ts
> +    const claim: Claim = await getCaseDataFromStore(redisKey);
why you dont use the same way as get: .... getClaimById

2024-05-27 08:59 UTC, laarmada commented on src/main/routes/features/generalApplication/respondentWantToUploadDocumentsController.ts
> +      await saveRespondentWantToUploadDoc(redisKey, claim, req.body.option);
you can pass the req and remove the line 49.... toy can include the generateRedisKey into the saveRespondentWantToUploadDoc method

2024-05-29 14:06 UTC, laarmada approved these changes

2024-05-30 09:58 UTC, laarmada commented on src/main/modules/nunjucks/index.ts
> +      }).filter(item => item);
any idea of that? could you talk with Neeta the reason to avoid problems across other pages?

2024-05-30 11:55 UTC, jeswanth-hmcts submitted a review, later dismissed

2024-05-30 12:51 UTC, david-jeronimo submitted a review, later dismissed

2024-05-30 13:05 UTC, neeta-hmcts requested changes

2024-05-30 13:05 UTC, neeta-hmcts commented on src/main/services/features/generalApplication/response/respondentUploadEvidenceDocumentsService.ts
> +const translateErrors = (keys: FormValidationError[], t: (key: string) => string, formatValues?: { keyError: string, keyToReplace: string, valueToReplace: string }[]) => {
this is a duplicate method.. can be re-used from the application uploadEvidance service

2024-05-30 13:05 UTC, neeta-hmcts commented on src/main/views/features/generalApplication/respondent-upload-documents.njk
> +                    <a class="govuk-link" href="{{ row.actions.items[0].href }}&action=REMOVE_DOC">
REMOVE_DOC action not required

2024-05-30 13:47 UTC, kalachandrasekar1 commented on src/main/views/features/generalApplication/respondent-upload-documents.njk
> +                    <a class="govuk-link" href="{{ row.actions.items[0].href }}&action=REMOVE_DOC">
removed

2024-05-30 13:48 UTC, kalachandrasekar1 commented on src/main/services/features/generalApplication/response/respondentUploadEvidenceDocumentsService.ts
> +const translateErrors = (keys: FormValidationError[], t: (key: string) => string, formatValues?: { keyError: string, keyToReplace: string, valueToReplace: string }[]) => {
updated to reuse uploadEvidance service class method

2024-05-30 14:16 UTC, neeta-hmcts approved these changes

2024-05-30 14:17 UTC, jeswanth-hmcts submitted a review, later dismissed

2024-07-12 14:24 UTC, merged