CIV-13608
hmcts/civil-citizen-ui pull request #3882
Opened 2024-05-28 13:32 UTC by manish14836

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-13608

### Change description ###

Error messages for additional application

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2024-05-30 09:23 UTC, laarmada commented on src/main/routes/features/generalApplication/applicationTypeController.ts
> +export const additionalApplicationErrorMessages: Partial<{ [key in ApplicationTypeOption]: string; }> = {
why we have in the controller file function or utils? we should move to other file or the related service one.

2024-05-30 13:07 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/en.json
> +        "ASK_DO_SOMETHING": "Ask the court to do:wqa:qa something that's not on this list",
Why you need to use :wqa:qa?

2024-05-30 13:08 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/en.json
> +        "ASK_DO_SOMETHING": "Ask the court to do:wqa:qa something that's not on this list",
Should we use it as well in cy.json?

2024-05-30 13:09 UTC, GorilaNaranja commented on src/main/routes/features/generalApplication/addAnotherApplicationController.ts
> +      const redirectUrl = APPLICATION_TYPE_URL.replace(':id', claimId);
use constructResponseUrlWithIdParams()

2024-05-30 13:28 UTC, manish14836 commented on src/main/routes/features/generalApplication/addAnotherApplicationController.ts
> +      const redirectUrl = APPLICATION_TYPE_URL.replace(':id', claimId);
Done

2024-05-30 13:28 UTC, manish14836 commented on src/main/modules/i18n/locales/en.json
> +        "ASK_DO_SOMETHING": "Ask the court to do:wqa:qa something that's not on this list",
It was added by mistake. Removed

2024-05-30 13:28 UTC, manish14836 commented on src/main/routes/features/generalApplication/applicationTypeController.ts
> +export const additionalApplicationErrorMessages: Partial<{ [key in ApplicationTypeOption]: string; }> = {
Moved to generalApplicationService

2024-05-30 13:41 UTC, GorilaNaranja approved these changes

2024-05-31 08:36 UTC, laarmada requested changes

2024-05-31 08:36 UTC, laarmada commented on src/main/routes/features/generalApplication/checkAnswersController.ts
> +function getRedirectUrl(claimId: string, claim: Claim): string {
please extract this to the related service.

2024-05-31 08:36 UTC, laarmada commented on src/main/routes/features/generalApplication/checkAnswersController.ts
> +function hearingMoreThan14DaysInFuture(claim: Claim): boolean {
please extract this to the related service.

2024-05-31 10:38 UTC, laarmada submitted a review, later dismissed

2024-05-31 11:59 UTC, GorilaNaranja submitted a review, later dismissed

2024-06-03 14:01 UTC, merged