Civ 922 lr claimant details
hmcts/civil-citizen-ui pull request #391
Opened 2022-05-03 15:01 UTC by TatsyMaslova

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-922

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-05-04 06:51 UTC, laarmada approved these changes

2022-05-04 07:02 UTC, laarmada requested changes
important

2022-05-04 07:02 UTC, laarmada commented on src/main/routes/urls.ts
> +export const CLAIMANT_DETAILS_URL = `${DASHBOARD_URL}/:id/contact-them`;
where is the contact-them pages and other changes? Take care about it if there is other PR because we have only 1 Jira issue....

2022-05-04 07:06 UTC, laarmada commented on src/main/routes/urls.ts
> +export const CLAIMANT_DETAILS_URL = `${DASHBOARD_URL}/:id/contact-them`;
https://github.com/hmcts/civil-citizen-ui/pull/338

I don´t know why : export const CLAIMANT_DETAILS_URL = `${DASHBOARD_URL}/:id/contact-them`;

I think are different:  we have in the old cmc: 
claimant-individual-details
claimant-organisation-details
claimant-company-details
claimant-sole-trader-details
.........

2022-05-04 08:13 UTC, TatsyMaslova commented on src/main/routes/urls.ts
> +export const CLAIMANT_DETAILS_URL = `${DASHBOARD_URL}/:id/contact-them`;
in the old cmc there is a page called conact-them.njk. When i took over from Fergal his page was called claimant-details. I can rename it to contact-them as in ocmc. but i think we could do that in another slice when we will require other things and can rename the page accordingly. if you look at the story and at the ocmc the url is contact-them

2022-05-04 14:40 UTC, laarmada approved these changes

2022-05-04 15:24 UTC, taomoh commented on src/main/routes/urls.ts
> +export const DEBTS_URL = `${STATEMENT_OF_MEANS_URL}/debts`;
Duplicate of CITIZEN_DEBTS_URL

2022-05-04 15:24 UTC, taomoh commented on src/main/views/features/dashboard/contact-them.njk
> +      {% set otherParty = 'Claimant' %}
missing translation function

2022-05-04 15:24 UTC, taomoh commented on src/main/views/features/dashboard/contact-them.njk
> +              <div class="govuk-body govuk-!-margin-bottom-0">{{ 'Phone: ' }}{{ phone }}</div>
Missing translation function

2022-05-04 15:24 UTC, taomoh commented on src/main/views/features/dashboard/contact-them.njk
> +              <div class="govuk-body govuk-!-margin-bottom-6">{{ 'Email: ' }}<a
Missing translation function

2022-05-04 15:24 UTC, taomoh commented on src/main/views/features/dashboard/contact-them.njk
> +        {{ aboutClaimWidget({header:header,lines:[{title: 'Claimant name:', href: otherPartyLabel, hrefContact: otherPartyName},{title: 'Claim amount:', content:totalClaimAmount},{title: 'Claim detai
Translation has to happen at some stage. Either here or within one of the widgets

2022-05-04 15:24 UTC, taomoh commented on src/main/views/features/response/financialDetails/financial-details.njk
> +          <a href="{{claimantDetailsUrl}}">{{ t('Get ') }} {{ applicant1Details }}{{ t("'s contact details.") }}</a>
Are the inside curly brackets required?

2022-05-05 08:06 UTC, TatsyMaslova commented on src/main/views/features/dashboard/contact-them.njk
> +      {% set otherParty = 'Claimant' %}
it is translated in other elements for example: 
```
 <span class="govuk-caption-l  govuk-!-padding-top-0">{{ t(otherParty) }}</span>
          <h1 class="govuk-heading-l govuk-!-margin-bottom-6">{{ t(otherPartyName) }}</h1>
```

2022-05-05 08:07 UTC, TatsyMaslova commented on src/main/views/features/dashboard/contact-them.njk
> +        {{ aboutClaimWidget({header:header,lines:[{title: 'Claimant name:', href: otherPartyLabel, hrefContact: otherPartyName},{title: 'Claim amount:', content:totalClaimAmount},{title: 'Claim detai
it is in the widget 
```
{% macro newLine(title, content, href, hrefContact) %}
  <p class="govuk-body-s govuk-!-margin-bottom-0 govuk-!-font-weight-bold">{{ t(title) }}</p>
```

2022-05-05 08:10 UTC, TatsyMaslova commented on src/main/views/features/response/financialDetails/financial-details.njk
> +          <a href="{{claimantDetailsUrl}}">{{ t('Get ') }} {{ applicant1Details }}{{ t("'s contact details.") }}</a>
yes i think so. I think Fergal added those so that they represent the claimant details in the financial details page. I think he put different variables in curly brackets to avoid concatenation +

2022-05-05 08:15 UTC, TatsyMaslova commented on src/main/views/features/dashboard/contact-them.njk
> +              <div class="govuk-body govuk-!-margin-bottom-6">{{ 'Email: ' }}<a
done thank you

2022-05-05 08:17 UTC, TatsyMaslova commented on src/main/routes/urls.ts
> +export const DEBTS_URL = `${STATEMENT_OF_MEANS_URL}/debts`;
done thank you

2022-05-05 08:17 UTC, TatsyMaslova commented on src/main/views/features/dashboard/contact-them.njk
> +              <div class="govuk-body govuk-!-margin-bottom-0">{{ 'Phone: ' }}{{ phone }}</div>
done thank you

2022-05-05 08:22 UTC, taomoh approved these changes

2022-05-05 14:40 UTC, GorilaNaranja commented on src/main/routes/features/dashboard/contactThemController.ts
> +let logger: winston.Logger = Logger.getLogger('claimantDetailsController');
Should we call the logger claimantDetailsController or contactThemController?

2022-05-05 14:40 UTC, GorilaNaranja commented on src/main/routes/features/response/financialDetails/financialDetailsController.ts
> +      const counterpartyType: CounterpartyType = claim.respondent1.type;
I'm not sure but I think if `respondent1` doesn't exist it will throw an error. So maybe we need to check that `respondent1` exist before to access `.type`.

I think question mark could solve it 
`const counterpartyType: CounterpartyType = claim.respondent1?.type;`

2022-05-09 14:30 UTC, merged