CIV-14215 - CUI Dashboard (old vs new)
hmcts/civil-citizen-ui pull request #4029
Opened 2024-06-19 11:15 UTC by neeta-hmcts

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-14215

### Change description ###
added new feature toggle to switch between old/new dashboard wrto claim submitDate

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-06-20 13:46 UTC, dharmendrak approved these changes

2024-06-21 08:20 UTC, kenneth-hmcts approved these changes

2024-06-21 08:26 UTC, laarmada requested changes
I know the scope of the issue is skip the old claims from the dashboard to avoid the links but the isDashboardServiceEnabled flag is to hide or allow the newDashboard develop....

2024-06-21 08:26 UTC, laarmada commented on src/main/app/auth/launchdarkly/launchDarklyClient.ts
> +async function getUser(epoch: any): Promise<LDUser> {
could be not any type?

2024-06-21 08:26 UTC, laarmada commented on src/main/routes/features/dashboard/claimantDashboardController.ts
> +    if (isCUIR2Enabled){
maybe we have problems if we dont check isDashboardEnabled because we use that in civil-service and camunda/ccd and we could have problems: 
await getNotifications(dashboardId, claim, caseRole, req, lng);
 await getDashboardForm(caseRole, claim, dashboardId, req, isCarmApplicable);
.....

2024-06-21 08:26 UTC, laarmada commented on src/main/routes/features/response/claimDetails/claimDetailsController.ts
> +    const claimDetailsViewPath = (isCUIReleaseTwo) ? claimDetailsViewPathNew : claimDetailsViewPathOld;
take care with removal of isDashboardEnabled

2024-06-21 08:26 UTC, laarmada commented on src/test/unit/routes/features/caseProgression/cancelYourUploadController.test.ts
> +          expect(res.header.location).toEqual(OLD_DASHBOARD_CLAIMANT_URL.replace(':id', '1111'));
that test is not correct so of you have removed the isDashboardEnabled flag and only check isCUIReleaseTwoEnabled it should be also go to DASHBOARD_CLAIMANT_URL .....

2024-06-21 08:33 UTC, laarmada submitted a review, later dismissed

2024-06-21 09:09 UTC, neeta-hmcts commented on src/main/app/auth/launchdarkly/launchDarklyClient.ts
> +async function getUser(epoch: any): Promise<LDUser> {
fixed this to string

2024-06-21 09:25 UTC, neeta-hmcts commented on src/main/routes/features/dashboard/claimantDashboardController.ts
> +    if (isCUIR2Enabled){
this has been taken care of in https://github.com/hmcts/civil-service/pull/4947 - basically in stateFlowEngine if the claim is submitted post-CUI R2 then only a Dashboard notification will be generated.

If the Claim is submitted before CUIR2 and after R2 goes live dashboard notification will not be generated for the Lr V LiP claim.  As  those claims are submitted before CUI R2

2024-06-21 09:25 UTC, neeta-hmcts commented on src/main/routes/features/response/claimDetails/claimDetailsController.ts
> +    const claimDetailsViewPath = (isCUIReleaseTwo) ? claimDetailsViewPathNew : claimDetailsViewPathOld;
done

2024-06-21 09:48 UTC, neeta-hmcts commented on src/test/unit/routes/features/caseProgression/cancelYourUploadController.test.ts
> +          expect(res.header.location).toEqual(OLD_DASHBOARD_CLAIMANT_URL.replace(':id', '1111'));
fixed it

2024-06-21 20:04 UTC, closed without merging