bugFix/CIV-2460/Prevent displaying individual defendant details with errors
hmcts/civil-citizen-ui pull request #407
Opened 2022-05-11 12:29 UTC by laperla11

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-2460

### Change description ###
Display organisation/company defendant details when there is an error message on page instead of individual defendant details. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-11 12:33 UTC, TatsyMaslova commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +      renderPageWithError(res, citizenAddress, citizenCorrespondenceAddress, errorList, req, responseDataRedis, contactPerson);
should you add a unit test for post - so that it returns the correct view when there are errors?

2022-05-11 14:14 UTC, GorilaNaranja approved these changes

2022-05-12 07:05 UTC, laarmada requested changes

2022-05-12 07:05 UTC, laarmada commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +  const responseDataRedis: Respondent = await getRespondentInformation(req.params.id);
you can avoid to call again to redis if you have:  let responseDataRedis instead of constant in citizenDetailsController.get.... with this approach you will save a lot of lines of code.

2022-05-12 07:05 UTC, laarmada commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +      renderPageWithError(res, citizenAddress, citizenCorrespondenceAddress, errorList, req, responseDataRedis, contactPerson);
here you can avoid this line with the "above comment"

2022-05-12 07:16 UTC, TatsyMaslova approved these changes

2022-05-12 08:08 UTC, laperla11 commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +  const responseDataRedis: Respondent = await getRespondentInformation(req.params.id);
I believe get and post request controller should have their block scope responseDataRedis data instead of global scope responseDataRedis. Happy to discuss if you have time.

2022-05-12 15:20 UTC, laarmada approved these changes

2022-05-12 16:25 UTC, merged