Civ 1978 timeline of events
hmcts/civil-citizen-ui pull request #409
Opened 2022-05-12 06:54 UTC by TatsyMaslova

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-1978

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-05-12 10:06 UTC, RosDiaf approved these changes

2022-05-12 10:53 UTC, laperla11 approved these changes
LGTM

2022-05-13 10:42 UTC, laarmada requested changes

2022-05-13 10:42 UTC, laarmada commented on src/main/modules/nunjucks/filters/dateFilter.ts
> +import {DateTime} from 'luxon';
Uncovered Lines on sonar

2022-05-13 10:42 UTC, laarmada commented on src/main/routes/urls.ts
> +export const CITIZEN_EVIDENCE_URL = `${BASE_CASE_RESPONSE_URL}/evidence`;
it's evidence no defendant/claimant-evidence?

2022-05-13 11:10 UTC, TatsyMaslova commented on src/main/routes/urls.ts
> +export const CITIZEN_EVIDENCE_URL = `${BASE_CASE_RESPONSE_URL}/evidence`;
it's evidence. and goes to rosario's screen. just like in ocmc

2022-05-13 11:17 UTC, laarmada commented on src/main/routes/urls.ts
> +export const CITIZEN_EVIDENCE_URL = `${BASE_CASE_RESPONSE_URL}/evidence`;
so sorry I couldn't find evidence screen in the old cmc.....

2022-05-13 11:17 UTC, laarmada commented on src/main/routes/urls.ts
> +export const CITIZEN_EVIDENCE_URL = `${BASE_CASE_RESPONSE_URL}/evidence`;
now!! sorry :)

2022-05-13 11:21 UTC, laarmada approved these changes

2022-05-16 13:05 UTC, merged