Feature/CIV-1189/first time response task list
hmcts/civil-citizen-ui pull request #416
Opened 2022-05-16 08:23 UTC by laperla11

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-1189

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-16 11:12 UTC, TatsyMaslova commented on src/main/common/utils/dateUtils.ts
> +export const isPastDeadline = (dateTime: DateTime, deadline: Date | string) => {
not sure why you need to pass datetime parameter

2022-05-16 11:14 UTC, TatsyMaslova commented on src/main/common/utils/taskList/taskListBuilder.ts
> +  const isDeadlinePassed = isPastDeadline(now, caseData.respondent1ResponseDeadline);
you could have just one parameter instead with the deadline and compare it to current date in the utils

2022-05-16 11:17 UTC, TatsyMaslova commented on src/main/common/utils/taskList/tasks/checkAndSubmitYourResponse.ts
> +  const redirectionURL = isInCompletsubmission ? 'incomplete-submission' : 'check-and-send';
not sure whether redirect urls should be strings. I understand that we would add these when the pages are created but thought would be good to have them in our urls already so that when Jisha tests the urls are correct and corresponding to the ocmc ones

2022-05-16 15:25 UTC, taomoh requested changes

2022-05-16 15:25 UTC, taomoh commented on src/test/unit/modules/taskListService.test.ts
> +    const mockTaskLists = getTaskLists(claim, caseData, mockId);
I feel that using mock to name the return of the function under test can be misleading. `actualTaskList` would be a more accurate name

2022-05-16 15:25 UTC, taomoh commented on src/test/unit/modules/taskListService.test.ts
> +    const mockTaskLists = getTaskLists(claim, caseData, mockId);
`actualTaskList` would be a more accurate name. See explanation in comment above

2022-05-16 15:25 UTC, taomoh commented on src/test/unit/modules/taskListService.test.ts
> +    const mockTaskLists = getTaskLists(claim, caseData, mockId);
`actualTaskList` would be a more accurate name. See explanation in comment above

2022-05-16 15:25 UTC, taomoh commented on src/test/unit/modules/taskListService.test.ts
> +    const mockTaskLists = getTaskLists(claim, caseData, mockId);
`actualTaskList` would be a more accurate name. See explanation in comment above

2022-05-16 16:30 UTC, laperla11 commented on src/test/unit/modules/taskListService.test.ts
> +    const mockTaskLists = getTaskLists(claim, caseData, mockId);
same here

2022-05-16 16:35 UTC, laperla11 commented on src/main/modules/taskListService.ts
> +    isInCompletsubmission = false;
done

2022-05-16 16:35 UTC, laperla11 commented on src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
> +    res.status(500).send({ error: error.message });
done

2022-05-16 16:40 UTC, laperla11 commented on src/main/common/utils/dateUtils.ts
> +  /* @ts-expect-error : Argument of type 'Date' is not assignable to parameter of type 'string'.ts(2345) */
but this is not a proper error as in fact the typeof date is string although it is assigned with `Date`, otherwise the conversion will not work.

2022-05-16 16:40 UTC, laperla11 commented on src/main/common/utils/taskList/tasks/checkAndSubmitYourResponse.ts
> +export const getCheckAndSubmitYourResponseTask = (claim: Claim, caseData: Claim, claimId: string, isInCompletsubmission: boolean): Task => {
done

2022-05-16 16:50 UTC, laperla11 commented on src/main/common/utils/taskList/tasks/checkAndSubmitYourResponse.ts
> +  const redirectionURL = isInCompletsubmission ? 'incomplete-submission' : 'check-and-send';
I put them as placeholder as we haven't developed those pages yet and put  a TODO on line 21.

2022-05-16 16:51 UTC, laperla11 commented on src/main/common/utils/taskList/tasks/confirmYourDetails.ts
> +  let isTaskCompleted = TaskStatus.COMPLETE;
same here

2022-05-16 16:52 UTC, laperla11 commented on src/main/common/utils/taskList/tasks/confirmYourDetails.ts
> +  if (!caseData?.respondent1?.correspondenceAddress && !caseData?.respondent1?.primaryAddress) {
I implemented that logic as we discussed during S & T.

2022-05-16 16:53 UTC, laperla11 commented on src/main/views/features/response/task-list.njk
> +{% set heading = 'Respond to a money claim' %}
done

2022-05-16 16:54 UTC, laperla11 commented on src/main/views/features/response/task-list.njk
>            <h2 class="govuk-heading-s govuk-!-margin-bottom-2">{{title}}</h2>
done

2022-05-16 17:53 UTC, taomoh commented on src/main/common/utils/taskList/tasks/checkAndSubmitYourResponse.ts
> +  const isTaskCompleted = TaskStatus.INCOMPLETE;
What I meant is that you used a boolean variable name (`isTaskCompleted`) for an enum type (`TaskStatus`)

2022-05-17 08:01 UTC, TatsyMaslova commented on src/main/common/utils/taskList/tasks/taskListHelpers.ts
> +  return !respondent1?.correspondenceAddress && !respondent1?.primaryAddress;
I think you will have a bug here. because correspondance address is not mandatory it may be missing if the user sais its the same as primary. was just looking at a bug and realised this

2022-05-17 10:01 UTC, taomoh approved these changes

2022-05-17 15:14 UTC, merged