Civ 2136 court fees
hmcts/civil-citizen-ui pull request #428
Opened 2022-05-20 14:07 UTC by GorilaNaranja

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-2136

### Change description ###
Reject - Reject all and Counterclaim - Court fees

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-20 14:08 UTC, GorilaNaranja commented on src/main/views/features/mediation/i-dont-want-free-mediation.njk
> +              <a class="govuk-link" href="../response/task-list">
NOTE: This is not the scope of the issue but I found that bug and I solve it

2022-05-23 09:56 UTC, LeonardoPalmeiro requested changes

2022-05-23 09:56 UTC, LeonardoPalmeiro commented on src/main/app/client/civilServiceClient.ts
> +  getRangeFeesMock(): FeeRange[] {
please try to create the method as promise in this case, when we have the service into civil-service then we don't have to change nothing.

2022-05-23 11:34 UTC, laarmada approved these changes

2022-05-24 10:23 UTC, commitBlob approved these changes

2022-05-24 11:28 UTC, LeonardoPalmeiro approved these changes

2022-05-26 11:59 UTC, merged