Civ 2062 why do you disagree with the claim
hmcts/civil-citizen-ui pull request #435
Opened 2022-05-23 06:51 UTC by laarmada

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-2062

### Change description ###

'Why do you disagree with the claim' screen

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-05-23 07:34 UTC, commitBlob reviewed
I can't see view unit tests?

2022-05-23 07:34 UTC, commitBlob commented on src/main/views/features/response/your-defence.njk
> +      {% set theirReason = 'Reason your defence Reason your defenceReason your defenceReason your defenceReason your defenceReason your defenceReason your defence
was this left in intentionally?

2022-05-23 07:34 UTC, commitBlob commented on src/main/views/features/response/your-defence.njk
> +      {% set heading = 'Why do you disagree with the claim?' %}
This line is missing translation

2022-05-23 07:34 UTC, commitBlob commented on src/main/views/features/response/your-defence.njk
> +      {% set labelContent =  '<p class="govuk-!-font-weight-bold">' + t("Briefly explain why you disagree with the claim") + '</p>' +
we've agreed to use keys for translations, could you refactor to be something like Tanya and myself did please.
https://github.com/hmcts/civil-citizen-ui/blob/CIV-2195_check_your_answers_pay_immediately/src/main/modules/i18n/locales/en.json
https://github.com/hmcts/civil-citizen-ui/blob/features/CIV-2488-reject-paid-less/src/main/modules/i18n/locales/en.json

2022-05-23 07:34 UTC, commitBlob commented on src/test/unit/routes/features/response/yourDefenceController.test.ts
> +      const header = 'Why do you disagree with the claim?';
maybe you can remove header to the upper scope and have it declared once as it doesn't seem to change in the tests

2022-05-23 09:15 UTC, LeonardoPalmeiro requested changes

2022-05-23 11:32 UTC, laarmada commented on src/main/views/macro/expandableSection.njk
> +      <input id="{{ id }}" type="checkbox">
that´s in the scope of the issue, show more and show less.

2022-05-23 12:05 UTC, laarmada commented on src/main/views/features/response/your-defence.njk
> +                {{ t('Your response will be sent to {{ claimantFullName }}.', { claimantFullName: claimantFullName }) }}
I just to check it and it´s mandatory else doesn´t work

2022-05-23 12:05 UTC, laarmada commented on src/main/views/features/response/your-defence.njk
> +      {% set theirReason = 'Reason your defence Reason your defenceReason your defenceReason your defenceReason your defenceReason your defenceReason your defence
done

2022-05-23 12:07 UTC, laarmada commented on src/test/unit/routes/features/response/yourDefenceController.test.ts
> +      const header = 'Why do you disagree with the claim?';
it´s to maintain the same behaviour like in the view, the claimant name change depending of the type...

2022-05-23 12:09 UTC, laarmada commented on src/main/views/features/response/your-defence.njk
> +      {% set theirReason = 'Reason your defence Reason your defenceReason your defenceReason your defenceReason your defenceReason your defenceReason your defence
I have update retrieving information from correct data in redis.

2022-05-24 08:48 UTC, GorilaNaranja approved these changes

2022-05-24 11:02 UTC, LeonardoPalmeiro approved these changes

2022-05-24 12:32 UTC, laperla11 approved these changes

2022-05-25 12:21 UTC, taomoh commented on src/main/common/utils/languajeToogleUtils.ts
> +const getLng = (lang: string | unknown): string => {
typo in file name

2022-05-25 12:22 UTC, taomoh requested changes
typo in file name. It should be languageToggleUtils

2022-05-25 12:24 UTC, TatsyMaslova commented on src/main/common/utils/languajeToogleUtils.ts
> +const getLng = (lang: string | unknown): string => {
And I think we already have this in languageToggleUitls:
const getLng = (lang: string | unknown): string => {
  return lang ? String(lang) : 'en';
};

export {
  getLng,
};

2022-05-25 12:26 UTC, TatsyMaslova commented on src/main/common/utils/languajeToogleUtils.ts
> +const getLng = (lang: string | unknown): string => {
![Capture2](https://user-images.githubusercontent.com/95431510/170261542-9d840092-856a-49b0-a2c4-b654942f57ec.JPG)

2022-05-25 13:33 UTC, laarmada commented on src/main/common/utils/languajeToogleUtils.ts
> +const getLng = (lang: string | unknown): string => {
two things, please don´t request change for an issue in PO review. On the other hand, this change come from master:
![image](https://user-images.githubusercontent.com/23473639/170274579-40d13851-e20d-4c91-bafc-0b4f8fd43d3c.png)

2022-05-25 14:14 UTC, TatsyMaslova commented on src/main/common/utils/languajeToogleUtils.ts
> +const getLng = (lang: string | unknown): string => {
Sorry Sergio but this change does not come from master. you misunderstood my comment. there is already a file with no spelling mistakes its called lanugageToggleUtils.ts Whereas in your pr you are introducing a new file with typo on the name that does exactly the same thing as languageToggleUtils.ts . If your pr goes to master we will have two files in utils that do the same thing and have the same export function.

2022-05-25 14:33 UTC, laarmada commented on src/main/common/utils/languajeToogleUtils.ts
> +const getLng = (lang: string | unknown): string => {
Hahaha I can see the error ok @taomoh I just to remove the wrong file...

2022-05-25 14:36 UTC, taomoh approved these changes

2022-05-26 08:20 UTC, TatsyMaslova approved these changes

2022-05-26 13:09 UTC, merged