Feature/civ 1187 complete all sections
hmcts/civil-citizen-ui pull request #439
Opened 2022-05-24 23:06 UTC by taomoh

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-1187

### Change description ###

Complete all sections screen

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-05-25 12:43 UTC, commitBlob reviewed
Looks good, just a reminder to change translations into keys in both  incomplete-submission and remaining-tasks-fragment nunjuck files

2022-05-25 13:21 UTC, taomoh commented
> Looks good, just a reminder to change translations into keys in both `incomplete-submission` and `remaining-tasks-fragment` nunjuck files

@commitBlob , I've just pushed these changes and the complete tasks generic guard as well. Please take a look and let me know, if you'd like to discuss

2022-05-25 13:42 UTC, commitBlob approved these changes

2022-05-25 14:25 UTC, TatsyMaslova approved these changes

2022-05-25 14:33 UTC, laperla11 approved these changes

2022-05-25 15:14 UTC, LeonardoPalmeiro requested changes

2022-05-25 15:18 UTC, taomoh commented on src/main/routes/features/response/taskListController.ts
> +}
Not sure I am following. Let's talk about it

2022-05-25 15:19 UTC, taomoh commented on src/main/routes/guards/allResponseTasksCompletedGuard.ts
> +    return async (req: express.Request, res: express.Response, next: express.NextFunction): Promise<void> => {
I think it should be void, as next and redirect return types are also void

2022-05-25 15:52 UTC, taomoh commented on src/main/routes/features/response/taskListController.ts
> +}
As per our discussion, I've moved the Session type enhancement to app.ts, so that the enhanced session type is accessible throughout the application

2022-05-26 07:13 UTC, LeonardoPalmeiro approved these changes

2022-05-30 10:20 UTC, closed without merging