CIV-15076 Certificate of Satisfaction evidence of the debt payment
hmcts/civil-citizen-ui pull request #4639
Opened 2024-09-25 17:10 UTC by sherlynkhaw

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-15076

### Change description ###
- added evidence of the debt payment page

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-09-25 17:25 UTC, sherlynkhaw commented on src/main/common/models/generalApplication/CertificateOfSatisfactionOrCanceled.ts
> +// import {DefendantFinalPaymentDate} from 'form/models/certOfSorC/defendantFinalPaymentDate';
this is from omaira's branch, i commented it out for now because i didn't need it in my own code

2024-09-26 11:45 UTC, LeonardoPalmeiro approved these changes

2024-09-26 11:58 UTC, laarmada requested changes

2024-09-26 11:58 UTC, laarmada commented on src/main/services/features/generalApplication/certOfSorC/debtPaymentEvidenceService.ts
> +    const caseData = await getCaseDataFromStore(claimId);
use await getClaimById(claimId, req, true);

2024-09-26 11:58 UTC, laarmada commented on src/main/services/features/generalApplication/certOfSorC/debtPaymentEvidenceService.ts
> +    await saveDraftClaim(claimId, caseData);
use the rediskey

2024-09-26 11:58 UTC, laarmada commented on src/main/services/features/generalApplication/certOfSorC/debtPaymentEvidenceService.ts
> +  public async saveDebtPaymentEvidence (claimId: string, debtPaymentEvidence: DebtPaymentEvidence) {
pass req instead of claimID

2024-09-26 11:58 UTC, laarmada commented on src/main/routes/features/generalApplication/certOfSorc/debtPaymentEvidenceController.ts
> +        await debtPaymentEvidenceService.saveDebtPaymentEvidence(redisKey, form.model);
send the req vble

2024-09-26 12:03 UTC, kalachandrasekar1 commented on src/main/common/models/generalApplication/CertificateOfSatisfactionOrCanceled.ts
> +// import {DefendantFinalPaymentDate} from 'form/models/certOfSorC/defendantFinalPaymentDate';
uncomment it to avoid merge conflicts

2024-09-26 12:05 UTC, kalachandrasekar1 commented on src/main/routes/features/generalApplication/certOfSorc/debtPaymentEvidenceController.ts
> +import {
update file path same as existing cosc prs

2024-09-26 12:06 UTC, kalachandrasekar1 commented on src/main/services/features/generalApplication/certOfSorC/debtPaymentEvidenceService.ts
> +import {DebtPaymentEvidence} from 'models/generalApplication/debtPaymentEvidence';
update file path same as existing cosc prs

2024-09-26 12:06 UTC, kalachandrasekar1 commented on src/main/views/features/certOfSorc/debt-payment-evidence.njk
> +{% extends "claim-details-tpl-dashboard.njk" %}
update file path same as existing cosc prs

2024-09-26 12:11 UTC, sherlynkhaw commented on src/main/services/features/generalApplication/certOfSorC/debtPaymentEvidenceService.ts
> +    await saveDraftClaim(claimId, caseData);
this is the rediskey, it's called from controller as:

        await debtPaymentEvidenceService.saveDebtPaymentEvidence(redisKey, form.model);

2024-09-26 12:57 UTC, sherlynkhaw commented on src/main/common/models/generalApplication/CertificateOfSatisfactionOrCanceled.ts
> +// import {DefendantFinalPaymentDate} from 'form/models/certOfSorC/defendantFinalPaymentDate';
I can't uncomment because i don't have those files. i took it from omaira's branch but didn't branch off hers.

2024-09-26 13:43 UTC, sherlynkhaw commented on src/main/common/models/generalApplication/CertificateOfSatisfactionOrCanceled.ts
> +// import {DefendantFinalPaymentDate} from 'form/models/certOfSorC/defendantFinalPaymentDate';
i'll remove it completely

2024-09-26 13:56 UTC, kalachandrasekar1 approved these changes

2024-09-27 09:27 UTC, LeonardoPalmeiro approved these changes

2024-09-30 11:33 UTC, merged