Feature/civ 923 leo
hmcts/civil-citizen-ui pull request #483
Opened 2022-05-31 14:42 UTC by GorilaNaranja

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-31 15:25 UTC, laarmada requested changes
hard job!

2022-05-31 15:25 UTC, laarmada commented on src/main/routes/features/dashboard/claimSummaryController.ts
> +      '<p class="govuk-body">More information about the <a class="govuk-link" href="https://www.gov.uk/government/publications/debt-respite-scheme-breathing-space-guidance/debt-respite-scheme-breathi
where is t function to translate

2022-05-31 15:25 UTC, laarmada commented on src/main/routes/features/dashboard/claimSummaryController.ts
> +      '<p class="govuk-body">If you’ve been paid or you’ve made another agreement with the defendant, you need to tell us.</p>',
or key?

2022-06-01 07:02 UTC, GorilaNaranja commented on src/main/routes/features/dashboard/claimSummaryController.ts
> +      '<p class="govuk-body">If you’ve been paid or you’ve made another agreement with the defendant, you need to tell us.</p>',
This component is only a probe of concept to check if we can pass html as parameter.

2022-06-01 07:04 UTC, laarmada approved these changes
ok

2022-06-01 08:19 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/cy.json
> +    "CLAIM_DETAILS": {
Updated

2022-06-01 10:38 UTC, merged