Civ 2799 partial admission when to pay
hmcts/civil-citizen-ui pull request #487
Opened 2022-06-07 08:57 UTC by laperla11

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-2799

### Change description ###
Payment option for partial admission

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-06-07 12:04 UTC, TatsyMaslova commented on src/main/common/models/claim.ts
> +    return this?.respondent1?.responseType === ResponseType.FULL_ADMISSION;
i don't think this will ever be null or undefined because it will be an instance of claim

2022-06-07 12:06 UTC, TatsyMaslova commented on src/main/routes/features/response/admission/partialAdmission/partialAdmissionPaymentOptionController.ts
> +    if (!claim?.partialAdmissionPaymentAmount() || !claim?.isPartialAdmission()) {
i think getCaseDataFromStore always returns a claim. so no need to check whether claim is undefined or null. you could have !claim.partialAdmissonPaymentAmount() instead

2022-06-07 13:12 UTC, taomoh reviewed
LG overall. Some minor comments

2022-06-07 13:12 UTC, taomoh commented on src/main/modules/i18n/locales/cy.json
> +      "WHY_DO_YOU_WANT_TO_PAY": "When do you want to pay?"
Key should be alphabetically orders

2022-06-07 13:12 UTC, taomoh commented on src/main/routes/features/response/admission/partialAdmission/partialAdmissionPaymentOptionController.ts
> +import {CITIZEN_PARTIAL_ADMISSION_PAYMENT_DATE_URL, CITIZEN_PARTIAL_ADMISSION_PAYMENT_OPTION_URL, CLAIM_TASK_LIST_URL} from '../../../../urls';
putting these individual URLs in separate lines would be more merge-friendly

2022-06-07 13:28 UTC, laarmada requested changes

2022-06-07 13:28 UTC, laarmada commented on src/main/common/models/partialAdmission.ts
> +  paymentDate?: Date;
I think that´s wrong: 
![image](https://user-images.githubusercontent.com/23473639/172389182-c58f78fc-5a1f-4e2a-9a70-27da6ebe664c.png)

2022-06-07 15:40 UTC, laperla11 commented on src/main/modules/i18n/locales/en.json
> +      "WHY_DO_YOU_WANT_TO_PAY": "When do you want to pay?"
changed the orders

2022-06-07 15:41 UTC, laperla11 commented on src/main/routes/features/response/admission/partialAdmission/partialAdmissionPaymentOptionController.ts
> +    if (!claim?.partialAdmissionPaymentAmount() || !claim?.isPartialAdmission()) {
removed the unnecessary null check.

2022-06-07 15:43 UTC, laperla11 commented on src/main/services/features/response/admission/paymentOptionService.ts
> +    logger.error(`${error.stack || error}`);
changed this line as advised

2022-06-08 13:18 UTC, TatsyMaslova approved these changes

2022-06-08 13:21 UTC, GorilaNaranja approved these changes

2022-06-08 13:27 UTC, laperla11 commented on src/main/common/models/partialAdmission.ts
> +  paymentDate?: Date;
I included the `PaymentIntention` model

2022-06-08 13:27 UTC, laperla11 commented on src/main/services/features/response/admission/paymentOptionService.ts
> +      paymentOption.paymentType = claim.paymentOption as PaymentOptionType;
I fixed it as we discussed

2022-06-08 14:48 UTC, laarmada approved these changes

2022-06-13 15:05 UTC, closed without merging

2022-06-13 15:06 UTC, laperla11 commented
created new PR for build issues;
https://github.com/hmcts/civil-citizen-ui/pull/502