feature/CIV-1979/Display timeline as pdf
hmcts/civil-citizen-ui pull request #503
Opened 2022-06-13 16:25 UTC by laperla11

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###
Display claimant timeline as pdf 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-06-13 18:11 UTC, laarmada approved these changes

2022-06-14 12:33 UTC, taomoh requested changes

2022-06-14 12:33 UTC, taomoh commented on src/main/routes/features/response/timelineOfEvents/defendantTimelineController.ts
> +      const pdfUrl = `/case/${req.params.id}/timeline/documents/${claim.extractDocumentId()}`;
Maybe worth a constant?

2022-06-15 13:12 UTC, laperla11 commented on config/custom-environment-variables.yaml
> +    clientID: IDAM_CLIENT_ID
changed the name as microserviceName.

2022-06-15 14:37 UTC, taomoh commented on src/main/app/client/serviceAuthProviderClient.ts
> +    const serviceAuthTokenGeneratorUrl = '/testing-support/lease';
As discussed please raise a tech debt ticket to switch to the `/lease` endpoint in the future, which use one-time-password mechanism.
And then we can resolve this comment

2022-06-15 15:59 UTC, taomoh commented on src/main/routes/features/response/timelineOfEvents/defendantTimelineController.ts
> +      const pdfUrl = CASE_TIMELINE_DOCUMENTS_URL.replace(':id', req.params.id);
`documentId` substitution is missing

2022-06-15 16:41 UTC, osheaf01 commented on src/main/app/client/serviceAuthProviderClient.ts
> +
Just fmi, is this a typescript version of Java generics?

2022-06-15 17:18 UTC, RosDiaf approved these changes

2022-06-16 07:48 UTC, TatsyMaslova commented on src/test/unit/app/client/dmStoreClient.test.ts
> +  it('retrieve document by document id', async () => {
should we put a test there for not so happy path when it throws the exception?

2022-06-16 10:49 UTC, taomoh commented on src/main/routes/features/response/timelineOfEvents/defendantTimelineController.ts
> +      const pdfUrl = CASE_TIMELINE_DOCUMENTS_URL.replace(':id', req.params.id);
@laperla11 issue hasn't been resolved

2022-06-16 10:50 UTC, taomoh commented on src/main/routes/features/response/timelineOfEvents/defendantTimelineController.ts
> +      const pdfUrl = CASE_TIMELINE_DOCUMENTS_URL.replace(':id', req.params.id);
@laperla11 issue hasn't been resolved

2022-06-16 11:25 UTC, taomoh commented on src/main/app/client/serviceAuthProviderClient.ts
> +    const serviceAuthTokenGeneratorUrl = '/testing-support/lease';
test

2022-06-16 11:27 UTC, laperla11 commented on src/main/routes/features/response/timelineOfEvents/defendantTimelineController.ts
> +      const pdfUrl = CASE_TIMELINE_DOCUMENTS_URL.replace(':id', req.params.id);
I have explained it personally

2022-06-16 11:27 UTC, laperla11 commented on src/main/app/client/serviceAuthProviderClient.ts
> +    const serviceAuthTokenGeneratorUrl = '/testing-support/lease';
I created the tech debt ticket for it;
https://tools.hmcts.net/jira/browse/CIV-3046

2022-06-16 11:28 UTC, taomoh approved these changes

2022-06-16 11:43 UTC, laperla11 commented on src/test/unit/app/client/dmStoreClient.test.ts
> +  it('retrieve document by document id', async () => {
included the test for error exception.

2022-06-20 16:49 UTC, merged