DTSCCI-1224 CUI CNBC Webchat
hmcts/civil-citizen-ui pull request #5169
Opened 2024-11-29 16:53 UTC by velimd

### JIRA link ###
https://tools.hmcts.net/jira/browse/DTSCCI-1224

### Change description ###
Add webchat for CNBC

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2024-12-16 12:19 UTC, rishikrsharma submitted a review, later dismissed

2024-12-16 15:15 UTC, peterpilgrim approved these changes

2025-01-09 11:22 UTC, rishikrsharma submitted a review, later dismissed

2025-01-09 12:20 UTC, peterpilgrim requested changes
lgtm

2025-01-10 08:42 UTC, ruban72 approved these changes

2025-01-13 11:24 UTC, rishikrsharma approved these changes

2025-01-13 11:26 UTC, AbuSalamHMCTS approved these changes

2025-01-14 13:20 UTC, ruban72 approved these changes

2025-01-16 13:32 UTC, rishikrsharma approved these changes

2025-01-17 08:33 UTC, ruban72 approved these changes

2025-01-17 14:33 UTC, ruban72 approved these changes

2025-01-17 14:34 UTC, merged