add translations
hmcts/civil-citizen-ui pull request #526
Opened 2022-06-21 19:34 UTC by laarmada

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-2760

### Change description ###

https://tools.hmcts.net/jira/browse/CIV-2760

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-06-22 07:13 UTC, LeonardoPalmeiro approved these changes

2022-06-22 08:25 UTC, laperla11 requested changes

2022-06-22 08:25 UTC, laperla11 commented on src/main/views/features/dashboard/contact-them.njk
> +      {% set otherPartyLabel = t('contact-them') %}
Shouldn't we use key here instead of text?

2022-06-22 08:25 UTC, laperla11 commented on src/main/views/features/dashboard/contact-them.njk
>        {% set header = t('About claim') %}
same here

2022-06-22 08:25 UTC, laperla11 commented on src/main/views/features/dashboard/contact-them.njk
> +      {% set heading = t('Contact')+ ' '+ t(otherParty) %}
same here

2022-06-22 08:25 UTC, laperla11 commented on src/main/modules/i18n/locales/cy.json
>        "ABOUT_CLAIM": "About claim",
translation is missing here

2022-06-22 09:31 UTC, GorilaNaranja requested changes

2022-06-22 09:31 UTC, GorilaNaranja commented on src/main/views/features/dashboard/contact-them.njk
> +      {% set otherPartyLabel = t('contact-them') %}
This is not a translations, this is for href so we have to delete t function here
`{% set otherPartyLabel = 'contact-them' %}`

2022-06-22 18:16 UTC, laarmada commented on src/main/views/features/dashboard/contact-them.njk
> +      {% set otherPartyLabel = t('contact-them') %}
done!!!!

2022-06-22 18:41 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
>        "ABOUT_CLAIM": "About claim",
done

2022-06-23 07:47 UTC, GorilaNaranja approved these changes

2022-06-28 12:51 UTC, merged