Civ 809 task list part admit
hmcts/civil-citizen-ui pull request #533
Opened 2022-06-23 10:16 UTC by GorilaNaranja

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-809

### Change description ###
Response Task List - Part Admit

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-06-23 14:39 UTC, laperla11 approved these changes

2022-06-23 14:39 UTC, laperla11 commented on src/main/common/utils/taskList/tasks/giveUsDetailsHearing.ts
> +  // TODO: add task complete logic
I am not sure if this is part of your ticket?

2022-06-23 14:50 UTC, TatsyMaslova commented on src/main/common/utils/taskList/taskListBuilder.ts
> +    if (caseData.respondent1?.responseType === ResponseType.PART_ADMISSION) {
Same thing as above perhaps avoid these descriptive comments and put the code into a descriptive function?

2022-06-23 14:51 UTC, GorilaNaranja commented on src/main/common/utils/taskList/tasks/giveUsDetailsHearing.ts
> +  // TODO: add task complete logic
This page doesn't exist yet but I need to add that task to the tasklist

2022-06-23 14:53 UTC, GorilaNaranja commented on src/main/common/utils/taskList/taskListBuilder.ts
> +    if (caseData.respondent1?.responseType === ResponseType.FULL_ADMISSION) {
Done

2022-06-23 14:53 UTC, GorilaNaranja commented on src/main/common/utils/taskList/taskListBuilder.ts
> +    if (caseData.respondent1?.responseType === ResponseType.PART_ADMISSION) {
Done

2022-06-23 14:57 UTC, TatsyMaslova approved these changes

2022-06-24 09:25 UTC, laarmada requested changes
sonar fine :)

2022-06-24 09:25 UTC, laarmada commented on src/main/common/utils/taskList/tasks/whenWillYouPay.ts
> +  if (caseData.partialAdmission?.paymentIntention?.paymentOption === PaymentOptionType.IMMEDIATELY) {
put altogether in one line (17 to 25 only one if) to avoid  repeat whenWillYouPayTask.status = TaskStatus.COMPLETE;

2022-06-24 09:25 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +      "TITLE": "Respond to claim",
in alphabetic order please

2022-06-24 09:25 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +      "TITLE": "Submit",
in alphabetic order please

2022-06-24 09:25 UTC, laarmada commented on src/main/modules/i18n/locales/en.json
> +      "TITLE": "Prepare your response",
in alphabetic order please

2022-06-24 09:25 UTC, laarmada commented on src/main/modules/i18n/locales/en.json
> +      "TITLE": "Resolving the claim",
in alphabetic order please

2022-06-24 09:25 UTC, laarmada commented on src/main/modules/i18n/locales/en.json
> +      "TITLE": "Respond to claim",
in alphabetic order please

2022-06-24 09:25 UTC, laarmada commented on src/main/modules/i18n/locales/en.json
> +      "CHECK_AND_SUBMIT": "Check and submit your response"
in alphabetic order please

2022-06-24 09:25 UTC, laarmada commented on src/main/modules/i18n/locales/en.json
> +      "GIVE_US_DETAILS": "Give us details in case there´s a hearing"
in alphabetic order please

2022-06-24 11:58 UTC, GorilaNaranja commented on src/main/common/utils/taskList/tasks/freeTelephoneMediation.ts
> +    if (caseData.mediation?.companyTelephoneNumber?.option === YesNo.NO) {
Yes that should work the same, I prefer to keep it like this for readability

2022-06-24 12:00 UTC, GorilaNaranja commented on src/main/common/utils/taskList/tasks/whenWillYouPay.ts
> +  if (caseData.partialAdmission?.paymentIntention?.paymentOption === PaymentOptionType.IMMEDIATELY) {
same here, we can avoid some lines but I prefer to keep it more readable

2022-06-27 08:09 UTC, laarmada approved these changes

2022-06-28 13:21 UTC, merged