CIV-3603 Refactor deprecated form 2
hmcts/civil-citizen-ui pull request #628
Opened 2022-07-22 07:25 UTC by hmcts-version1-pablo

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-3603
### Change description ###
Refactor from Form to Generic Form:
- CitizenTelephoneNumber
- RepaymentPlanForm
- Carer
- DebtItems
- Debts

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

2022-07-27 10:23 UTC, laperla11 requested changes

2022-07-27 10:23 UTC, laperla11 commented on src/main/views/features/response/repaymentPlan/repaymentPlan.njk
> +      {% set totalAmountClaimedText = t('The total amount claimed is £' + form.model.totalClaimAmount + '. This includes the claim fee and any interest.') %}
we need translation key here.

2022-07-27 10:30 UTC, hmcts-version1-pablo commented on src/main/modules/i18n/locales/en.json
> +    "FIRST_PAYMENT_DATE_IN_THE_FUTURE_REQUIRED": "Enter a first PRUEBA payment date in the future",
Ouh yes, sorry.

2022-07-27 10:31 UTC, hmcts-version1-pablo commented on src/main/views/features/response/repaymentPlan/repaymentPlan.njk
> +      {% set totalAmountClaimedText = t('The total amount claimed is £' + form.model.totalClaimAmount + '. This includes the claim fee and any interest.') %}
The scope of this task was only refactoring, for the translation there is another task that will be done in this sprint. https://tools.hmcts.net/jira/browse/CIV-3620

2022-07-28 08:47 UTC, laperla11 approved these changes

2022-08-01 08:04 UTC, merged