CIV-3172 - Welsh UI translations 7
hmcts/civil-citizen-ui pull request #638
Opened 2022-07-25 12:20 UTC by hmcts-version1-pablo

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-3172

### Change description ###

Welsh content translation of the following screens: 

"Send claimant your financial details"
"What are you self-employed as?"
"What regular income do you receive?"
"Who employs you"

In addition to changing the validation of errors by the keys of these.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X ] No
```

2022-07-25 15:23 UTC, commitBlob commented on src/main/modules/i18n/locales/en.json
> +    "WEEK" : "Week",
In common we have schedule object with similar translation, can we add them to the same object please

2022-07-25 15:28 UTC, commitBlob commented on src/main/modules/i18n/locales/en.json
> +        "CHILD_TAX" : "Select how often you receive Child Tax Credit",
Same as income and if these are error message we should put them under errors object

2022-07-25 15:29 UTC, commitBlob commented on src/main/modules/i18n/locales/en.json
> +        "CHILD_TAX" : "Enter a valid Child Tax Credit amount, maximum two decimal places",
If these are error messages they should be placed within ERRORS object

2022-07-25 15:31 UTC, commitBlob commented on src/main/views/features/response/statementOfMeans/expenses/regular-expenses.njk
>    {% set amountLabel = 'Amount paid' %}
should these be translated as well?

2022-07-25 15:38 UTC, hmcts-version1-pablo commented on src/main/modules/i18n/locales/en.json
> +        "CHILD_TAX" : "Enter a valid Child Tax Credit amount, maximum two decimal places",
The first version was made with objects for errors. But when built dynamically the errorSummary cannot map the objects and was changed to this.

2022-07-25 15:39 UTC, hmcts-version1-pablo commented on src/main/views/features/response/statementOfMeans/expenses/regular-expenses.njk
>    {% set amountLabel = 'Amount paid' %}
It's translated in errorSummary

2022-07-26 06:32 UTC, hmcts-version1-pablo commented on src/main/modules/i18n/locales/en.json
> +      "REJECT_COURT_MAKE_NEW_PLAN_BASED" : "'If they reject your plan, the court will make a new plan based on your financial details."
Fixed! Thank you

2022-07-26 06:33 UTC, hmcts-version1-pablo commented on src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
> +      switch (name) {
I have changed it to sourceName, I think that incomeTypeOption it's not a good option because this class is used for income sources and expense sources.

2022-07-26 06:50 UTC, hmcts-version1-pablo commented on src/main/modules/i18n/locales/en.json
> +    "WEEK" : "Week",
Fixed! Thank you

2022-07-26 07:33 UTC, hmcts-version1-pablo commented on src/main/views/features/response/statementOfMeans/expenses/regular-expenses.njk
>    {% set amountLabel = 'Amount paid' %}
This screen it's not in the scope of the issue, but the validationErrors are shared in a common class. For that reason I must changed that part.

2022-07-26 07:34 UTC, commitBlob commented on src/main/views/features/response/statementOfMeans/expenses/regular-expenses.njk
>    {% set amountLabel = 'Amount paid' %}
I am looking at ` {% set amountLabel = 'Amount paid' %}` and lines below here

2022-07-26 07:40 UTC, commitBlob requested changes

2022-07-26 07:40 UTC, commitBlob commented on src/main/modules/i18n/locales/en.json
> +        "CHILD_TAX" : "Enter how much Child Tax Credit you receive",
I don't see any changes / comments on this? If unclear I can show you what I have in mind

2022-07-26 07:47 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/cy.json
> +      "GET_APPLICANT_CONTACT_DETAILS" : "Get {{ applicant1Details }} 's contact details.",
We are missing some welsh translations. Do we have these translations?

2022-07-26 07:47 UTC, hmcts-version1-pablo commented on src/main/modules/i18n/locales/en.json
> +        "CHILD_TAX" : "Enter how much Child Tax Credit you receive",
I have respond you in other comment review:
The first version was made with objects for errors. But when built dynamically the errorSummary cannot map the objects and was changed to this.

2022-07-26 07:50 UTC, laarmada commented on src/main/views/features/response/statementOfMeans/expenses/regular-expenses.njk
>    {% set amountLabel = 'Amount paid' %}
This screen will be translated in other issue. He has modify some parts because it has some commons structure with the other screen already translated.

2022-07-26 07:50 UTC, hmcts-version1-pablo commented on src/main/modules/i18n/locales/cy.json
> +      "GET_APPLICANT_CONTACT_DETAILS" : "Get {{ applicant1Details }} 's contact details.",
We don't have it

2022-07-26 07:51 UTC, laarmada approved these changes

2022-07-26 08:06 UTC, GorilaNaranja approved these changes
Good work Pablo! please add the changes from Maro's comments before merge it

2022-07-26 08:10 UTC, commitBlob approved these changes

2022-07-26 08:37 UTC, laperla11 requested changes

2022-07-26 08:37 UTC, laperla11 commented on src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
>      return 'Enter other expense source';
Shouldn't we translate this line?

2022-07-26 08:37 UTC, laperla11 commented on src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
> +    return `Enter how much you pay for ${sourceName ? sourceName : ExpenseType.OTHER}`;
same here

2022-07-26 08:37 UTC, laperla11 commented on src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
> +    return `Enter a valid ${sourceName} amount, maximum two decimal places`;
same here

2022-07-26 08:37 UTC, laperla11 commented on src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
> +    return `Select how often you pay for ${sourceName ? sourceName : ExpenseType.OTHER}`;
same here

2022-07-26 08:41 UTC, hmcts-version1-pablo commented on src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
> +    return `Enter how much you pay for ${sourceName ? sourceName : ExpenseType.OTHER}`;
No, this is for other screen that are not in the scope of my issue.  The screen is regular-income and what you have comment is for regular-expenses, it will be translated in other issue.

2022-07-26 08:41 UTC, hmcts-version1-pablo commented on src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
> +    return `Enter a valid ${sourceName} amount, maximum two decimal places`;
No, this is for other screen that are not in the scope of my issue.  The screen is regular-income and what you have comment is for regular-expenses, it will be translated in other issue.

2022-07-26 08:41 UTC, hmcts-version1-pablo commented on src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
> +    return `Select how often you pay for ${sourceName ? sourceName : ExpenseType.OTHER}`;
No, this is for other screen that are not in the scope of my issue.  The screen is regular-income and what you have comment is for regular-expenses, it will be translated in other issue.

2022-07-26 08:41 UTC, hmcts-version1-pablo commented on src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
>      return 'Enter other expense source';
No, this is for other screen that are not in the scope of my issue.  The screen is regular-income and what you have comment is for regular-expenses, it will be translated in other issue.

2022-07-26 08:42 UTC, laperla11 approved these changes

2022-07-29 12:04 UTC, closed without merging