CIV-3604: Try the new online service
hmcts/civil-citizen-ui pull request #749
Opened 2022-08-22 08:03 UTC by hmcts-version1-pablo

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-3604

### Change description ###

Screen informing about the new online service.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

2022-08-22 12:24 UTC, laperla11 requested changes

2022-08-22 12:24 UTC, laperla11 commented on src/main/routes/urls.ts
> +export const ELIGIBILITY_URL = '/eligibility';
Can you pls change it to `const BASE_ELIGIBILITY_URL = '/eligibility';` to align with other eligibity PRs.

2022-08-22 13:54 UTC, GorilaNaranja requested changes

2022-08-22 13:54 UTC, GorilaNaranja commented on src/main/routes/features/eligibility/tryNewServiceController.ts
> +tryNewServiceController.get(ELIGIBILITY_URL, async (_req, res) => {
You can import express to set the types of req and res

`import * as express from 'express';`

`(req: express.Request, res: express.Response)`

2022-08-22 13:54 UTC, GorilaNaranja commented on src/main/routes/features/eligibility/tryNewServiceController.ts
> +tryNewServiceController.post(ELIGIBILITY_URL, async (req, res) => {
same here, add types

2022-08-22 13:54 UTC, GorilaNaranja commented on src/main/views/features/eligibility/try-new-service.njk
> +
Not sure but I think sonar or lint complain about more than 1 empty line, please one empty line

2022-08-22 14:21 UTC, hmcts-version1-pablo commented on src/main/views/features/eligibility/try-new-service.njk
> +          <form method="post" novalidate>
Very good point! I'm going to modify it

2022-08-22 14:42 UTC, hmcts-version1-pablo commented on src/main/routes/urls.ts
> +export const ELIGIBILITY_URL = '/eligibility';
Done!

2022-08-22 14:43 UTC, hmcts-version1-pablo commented on src/main/views/features/eligibility/try-new-service.njk
> +          <form method="post" novalidate>
Done!

2022-08-22 14:43 UTC, hmcts-version1-pablo commented on src/main/routes/features/eligibility/tryNewServiceController.ts
> +tryNewServiceController.get(ELIGIBILITY_URL, async (_req, res) => {
Done!

2022-08-22 14:43 UTC, hmcts-version1-pablo commented on src/main/routes/features/eligibility/tryNewServiceController.ts
> +tryNewServiceController.post(ELIGIBILITY_URL, async (req, res) => {
Done!

2022-08-23 07:52 UTC, GorilaNaranja approved these changes

2022-08-23 08:07 UTC, laperla11 approved these changes

2022-08-24 07:38 UTC, merged