Civ 3768 some useful info about help fees
hmcts/civil-citizen-ui pull request #780
Opened 2022-08-29 11:59 UTC by GorilaNaranja

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-3768

### Change description ###
Some useful information about Help with Fees

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-08-29 13:27 UTC, hmcts-version1-domini approved these changes

2022-08-29 13:52 UTC, portizdev requested changes

2022-08-29 13:52 UTC, portizdev commented on src/main/modules/i18n/locales/cy.json
> +      "CONTINUE_HELP_WITH_FEES": "Do you wish to continue to make a Help with Fees Application?"
Sorry about that but.. alphabetic order haha 😉

2022-08-29 13:52 UTC, portizdev commented on src/main/views/features/public/eligibility/some-useful-info-fees.njk
> +    },
This must be here?

2022-08-29 13:52 UTC, portizdev commented on src/test/unit/views/features/public/eligibility/some-useful-info-fees.test.ts
> +describe('Eligibility Tenancy Deposit View', () => {
Wrong title

2022-08-29 14:10 UTC, GorilaNaranja commented on src/main/modules/i18n/locales/cy.json
> +      "CONTINUE_HELP_WITH_FEES": "Do you wish to continue to make a Help with Fees Application?"
Good point

2022-08-29 14:11 UTC, GorilaNaranja commented on src/main/views/features/public/eligibility/some-useful-info-fees.njk
> +    },
Nop, pasted accidentally

2022-08-29 14:11 UTC, GorilaNaranja commented on src/test/unit/views/features/public/eligibility/some-useful-info-fees.test.ts
> +describe('Eligibility Tenancy Deposit View', () => {
Done

2022-08-29 14:14 UTC, portizdev approved these changes

2022-08-30 08:49 UTC, RosDiaf approved these changes

2022-08-31 10:29 UTC, merged