CIV-4658 - Features - DQ - Tried to Settle the Claim
hmcts/civil-citizen-ui pull request #846
Opened 2022-09-14 10:41 UTC by commitBlob

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4658

### Change description ###
- implement tried to settle the claim and appropriate unit tests
- fix couple of typos
- re-order alphabetically test messages

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-09-14 12:59 UTC, RosDiaf approved these changes

2022-09-14 13:45 UTC, laperla11 approved these changes

2022-09-15 10:58 UTC, TatsyMaslova approved these changes

2022-09-15 12:52 UTC, laarmada requested changes

2022-09-15 12:52 UTC, laarmada commented on src/main/common/models/claim.ts
> +  directionQuestionnaire?: DirectionQuestionnaire;
if you have add directionQuestionnaire?: DirectionQuestionnaire; to the model, maybe we need to include the other related as:
vulnerability
determinationWithoutHearing
..... and the next ones....

at this way we could use only one service for all cases instead of one for each, saving time, effort and code.
what do you think?

2022-09-15 13:12 UTC, commitBlob commented on src/main/common/models/claim.ts
> +  directionQuestionnaire?: DirectionQuestionnaire;
I believe it will be rather big one service, that's why I've separated it, but agree that all dq related fields should be part of the dq model, we are waiting sampan's ticket to get the list of all fields

2022-09-15 14:27 UTC, laarmada commented on src/main/common/models/claim.ts
> +  directionQuestionnaire?: DirectionQuestionnaire;
I have done the dynamic service in my branch is so easy to do that, we can see after the stand up.

2022-09-15 14:28 UTC, laarmada approved these changes

2022-09-15 14:29 UTC, merged