CIV-4742: Defendant Response - DQ - Small Claims - Using an expert
hmcts/civil-citizen-ui pull request #858
Opened 2022-09-16 15:08 UTC by portizdev

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4742

### Change description ###
- Screen "Using an expert" 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X ] No
```

2022-09-18 16:23 UTC, laarmada requested changes

2022-09-18 16:23 UTC, laarmada commented on src/main/routes/urls.ts
> +export const DQ_GIVE_EVIDENCE_YOURSELF_URL = `${DIRECTIONS_QUESTIONNAIRE_URL}/evidence-yourself`;
please use that:
export const DQ_DEFENDANT_EXPERT_EVIDENCE_URL = `${DIRECTIONS_QUESTIONNAIRE_URL}/defendant-expert-evidence`;
export const DQ_DEFENDANT_EXPERT_REPORTS_URL = `${DIRECTIONS_QUESTIONNAIRE_URL}/defendant-expert-reports`;

2022-09-19 10:01 UTC, GorilaNaranja approved these changes

2022-09-19 10:17 UTC, portizdev commented on src/main/routes/urls.ts
> +export const DQ_GIVE_EVIDENCE_YOURSELF_URL = `${DIRECTIONS_QUESTIONNAIRE_URL}/evidence-yourself`;
DQ_DEFENDANT_EXPERT_EVIDENCE_URL  done.
DQ_DEFENDANT_EXPERT_REPORTS_URL is already in master with another name so I have to keep the name that is in master.

2022-09-20 07:51 UTC, laarmada approved these changes

2022-09-23 15:10 UTC, merged