CIV-4665: DQ - FT - Have you already sent expert reports
hmcts/civil-citizen-ui pull request #859
Opened 2022-09-16 15:38 UTC by kenneth-hmcts

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4665

### Change description ###
This PR contains the change by adding a page asking expert report is sent or not

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-09-20 08:17 UTC, commitBlob commented on src/main/views/features/directionsQuestionnaire/expert-reports.njk
> +{% from "govuk/components/inset-text/macro.njk" import govukInsetText %}
```
{% from "govuk/components/inset-text/macro.njk" import govukInsetText %}
{% from "govuk/components/textarea/macro.njk" import govukTextarea %}
```

you don't need these imports

2022-09-20 08:17 UTC, commitBlob commented on src/main/routes/features/directionsQuestionnaire/expertReportsController.ts
> +  const expertReportsForm = Object.assign(form);
```
 const expertReportsForm = Object.assign(form);
 expertReportsForm.option = form.model.option;
```
I think you don't need to do this for your case, would you mind trying to remove it please and check whether selection is persisted after save.
Expected behaviour:
Select an option, save and continue, come back to the page and selection should be persisted.

If above doesn't happen then keep these two lines.

2022-09-20 09:19 UTC, kenneth-hmcts commented on src/main/views/features/directionsQuestionnaire/expert-reports.njk
> +{% from "govuk/components/inset-text/macro.njk" import govukInsetText %}
Unused import have been removed

2022-09-20 09:20 UTC, kenneth-hmcts commented on src/main/routes/features/directionsQuestionnaire/expertReportsController.ts
> +  const expertReportsForm = Object.assign(form);
Codes have been changed for that part. Checked with same as the expected behaviour.

2022-09-20 09:22 UTC, commitBlob approved these changes

2022-09-20 10:11 UTC, GorilaNaranja commented on src/main/services/features/directionsQuestionnaire/expertReportsService.ts
> +const getExpertReportsForm = (expertReports: ExpertReportsOptions): ExpertReports => {
I think this function should return GenericForm type so we won't need this line in the controller 
`const form = new GenericForm(expertReports);`

2022-09-20 10:11 UTC, GorilaNaranja commented on src/main/services/features/directionsQuestionnaire/expertReportsService.ts
> +    caseData.directionQuestionnaire = {...caseData.directionQuestionnaire};
You can try to use this instead lines 25 and 26
`  caseData.directionQuestionnaire = {...caseData.directionQuestionnaire, expertReports};
`

2022-09-20 10:14 UTC, GorilaNaranja approved these changes

2022-09-20 10:38 UTC, kenneth-hmcts commented on src/main/services/features/directionsQuestionnaire/expertReportsService.ts
> +const getExpertReportsForm = (expertReports: ExpertReportsOptions): ExpertReports => {
After discussion, there will be more changes if we change to generic form. So keep the same.

2022-09-20 10:39 UTC, kenneth-hmcts commented on src/main/services/features/directionsQuestionnaire/expertReportsService.ts
> +    caseData.directionQuestionnaire = {...caseData.directionQuestionnaire};
Changes have been made. Retest has been done and same behaviour as expected

2022-09-22 14:23 UTC, commitBlob approved these changes

2022-09-22 14:31 UTC, GorilaNaranja approved these changes

2022-09-22 14:38 UTC, laarmada requested changes

2022-09-22 14:38 UTC, laarmada commented on src/main/services/features/directionsQuestionnaire/sentExpertReportsService.ts
> +import {SentExpertReports} from '../../../common/models/directionsQuestionnaire/sentExpertReports';
you can remove that class and the related test

2022-09-22 14:38 UTC, laarmada commented on src/main/routes/features/directionsQuestionnaire/sentExpertReportsController.ts
> +      await saveSentExpertReports(claimId, expertReports);
use save generic directionQuestionaire

2022-09-22 14:38 UTC, laarmada commented on src/main/routes/features/directionsQuestionnaire/sentExpertReportsController.ts
> +    const expertReports = getSentExpertReportsForm(req.body.sentExpertReportsOptions);
use getform generic directionQuestionaire

2022-09-22 14:38 UTC, laarmada commented on src/main/routes/features/directionsQuestionnaire/sentExpertReportsController.ts
> +    renderView(new GenericForm(await getSentExpertReports(req.params.id)), res);
use get generic directionQuestionaire

2022-09-23 09:32 UTC, laarmada approved these changes

2022-09-23 16:08 UTC, merged