Feat/civ 4225
hmcts/civil-citizen-ui pull request #871
Opened 2022-09-22 13:09 UTC by lfazelyniaHMCTS

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4225

### Change description ###
Add claimant details (for individual) screen for the claim issue journey

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-09-22 14:17 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +    const caseId = req.session?.user?.id;
this logic could be in a service rather than in the controller

2022-09-22 14:19 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +  const caseId = req.session?.user?.id;
again the same applies here - the save logic could be in the service rather than in the controller. Also don't we have similar thing for defendant details? we could have created a generic serivice and hence refactor both. but if it is difficult then perhaps just do this for this one

2022-09-22 15:25 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +    let claimantIndividualCorrespondenceAddress = new GenericForm<CitizenCorrespondenceAddress>(new CitizenCorrespondenceAddress(
how come this is not a const?

2022-09-22 15:26 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +      if (req.body.postToThisAddress === YesNo.NO) {
this logic should probably be outside the controller

2022-09-22 15:28 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +    let claimantIndividualCorrespondenceAddress = new GenericForm<CitizenCorrespondenceAddress>(new CitizenCorrespondenceAddress(
also applies here. and it seems that CitizenCorrespondenceAddress is the same as CitizenAddress.. perhaps we need to raise a techdebpt to refactor this and just have one class for both

2022-09-23 06:35 UTC, portizdev commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +      res.redirect(constructResponseUrlWithIdParams(temporaryId, CLAIM_CLAIMANT_DOB));
Why we need to use temporaryId to construct the URL?

2022-09-23 06:35 UTC, portizdev commented on src/main/views/features/claim/claimant-individual-details.njk
> +                text: "Title"
All text displayed should be in the translation files cy.json and en.json to facilitate translation.

2022-09-23 06:35 UTC, portizdev commented on src/main/views/features/claim/claimant-individual-details.njk
> +                text: "First name"
Same here (translation files)

2022-09-23 06:35 UTC, portizdev commented on src/main/views/features/claim/claimant-individual-details.njk
> +                text: "Last name"
Same here (translation files)

2022-09-23 08:03 UTC, laarmada requested changes

2022-09-23 08:03 UTC, laarmada commented on src/test/unit/views/features/claim/claimant-individual-details.test.ts
> +import config from 'config';
where is the claimantDetailsService.test.ts?

2022-09-26 08:45 UTC, commitBlob commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +    partyName: partyName,
just to clarify what is Sergio saying.
In JS we can do only `partyName` when the property and the value are named same

2022-09-27 11:27 UTC, lfazelyniaHMCTS commented on src/main/views/features/claim/claimant-individual-details.njk
> +                text: "Last name"
Resolved

2022-09-27 11:27 UTC, lfazelyniaHMCTS commented on src/main/views/features/claim/claimant-individual-details.njk
> +                text: "First name"
Resolved

2022-09-27 11:27 UTC, lfazelyniaHMCTS commented on src/main/views/features/claim/claimant-individual-details.njk
> +                text: "Title"
Resolved

2022-09-27 11:36 UTC, lfazelyniaHMCTS commented on src/test/unit/views/features/claim/claimant-individual-details.test.ts
> +import config from 'config';
Resolved

2022-09-27 11:36 UTC, lfazelyniaHMCTS commented on src/main/common/form/models/partyDetails.ts
> +  isEmpty() {
Removed, not used

2022-09-27 11:36 UTC, lfazelyniaHMCTS commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +    partyName: partyName,
Resolved

2022-09-27 11:36 UTC, lfazelyniaHMCTS commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +      res.redirect(constructResponseUrlWithIdParams(temporaryId, CLAIM_CLAIMANT_DOB));
Not needed, replaced with caseId const

2022-09-27 13:14 UTC, TatsyMaslova commented on src/test/a11y/ignored-urls.ts
> +  urls.CLAIM_CLAIMANT_INDIVIDUAL_DETAILS_URL,
we should not ignore this url unless there is a good reason. we should make sure that we have accessibility tests running for everthing. the urls that are ignored are in technical debt. we should not introduce more

2022-09-27 13:32 UTC, lfazelyniaHMCTS commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +      req.body.primaryAddressLine1,
Me and @laperla11 have discussed this
Not a simple job to refactor  as being used by other CitizenDetailsController
Changing it here would require big changes on that controller there as well
Like you mentioned in other comment for CitizenCorrespondenceAddress, it would be better to add as a tech debt rather than part of this ticket

2022-09-27 13:34 UTC, lfazelyniaHMCTS commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +    let claimantIndividualCorrespondenceAddress = new GenericForm<CitizenCorrespondenceAddress>(new CitizenCorrespondenceAddress(
> how come this is not a const?
Const change will be done in next commit


> also applies here. and it seems that CitizenCorrespondenceAddress is the same as CitizenAddress.. perhaps we need to raise a techdebpt to refactor this and just have one class for both
Resolution same as comment you made regarding CitizenAddress

2022-09-27 13:48 UTC, TatsyMaslova commented on src/main/routes/features/claim/claimantIndividualDetailsController.ts
> +      req.body.primaryAddressLine1,
Sorry I disagree. if we have overriden constructor then no need to change anywhere else (i.e. in the other controller)

2022-09-28 08:04 UTC, TatsyMaslova commented on src/main/common/form/models/citizenAddress.ts
> +  static fromObject(value?: any, redisData?: boolean): CitizenAddress {
we should avoid any type. perhaps you could use Record<string, string>

2022-09-28 08:05 UTC, TatsyMaslova commented on src/main/common/form/models/citizenAddress.ts
> +  if (redisData){
not sure why you need boolean redis data there. looks like you do the same thing when its true or false?

2022-09-28 08:09 UTC, TatsyMaslova commented on src/main/common/form/models/citizenAddress.ts
> +  if (redisData){
ah i can see that you have different types there. you can create fromObject and fromJson instead like Kadir.

2022-09-28 08:13 UTC, TatsyMaslova commented on src/main/common/form/models/partyDetails.ts
> +  static fromObject(value?: any, redisData?: boolean): PartyDetails {
same comment as above here. we should avoid any type. and also perhaps knowledge where the data is coming from. perhaps you should do the same as Kadir has done.

2022-09-28 08:16 UTC, lfazelyniaHMCTS commented on src/test/a11y/ignored-urls.ts
> +  urls.CLAIM_CLAIMANT_INDIVIDUAL_DETAILS_URL,
this is temporary will be removed

2022-09-28 15:28 UTC, TatsyMaslova approved these changes

2022-09-29 08:30 UTC, portizdev approved these changes

2022-09-29 10:13 UTC, laarmada approved these changes

2022-09-30 07:47 UTC, merged