CIV-4599: Defendant Response - Claimant LR email notifications
hmcts/civil-citizen-ui pull request #880
Opened 2022-09-26 14:01 UTC by kenneth-hmcts

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4599

### Change description ###
This PR contains that changes for the translation from citizen UI part to ccd definition part

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-09-26 21:43 UTC, laarmada requested changes

2022-09-26 21:43 UTC, laarmada commented on src/main/common/form/models/yesNo.ts
> +export enum YesNoToCcdTranslation {
for generic purpose we can use YesNoUpperCamelCase instead of YesNoToCcdTranslation

2022-09-27 07:30 UTC, commitBlob commented on src/main/common/models/ccdResponse/ccdAgreedMediation.ts
> +  return mediation?.canWeUse?.option ? YesNoToCcdTranslation.YES
I like ternary operators but Sonar is complaining that nested ternaries are code smell.
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&pullRequest=880&id=civil-citizen-ui&open=AYN6VxBIdMmx1aShV3tL

Would you mind refactoring it into if/else  conditions please

2022-09-27 09:47 UTC, kenneth-hmcts commented on src/main/common/form/models/yesNo.ts
> +export enum YesNoToCcdTranslation {
Changed to YesNoUpperCamelCase in the model

2022-09-27 09:47 UTC, kenneth-hmcts commented on src/main/common/models/ccdResponse/ccdAgreedMediation.ts
> +  return mediation?.canWeUse?.option ? YesNoToCcdTranslation.YES
Code is refactored and the code smell should be removed
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&pullRequest=880&id=civil-citizen-ui

2022-09-27 14:20 UTC, commitBlob approved these changes

2022-10-05 09:07 UTC, merged