CIV-4690: DQ - Do you want to ask for a telephone or video hearing
hmcts/civil-citizen-ui pull request #886
Opened 2022-09-28 09:59 UTC by kenneth-hmcts

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4690

### Change description ###
This PR contains the change for the page asking for telephone or video hearing

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-09-28 10:44 UTC, TatsyMaslova commented on src/main/routes/features/directionsQuestionnaire/phoneOrVideoHearingController.ts
> +    const directionQuestionnaire = await getDirectionQuestionnaire(req.params.id);
this could be in a service rather than in the controller

2022-09-28 10:48 UTC, TatsyMaslova commented on src/main/routes/features/directionsQuestionnaire/phoneOrVideoHearingController.ts
> +    const phoneOrVideoHearing = directionQuestionnaire.phoneOrVideoHearing ? new PhoneOrVideoHearing(directionQuestionnaire.phoneOrVideoHearing.option, directionQuestionnaire.phoneOrVideoHearing.deta
I don't quite like the logic here in the controller where it has to create a new  mode from existing or empty. 1. this logic/knowledge can be hidden from the controller (not its business) and 2. if we do have phoneOrHearing model in redis we should just return it instead of creating a new one

2022-09-28 10:49 UTC, laarmada requested changes

2022-09-28 10:49 UTC, laarmada commented on src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
> +  phoneOrVideoHearing?: PhoneOrVideoHearing;
that should be under hearing?: Hearing, as model describe.

2022-09-28 10:49 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +    "PHONE_OR_VIDEO_HEARING": {
Please in order A-Z

2022-09-28 10:49 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +    "VALID_PHONE_OR_VIDEO_HEARING": {
Please in order A-Z

2022-09-28 10:49 UTC, laarmada commented on src/main/modules/i18n/locales/en.json
> +      "PAGE_TITLE": "Do you want to ask for a telephone or video hearing?",
Please in order A-Z

2022-09-28 10:49 UTC, laarmada commented on src/main/modules/i18n/locales/en.json
> +    "VALID_PHONE_OR_VIDEO_HEARING": {
Please in order A-Z

2022-09-28 11:36 UTC, kenneth-hmcts commented on src/main/modules/i18n/locales/en.json
> +    "VALID_PHONE_OR_VIDEO_HEARING": {
Ordering should be changed

2022-09-28 11:36 UTC, kenneth-hmcts commented on src/main/modules/i18n/locales/en.json
> +      "PAGE_TITLE": "Do you want to ask for a telephone or video hearing?",
Ordering should be changed

2022-09-28 11:36 UTC, kenneth-hmcts commented on src/main/modules/i18n/locales/cy.json
> +    "VALID_PHONE_OR_VIDEO_HEARING": {
Ordering should be changed

2022-09-28 11:36 UTC, kenneth-hmcts commented on src/main/modules/i18n/locales/cy.json
> +    "PHONE_OR_VIDEO_HEARING": {
Ordering should be changed

2022-10-03 15:43 UTC, laperla11 commented on src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
> +  phoneOrVideoHearing?: PhoneOrVideoHearing;
resolved

2022-10-03 16:05 UTC, TatsyMaslova approved these changes

2022-10-04 07:25 UTC, laarmada approved these changes

2022-10-04 10:09 UTC, merged