CIV-4226 - Feature - Claimant Date of Birth
hmcts/civil-citizen-ui pull request #890
Opened 2022-09-29 10:55 UTC by commitBlob

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4226

### Change description ###
Implement claimant date of birth page

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-09-29 14:25 UTC, RosDiaf approved these changes

2022-09-30 08:10 UTC, laperla11 requested changes

2022-09-30 08:10 UTC, laperla11 commented on src/main/views/features/public/claim/claimant-dob.njk
> +{% extends "claim-details-tpl.njk" %}
isn't it possible to use `citizen-dob.njk`?

2022-10-03 10:57 UTC, commitBlob commented on src/main/views/features/public/claim/claimant-dob.njk
> +{% extends "claim-details-tpl.njk" %}
Seems like title is slightly different, will see if I can try to come up with something smart.

2022-10-04 10:37 UTC, merged