CIV-4683: Defendant Response - DQ - Why are you, your experts or witnesses unavailable for a hearing for <<xx>> days?
hmcts/civil-citizen-ui pull request #921
Opened 2022-10-03 14:51 UTC by portizdev

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4683

### Change description ###
- "Why are you, your experts or witnesses unavailable for a hearing for <<xx>> days?" screen
- TO DO: Change the hardcoded 22 to the correct number of days (To be calculated on the page "Are there any dates in the next 12 months when you, your experts or your witnesses cannot attend a hearing?")

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X ] No
```

2022-10-04 07:31 UTC, laarmada requested changes

2022-10-04 07:31 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +    "WHY_UNAVAILABLE_FOR_HEARING": {
is not at the same line of en.json file

2022-10-04 07:35 UTC, portizdev commented on src/main/modules/i18n/locales/cy.json
> +    "WHY_UNAVAILABLE_FOR_HEARING": {
A translation of the response submission pages was missing. Fixed.

2022-10-04 07:54 UTC, commitBlob commented on src/main/routes/features/directionsQuestionnaire/whyUnavailableForHearingController.ts
> +  res.render(whyUnavailableForHearingViewPath, {form, days:22});
this might be hard todo to spot and it would require a bit of refactoring as someone would need to change renderView, get, post, and create calculation service function.
I would pass the days to renderView as a param which would come from the service call in the get and post controllers.

2022-10-04 08:01 UTC, portizdev commented on src/main/routes/features/directionsQuestionnaire/whyUnavailableForHearingController.ts
> +  res.render(whyUnavailableForHearingViewPath, {form, days:22});
Ok, I will create the service (without the calculation) and create the call in get and post and the parameter in render View.
I leave the TODO only in the service.

2022-10-04 08:28 UTC, laperla11 approved these changes

2022-10-04 08:28 UTC, laperla11 commented on src/main/routes/features/directionsQuestionnaire/whyUnavailableForHearingController.ts
> +  res.render(whyUnavailableForHearingViewPath, {form, days:22});
I would recommend also creating a tech debt ticket to monitor this TODO

2022-10-04 09:27 UTC, portizdev commented on src/main/routes/features/directionsQuestionnaire/whyUnavailableForHearingController.ts
> +  res.render(whyUnavailableForHearingViewPath, {form, days:22});
Done! https://tools.hmcts.net/jira/browse/CIV-5151

2022-10-04 10:04 UTC, commitBlob approved these changes

2022-10-05 08:36 UTC, laarmada approved these changes

2022-10-05 10:03 UTC, merged