CIV-4288: Their email address (optional)
hmcts/civil-citizen-ui pull request #932
Opened 2022-10-05 10:30 UTC by kenneth-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4288

### Change description ###
This PR contains the change for the email address page for the defendant

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-10-05 11:39 UTC, TatsyMaslova commented on src/main/modules/i18n/locales/en.json
> +    "VALID_ENTER_VALID_EMAIL_ADDRESS": "Enter valid email address",
sorry i don't like he name of the key. perhaps VALID_EMAIL_ADDRESS? otherwise does not sound very english

2022-10-05 11:42 UTC, TatsyMaslova commented on src/test/utils/errorMessageTestConstants.ts
> +  VALID_ENTER_VALID_EMAIL_ADDRESS = 'Enter valid email address',
same comment as above

2022-10-05 11:50 UTC, kenneth-hmcts commented on src/main/modules/i18n/locales/en.json
> +    "VALID_ENTER_VALID_EMAIL_ADDRESS": "Enter valid email address",
Error message key changed as suggested above

2022-10-05 11:50 UTC, kenneth-hmcts commented on src/test/utils/errorMessageTestConstants.ts
> +  VALID_ENTER_VALID_EMAIL_ADDRESS = 'Enter valid email address',
Error message key changed as suggested above

2022-10-05 11:51 UTC, TatsyMaslova approved these changes

2022-10-05 12:58 UTC, laarmada requested changes

2022-10-05 12:58 UTC, laarmada commented on src/main/common/models/respondent.ts
> +  emailAddress?: string;
We should use Party instead of respondent.ts

2022-10-05 12:58 UTC, laarmada commented on src/main/common/form/models/claim/defendantEmail.ts
> +export class DefendantEmail {
if we use Party.ts class and add that new field is not necessary create a specific class only for the email. No make sense for me.

2022-10-05 12:58 UTC, laarmada commented on src/main/services/features/claim/defendantEmailService.ts
> +const {Logger} = require('@hmcts/nodejs-logging');
if we are using respondent, we can use only one service to get and save respondent not individual field.

2022-10-06 09:07 UTC, commitBlob commented on src/main/routes/urls.ts
> +export const DEFENDANT_EMAIL_URL = `${BASE_CLAIM_URL}/defendant-email`;
Can you refactor `DEFENDANT_EMAIL_URL` into `CLAIM_DEFENDANT_EMAIL_URL` please

2022-10-06 10:14 UTC, kenneth-hmcts commented on src/main/routes/urls.ts
> +export const DEFENDANT_EMAIL_URL = `${BASE_CLAIM_URL}/defendant-email`;
Updated as suggested above

2022-10-07 15:10 UTC, laarmada requested changes

2022-10-07 15:10 UTC, laarmada commented on src/main/modules/i18n/locales/en.json
> +      "DEFENDANT_EMAIL": {
could we add under "YOUR_DETAILS", what do you think?

2022-10-07 15:10 UTC, laarmada commented on src/main/routes/features/public/claim/defendantEmailController.ts
> +import {DefendantEmail} from '../../../../common/form/models/claim/defendantEmail';
create the class under features/claim/yourDetails instead of features/public

2022-10-07 15:10 UTC, laarmada commented on src/main/services/features/claim/defendantEmailService.ts
> +import {getCaseDataFromStore, saveDraftClaim} from '../../../modules/draft-store/draftStoreService';
I'm not sure but /claim means claim spike/journey or claimant. Whats the difference with /response

2022-10-07 15:10 UTC, laarmada commented on src/main/views/features/public/claim/defendant-email.njk
> +{% extends "claim-details-tpl.njk" %}
why we have two pages???? remove the public one no?

2022-10-07 15:10 UTC, laarmada commented on src/test/utils/errorMessageTestConstants.ts
> +  VALID_EMAIL_ADDRESS = 'Enter valid email address',
why we need that? already have in en.json

2022-10-10 14:34 UTC, laarmada approved these changes

2022-10-12 09:31 UTC, merged