CIV-4320 - Features - Their Details (Organisation)
hmcts/civil-citizen-ui pull request #937
Opened 2022-10-06 14:05 UTC by commitBlob

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-10-10 14:49 UTC, kenneth-hmcts approved these changes

2022-10-11 08:34 UTC, TatsyMaslova approved these changes

2022-10-11 08:48 UTC, laperla11 approved these changes

2022-10-11 08:48 UTC, laarmada requested changes
we can merge that one only for point purpose but we need to refactor it as well.

2022-10-11 08:48 UTC, laarmada commented on src/main/common/form/models/companyOrOrganisationPartyDetails.ts
> +  @ValidateIf(o => o.partyName !== undefined)
if we create a new PartyDetails instead of use Party class the refactor will be hard because we will remove that one and change the party class again....

2022-10-11 08:48 UTC, laarmada commented on src/main/modules/i18n/locales/cy.json
> +      "UK_POSTCODE": "Enter a UK postcode"
good structure

2022-10-11 08:48 UTC, laarmada commented on src/main/modules/i18n/locales/en.json
> +      "UK_POSTCODE": "Enter a UK postcode"
we have missing some lines from en.json

2022-10-11 08:48 UTC, laarmada commented on src/main/routes/features/claim/defendant/defendantDetailsController.ts
> +      await saveDefendant(userId, undefined, partyDetailsAndPrimaryAddress, true);
undefined? is not possible to avoid send the value if that is optional?
On the other hang, use a boolean to said if you want save the full object or not I dont like that approach.....

2022-10-11 08:48 UTC, laarmada commented on src/main/services/features/claim/partyTypeService.ts
>  import {ClaimantOrDefendant, PartyType} from '../../../common/models/partyType';
I will refactor in the next issue the claimant part with that approach good point

2022-10-11 08:48 UTC, laarmada commented on src/main/views/features/claim/defendant/defendant-details-individual-or-sole-trader.njk
> +
the empty data is for the next issue right?

2022-10-11 08:51 UTC, laarmada approved these changes

2022-10-11 08:51 UTC, commitBlob commented on src/main/views/features/claim/defendant/defendant-details-individual-or-sole-trader.njk
> +
yeah, empty bits are for the next stories, I just tried to make it obvious for whoever picks it up

2022-10-11 08:53 UTC, commitBlob commented on src/main/modules/i18n/locales/en.json
> +      "UK_POSTCODE": "Enter a UK postcode"
I believe, Pablo addressed this misalign in one of his tickets

2022-10-11 09:08 UTC, portizdev approved these changes

2022-10-12 08:09 UTC, merged