Civ 4284 your details an other type
hmcts/civil-citizen-ui pull request #963
Opened 2022-10-11 14:13 UTC by laarmada

### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-4284

### Change description ###

Enter organisation details' screen

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-11 15:05 UTC, laperla11 requested changes

2022-10-11 15:05 UTC, laperla11 commented on src/main/routes/features/claim/yourDetails/claimantDoBController.ts
> +      await saveDraftClaim(req.params.id, claim);
req.params.id is not available for claim journey, you need req.session.user.id here

2022-10-12 06:45 UTC, portizdev commented on src/main/routes/features/claim/yourDetails/claimantDoBController.ts
> +      await saveDraftClaim(req.params.id, claim);
Done!

2022-10-12 06:45 UTC, portizdev approved these changes

2022-10-12 07:30 UTC, laperla11 approved these changes

2022-10-12 07:55 UTC, commitBlob commented on src/test/unit/views/features/claim/yourDetails/claimant-organisation-details.test.ts
> +  beforeEach(() => {
can you change this to `beforeAll` please. We don't need to call this for every test

2022-10-12 07:55 UTC, commitBlob commented on src/test/unit/views/features/claim/yourDetails/claimant-organisation-details.test.ts
> +    beforeEach(async () => {
can you change this to `beforeAll` please. We don't need to call this for every test as page content doesn't change

2022-10-12 07:58 UTC, TatsyMaslova approved these changes

2022-10-12 09:01 UTC, portizdev commented on src/main/routes/features/claim/yourDetails/defendantPartyTypeController.ts
> +import {Party} from 'models/party';
Sometimes it fails me, in this case it was working but for consistency I have changed it to the full route.

2022-10-12 09:02 UTC, portizdev commented on src/test/unit/views/features/claim/yourDetails/claimant-organisation-details.test.ts
> +    beforeEach(async () => {
Done

2022-10-12 14:59 UTC, merged