CIV-4338: When do you want to stop claiming interest?
hmcts/civil-citizen-ui pull request #981
Opened 2022-10-14 10:48 UTC by kenneth-hmcts

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-4338

### Change description ###
This PR contains the changes for the page When do you want to stop claiming interest?

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-14 12:05 UTC, TatsyMaslova approved these changes

2022-10-14 13:45 UTC, RosDiaf approved these changes

2022-10-17 07:50 UTC, laarmada requested changes
please improve the coverage: https://sonarcloud.io/summary/new_code?id=civil-citizen-ui&pullRequest=981

2022-10-17 07:50 UTC, laarmada commented on src/main/common/form/models/interest/interestEndDateSelection.ts
> +import {IsDefined} from 'class-validator';
Why that name and not interestEndDate.ts?

2022-10-17 07:50 UTC, laarmada commented on src/main/common/form/models/interest/interest.ts
> +  interestEndDate?: InterestEndDateType;
here should be interestEndDate.ts or current interestEndDateSelection.ts

2022-10-17 07:50 UTC, laarmada commented on src/main/routes/features/claim/interest/interestEndDateController.ts
> +    const interestEndDate = Object.assign(new InterestEndDateSelection(), interest.interestEndDate);
const interestEndDate = new InterestEndDateSelection(interest.interestEndDate));
we dont need to use assign

2022-10-18 11:06 UTC, commitBlob commented
removing labels as no one is working on this PR at the moment.

2022-10-20 06:23 UTC, laarmada approved these changes

2022-10-20 12:42 UTC, merged