CIV-4394 - Features - Claim Timeline
hmcts/civil-citizen-ui pull request #990
Opened 2022-10-18 09:31 UTC by commitBlob

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-10-18 13:55 UTC, laarmada requested changes

2022-10-18 13:55 UTC, laarmada commented on src/main/common/models/party.ts
> +  timeline?: Timeline;
for me no make sense timeline inside of Party, I think it should be into ClaimDetails....

2022-10-18 13:55 UTC, laarmada commented on src/main/common/form/models/timeLineOfEvents/timeline.ts
> +  atLeastOneRowRequired?: boolean;
why you use the current simlar approach for that: 

@Validate(AtLeastOneEmployerValidator, { message: 'ERRORS.VALID_ENTER_AT_LEAST_ONE_EMPLOYER' })
  @ValidateNested()
    rows: Employer[];
    
    ..... atLeastOneRowRequired vble in the model no is good...

2022-10-18 13:55 UTC, laarmada commented on src/main/services/features/claim/yourDetails/timelineService.ts
> +    form.errors.push(new FormValidationError({property: 'atLeastOneFieldRequired', constraints: {text: 'ERRORS.ONE_ROW_REQUIRED'}}));
I dont like put keys in everywhere of the code if it´s not necessary, using @Validate(AtLeastOne..... you can save that...

2022-10-18 14:01 UTC, commitBlob commented on src/main/common/models/party.ts
> +  timeline?: Timeline;
There are 2 timelines to be provided, one for applicant, one for respondent. 
How do you want to distinguish between these?

2022-10-18 14:04 UTC, commitBlob commented on src/main/services/features/claim/yourDetails/timelineService.ts
> +    form.errors.push(new FormValidationError({property: 'atLeastOneFieldRequired', constraints: {text: 'ERRORS.ONE_ROW_REQUIRED'}}));
I can't put this in model because on my view minimum 1 field is required, on the other one timeline is optional

2022-10-18 14:05 UTC, laarmada commented on src/main/common/models/party.ts
> +  timeline?: Timeline;
One under ClaimDetails and the old one (defendant) current under claim we need to decide it it could be DefendantDetails

2022-10-18 14:16 UTC, commitBlob commented on src/main/common/models/party.ts
> +  timeline?: Timeline;
so you want to mix apples and oranges? Why is one Claim details and other is defendant details? That doesn't make absolute sense for me.
I am applicant, and I want to add timeline. Which object am I updating? ClaimDetails timeline or DefendantDetails timeline?

2022-10-19 13:07 UTC, laperla11 approved these changes

2022-10-19 13:24 UTC, laarmada approved these changes

2022-10-19 13:37 UTC, TatsyMaslova approved these changes

2022-10-20 14:24 UTC, merged